### ISSUE TITLE
Problem emerging palp-2.1

### ISSUE THREAD

**Issue by rkiyanchuk** [cschwan/sage-on-gentoo#178]
The website containing archive with palp-2.1 http://hep.itp.tuwien.ac.at/  is down and I can't emerge it. It's not the issue of `sage-on-gentoo`, but how can the problem with the ebuid be solved?

**Comment by askme765cs** [comment]
The website is down again,leading to the faiurel of install.A mirror of http://hep.itp.tuwien.ac.at/ as well as ebuild update may be needed.
