### ISSUE TITLE
[TRACKER] Sage migration to python3

### ISSUE THREAD

**Issue by cschwan** [cschwan/sage-on-gentoo#212]
This serves as a tracker bug for the python3 status of Sage's dependencies.
## READY FOR PYTHON 3.2
- cvxopt (>=1.1.6 in s-o-g overlay)
- cython
- docutils
- ipython (>= 0.13.1-r1)
- jinja
- matplotlib (>= 1.2.0-r2)
- mpmath
- numpy
- pycrypto
- scipy (>= 0.12.0)
- sphinx
- sqlalchemy (>= 0.8.1)
- sympy (>= 0.7.2-r1 in tree)
## READY FOR PYTHON 3.2 BUT NOT IN PORTAGE
- networkx (see https://pypi.python.org/pypi/networkx)
- rpy (might work, see https://pypi.python.org/pypi/rpy2 and http://rpy.sourceforge.net/news.html)
## NO OFFICIAL SUPPORT FOR PYTHON 3.2 OR UNKNOWN
- flask-autoindex
- flask-babel
- flask-openid
- gdmodule
- polybori
- pexpect
- webassets (see progress on https://github.com/miracle2k/webassets/issues/194)
## DEFINITIVELY NOT WORKING WITH PYTHON 3.2
- pynac (I tried this lately; relies on some deprecated python C functions; patching is not that stgraightforward; sage-clib might require patches as well)
- twisted / twisted-mail / twisted-web (see http://twistedmatrix.com/trac/milestone/Python-3.x)

**Comment by devurandom** [comment]
From the list above, the following have Python 3 support and are available in Gentoo or this overlay:
* flask-autoindex
* flask-babel
* networkx
* pexpect
* rpy
* twisted (unified ebuild; twisted-mail, twisted-web are no longer being updated separately)
* webassets

No Python 3 support in Gentoo, but available:
* flask-openid
* gdmodule
* pynac

Completely missing in Gentoo:
* polybori

**Comment by kiwifb** [comment]
Things may need updating. 
* sage probably won't need twisted with python 3. twisted is used by the old sage notebook which is deprecated in favor of jupyter.
* webassets see above
* pynac now has support for python 3 in this overlay. Hackish to support multiple python at the same time. Out of the box will build with either python 2 or python 3.
* polybori is abandoned and has been replaced by brial and recently I separated the python part in a sage-brial ebuild which support multiple python.

**Comment by kiwifb** [comment]
I should add the following: sage 8.0 will build with python 3.6 which is the current target upstream. It builds with python 3.6 but still crash on start up. This is still a work in progress but now sage-on-gentoo tracks the fact that sage builds with python 3.6.

**Comment by kiwifb** [comment]
While it is not complete, sage now can start with python 3.6. There are still broken part but everything apart from the legacy notebook (which is tacitely deprecated now and will officially be in sage-8.5) and some of its dependencies are now building and installing with python 3.6.

The area still worked on are
* building the documentation
* running the doctest suite successfully.

At this stage I think this tracker has served its purpose.
