### ISSUE TITLE
Interface doctest failure

### ISSUE THREAD

**Issue by cschwan** [cschwan/sage-on-gentoo#224]
<pre>sage -t /usr/share/sage/devel/sage/sage/interfaces/tests.py
**********************************************************************
File "/usr/share/sage/devel/sage/sage/interfaces/tests.py", line 34, in sage.interfaces.tests
Failed example:
    subprocess.call("echo syntax error | ecl", **kwds)
Expected:
    0
Got:
    139
**********************************************************************
File "/usr/share/sage/devel/sage/sage/interfaces/tests.py", line 42, in sage.interfaces.tests
Failed example:
    subprocess.call("echo syntax error | singular", **kwds)
Expected:
    0
Got:
    127
**********************************************************************
1 item had failures:
   2 of  18 in sage.interfaces.tests
    [17 tests, 2 failures, 9.55 s]</pre>

**Comment by kiwifb** [comment]
I think that test works in vanilla sage because of a patch they added to `ecl` and that I won't carry. If we want the test suite to pass perfectly I'd just remove this particular test.
