### ISSUE TITLE
Additional package.accept_keywords and package.use entries?

### ISSUE THREAD

**Issue by equaeghe** [cschwan/sage-on-gentoo#269]
Install of sage on mostly stable Gentoo amd64. It went fine, but I had to add some entries to

* package.accept_keywords

...
    # required by sci-chemistry/jmol-applet-12.3.14::sage-on-gentoo
    # required by sci-mathematics/sage-notebook-0.10.7.2-r1::sage-on-gentoo[java]
    # required by sci-mathematics/sage-6.0-r1::sage-on-gentoo
    # required by sci-mathematics/sage-data-conway_polynomials-0.4-r1::sage-on-gentoo
    =sci-libs/naga-2.1 ~amd64
...

* package.use

...
    # required by dev-texlive/texlive-xetex-2012
    # required by dev-python/matplotlib-1.3.1[latex]
    # required by sci-mathematics/sage-6.0-r1::sage-on-gentoo
    # required by sci-mathematics/sage-notebook-0.10.7.2-r1::sage-on-gentoo
    =app-text/texlive-core-2012-r1 xetex
    # required by dev-python/matplotlib-1.3.1
    # required by sci-mathematics/sage-6.0-r1::sage-on-gentoo
    # required by sci-mathematics/sage-notebook-0.10.7.2-r1::sage-on-gentoo
    =x11-base/xorg-server-1.14.3-r2 xvfb
...

Solely FYI. Not really an issue. (And also: many thanks for maintaining this overlay!)

~~(Don't know how to avoid large bold, sorry...)~~

**Comment by cschwan** [comment]
Hm. I came across this one today:

<pre>The following keyword changes are necessary to proceed:
 (see "package.accept_keywords" in the portage(5) man page for more details)
# required by sci-libs/fplll-4.0.4
# required by sci-mathematics/sage-6.5::sage-on-gentoo
# required by sci-mathematics/sage-notebook-0.11.4-r2::sage-on-gentoo
=dev-libs/gmp-6.0.0a ~amd64</pre>

But the in-tree fplll depends on `>=dev-libs/gmp-4.2.0:0`. Huh?

**Comment by kiwifb** [comment]
`Huh?` indeed. I cannot think of anything that depend on that version of gmp. All I can think of is that somehow you masked all version of gmp. Then portage will go and ask for the highest version.
