### ISSUE TITLE
pin maxima in sage to sage-on-gentoo version

### ISSUE THREAD

**Issue by strogdon** [cschwan/sage-on-gentoo#313]
Should maxima be pinned to the sage-on-gentoo version? With the main-tree maxima-5.33.0 I get failures:
```
sage -t --long usr/share/sage/src/sage/symbolic/integration/integral.py
**********************************************************************
File "usr/share/sage/src/sage/symbolic/integration/integral.py", line 658, in sage.symbolic.integration.integral.integrate
Failed example:
    integrate(f, x, 0, 2*pi)  # long time (4s on sage.math, 2012)
...
    RuntimeError: ECL says: Detected access to an invalid or protected memory address.
**********************************************************************
```
and
```
sage -t --long usr/share/sage/src/sage/calculus/calculus.py
**********************************************************************
File "usr/share/sage/src/sage/calculus/calculus.py", line 145, in sage.calculus.calculus
Failed example:
    e^M
...
    TypeError: ECL says: Error executing code in Maxima: Unable to find the spectral representation
**********************************************************************
File "usr/share/sage/src/sage/calculus/calculus.py", line 148, in sage.calculus.calculus
Failed example:
    e^M
...
    TypeError: ECL says: Error executing code in Maxima: Unable to find the spectral representation
**********************************************************************

```
which go away with the sage-on-gentoo version. Here I have to force the sage-on-gentoo version to install by masking the main-tree version.

**Comment by strogdon** [comment]
maxima-5.36.0 is now in the main tree and updating world pulls it in. Here 5.36.0 has the same ECL issues that's mentioned above. Fortunately, in prefix 5.36.0 fails to build.

**Comment by kiwifb** [comment]
Yes no one seems to have taken notice of our requests. In other news ecls 15.x works with maxima 5.35 and sage.

**Comment by kiwifb** [comment]
Hit me on the head will you. You only have the issue on prefix? As a side issue what is failing in the 5.36 build, I am not sure if 5.36 is compatible with sage. I should just pin things down unless proven otherwise.

**Comment by strogdon** [comment]
5.36.0 builds on Gentoo but fails to build in Prefix. I filed a bug for that, https://bugs.gentoo.org/show_bug.cgi?id=548260. It is a simple fix. However, 5.36.0 doesn't appear to be compatible with Sage (certainly 6.7.beta3). Both these tests have failing parts
```
sage -t --long /usr/share/sage/src/sage/symbolic/integration/integral.py
sage -t --long /usr/share/sage/src/sage/calculus/calculus.py
```
I only know of these failure for sure.

**Comment by kiwifb** [comment]
Pinning time....

**Comment by kiwifb** [comment]
Pinned.

**Comment by kiwifb** [comment]
The failing test look ugly but may be because some of the patches we carry are not in 5.36 and not in the main tree. I may look into that.

**Comment by kiwifb** [comment]
Don't remember what was wrong with that but the issue is gone now.
