### ISSUE TITLE
Rebuilding sage library via "sage -b" not working

### ISSUE THREAD

**Issue by spinfoam** [cschwan/sage-on-gentoo#321]
I have tried to install a package to sage (Sage Manifolds). This includes rebuilding sage library ("sage -b") and installing documentation ("sage --docbuild"). Both give me error of the following type (for "sage -b"):
<code><pre>
sage-run received unknown option: -b 
usage: sage [options] 
Try 'sage -h' for more information.
</pre></code>
I am likely missing something simple but I haven't been able to solve it. 

Thank you for any help.

And thank you very much for the amount of work you devote to providing us with sage ebuilds.

**Comment by kiwifb** [comment]
I cannot go any further than giving you a custom ebuild at this stage. If you need more support for this you can re-open this issue.
