### ISSUE TITLE
maxima-5.35.1-r2 fails to install in Prefix

### ISSUE THREAD

**Issue by strogdon** [cschwan/sage-on-gentoo#335]
A build in prefix gives:
```
 * QA Notice: the following files are outside of the prefix:
 * /usr
 * /usr/share
 * /usr/share/emacs
 * /usr/share/emacs/site-lisp
 * /usr/share/emacs/site-lisp/maxima
 * /usr/share/emacs/site-lisp/maxima/maxima.el
 * /usr/share/emacs/site-lisp/maxima/emaxima.sty
 * /usr/share/emacs/site-lisp/maxima/smart-complete.el
 * /usr/share/emacs/site-lisp/maxima/emaxima.lisp
 * /usr/share/emacs/site-lisp/maxima/bookmode.el
 * /usr/share/emacs/site-lisp/maxima/emaxima.el
 * /usr/share/emacs/site-lisp/maxima/sshell.el
 * /usr/share/emacs/site-lisp/maxima/maxima-font-lock.el
 * /usr/share/emacs/site-lisp/maxima/dbl.el
 * ERROR: sci-mathematics/maxima-5.35.1-r2::sage-on-gentoo failed:
 *   Aborting due to QA concerns: there are files installed outside the prefix
 * 
```
It appears that ``EPREFIX`` is not being prepended as it should. I tried various things without success but didn't investigate fully.

**Comment by kiwifb** [comment]
Odd I didn't notice difference affecting prefix when I rebased. I'll look into it shortly.

**Comment by kiwifb** [comment]
Think I found it, sorry for the delay. Can you give a try to it now?

**Comment by strogdon** [comment]
Now I get double prefix errors:
```
^[[33;01m*^[[0m QA Notice: storage/strogdon/gentoo-redlizard///storage/strogdon/gentoo-redlizard/usr/lib/maxima/5.35.1 double prefix
 ^[[33;01m*^[[0m QA Notice: storage/strogdon/gentoo-redlizard///storage/strogdon/gentoo-redlizard/usr/lib/maxima/5.35.1/binary-ecl double prefix
 ^[[33;01m*^[[0m QA Notice: storage/strogdon/gentoo-redlizard///storage/strogdon/gentoo-redlizard/usr/lib/maxima/5.35.1/binary-ecl/maxima double prefix
 ^[[31;01m*^[[0m ERROR: sci-mathematics/maxima-5.35.1-r2::sage-on-gentoo failed:
 ^[[31;01m*^[[0m   Aborting due to QA concerns: double prefix files installed
```
I seems as though the ``SITELISP`` is not being prepended correctly. I had tried
```
emake DESTDIR="${D}" emacsdir="${ED}${SITELISP}/${PN}" install
````
but that didn't work either.

**Comment by kiwifb** [comment]
Yes the SITELISP variable isn't prefixed. I think just adding ${EPREFIX}/ in front will help. pushed again.

**Comment by strogdon** [comment]
Of course ``emacsdir="${ED}${SITELISP}/${PN}" install`` will not work since only ``EPREFIX`` is needed.

**Comment by kiwifb** [comment]
I was going to suggest opening a bug against elips-common.eclass but on further examination it may be misguided. The real issue is that the eclass is not used to install the .el files, the installation mechanism provided by the eclass is properly prefixed.

I am not sure reorganising that code would help.

**Comment by strogdon** [comment]
Yes this did fix things and I also had noticed in ``trying`` to fix things that the elisp-common.eclass did do the correct thing but it was not really used.

**Comment by kiwifb** [comment]
cool, closing then.
