### ISSUE TITLE
file collisions: /usr/bin/python-exec2

### ISSUE THREAD

**Issue by strogdon** [cschwan/sage-on-gentoo#337]
Both sage-baselayout and dev-vcs/git install the symlink
```
ls -al /usr/bin/python-exec2
lrwxrwxrwx 1 root root 31 Feb 19 20:51 /usr/bin/python-exec2 -> ../lib/python-exec/python-exec2
```
and I get file collisions that don't seem to be resolvable. I don't recall seeing this previously? And I have collision-protect turned off in ``make.conf``. Perhaps the order of install is important. This appeared while rebuilding git-2.0.5 with sage-baselayout-9999 installed.

**Comment by strogdon** [comment]
I should have posted the failure:
```
Detected file collision(s):

        /usr/bin/python-exec2

Searching all installed packages for file collisions...

Press Ctrl-C to Stop

sci-mathematics/sage-baselayout-9999:0::sage-on-gentoo
        /usr/bin/python-exec2

Package 'dev-vcs/git-2.0.5' NOT merged due to file collisions. If
necessary, refer to your elog messages for the whole content of the
above message.
```

**Comment by kiwifb** [comment]
```
ll /usr/bin/python-exec2
ls: cannot access /usr/bin/python-exec2: No such file or directory
```
Not present here. I will have to see if it is something from an eclass update.

**Comment by kiwifb** [comment]
eclass flip-flopping, are you a late upgrader for dev-lang/python-exec? It should be 2.0.1-r1.

**Comment by strogdon** [comment]
That's the python-exec that I have. FWIW this appeared after a sync and updating world.

**Comment by kiwifb** [comment]
OK doing that just now, we'll see.

**Comment by kiwifb** [comment]
Just reinstalled git, still no ```/usr/bin/python-exec2```

**Comment by strogdon** [comment]
Ahh. python-exec is old! It was never updated. Let me manually do it and then see.

**Comment by strogdon** [comment]
The python-exec is old
```
ls -al /usr/bin/python-exec
-rwxr-xr-x 1 root root 1397 Mar 12  2014 /usr/bin/python-exec
```
I manually updated python-exec and I still get the collisions when installing ``git``. So I
```
rm /usr/bin/python-exec
emerge -1 dev-lang/python-exec 
emerge -1 sci-mathematics/sage-baselayout
emerge -1 dev-vcs/git
```
And now
```
* Detected file collision(s):
 * 
 *      /usr/bin/python-exec2
 * 
 * Searching all installed packages for file collisions...
 * 
 * Press Ctrl-C to Stop
 * 
 * sci-mathematics/sage-baselayout-9999:0::sage-on-gentoo
 *      /usr/bin/python-exec2
 * 
 * Package 'dev-vcs/git-2.0.5' NOT merged due to file collisions.
```
with
```
ls -al /usr/bin/python-exec2 
lrwxrwxrwx 1 root root 31 Feb 22 14:41 /usr/bin/python-exec2 -> ../lib/python-exec/python-exec2
```
Strange?

**Comment by kiwifb** [comment]
I have a dim memory that the file needed to be removed manually.
```
rm /usr/bin/python-exec2
```

**Comment by strogdon** [comment]
Here after removing the symlink ``/usr/bin/python-exec2``, sage-baselayout-9999 re-installs it. And then installing ``git`` will fail.

**Comment by kiwifb** [comment]
With what message?

**Comment by strogdon** [comment]
I think it failed because of file collisions, although I'm not now positive. I did 
```
rm /usr/bin/python-exec2
emerge -1 dev-vcs/git
emerge -1 sci-mathematics/sage-baselayout
```
without a problem. And
```
rm /usr/bin/python-exec2
emerge -C git
emerge -1 sage-baselayout
```
pulled in git first and then sage-baselayout. So there must be a correct order of merging. I guess.

**Comment by kiwifb** [comment]
Still very curious. I wonder if we should ask someone like mgorny. Then again I am surprised you have not been forced to upgrade earlier so it may be a pitfall due to slow removal of the link.
