### ISSUE TITLE
sage-doc-6.5 fails due to babel problems

### ISSUE THREAD

**Issue by gagern** [cschwan/sage-on-gentoo#338]
Apparently the sage docs fail to build for lack of some babel setting:

```
[a_tour_of] resolving references...

(/usr/share/texmf-dist/tex/latex/base/utf8.def
(/usr/share/texmf-dist/tex/latex/base/t1enc.dfu)
(/usr/share/texmf-dist/tex/latex/base/ot1enc.dfu)
(/usr/share/texmf-dist/tex/latex/base/omsenc.dfu)))
(/usr/share/texmf-dist/tex/latex/cmap/cmap.sty)
(/usr/share/texmf-dist/tex/latex/base/fontenc.sty
(/usr/share/texmf-dist/tex/latex/base/t1enc.def)<<t1.cmap>>)
(/usr/share/texmf-dist/tex/generic/babel/babel.sty

! Package babel Error: You haven't specified a language option.

See the babel package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.332 ...ry to proceed from here, type x to quit.}
                                                  
? 
! Emergency stop.
 ...                                              
```

I guess this might have been for one of the non-english copies of the tour document; there were several similar errors later on. Perhaps my problem is the fact that I probably don't have babel support files for magyar, italian or brazil installed. Does this package perhaps depend on dev-texlive/texlive-lang{hungarian,italian}? What package do I need for brazil? `texmfind brazil.ldf` returns only some `gloss-brazil.ldf` from xetex. I see the ebuild already depends on portuguese, so perhaps that's sufficient.

I guess for the time being I'll disable the `pdf` USE flag, but I'd like you to know about these issues nevertheless. I'll give the package a re-run (with USE=pdf) after I merged the packages mentioned above, but not today.

**Comment by kiwifb** [comment]
sage-doc is crufty I recommend use of sage-doc-bin (which I need to update now that the official docs are out). We seriously need to do something 
 1) about the pdf generation which is where those problem appear
 2) language selection. We should be able to only build and test a subset

Anyway this is stuff for #210 which is our long suffering ticket about building the doc and I understand if don't want to read it all.

**Comment by kiwifb** [comment]
I have updated sage-doc-bin if you are interested in installing pdf documentation.

**Comment by kiwifb** [comment]
Actually now that I remember it when I first created a sage-doc-bin for 6.4 I explicitly removed pdf generation for sage-doc-6.4 because we know it is broken. So It was a sloppy release from me. I'll put the ebuild in line.

**Comment by saraedum** [comment]
@kiwifb I just ran into this issue on ArchLinux (so not gentoo…). Did you eventually find out how to resolve this problem? Not sure what's so special about the German Tour of Sage.

**Comment by kiwifb** [comment]
This problem is like https://trac.sagemath.org/ticket/17874 in fact. It seems to point to an underlying problem with missing a component of TeXlive.
I currently do not suffer from that problem when I build the full doc including pdf for stable releases. 
Look to see if you have a folder called `babel-german` in your texlive install.
