### ISSUE TITLE
Error while building sci-mathematics/sage-6.5: "bot" undeclared in pari_instance.{c,pyx}

### ISSUE THREAD

**Issue by aleclearmind** [cschwan/sage-on-gentoo#341]
Hi, I'm trying to build sage 6.5 but I get the following error:

http://paste.ubuntu.com/10684341/

Here's the pari_instance.c file generated by Cython:

http://paste.ubuntu.com/10684362/

The offending part of the pari_instance.pyx is the following:

    if bot:
      return  # pari already initialized.
    
    global top, bot

I've tried to move the global declaration before the usage of bot, and also to give a default value to bot (and top) outside the function without results. I'm using Cython 0.21.2.

Any idea on why this happens?

**Comment by kiwifb** [comment]
Which version of pari?

**Comment by aleclearmind** [comment]
OK, I've solved, `sci-mathematics/pari-2.8_pre20150307` was causing the error, switching to `sci-mathematics/pari-2.7.1-r2` fixes the issue. pari-2.8 [was required by `lcalc/lcalc-1.23-r7`](https://github.com/cschwan/sage-on-gentoo/blob/master/sci-mathematics/lcalc/lcalc-1.23-r7.ebuild#L22), switching back to r6 solved the dependency problem.

Thank you for pointing me in the right direction.

**Comment by kiwifb** [comment]
`lcalc-1.23-r7` doesn't require `pari-2.8_prexxxx` at all. But `pari-2.8_prexxx` should masked by package.mask provided by the overlay so you must have unmasked it somehow. I should pin down the version of pari in sge 6.5 to avoid this kind of trouble when 6.6 is out. `lcalc-1.23-r7` is supposed to work with any version of pari and a rebuild of it is triggered if you change major version.
