### ISSUE TITLE
Sage ipython notebook is broken

### ISSUE THREAD

**Issue by strogdon** [cschwan/sage-on-gentoo#342]
I suppose someone will eventually hit upon this. In trying to launch the ipython notebook from Sage 
```
sage --notebook=ipython
```
and then attempting to create a `Sage` kernel notebook from the `New` menu I get
```
[I 14:48:36.658 NotebookApp] Creating new notebook in 
[E 14:48:38.283 NotebookApp] Unhandled error in API request
    Traceback (most recent call last):
      File "/usr/lib64/python2.7/site-packages/IPython/html/base/handlers.py", line 365, in wrapper
        result = yield gen.maybe_future(method(self, *args, **kwargs))
      File "/usr/lib64/python2.7/site-packages/IPython/html/services/sessions/handlers.py", line 53, in post
        model = sm.create_session(path=path, kernel_name=kernel_name)
      File "/usr/lib64/python2.7/site-packages/IPython/html/services/sessions/sessionmanager.py", line 66, in create_session
        kernel_name=kernel_name)
      File "/usr/lib64/python2.7/site-packages/IPython/html/services/kernels/kernelmanager.py", line 84, in start_kernel
        kernel_name=kernel_name, **kwargs)
      File "/usr/lib64/python2.7/site-packages/IPython/kernel/multikernelmanager.py", line 112, in start_kernel
        km.start_kernel(**kwargs)
      File "/usr/lib64/python2.7/site-packages/IPython/kernel/manager.py", line 240, in start_kernel
        **kw)
      File "/usr/lib64/python2.7/site-packages/IPython/kernel/manager.py", line 189, in _launch_kernel
        return launch_kernel(kernel_cmd, **kw)
      File "/usr/lib64/python2.7/site-packages/IPython/kernel/launcher.py", line 213, in launch_kernel
        proc = Popen(cmd, **kwargs)
      File "/usr/lib64/python2.7/subprocess.py", line 710, in __init__
        errread, errwrite)
      File "/usr/lib64/python2.7/subprocess.py", line 1335, in _execute_child
        raise child_exception
    OSError: [Errno 2] No such file or directory
[E 14:48:38.463 NotebookApp] {
      "Origin": "http://localhost:8888", 
      "Content-Length": "81", 
      "Accept-Language": "en-US,en;q=0.8", 
      "Accept-Encoding": "gzip, deflate", 
      "Connection": "keep-alive", 
      "Accept": "application/json, text/javascript, */*; q=0.01", 
      "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.76 Safari/537.36", 
      "Host": "localhost:8888", 
      "X-Requested-With": "XMLHttpRequest", 
      "Cookie": "org.cups.sid=dbc063b23835034b199d53116f670f80; nb_session_8080=; session=\"5M1ag1Ocp0ASrA1RSouq0bt/UIQ=?username=UydhZG1pbicKcDAKLg==\"", 
      "Referer": "http://localhost:8888/notebooks/Untitled.ipynb?kernel_name=sage_6_6_rc2", 
      "Content-Type": "application/x-www-form-urlencoded; charset=UTF-8"
    }
[E 14:48:38.463 NotebookApp] 500 POST /api/sessions (127.0.0.1) 305.88ms referer=http://localhost:8888/notebooks/Untitled.ipynb?kernel_name=sage_6_6_rc2
```
It's not clear on first glance where the problem is. I'm able to successfully create a `Python 2` notebook, but it doesn't appear to be Sage-aware. Of course this `Sage ipython notebook` is a work-in-progress.

**Comment by kiwifb** [comment]
I think we should post it on sage-devel, someone may give us a clue. I am guessing something is searched in the wrong directory even after I insisted on using get_ipython_dir.

**Comment by kiwifb** [comment]
Do you have any file named sage* under `~/.ipython`?

**Comment by strogdon** [comment]
Nothing with sage* directly under ~/.ipython. But there are folders starting as sage* under ~/.ipython/kernels. But these were probably created by vanilla Sage.

**Comment by kiwifb** [comment]
No that must be sage-on-gentoo. Vanilla defines `IPYTHONDIR` to be `.sage/ipithon` and puts its stuff there.

**Comment by kiwifb** [comment]
OK I am guessing this guy is wrong
```
more .ipython/kernels/sage_6_6_rc2/kernel.json 
{"display_name": "Sage 6.6.rc2", "argv": ["/usr/share/sage/sage", "-python", "-m", "sage.repl.ipython_kernel", "-f", "{connection_file}"]}
```
We don't have `/usr/share/sage/sage` that's one `sage` too many. I have to work out what it should be, I already kind of know where this file is produced.

**Comment by kiwifb** [comment]
```
        return [
            os.path.join(SAGE_ROOT, 'sage'),
            '-python',
            '-m', 'sage.repl.ipython_kernel',
            '-f', '{connection_file}',
        ]
```
in `sage/repl/ipython_kernel/install.py` it want the `sage` executable to execute a python script. Overly complicated for us. Patch coming later, do you know if a similar problem plagues sage 6.5?

**Comment by strogdon** [comment]
I don't know about sage 6.5. I don't have access to a machine with it installed at the moment.

**Comment by kiwifb** [comment]
I'll see if I can just figure it out.

**Comment by kiwifb** [comment]
Nope, I don't think we have anything like it in sage 6.5 or before. My last commit should fix things but I cannot really test it myself as my dev machine is on the  other side of the university firewall.

**Comment by strogdon** [comment]
Ditto here. I will have to wait to test it too since I don't have enough bandwidth to remotely spawn a browser and do anything meaningful in it. This laptop here is too slow to upgrade prefix. So I'm stuck with Sage 6.2

**Comment by strogdon** [comment]
This seems good here. At least I don't see any problem after testing. Closing.

**Comment by kiwifb** [comment]
Cool thx.
