### ISSUE TITLE
sage-doc install a lot of font images can we do something about it?

### ISSUE THREAD

**Issue by kiwifb** [cschwan/sage-on-gentoo#344]
With just English and French I have a couple hundred thousands files and I suspect most of them are `.png` for fonts. There should be a way of reducing this.

**Comment by kiwifb** [comment]
First bit of real work on this for further testing. As stated in the commit it may require the previous version of sage-doc to be unmerged first. It will also need adjusting for prefix, I only thought about it after merging but the final layout of the ebuild is not prefix safe.

**Comment by kiwifb** [comment]
Prefix support pushed.

**Comment by kiwifb** [comment]
With `LINGUAS="en fr" USE="html -pdf"` before the change `du -h /usr/share/doc/sage` reported 1.7G. With the new ebuild: 274MB. 

Out of this `du -h /usr/share/doc/sage/html/_static/` is 116MB.

I just generated a build the full html doc for all languages without removing the duplicate stuff: 2.8G. Small wonder that takes ages to merge.

**Comment by kiwifb** [comment]
Vanilla sage has a much smaller footprint and I thought it was down to a higher version of mathjax but I think that it is actually down to this patch https://github.com/sagemath/sage/blob/master/build/pkgs/mathjax/patches/nopng_config.patch

where png image of the fonts are suppressed. I wonder if we can set it while we are building sage-doc somehow rather than patching grossly like sage does.

**Comment by strogdon** [comment]
I'm a bit confused. So what is the origin of all these `.png` files? On gentoo
```
find /usr/share/doc/sage/ | grep png | wc -l
29564
```
and on vanilla Sage
```
find src/doc/output/ | grep png | wc -l
580
```
And are they really needed?

**Comment by kiwifb** [comment]
Where do they come from? Generated by `mathjax` as far as I understand. Are they all needed, well the apparent answer is no. The patch I quoted above to mathjax in vanilla sage is what removes most of them if I am not mistaken. Is your number with `sage-doc-9999-r1`? If so, does count links several times?

**Comment by strogdon** [comment]
Yes this is with `sage-doc-9999-r1`. I'm not sure what you mean by `does count links several times?`. I don't see any duplicates and most are under `sage/html/_static`.
```
find /usr/share/doc/sage/html/_static/ -name *.png | wc -l
28825
```

**Comment by kiwifb** [comment]
Before I created the link to the central location that folder was basically duplicated (with small variation) in every subfolder. That one of the reason we have such a huge number of files before this version of sage-doc. We still have a big number of files and a huge number at build time but it is an improvement.

It looks like there should be a way to do what the patch does at generation time and I think someone tried it but it didn't work - probably not done properly.
https://github.com/sagemath/sage/blob/master/src/doc/common/themes/sage/static/mathjax_sage.js_t

**Comment by strogdon** [comment]
Some thoughts? Including the patch https://github.com/sagemath/sage/blob/master/build/pkgs/mathjax/patches/nopng_config.patch when installing `mathjax` installs, in addition to the `png` image fonts other stuff.
```
ls /usr/share/mathjax/fonts/HTML-CSS/TeX/
eot  otf  png  svg  woff
```
Vanilla Sage keeps only the `woff` folder. In addition vanilla has a `HTML-CSS/STIX-Web/ ` folder that I don't see with `mathjax-2.2`. It seems that this line
```
exclude_patterns=['**/'+os.path.join(mathjax_relative, i) for i in ('docs', 'README*', 'test',
                                                                        'unpacked', 'LICENSE')]
```
in `src/doc/common/conf.py` is responsible for excluding stuff from being installed. If this line is changed to
```
exclude_patterns=['**/'+os.path.join(mathjax_relative, i) for i in ('docs', 'README*', 'test',
                                                                        'unpacked', 'LICENSE', 'fonts/HTML-CSS/TeX/png')]
```
then the `png` folder is not copied over to the `image` folder prior to install in the `live` system.
```
ls /usr/share/doc/sage/html/_static/fonts/HTML-CSS/TeX/
eot  otf  svg  woff
```
and
```
find /usr/share/doc/sage/html/_static/ -type f -name *.png | wc -l
15
```
I don't know if this breaks anything and I'm not sure how to test it.

**Comment by kiwifb** [comment]
Well, that sounds interesting indeed, we need to have a nice formula rendered in the notebook to see if it has an impact.

**Comment by strogdon** [comment]
OK, with this `new` setup, if I remove the `usr/share/doc/sage/html/_static` folder then the static version of the documentation is really ugly and with the `_static` folder in place it looks like it should look. I'm not fully conversant on how to use `MathJax` in the notebook but if I enter
```
html('\[\int_{-1}^1\int_{-\sqrt{1-x^2}}^{\sqrt{1-x^2}}\int_{-\sqrt{1-x^2-y^2}}^{\sqrt{1-x^2-y^2}}\,e^{(x^2+y^2+z^2)^{3/2}}\;{\mathrm d}z\,{\mathrm d}y\,{\mathrm d}x\]')
```
then I get an appropriately type set formula on which if I right-click I get a `MathJax` menu.

**Comment by strogdon** [comment]
I do observe some anomalous behavior with firefox-31.5.3 and seamonkey-2.33.1. The above was with chromium-41.0.2272.118. See https://groups.google.com/forum/#!topic/sage-devel/ZgsHt0Hqg6o for reference. With the `png` (image fonts) removed I get a similar problem when viewing `weyl_algebra.html` with firefox or seamonkey. However, with the `png` fonts in place there doesn't appear to be a problem. But the problem would exist also when running vanilla sage with firefox or seamonkey.

**Comment by kiwifb** [comment]
I am updating mathjax on my box to see if it will get rid of some math typesetting error I see in the notebook. The install time of mathjax 2.2 correlates nicely with the install of sage-doc.
```
genlop -t mathjax
 * dev-libs/mathjax

     Fri Oct 17 22:07:33 2014 >>> dev-libs/mathjax-2.2
       merge time: 30 minutes and 46 seconds.
```
mathjax 2.4 installs faster may be it will have an impact.

**Comment by kiwifb** [comment]
Suggested improvement to portage to process png files faster at https://bugs.gentoo.org/show_bug.cgi?id=630292 . All png files are gathered and are passed to pngfix for inspection/fixing. In my case ~32000 files.

It is all serial. The suggested enhancement will make the processing parallel. Of course it is best done on a fast file system like shm.

**Comment by kiwifb** [comment]
Last issue with the new way of doing thing. We need to hard block old version of sage as some directories are replaced by symlinks which is a no-no in the PMS and portage will object to it.

**Comment by strogdon** [comment]
A preliminary emerge of `sage-9999` in Prefix seems to indicate a regression. It now takes a significant amount of time to perform the install compared to the situation prior to https://github.com/cschwan/sage-on-gentoo/commit/460dcbb85da2f4d26ec1df1a56f335a93e40f0c4. Again this is just preliminary.

**Comment by kiwifb** [comment]
Strange, it is noticeably faster for me. The number of files to be checked and copied dropped dramatically.

**Comment by strogdon** [comment]
I also noticed that prior to https://github.com/cschwan/sage-on-gentoo/commit/460dcbb85da2f4d26ec1df1a56f335a93e40f0c4  an uninstall only checked
3, maybe 4 folders for collisions (I don't know which ones now). But after the commit all of the `_static` symlinks are checked. Again this is in Prefix.

**Comment by kiwifb** [comment]
Hum, that could be coincidental with the last portage update.

**Comment by strogdon** [comment]
And uninstallng when installed without the commit only checks
```
 * Directory symlink(s) may need protection:
 * 
 * 	/storage/strogdon/gentoo-rap/usr/share/jupyter/kernels/sagemath/doc
 * 	/storage/strogdon/gentoo-rap/usr/share/jupyter/nbextensions/jsmol
 * 	/storage/strogdon/gentoo-rap/usr/share/jupyter/nbextensions/mathjax
```
instead of all the `_static` symlinks.

**Comment by kiwifb** [comment]
Looking at the output of `genlop -t sage` my speed up must be completely subjective. Unless there is something that is not included in the timing. Even my small patch to portage to get pngfix run faster doesn't add to something that is a big win.
At least there should be a win in term of space and number of files installed. Not as much as when I started to link all the `_static` subfolders to a main copy though.

**Comment by kiwifb** [comment]
I consider this finished for the time being.
