### ISSUE TITLE
sage-jmol-bin doesn't install jmol script

### ISSUE THREAD

**Issue by strogdon** [cschwan/sage-on-gentoo#347]
sage-jmol-bin installs the `Jmol` script but not `jmol`. Apparently `jmol` is needed since from the Sage prompt
```
sage: sphere()
Launched jmol viewer for Graphics3d Object
```
and the `jmol` viewer isn't spawned. Adding a symlink `jmol -> Jmol` fixes this. Or perhaps Sage should be patched to use `Jmol`? On my Prefix things work because an old `jmol` script was never removed. But on Gentoo there is no `jmol`. This is somewhat odd since from the notebook `sphere()` does work, with the exception of a problem with fonts. There is
```
Error typesetting mathematics 
```
But this is a separate issue, perhaps `mathjax` related.

**Comment by strogdon** [comment]
The
```
Error typesetting mathematics 
```
is present on sage-6.6 as well as 6.7.beta1

**Comment by kiwifb** [comment]
An oversight on my part obviously. May be I have an old link on my system too. I'll have to check on Monday. I'll see if I can commit a proper fix from my mac - my normal machine is off because electricity is to be cut in my campus building over the week end.

**Comment by strogdon** [comment]
The
```
Error typesetting mathematics
```
in the notebook seemed to be confined to Prefix. I didn't imagine this, but upon removing `mathjax` and re-installing it the issue went away. I don't see how, but it did.

**Comment by kiwifb** [comment]
`dosym` is driving me up the wall. Either it is completely or it is broken in my mac prefix. When I try to use it does seem to create the right symlink as desired. The problem is that it also destroy the file it links too.

**Comment by strogdon** [comment]
I noticed with the old jmol ebuilds that the launcher script was called `jmol`, but apparently that won't work here. I suppose we could, though redundant, create two launcher scripts by adding
```
        java-pkg_dolauncher ${MY_PM} --main org.openscience.jmol.app.Jmol \
                --java_args "-Xmx512m"
```
It is odd that the notebook, apparently, uses `Jmol` while from the Sage prompt `jmol` is used?

**Comment by strogdon** [comment]
In thinking a bit more the `{j,J}mol` launcher script is probably not called from the notebook.

**Comment by strogdon** [comment]
I'm wondering if the launcher script should be installed as `jmol` and not `Jmol`? Would that break anything? I believe vanilla Sage installs it that way.

**Comment by kiwifb** [comment]
Two instances I believe start jmol as `jmol` are in `repl/rich_output/backend_ipython.py` and `structure/graphics_file.py`. The notebook can load the applet directly. `Jmol` doesn't seem to ever be called as an executable inside of sage as far as I can see.

**Comment by kiwifb** [comment]
I believe I can easily get the launcher script changed to `jmol` instead of `Jmol` I am fairly sure using `Jmol` was an oversight.

**Comment by kiwifb** [comment]
OK pushed a fix. You will have to update sage-jmol-bin.

**Comment by strogdon** [comment]
I'm good here. Closing.
