### ISSUE TITLE
sci-mathematics/flint-2.4.4-r1 emake failed

### ISSUE THREAD

**Issue by chi86** [cschwan/sage-on-gentoo#357]
Hi,
it just updated sage and i have the problem, that the emerge of flint crashes:

...
make[3]: Entering directory '/var/tmp/portage/sci-mathematics/flint-2.4.4-r1/work/flint-2.4.4'
x86_64-pc-linux-gnu-g++ -fPIC -O2 -march=athlon64 -pipe -DFLINT_CPIMPORT=\"/usr/share/flint/CPimport.txt\" -I/var/tmp/portage/sci-mathematics/flint-2.4.4-r1/work/flint-2.4.4 -I/usr/include -I/usr/include -I/usr/include -c interfaces/NTL-interface.cpp -o build/interfaces/NTL-interface.lo;
In file included from interfaces/NTL-interface.cpp:37:0:
/usr/include/NTL/g_lip.h: In function ‘long int _ntl_gmaxalloc(_ntl_gbigint)’:
/usr/include/NTL/g_lip.h:399:10: error: redefinition of ‘long int _ntl_gmaxalloc(_ntl_gbigint)’
     long _ntl_gmaxalloc(_ntl_gbigint x)
          ^
In file included from /usr/include/NTL/lip.h:12:0,
                 from /usr/include/NTL/ZZ.h:18,
                 from interfaces/NTL-interface.cpp:32:
/usr/include/NTL/g_lip.h:399:10: error: ‘long int _ntl_gmaxalloc(_ntl_gbigint)’ previously defined here
     long _ntl_gmaxalloc(_ntl_gbigint x)
          ^
Makefile:244: recipe for target 'build/interfaces/NTL-interface.lo' failed
make[3]: *** [build/interfaces/NTL-interface.lo] Error 1
make[3]: Leaving directory '/var/tmp/portage/sci-mathematics/flint-2.4.4-r1/work/flint-2.4.4'
x86_64-pc-linux-gnu-g++: error: build/interfaces/NTL-interface.lo: No such file or directory
Makefile:136: recipe for target 'libflint.so' failed
make[2]: *** [libflint.so] Error 1
make[2]: Leaving directory '/var/tmp/portage/sci-mathematics/flint-2.4.4-r1/work/flint-2.4.4'
Makefile:163: recipe for target 'library' failed
make[1]: *** [library] Error 2
make[1]: Leaving directory '/var/tmp/portage/sci-mathematics/flint-2.4.4-r1/work/flint-2.4.4'
Makefile:100: recipe for target 'verbose' failed
make: *** [verbose] Error 2
 * ERROR: sci-mathematics/flint-2.4.4-r1::gentoo failed (compile phase):
 *   emake failed
 * 
 * If you need support, post the output of `emerge --info '=sci-mathematics/flint-2.4.4-r1::gentoo'`,
 * the complete build log and the output of `emerge -pqv '=sci-mathematics/flint-2.4.4-r1::gentoo'`.
 * The complete build log is located at '/var/tmp/portage/sci-mathematics/flint-2.4.4-r1/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/sci-mathematics/flint-2.4.4-r1/temp/environment'.
 * Working directory: '/var/tmp/portage/sci-mathematics/flint-2.4.4-r1/work/flint-2.4.4'
 * S: '/var/tmp/portage/sci-mathematics/flint-2.4.4-r1/work/flint-2.4.4'

Is it just my problem or did someone else noticed this?

**Comment by kiwifb** [comment]
You shouldn't be using `flint-2.4.4` but `flint-2.4.5`. You are probably not using the right keyword file. The problem you have is that flint 2.4.4 from the tree is not compatible with `ntl-6.2.1` but `flint-2.4.5` is. 
Did you link `package.keywords/sage` inside your `/etc/portage/package.accept_keywords` folder?

**Comment by chi86** [comment]
Ok no I did not link that. I 'put package.keywords/sage' inside my '/etc/portage/package.accept_keywords' but it still emerged 'flint-2.4.4'!

**Comment by kiwifb** [comment]
You should use a link rather than copying because we are updating that file. Can you give the output of `eix flint`?

**Comment by chi86** [comment]
irrenfried # eix flint
[I] sci-mathematics/flint
     Available versions:  ~2.3^m ~2.4.3^m 2.4.4-r1^m ~2.4.5^m {doc gc ntl static-libs test}
     Installed versions:  2.4.4-r1^m(01:02:19 PM 10/13/2014)(ntl -doc -gc -static-libs -test)
     Homepage:            http://www.flintlib.org/
     Description:         Fast Library for Number Theory

[I] sci-mathematics/flintqs [1]
     Available versions:  (~)20070817^m
     Installed versions:  20070817^m(11:07:06 AM 10/13/2014)
     Homepage:            http://www.sagemath.org/
     Description:         William Hart's GPL'd highly optimized multi-polynomial quadratic sieve for integer factorization

* sys-infiniband/mstflint
     Available versions:  
     (3.5)  ~1.4-r1
     (3.12) ~3.5.0
     Homepage:            http://www.openfabrics.org/
     Description:         Mellanox firmware burning application

[1] "sage-on-gentoo" /var/lib/layman/sage-on-gentoo

Found 3 matches.

**Comment by chi86** [comment]
How do I use a link? I have nver done that before.

**Comment by kiwifb** [comment]
Clearly it has worked properly. `/etc/portage/package.accept_keywords` can be a file or directory. If it is a directory all the files in it are scanned for keywords. So from `/etc/portage/package.accept_keywords/` do `ln -s /var/lib/layman/sage-on-gentoo/package.keywords/sage sage`.

**Comment by chi86** [comment]
Thanks it works now!!!!!!

**Comment by kiwifb** [comment]
Good.
