### ISSUE TITLE
Sage docs fail to build

### ISSUE THREAD

**Issue by strogdon** [cschwan/sage-on-gentoo#361]
I have seen this on two different occasions - one with a 6.8.betaX and now with 6.8.rc0 so maybe there is something. So far restarting the build fixed things. The build failure is
```
Building reference manual, first pass.

[dynamics ] Exception occurred:
[dynamics ] File "/usr/lib64/python2.7/site-packages/matplotlib/font_manager.py", line 949, in pickle_dump
[dynamics ] with open(filename, 'wb') as fh:
[dynamics ] IOError: [Errno 2] No such file or directory: u'/var/tmp/portage/sci-mathematics/sage-9999/temp/matplotlib-root/fontList.cache'
[dynamics ] The full traceback has been saved in /var/tmp/portage/sci-mathematics/sage-9999/temp/sphinx-err-uyPt2Q.log, if you want to report the issue to the developers.
[dynamics ] Please also report this if it was a user error, so that a better error message can be provided next time.
[dynamics ] A bug report can be filed in the tracker at <https://bitbucket.org/birkenfeld/sphinx/issues/>. Thanks!
Error building the documentation.
Traceback (most recent call last):
  File "doc/common/builder.py", line 1626, in <module>
    getattr(get_builder(name), type)()
  File "doc/common/builder.py", line 292, in _wrapper
    getattr(get_builder(document), 'inventory')(*args, **kwds)
  File "doc/common/builder.py", line 503, in _wrapper
    x.get(99999)
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 558, in get
    raise self._value
OSError: [dynamics ] Exception occurred:
```
The content of `sphinx-err-uyPt2Q.log` is:
```
# Sphinx version: 1.2.2
# Python version: 2.7.9
# Docutils version: 0.12 release
# Jinja2 version: 2.7.3
# Loaded extensions:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/sphinx/cmdline.py", line 253, in main
    warningiserror, tags, verbosity, parallel)
  File "/usr/lib64/python2.7/site-packages/sphinx/application.py", line 119, in __init__
    self.setup_extension(extension)
  File "/usr/lib64/python2.7/site-packages/sphinx/application.py", line 325, in setup_extension
    mod = __import__(extension, None, None, ['setup'])
  File "/usr/lib64/python2.7/site-packages/matplotlib/sphinxext/plot_directive.py", line 165, in <module>
    import matplotlib.pyplot as plt
  File "/usr/lib64/python2.7/site-packages/matplotlib/pyplot.py", line 27, in <module>
    import matplotlib.colorbar
  File "/usr/lib64/python2.7/site-packages/matplotlib/colorbar.py", line 34, in <module>
    import matplotlib.collections as collections
  File "/usr/lib64/python2.7/site-packages/matplotlib/collections.py", line 27, in <module>
    import matplotlib.backend_bases as backend_bases
  File "/usr/lib64/python2.7/site-packages/matplotlib/backend_bases.py", line 56, in <module>
    import matplotlib.textpath as textpath
  File "/usr/lib64/python2.7/site-packages/matplotlib/textpath.py", line 19, in <module>
    import matplotlib.font_manager as font_manager
  File "/usr/lib64/python2.7/site-packages/matplotlib/font_manager.py", line 1412, in <module>
    _rebuild()
  File "/usr/lib64/python2.7/site-packages/matplotlib/font_manager.py", line 1399, in _rebuild
    pickle_dump(fontManager, _fmcache)
  File "/usr/lib64/python2.7/site-packages/matplotlib/font_manager.py", line 949, in pickle_dump
    with open(filename, 'wb') as fh:
IOError: [Errno 2] No such file or directory: u'/var/tmp/portage/sci-mathematics/sage-9999/temp/matplotlib-root/fontList.cache'
```
and the `temp` folder contains:

ls -al
```
total 2884
drwxrwxr-x 5 portage portage    4096 Jul 15 22:06 .
drwxrwxr-x 7 portage portage    4096 Jul 15 21:51 ..
-rw-rw-r-- 1 portage portage 1326568 Jul 15 21:51 build-python2_7.log
-rw-rw---- 1 portage portage 1364678 Jul 15 21:51 build.log
-rw-rw-r-- 1 portage portage   11604 Jul 15 21:50 eclass-debug.log
-rw-rw-r-- 1 portage portage  192919 Jul 15 21:40 environment
-rw-rw-r-- 1 portage portage    3437 Jul 15 21:39 epatch.log
-rw-rw-r-- 1 portage portage       5 Jul 15 21:39 epatch_user.log
drwxrwxr-x 2 portage portage    4096 Jul 15 21:51 logging
-rw-r--r-- 1 root    root          0 Jul 15 22:06 ls_al
drwxrwxr-x 2 portage portage    4096 Jul 15 21:39 matplotlib-
drwxrwxr-x 4 portage portage    4096 Jul 15 21:39 python2.7
-rw-rw-r-- 1 portage portage     230 Jul 15 21:39 sage-sage.desktop
-rw------- 1 portage portage    1891 Jul 15 21:51 sphinx-err-uyPt2Q.log
```
Perhaps parallel build? The `matplotlib-root` folder doesn't exist and and while watching the contents of the `temp` folder evolve while building, the `matplotlib-root` folder never appears; even on a successful build.

**Comment by kiwifb** [comment]
Yes I have seen this repeatedly and randomly. I added a line in the ebuild to create the folder in question at the level of 6.8.beta8 and haven't seen the problem since. But obviously that was just luck. I see from your listing that my fix isn't good. it created `matplotlib-` instead of `matplotlib-root`. I think I can fix that.

It is a parallel build issue and a `sphinx` issue. `sphinx` should check that the folder exists before trying to open the file. Can you attach `sphinx-err-uyPt2Q.log` that would help patch it.

**Comment by strogdon** [comment]
`sphinx-err-uyPt2Q.log` is listed above.

**Comment by kiwifb** [comment]
So it is. So actually what needs to be fixed is matplotlib. I'll look into it later.

**Comment by strogdon** [comment]
I've only seen the failure on Gentoo. If it were to fail in Prefix would the missing folder still be `matplotlib-root`?

**Comment by kiwifb** [comment]
No. When I use `ebuild` as a regular user to test the build my user name is used. It looks like when you use `emerge` as root `$USER` is not set. Anyway I have just pushed what I hope is a more subtle fix. I may have to re-introduce creation of the folder though, but the logic in matplotlib should clearly create it. At least if I have to create it I shouldn't be dependent on the content of `$USER` anymore.

**Comment by strogdon** [comment]
From `matplotlib/font_manager.py` there is
```
    if not 'TRAVIS' in os.environ:
        cachedir = get_cachedir()
        if cachedir is not None:
            if six.PY3:
                _fmcache = os.path.join(cachedir, 'fontList.py3k.cache')
            else:
                _fmcache = os.path.join(cachedir, 'fontList.cache')
```
As root from python
```
>>> import matplotlib
>>> from matplotlib import get_cachedir
>>> get_cachedir()
u'/root/.cache/matplotlib'
```
On my machine there is the `.cache/matplotlib` folder but it is empty. I'm not sure what `get_cachedir()` is to return from within portage, nor why parallel building interferes.

**Comment by kiwifb** [comment]
Yes I am not sure either why we get `temp/matplotlib-root` in portage. Why not `homedir/.cache/matplotlib`? There may be a eclass or `matplotlibrc` specially for portage.

**Comment by strogdon** [comment]
The recent commit does appear to be the correct thing to do. At least `temp/matplotlib` is created with appropriate `*.cache` files. It's a wonder things would build previously? I'll let you close when you think building is correctly being handled.

**Comment by kiwifb** [comment]
I will leave this opened for a month at least to see if all occurrences are squashed. The failure is random probably because the folder was not created in time or was being created by another process. It is quite strange that upstream seems unaffected.

That being said I have issue with Gentoo's python threading that I don't have with sage's python. It is especially manifest with doctesting. But I don't know what's causing it. Any difficulties on that front?

**Comment by strogdon** [comment]
I haven't noticed any obvious threading issues. Let me know if you have a use case.

What I do find odd is, when there is a failure, that there is a search in `temp/matplotlib-root` for a `.cache` file. I don't see where the origin of the `matplotlib-root` is from the code.

**Comment by kiwifb** [comment]
It comes from right here:
```
fbissey@QCD-nzi3 ~ $ grep -rI matplotlib- /usr/lib64/python2.7/site-packages/matplotlib/*
/usr/lib64/python2.7/site-packages/matplotlib/__init__.py:    tempdir = os.path.join(tempdir, 'matplotlib-%s' % getpass.getuser())
/usr/lib64/python2.7/site-packages/matplotlib/mlab.py:                "matplotlib/files/matplotlib-toolkits, or use interp='linear' "
```
in `matplotlib/__init__.py` and I think what I have done completely bypass that function. May be I should ask upstream to make sure it exist in that function.

As for threading well, my machine has 12 cores and if I do more than `-tp 3` I'll get time outs (bucket loads). Individual python threads are showing between 400% and 500% cpu utilisation in `top` a sign of multithreading or use of openmp. May be it is openblas playing up... I may have some of checking that.

**Comment by strogdon** [comment]
With `export MPLCONFIGDIR="${T}"/matplotlib` removed from the sage ebuild I've been unable to produce a failure in Prefix. And there is no hint of a `fontList.cache` file anywhere. Very strange.

**Comment by kiwifb** [comment]
I am somewhat unsurprised by prefix not having a problem. Stuff can escape the sandbox in prefix especially at the moment (do you get message about "sandbox binary disabled"?). prefix seems in a strange shape right now.

**Comment by strogdon** [comment]
Yes, I see `!!! Problem with sandbox binary. Disabling...`.  Also - I have seen posts on gentoo-alt - but be wary of `sys-apps/portage-2.2.20`. It does not respect package masks!

**Comment by strogdon** [comment]
How quickly I forget. This issue is exactly the same as reported on https://github.com/cschwan/sage-on-gentoo/issues/210. However then the failure was in Prefix.

**Comment by strogdon** [comment]
I checked on vanilla Sage. There `MPLCONFIGDIR` is set to`$DOT_SAGE/matplotlib-VER` for compatibility reasons (see src/doc/en/installation/source.rst). `VER` is currently `1.4.3`. If, from the vanilla Sage repo, I
```
rm -rf $DOT_SAGE/matplotlib-VER
make doc-clean
make
```
then almost immediately the `$DOT_SAGE/matplotlib-VER` folder is recreated and as the build starts the `*.cache` stuff in that folder is generated. I suspect this is what prevents parallel build issues with sphinx. So, I believe your approach of setting `MPLCONFIGDIR` is the thing to do. Whether one should have to do this is yet another issue.

**Comment by kiwifb** [comment]
issue #210 has become way too big to casually read. But it makes sense, I believe that's an issue to potentially raise with matplotlib, the default folder should be created earlier but with all what you dug in mind, I think we can close this.
