### ISSUE TITLE
problems lazy_importing sandpiles

### ISSUE THREAD

**Issue by kiwifb** [cschwan/sage-on-gentoo#362]
All the doctest about sandpiles are failing here. Mostly because this line in `sage/sandpiles/all.py`

```
lazy_import('sage.sandpiles.examples', 'sandpiles')
```

`sandpiles` which should be the name under which `examples` is imported just doesn't stick and I cannot figure a way to make it.

**Comment by kiwifb** [comment]
Interestingly, no problems on my `hp1` prefix.

**Comment by strogdon** [comment]
Here if I change
```
sage.misc.lazy_import.lazy_import('sage.sandpiles.all', '*', globals())
```
to
```
from sage.sandpiles.all import *
```
in `sage/all.py` then I'm able to doctest `sage/sandpiles` without failures. How is `sage/all.py` generated? I don't see any changes to it in ticket http://trac.sagemath.org/ticket/18618 where `sandpiles` was changed.

**Comment by strogdon** [comment]
Perhaps the problem (sometimes?) is using `lazy_import` to import a file which itself uses `lazy_import`?

**Comment by kiwifb** [comment]
git blame says that line has been last changed in December 2012 https://github.com/sagemath/sage/commit/2609dec19eae79d59d68837b2856320bc617ca0c and you just reverted that line to its previous state. You are probably right that the double lazy_import may be to blame. I just wonder why I don't have the problem in prefix. I am wondering if a dependency is not met at the correct version.

**Comment by strogdon** [comment]
I do have the problem in my prefix.

**Comment by kiwifb** [comment]
I think I didn't have the problem in my prefix because it was brand new. Try
```
rm -f ~/.sage/cache/*
```

**Comment by kiwifb** [comment]
In vanilla the file in `.sage/cache` is somewhat versioned by the path ~SAGE_SRC` in `sage/misc/lazy_import_cache.py`:
```
    mangled = os.path.realpath(SAGE_SRC).replace(os.sep, '_')
    return os.path.join(DOT_SAGE, 'cache',
                        "%s-lazy_import_cache.pickle" % mangled)
```
I don't know if replacing `mangled` with something else (a version string) would hurt but it would be a good way to avoid problems.

**Comment by kiwifb** [comment]
I think I could replace `SAGE_SRC` by `SAGE_VERSION` without any ill effects. I may try to convince upstream to back that change.

**Comment by strogdon** [comment]
Yes, removing the cache folder contents allowed the doctests to pass.

**Comment by kiwifb** [comment]
OK my change didn't have any side effects and should prevent a stale pickle to interfere in the future so I am closing this issue.

**Comment by kiwifb** [comment]
Re-opening because I am removing the work around for experiments and I want to easily find this.

**Comment by kiwifb** [comment]
Nothing broke so far. Closing again.
