### ISSUE TITLE
Unmet requirements

### ISSUE THREAD

**Issue by chi86** [cschwan/sage-on-gentoo#364]
Hello!
I got your mail regarding upgrade to sage-6.8 and I tried to do that but the problem is I have some unmet requirements, which is wired because I use your package.use included as link!

Here is the output:
emerge @preserved-rebuild

 * IMPORTANT: 1 news items need reading for repository 'gentoo'.
 * Use eselect news read to view new items.

Calculating dependencies -

!!! Problem resolving dependencies for sci-mathematics/sage:0 from @preserved-rebuild
... done!

!!! The ebuild selected to satisfy "sci-mathematics/sage:0" has unmet requirements.
- sci-mathematics/sage-6.8::sage-on-gentoo USE="X bin-html pdf -arb -bliss -debug -html -latex -modular_decomposition -testsuite" ABI_X86="64" LINGUAS="-ca -de -en -fr -hu -it -pt -ru -tr" PYTHON_TARGETS="python2_7"

  The following REQUIRED_USE flag constraints are unsatisfied:
    bin-html? ( !pdf linguas_en )

  The above constraints are a subset of the following complete expression:
    html? ( linguas_en ) testsuite? ( any-of ( bin-html html ) ) bin-html? ( !html !pdf linguas_en ) any-of ( python_targets_python2_7 )

(dependency required by "@preserved-rebuild" [argument])

Thanks!!!!!

**Comment by kiwifb** [comment]
Hi,

yes the html documentation (`html` or `bin-html` useflags) requires `LINGUAS=en` in `make.conf` or `package.env`. Alternatively you can use `linguas_en` in `package.use` but using `LINGUAS` is better.

**Comment by chi86** [comment]
Thanks but there is still a problem:
Calculating dependencies /

!!! Problem resolving dependencies for sci-mathematics/sage from @selected
... done!

!!! The ebuild selected to satisfy "sci-mathematics/sage" has unmet requirements.
- sci-mathematics/sage-6.8::sage-on-gentoo USE="X bin-html pdf -arb -bliss -debug -html -latex -modular_decomposition -testsuite" ABI_X86="64" LINGUAS="en -ca -de -fr -hu -it -pt -ru -tr" PYTHON_TARGETS="python2_7"

  The following REQUIRED_USE flag constraints are unsatisfied:
    bin-html? ( !pdf )

  The above constraints are a subset of the following complete expression:
    html? ( linguas_en ) testsuite? ( any-of ( bin-html html ) ) bin-html? ( !html !pdf linguas_en ) any-of ( python_targets_python2_7 )

(dependency required by "@selected" [set])
(dependency required by "@world" [argument])

I could fix it in my own package.use but than I have sage dependencies in my package.use and in the sage one ....

**Comment by kiwifb** [comment]
I didn't want to force it on people by default but I could provide an extra file you could link inside the package.use folder. In this particular case we need to add 
```
sci-mathematics/sage bin-html -html -pdf linguas_en
```
I guess you could call it `sage-bin-html` it is ok to have useflags for sage in multiple files. In case of conflict the last one to be read (lexical order) wins.

**Comment by chi86** [comment]
Ok I did create a new file (sage-bin-html) in my package.use folder and I also had to put the following in my "package.accept_keywords" (I temporary created a new file "sage-6.8" ):

# required by sci-mathematics/octave-3.8.2::gentoo
# required by @selected
# required by @world (argument)
=sci-libs/cxsparse-3.1.2 ~amd64
# required by sci-mathematics/rw-0.7::gentoo[executable]
# required by sci-mathematics/sage-6.8::sage-on-gentoo
# required by sci-mathematics/sage-notebook-0.11.4-r3::sage-on-gentoo
# required by @selected
# required by @world (argument)
=dev-libs/igraph-0.7.1-r1 ~amd64

And it stared emerging! Thanks!

**Comment by kiwifb** [comment]
Ah yes, `cxsparse` and `igraph` are pulled by `rw[executable]` with `-executable` they wouldn't be required. I should add them by default, that's the best thing to do.

**Comment by chi86** [comment]
Ok it was to fast with the replay :). I got another error with pynac :

emerge =sci-libs/pynac-0.3.7

 * IMPORTANT: 1 news items need reading for repository 'gentoo'.
 * Use eselect news read to view new items.

Calculating dependencies... done!
>>> Verifying ebuild manifests
>>> Emerging (1 of 1) sci-libs/pynac-0.3.7::sage-on-gentoo
>>> Failed to emerge sci-libs/pynac-0.3.7, Log file:
>>>  '/var/tmp/portage/sci-libs/pynac-0.3.7/temp/build.log'
>>> Jobs: 0 of 1 complete, 1 failed                 Load avg: 0.58, 0.72, 0.99
 * Package:    sci-libs/pynac-0.3.7
 * Repository: sage-on-gentoo
 * Maintainer: sci@gentoo.org
 * USE:        abi_x86_64 amd64 elibc_glibc kernel_linux python_targets_python2_7 userland_GNU
 * FEATURES:   preserve-libs sandbox userpriv usersandbox
>>> cfg-update-1.8.2-r1: Checksum index is up-to-date ...
>>> Unpacking source...
>>> Source unpacked in /var/tmp/portage/sci-libs/pynac-0.3.7/work
>>> Preparing source in /var/tmp/portage/sci-libs/pynac-0.3.7/work/pynac-0.3.7 ...
 * Running eautoreconf in '/var/tmp/portage/sci-libs/pynac-0.3.7/work/pynac-0.3.7' ...
 * ERROR: sci-libs/pynac-0.3.7::sage-on-gentoo failed (prepare phase):
 *   Cannot find the latest automake! Tried 1.15:1.15
 * 
 * Call stack:
 *     ebuild.sh, line   93:  Called src_prepare
 *   environment, line 4028:  Called autotools-utils_src_prepare
 *   environment, line  988:  Called eautoreconf
 *   environment, line 1347:  Called _elibtoolize '--install' '--copy' '--force'
 *   environment, line  434:  Called autotools_run_tool 'libtoolize' '--install' '--copy' '--force' '--automake'
 *   environment, line 1087:  Called autotools_env_setup
 *   environment, line 1040:  Called die
 * The specific snippet of code:
 *           [[ ${WANT_AUTOMAKE} == "latest" ]] && die "Cannot find the latest automake! Tried ${_LATEST_AUTOMAKE[*]}";
 * 
 * If you need support, post the output of `emerge --info '=sci-libs/pynac-0.3.7::sage-on-gentoo'`,
 * the complete build log and the output of `emerge -pqv '=sci-libs/pynac-0.3.7::sage-on-gentoo'`.
 * The complete build log is located at '/var/tmp/portage/sci-libs/pynac-0.3.7/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/sci-libs/pynac-0.3.7/temp/environment'.
 * Working directory: '/var/tmp/portage/sci-libs/pynac-0.3.7/work/pynac-0.3.7'
 * S: '/var/tmp/portage/sci-libs/pynac-0.3.7/work/pynac-0.3.7'

 * Messages for package sci-libs/pynac-0.3.7:

 * ERROR: sci-libs/pynac-0.3.7::sage-on-gentoo failed (prepare phase):
 *   Cannot find the latest automake! Tried 1.15:1.15
 * 
 * Call stack:
 *     ebuild.sh, line   93:  Called src_prepare
 *   environment, line 4028:  Called autotools-utils_src_prepare
 *   environment, line  988:  Called eautoreconf
 *   environment, line 1347:  Called _elibtoolize '--install' '--copy' '--force'
 *   environment, line  434:  Called autotools_run_tool 'libtoolize' '--install' '--copy' '--force' '--automake'
 *   environment, line 1087:  Called autotools_env_setup
 *   environment, line 1040:  Called die
 * The specific snippet of code:
 *           [[ ${WANT_AUTOMAKE} == "latest" ]] && die "Cannot find the latest automake! Tried ${_LATEST_AUTOMAKE[*]}";
 * 
 * If you need support, post the output of `emerge --info '=sci-libs/pynac-0.3.7::sage-on-gentoo'`,
 * the complete build log and the output of `emerge -pqv '=sci-libs/pynac-0.3.7::sage-on-gentoo'`.
 * The complete build log is located at '/var/tmp/portage/sci-libs/pynac-0.3.7/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/sci-libs/pynac-0.3.7/temp/environment'.
 * Working directory: '/var/tmp/portage/sci-libs/pynac-0.3.7/work/pynac-0.3.7'
 * S: '/var/tmp/portage/sci-libs/pynac-0.3.7/work/pynac-0.3.7'

**Comment by kiwifb** [comment]
How did you end up with `pynac-0.3.7`? sage 6.8 uses `0.3.9.2`. Anyway what does `eix automake` report?

**Comment by chi86** [comment]
I got this when I tried 0.3.9.2:

emerge =sci-libs/pynac-0.3.9.2

 * IMPORTANT: 1 news items need reading for repository 'gentoo'.
 * Use eselect news read to view new items.

Calculating dependencies... done!
[ebuild     U ~] sci-libs/pynac-0.3.9.2 [0.3.7]

!!! Multiple package instances within a single package slot have been pulled
!!! into the dependency graph, resulting in a slot conflict:

sci-libs/pynac:0

  (sci-libs/pynac-0.3.9.2:0/0::sage-on-gentoo, ebuild scheduled for merge) pulled in by
    =sci-libs/pynac-0.3.9.2 (Argument)

  (sci-libs/pynac-0.3.7:0/0::sage-on-gentoo, installed) pulled in by
    ~sci-libs/pynac-0.3.7[python_targets_python2_7(-)?,-python_single_target_python2_7(-)] required by (sci-mathematics/sage-6.7-r1:0/0::sage-on-gentoo, installed)
    ^               ^^^^^                                                                                                                                                                                                 


It may be possible to solve this problem by using package.mask to
prevent one of those packages from being selected. However, it is also
possible that conflicting dependencies exist such that they are
impossible to satisfy simultaneously.  If such a conflict exists in
the dependencies of two different packages, then those packages can
not be installed simultaneously. You may want to try a larger value of
the --backtrack option, such as --backtrack=30, in order to see if
that will solve this conflict automatically.

For more information, see MASKED PACKAGES section in the emerge man
page or refer to the Gentoo Handbook.

**Comment by chi86** [comment]
eix automake
[I] sys-devel/automake
     Available versions:  
     (1.4)  1.4_p6-r2
     (1.5)  1.5-r2
     (1.6)  1.6.3-r2
     (1.7)  1.7.9-r3
     (1.8)  1.8.5-r5
     (1.9)  1.9.6-r4
     (1.10) 1.10.3-r1
     (1.11) 1.11.6-r1
     (1.12) 1.12.6
     (1.13) 1.13.4
     (1.14) 1.14.1
     (1.15) ~1.15
     (9999) **9999
     Installed versions:  1.11.6-r1(1.11)(07:58:43 AM 11/17/2014) 1.14.1(1.14)(02:23:23 PM 05/27/2015)
     Homepage:            http://www.gnu.org/software/automake/
     Description:         Used to generate Makefile.in from Makefile.am

[?] sys-devel/automake-wrapper
     Available versions:  3-r1 4 5 6 7 ~8 9 ~10
     Installed versions:  10(09:42:42 AM 07/07/2015)
     Homepage:            http://www.gentoo.org/
     Description:         wrapper for automake to manage multiple automake versions

Found 2 matches.

**Comment by chi86** [comment]
But I get the same error with 0.3.9.2

**Comment by kiwifb** [comment]
When did you last sync the main tree? Here `1.15` is stable, besides that I will check upstream pynac requirements on automake, I may have to put something explicit.

**Comment by chi86** [comment]
I sync the main tree always before I update my world .. so today

**Comment by kiwifb** [comment]
The dependency problem could be solved by unmerging sage completely first, then re-installing it, although it shouldn't necessary. For automake there is something not right with your current set up but I am not sure what it is. In any case it looks like you should install `automake-1.15`.

**Comment by chi86** [comment]
Ok I installed ´automake-1.15´ and it pulled `sci-libs/pynac-0.3.9.2` and it worked just fine. It still has 137 packages to install but for now it looks fine!

Thanks!

**Comment by kiwifb** [comment]
I have added a special use file to help with the documentation. But the automake situation of your machine is strange automake 1.15 shouldn't be reported as ~arch. Closing.
