### ISSUE TITLE
Cython version dependency should be >=

### ISSUE THREAD

**Issue by TheJJ** [cschwan/sage-on-gentoo#365]
Please don't depend on `~dev-python/cython-0.22`, `>= 0.22` should be sufficient and doesn't trigger a downgrade from 0.22.1 currently in `::gentoo`. I always need the newest cython version for [openage](https://github.com/SFTtech/openage) on my machine and therefore the downgrade is suboptimal.

**Comment by kiwifb** [comment]
Then I will need to provide a patched cython 0.22.1 for you. Plain 0.22.1 will fail to build sage, while all the patches included in cython-0.22-r* have been accepted upstream, most of them will only appear in cython-0.23 and are not included in 0.22.1.

**Comment by TheJJ** [comment]
I see, we also have some patches pending for 0.23, @mic-e fixed stuff for the openage python interface :)

**Comment by kiwifb** [comment]
Yes 0.22.1 is only a bug fix, no new features. At best I could try to see if we could use a 0.23.beta*, I have to check. Jeroen in sage upstream is looking at this (he is also the authors of all the patches used by sage).

**Comment by kiwifb** [comment]
I could migrate to 0.23.beta1 possibly 0.23.beta2 with minimal changes. Would that be acceptable? Also are using "stable" sage ebuild or the live ebuild (sage-9999)? If the latter I would limit the change to the live ebuild at least at first.

**Comment by TheJJ** [comment]
anything >= 0.22.1 is ok for now. the bugfixes in there are important for us.

**Comment by kiwifb** [comment]
Someone botched the way they released 0.23beta2, it being named 0.23b2 hurts the ebuild. I will conduct tests with 0.23b2 before unleashing it. Failing that I will probably give you beta1.

**Comment by kiwifb** [comment]
Things look all right on the live branch, will switch 6.8 in a few hours.

**Comment by kiwifb** [comment]
All done.

**Comment by TheJJ** [comment]
Thanks, seems to work :)
