### ISSUE TITLE
Sage-notebook: TypeError: load() got an unexpected keyword argument 'attach'

### ISSUE THREAD

**Issue by gagern** [cschwan/sage-on-gentoo#366]
The first line of a notebook causes an exception:

```
Error typesetting mathematics

Python 2.7.10 (default, May 30 2015, 15:56:22) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> 
>>> import os;os.chdir("/tmp/tmp1iYoOY");
>>> execfile("_sage_input_1.py")
START1

import os;os.chdir("/tmp/tmpJfv7zz");
execfile("_sage_input_2.py")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "_sage_input_1.py", line 25, in <module>
    load(os.path.join(os.environ['DOT_SAGE'], 'init.sage'), globals(),attach=True)
  File "sage/structure/sage_object.pyx", line 908, in sage.structure.sage_object.load (/var/tmp/portage/sci-mathematics/sage-6.8-r1/work/sage-6.8/src-python2_7/build/cythonized/sage/structure/sage_object.c:10943)
TypeError: load() got an unexpected keyword argument 'attach'
__SAGE__
__SAGE__import os;os.chdir("/tmp/tmpJfv7zz");
__SAGE__execfile("_sage_input_2.py")
START2
```

This is a `~amd64` system with `sci-mathematics/sage-6.8-r1` and `sci-mathematics/sage-notebook-0.11.4-r3`. I haven't been using the notebook on this system in quite a while, and had a number of updates in between, so it might well be that something went wrong at some point with the updates. I might re-emerge everything from the sage tree in an attempt to solve the issue, but I'll wait for a moment to see whether you have any ideas of how I could narrow this down in order to avoid this issue for others.

**Comment by kiwifb** [comment]
That rings a bell, I think I have seen this before - searching.

**Comment by kiwifb** [comment]
OK, I can reproduce it on sage-9999.

**Comment by kiwifb** [comment]
That looked familiar http://osdir.com/ml/sage-devel/2015-05/msg00149.html I forgot to include a patch in sage-notebook when I pushed to pexpect 3.3-r1. Working on it.

**Comment by kiwifb** [comment]
Upgrading sage-notebook should solve the problem.

**Comment by gagern** [comment]
Thanks for taking care of this so quickly. Hope to find time tomorrow to test this.

**Comment by kiwifb** [comment]
Since I have your attention, is this fixed for you?

**Comment by gagern** [comment]
Starting up the notebook… yes, fixed. Thanks! Sorry I forgot to report back sooner.
