### ISSUE TITLE
Emerging of emake fails

### ISSUE THREAD

**Issue by chi86** [cschwan/sage-on-gentoo#367]
Hi! I noticed that my sage wont work anymore:
`Oops, Sage crashed. We do our best to make it stable, but...`
And therefore I emerged it again but i got this error message:
`>>> Compiling source in /var/tmp/portage/sci-mathematics/sage-6.8-r1/work/sage-6.8/src ...
 * python2_7: running distutils-r1_run_phase distutils-r1_python_compile
/usr/bin/python2.7 setup.py build
************************************************************************
Traceback (most recent call last):
  File "setup.py", line 67, in <module>
    include_dirs = sage_include_directories(use_sources=True)
  File "/var/tmp/portage/sci-mathematics/sage-6.8-r1/work/sage-6.8/src-python2_7/sage/env.py", line 166, in sage_include_directories
    import os, numpy
  File "/usr/lib64/python2.7/site-packages/numpy/__init__.py", line 170, in <module>
    from . import add_newdocs
  File "/usr/lib64/python2.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/usr/lib64/python2.7/site-packages/numpy/lib/__init__.py", line 18, in <module>
    from .polynomial import *
  File "/usr/lib64/python2.7/site-packages/numpy/lib/polynomial.py", line 19, in <module>
    from numpy.linalg import eigvals, lstsq, inv
  File "/usr/lib64/python2.7/site-packages/numpy/linalg/__init__.py", line 51, in <module>
    from .linalg import *
  File "/usr/lib64/python2.7/site-packages/numpy/linalg/linalg.py", line 29, in <module>
    from numpy.linalg import lapack_lite, _umath_linalg
ImportError: liblapack.so.0: cannot open shared object file: No such file or directory
************************************************************************
Error building the Sage library
************************************************************************
 * ERROR: sci-mathematics/sage-6.8-r1::sage-on-gentoo failed (compile phase):
 *   (no error message)
 * 
 * Call stack:
 *     ebuild.sh, line   93:  Called src_compile
 *   environment, line 4449:  Called distutils-r1_src_compile
 *   environment, line 1282:  Called _distutils-r1_run_foreach_impl 'distutils-r1_python_compile'
 *   environment, line  552:  Called python_foreach_impl 'distutils-r1_run_phase' 'distutils-r1_python_compile'
 *   environment, line 3762:  Called multibuild_foreach_variant '_python_multibuild_wrapper' 'distutils-r1_run_phase' 'distutils-r1_python_compile'
 *   environment, line 2786:  Called _multibuild_run '_python_multibuild_wrapper' 'distutils-r1_run_phase' 'distutils-r1_python_compile'
 *   environment, line 2784:  Called _python_multibuild_wrapper 'distutils-r1_run_phase' 'distutils-r1_python_compile'
 *   environment, line  872:  Called distutils-r1_run_phase 'distutils-r1_python_compile'
 *   environment, line 1273:  Called distutils-r1_python_compile
 *   environment, line 1153:  Called esetup.py 'build'
 *   environment, line 1778:  Called die
 * The specific snippet of code:
 *       "${@}" || die
`

so it can't open the liblapack.so.0 at least that is what I think whats wrong ... So reinstalled that but it did not help ;(

**Comment by kiwifb** [comment]
The problem is with numpy. If you do
```
python
import numpy
```
You'll probably get the same message, so numpy is the thing you need to emerge again. But that may not be enough. You may be a victim of the current problems with the alternatives framework and blas/lapack from the science overlay. I may have to enter the fray on that one.

**Comment by chi86** [comment]
Your right:
`python
import nump`
does not work either!

I also noticed that the installation of scalpack crashes ....

**Comment by kiwifb** [comment]
Your blas/lapack stuff is probably in disarray. What does
```
pkg-config blas --libs
```
says?

**Comment by chi86** [comment]
It cant find blas:
`Package blas was not found in the pkg-config search path.
Perhaps you should add the directory containing `blas.pc'
to the PKG_CONFIG_PATH environment variable
No package 'blas' found
`

**Comment by kiwifb** [comment]
Yep, all down to the toilet. There is a problem with multi-abi (support for 32bit and 64bit at the same time) and the alternative framework. First step check what eselect says, may be it just needs resetting:
```
eselect blas list
eselect cblas list
eselect lapack list
```
Strictly speaking this is not a sage-on-gentoo problem but I'll try to help you, ok.

**Comment by chi86** [comment]
Thanks I really appreciate your help!
```
eselect blas list:
Installed BLAS for library directory lib64
  [1]   mkl-gfortran
  [2]   mkl-gfortran-threads *
```
```
Installed CBLAS for library directory lib64
  [1]   gsl *
  [2]   mkl-gfortran
  [3]   mkl-gfortran-threads
```
```
Installed LAPACK for library directory lib64
  [1]   mkl-gfortran *
  [2]   mkl-gfortran-threads
```

**Comment by kiwifb** [comment]
Using mkl may be another source of problem, there is a couple open bugs. Nevertheless according to `pkg-config` should report some stuff for `blas` and it doesn't. All I can point you to is this: https://github.com/gentoo-science/sci/issues/443#issuecomment-121600412

**Comment by chi86** [comment]
Thanks the problem was (as you said the mkl) I emerged `emerge -1 blas-reference; emerge -1 lapack-reference; emerge -1 cblas-reference` and set them with `eselect` and now it looks like it works again.
