### ISSUE TITLE
HTML documentation was not installed

### ISSUE THREAD

**Issue by chi86** [cschwan/sage-on-gentoo#368]
Hello!
I just (successfully) emerged sage but I noticed I did not got the Html doku:

```
 * You haven't requested the html documentation.
 * The html version of the sage manual won't be available in the sage notebook.
```

I thought the `bin-html` flag incudes the documentation?

**Comment by kiwifb** [comment]
Me thinks, I forgot to update when that message is displayed... Do not worry the message should be in error and if you have stuff under `/usr/share/doc/sage/html` then you are ok.

**Comment by chi86** [comment]
Ok thanks!

**Comment by kiwifb** [comment]
Keeping it open until I have fix that message....
