### ISSUE TITLE
sage-6.8-r1 failed to produce docs and thus failed to be installed

### ISSUE THREAD

**Issue by rtlix** [cschwan/sage-on-gentoo#369]
I have tried several times, bin-html html and pdf, both failed at last
here is part of the build log: https://bpaste.net/show/381df1c4b0d6
and emerge info: https://bpaste.net/show/445b1f0d4105

**Comment by kiwifb** [comment]
OK I must have messed up the `cython` dependency. Nothing to do with the documentation flag. What version of `cython` do you have.

**Comment by kiwifb** [comment]
OK there is something more, I didn't understand your paste properly. I think you ned to install `sage-notebook` before `sage` itself. That's a new development, I will see how I can enforce this properly. Although it shouldn't matter if you use `bin-html` could you post what happens when `bin-html -html` is on?

**Comment by rtlix** [comment]
dev-python/cython
      Latest version available: 0.23
      Latest version installed: 0.23

I'm on a newly built gentoo system, now sage was one of the three packages which failed to build, hoping that I can use sage tonight!
Or should I try to build it with USE='-bin-html -pdf -html'
Thanks a lot!

**Comment by rtlix** [comment]
I am now building sage with 'bin-html -pdf -html', later I can have the log
when I emerge sage, sage-notebook was pushed in the list after sage, I will try to  build it first

**Comment by kiwifb** [comment]
```
USE='bin-html -pdf -html'
```
should work.

**Comment by rtlix** [comment]
I'm afraid that it will take some time as it's fetching the doc, and the net is so slow......
I'll try to report later at the first time

**Comment by rtlix** [comment]
after having the dinner, it works!
thought, I'd like to have a pdf version of the documents...

**Comment by kiwifb** [comment]
Getting the pdf to work is a bit of an adventure. You have to have the right version of `sphinx` and the right texlive packages. We think we have some control over the texlive stuff but not completely sure.

**Comment by rtlix** [comment]
thanks very much! Nearly everything I have tried works fine!
but I find another problem, jmol(3d-plot) dosen't work with icedtea-7, I have to set the java-vm to icedtea-bin,

"/usr/lib64/python2.7/site-packages/sage/repl/rich_output/display_manager.py:570: RichReprWarning: Exception in _rich_repr_ while displaying object: Jmol failed to create file '/root/.sage/temp/rt/13758/dir_5wHYx4/preview.png', see '/root/.sage/temp/rt/13758/tmp_3K2tOA.txt' for details
  RichReprWarning,
Graphics3d Object"

dev-java/icedtea-7.2.5.5::gentoo was built with the following:
USE="X alsa cjk cups infinality jamvm javascript jbootstrap nsplugin nss pulseaudio source sunec webstart -cacao -debug -doc -examples -kerberos -pax_kernel (-selinux) -smartcard -test -zero"

by the way, icedtea was the second package that once can't be built on my system. I don't know how it was build successful this time after tried several times without changing USE.

**Comment by rtlix** [comment]
as sometimes my laptop is not available, then the html version is not so convenient, the pdf is more preferred for my smart phone.
just now, I want to get all the document in one package from sage official website, but I can not find one as once I did, download them one by one is a little troublesome, maybe the official can provide one..

**Comment by kiwifb** [comment]
Are you running `sage` as root? If so I would recommend trying as a normal user first. `icedtea` is notoriously difficult to build right, it is an `~arch` only package that will not go stable for the foreseable future. The recommendation is to use `icedtea-bin`.

Yes, upstream doesn't seem to provide documentation tarballs anymore. In a timely fashion at any rate. The bin-html documentation is something I generated myself from a vanilla sage build. I never produced an equivalent pdf set but I'll keep in mind that there is demand for the next version.

**Comment by rtlix** [comment]
My god! my system should have been crushed down with freeorion being built background!

Yes, my system haven't been well prepared, the root account is more convenient to do misc jobs and settings. And more often, when all done, I might feel too troublesome to switch to a regular user and have the system configured again, so the root account will become the daily used account ... I know it's not wisdom. but lucky, my system is  more often off-line and jobs are usually done with scripts which is checked and tested before, so it's not so serious.
Maybe next time, I will not build Icedtea myself, the icedtea-bin have met all what I need, or at least for now.
The pdf documents is indeed more convenient to take with, thanks for your attention and also for the bin-html!

**Comment by kiwifb** [comment]
`sage-6.9` now can use pre-generated pdf doc. I am closing this issue.
