### ISSUE TITLE
undefined symbol: arith_dedekind_sum

### ISSUE THREAD

**Issue by gagern** [cschwan/sage-on-gentoo#370]
After upgrading flint to 2.5.2, sage 6.8-r1 fails to start:

```
ImportError: /usr/lib64/python2.7/site-packages/sage/libs/flint/arith.so:
undefined symbol: arith_dedekind_sum
```

Judging from f2474ed7c67a593a841a0e0f0a8ea7a93f25e4a7, https://github.com/sagemath/sage/commit/3aece2b80b95e76db63d7223d578fac240a775af and https://github.com/wbhart/flint2/commit/64f656fb8db591ea11db606c7905de9f47b05e84 I'd assume that this symbol got renamed to `fmpq_dedekind_sum`. Not sure how to deal with this.

1. You could have the `sage` ebuild on older versions of `flint`.
2. You could change the `flint` ebuild, to export one name as an alias of the other.
3. You could mask flint 2.5 and rely on that mask. This seems like a temporary solution only, since one day the mask would be lifted and you'd have to have an explicit dependency nonetheless.
4. You could conditionally apply a patch, based on which version of flint is installed. This would require rebuilds with no indication that they are needed, which is ugly.

It would also be interesting to figure out a way to link against not `libflint.so` but its `SONAME`, i.e. `libflint.so.13` and similar, so that upgrades to the library force a rebuild of the package via the preserved-rebuild feature of portage. Not sure what `SONAME` the library from flint 2.4 had, though.

**Comment by kiwifb** [comment]
Oh yes that symbol, I think I had trouble with it with `arb`. I don't think the `flint` upgrade ticket had a patch for `sage` so a rebuild may be the only thing it needs. `flint-2.4` and earlier don't have `SONAME` and someone in Gentoo thought we shouldn't fix it in 2.4 in the Gentoo tree. I put a subslot in `flint-2.5` but that will only start to work with the next `sage` and so on.

**Comment by kiwifb** [comment]
Yes a rebuild of sage is needed `usr/include/flint/arith.h` as a line
```
#define arith_dedekind_sum fmpq_dedekind_sum
```
so everything will be alright. The lack of soname in 2.4 is probably why we currently don't trigger a rebuild. All I can do is add a post install message that rebuild may be needed.

**Comment by gagern** [comment]
Yes, rebuild fixed it here, too. Would you place that message with the `flint` package? As an alternative, you could create two different revisions of `sage`, with different `flint` dependencies so that a `flint` upgrade has to go hand in hand with a `sage` rebuild (and otherwise insignificant revbump). Do you want a pull request for this approach?

**Comment by kiwifb** [comment]
I think I will go for a "gratuitous" rev-bump to put everyone to `flint-2.5`. The main reason for the upgrade is a bug after all. I would welcome a pull request going that way for the sage-6.x ebuilds in the overlay. If you do make a pull request don't forget to update the package.keywords files.
