### ISSUE TITLE
SAGE_DOC incorrectly defined 

### ISSUE THREAD

**Issue by strogdon** [cschwan/sage-on-gentoo#372]
I discovered this while investigating some `sphinx` related issues and it may be of no consequence. From python
```
>>> from sage.env import SAGE_DOC
>>> SAGE_DOC
'/usr/share/sage/doc'
```
which isn't correct. This is set in `sage/env.py`. What is worrisome is that `SAGE_DOC` is imported in
`doc/common/builder.py ` which is used in building the docs.

**Comment by kiwifb** [comment]
OK I will chase this but while building doc the value of SAGE_DOC is set by the ebuild so it shouldn't be a problem at generation time. And if sage is started normally the value should be imported from `/etc/sage-env` which has `/usr/share/doc/sage` which is correct.

**Comment by strogdon** [comment]
So, I may be of no consequence - the `from sage.env import SAGE_DOC` is never used.

**Comment by kiwifb** [comment]
I still need to fix it, it is in the `sage-x.y-env.patch` files and I see how the mistake was made. I will make sure the right value is there. But indeed, the values from `env.py` should only be used if you use sage from a pure python shell.

**Comment by kiwifb** [comment]
Should be all fixed. Close the issue in your time.

**Comment by strogdon** [comment]
fixed. closing.
