### ISSUE TITLE
Sage shell failing to launch, but Sage Notebook working fine

### ISSUE THREAD

**Issue by fusion809** [cschwan/sage-on-gentoo#373]
Hi, 

For some reason I have noticed that while `sci-mathematics/sage` emerged without errors, calling `sage` from the command line gives the output:

```sh
Traceback (most recent call last):
  File "/usr/lib/python-exec/python2.7/sage-ipython", line 7, in <module>
    from sage.repl.interpreter import SageTerminalApp
  File "/usr/lib64/python2.7/site-packages/sage/repl/interpreter.py", line 107, in <module>
    from IPython import Config
ImportError: cannot import name Config
```

yet running `sage -notebook` or `sage -n` launches the Sage Notebook without error. I am running on Sabayon, so some packages I installed with Entropy, although the bulk of the dependencies I installed with Portage. 

Thanks for your time,
Brenton

**Comment by kiwifb** [comment]
Which version of `sage` and which version of `ipython` do you have?

**Comment by fusion809** [comment]
`6.8-r2` and `4.0.0-r2::science`, respectively.

**Comment by kiwifb** [comment]
OK I need to see if I made a mistake in the dependency or if they need adjusting. Don't use `ipython-4` with `sage-6.8` support for that is coming in `6.9`.

**Comment by fusion809** [comment]
OK, well I unmerged `ipython-4.0.0-r2::science` and installed `ipython-3.2.1::gentoo` and re-ran `emerge -av sage`, it gave:
```sh
These are the packages that would be merged, in order:

Calculating dependencies... done!
[ebuild     U  ] dev-python/ipython-4.0.0-r2::science [3.2.1::gentoo] USE="notebook* qt4 smp -doc -examples -matplotlib -mongodb -nbconvert {-test} -wxwidgets (-octave%)" PYTHON_TARGETS="python2_7 python3_4 -python3_3" 0 KiB
[ebuild   R    ] sci-mathematics/sage-6.8-r2::sage-on-gentoo  USE="X bin-html -arb -bliss -debug -html -latex -modular_decomposition -pdf -testsuite" LINGUAS="ca de en fr hu it pt ru tr" PYTHON_TARGETS="python2_7" 0 KiB
```

**Comment by kiwifb** [comment]
Yes you are on `~arch` so you are not offered `ipython-3.1` or `3.2`. Now that the cat is off my lap I can add a fix for that.

**Comment by kiwifb** [comment]
It looks like adding `fix issue #N` automatically closes the corresponding issue. Well can you sync the overlay and try again?

**Comment by kiwifb** [comment]
Actually the fix was not completely correct. If you haven't tried already you should now. Feedback, positive or negative appreciated.
