### ISSUE TITLE
sci-mathematics/lcalc-1.23-r7 installs non-readable header

### ISSUE THREAD

**Issue by veelai** [cschwan/sage-on-gentoo#374]
On my hardened ~amd64 machine I see an error during the build of sage, which is caused by an access violation for Ldokchitser.h, which is only readable by root on my system.

<pre>
$ ls -lah  /usr/include/Lfunction/Ldokchitser.h
-rw------- 1 root root 4.2K Oct  3 04:37 /usr/include/Lfunction/Ldokchitser.h
</pre>

**Comment by kiwifb** [comment]
That's odd but I guess the installation routine for `lcalc` is probably to blame. Curious that it didn't appear before.

**Comment by kiwifb** [comment]
I don't know how fast I will move on this, I just came back from leave without internet and have a big backlog. Ping again if you don't see an update by Wednesday. The installation of headers and libraries is done by `cp` which is not ideal (see https://github.com/cschwan/sage-on-gentoo/blob/master/sci-mathematics/lcalc/files/lcalc-1.23-makefile.patch) and should really be done properly by `install` with the right options.

**Comment by kiwifb** [comment]
Sync and re-emerge `lcalc` and see if that helps.

**Comment by veelai** [comment]
Works great. :)
