### ISSUE TITLE
fetch fails for sci-mathematics/sage-data-graphs-20150724

### ISSUE THREAD

**Issue by strogdon** [cschwan/sage-on-gentoo#375]
Here I get:
```
>>> Emerging (1 of 1) sci-mathematics/sage-data-graphs-20150724::sage-on-gentoo
>>> Downloading 'http://sagepad.org/spkg/upstream/graphs/graphs-20150724.tar.bz2'
--2015-10-13 20:10:49--  http://sagepad.org/spkg/upstream/graphs/graphs-20150724.tar.bz2
Resolving sagepad.org... 176.31.106.138
Connecting to sagepad.org|176.31.106.138|:80... failed: No route to host.
!!! Couldn't download 'graphs-20150724.tar.bz2'. Aborting.
 * Fetch failed for 'sci-mathematics/sage-data-graphs-20150724', Log file:
 *  '/local/gentoo-redlizard/var/tmp/portage/sci-mathematics/sage-data-graphs-20150724/temp/build.log'
```
Now this did work at one time because I have a copy on another machine.

**Comment by kiwifb** [comment]
Time to review the sage mirrors....

**Comment by kiwifb** [comment]
OK I put more mirrors so if the first one fails there will be other in the future.

**Comment by strogdon** [comment]
This is good now. There was also a fetch failure for `m4rie` but that's now fixed. However from the science overlay
```
>>> Downloading 'https://pypi.python.org/packages/source/i/ipython_genutils/ipython_genutils-0.1.0.tar.gz'
--2015-10-13 20:29:23--  https://pypi.python.org/packages/source/i/ipython_genutils/ipython_genutils-0.1.0.tar.gz
Resolving pypi.python.org... 23.235.40.223
Connecting to pypi.python.org|23.235.40.223|:443... connected.
ERROR: cannot verify pypi.python.org's certificate, issued by ‘CN=DigiCert SHA2 Extended Validation Server CA,OU=www.digicert.com,O=DigiCert Inc,C=US’:
  Unable to locally verify the issuer's authority.
To connect to pypi.python.org insecurely, use `--no-check-certificate'.
!!! Couldn't download 'ipython_genutils-0.1.0.tar.gz'. Aborting.
```
This also worked previously and I don't remember have to jump through hoops to download it?

**Comment by kiwifb** [comment]
Hum... prefix or pure gentoo? It could either be that your list of certificate is too old but more likely that the pypi certificate is somehow expired. I'll try.

**Comment by strogdon** [comment]
This was prefix. I will check gentoo. And now the same with `traitlets`.

**Comment by kiwifb** [comment]
It will be the same with anything coming from `pypi` presumably.

**Comment by kiwifb** [comment]
works here with a gentoo box. `app-misc/ca-certificates` and `dev-python/certifi` along with any changes to `openssl` are prime suspect for this.

**Comment by strogdon** [comment]
Gentoo works. It's just Prefix.

**Comment by kiwifb** [comment]
works on my prefix but I haven't updated it since the week end at least. Doing that now.

**Comment by strogdon** [comment]
Downgraded from `ca-certificates-20150426.3.20` to `ca-certificates-20140927.3.17.2` and things seem to be working.  The `ca-certificates-20150426.3.20`  is the only one stable on Gentoo.

**Comment by kiwifb** [comment]
I have `20141019.3.19-r1` in my prefix the rest is masked (possibly by me somehow). There was an update recently that required new `ca-certificates` and various bits that weren't behaving so I did mask stuff.

**Comment by strogdon** [comment]
I cut and pasted incorrectly. `app-misc/ca-certificates-20140927.3.17.2` is the only stable on Gentoo.

**Comment by strogdon** [comment]
I only had `20150426.3.20-r1` masked because it required `>=sys-devel/binutils-config-5` which didn't exit.

**Comment by kiwifb** [comment]
Well, I did go a bit further than that obviously.

**Comment by strogdon** [comment]
I guess this should be closed. The `ca-certificates` issue is tangential.
