### ISSUE TITLE
sci-mathematics/gap: missing proper Vim syntax support

### ISSUE THREAD

**Issue by Coacher** [cschwan/sage-on-gentoo#379]
Hello.

Now gap unconditionally dumps Vim syntax and indent files to `/usr/lib/gap/etc/`, but they have to be manually moved by user in order to be loaded automatically by Vim.

It would be better to have 'vim-syntax' USE and install these files to Vim's runtime path so they would be loaded automatically without user intervention.

Please fix.
If you are interested I can create a PR for this.

**Comment by kiwifb** [comment]
You are most welcome to create a PR. Of course we don't really want those files in `/usr/lib/gap/etc/`, somewhere appropriate for Gentoo, since you seem to be using `vim` (I don't) you probably know all about the right path.

**Comment by Coacher** [comment]
I've looked closer at Vim files shipped with GAP. There are two of them: one for highlight, one for indent.

The one that provides syntax highlighting is truly horrible with hardcoded colours that render GAP files unreadable. The one that provides indentation is very basic, but usable and can be helpful. Unfortunately, GAP does not provide a special file for Vim to learn to apply these indent and syntax rules to *.g, *.gi, *.gd files. This special file is very simple, though, and can be included in repo and copied during GAP installation to the appropriate place.

However, there exists https://github.com/petRUShka/vim-gap project, which also provides GAP support for Vim. Indent file is the same, but syntax highlighting is fixed. Also it 'just works', i.e. no need to add extra files manually. So, it is less painful to use instead of the files shipped with GAP. This project actually provides more than just hightlight and indent, but also syntax checking and macros.

I say we leave Vim files shipped with GAP as they were in case someone wants them. Those who want a proper GAP support in Vim definitely should look at https://github.com/petRUShka/vim-gap.

**Comment by Coacher** [comment]
What do you think?
Maybe a short einfo message could be added to make users aware of a better Vim support via https://github.com/petRUShka/vim-gap?

**Comment by kiwifb** [comment]
Hum... at the very least. I guess we could package it and have it pulled by useflag.

**Comment by Coacher** [comment]
This is of course the most desirable variant. I was unsure whether you are willing to add another package in repo for such a minor feature.

Again if you give it a go, I can work on a proper PR.

**Comment by Coacher** [comment]
Good. I'll prepare the PR in a couple of days.

**Comment by Coacher** [comment]
Fixed in commit a26c94648.
