### ISSUE TITLE
sci-mathematics/gap installs lots of build-time garbage like *.o files and configure scripts

### ISSUE THREAD

**Issue by Coacher** [cschwan/sage-on-gentoo#381]
Hello.

Here are some outputs with files that should not be installed at all:
```
$ equery b /usr/lib64/gap/config*
 * Searching for /usr/lib64/gap/config.log,/usr/lib64/gap/config.status,/usr/lib64/gap/configure,/usr/lib64/gap/configure.in ...
sci-mathematics/gap-4.7.8 (/usr/lib64/gap/configure)
sci-mathematics/gap-4.7.8 (/usr/lib64/gap/config.status)
sci-mathematics/gap-4.7.8 (/usr/lib64/gap/config.log)
sci-mathematics/gap-4.7.8 (/usr/lib64/gap/configure.in)
```
```
$ equery b /usr/lib64/gap/**/config*
 * Searching for /usr/lib64/gap/cnf/config.guess,/usr/lib64/gap/cnf/config.hin,/usr/lib64/gap/cnf/config.sub,/usr/lib64/gap/cnf/configure.in,/usr/lib64/gap/cnf/configure.out ...
sci-mathematics/gap-4.7.8 (/usr/lib64/gap/cnf/config.hin)
sci-mathematics/gap-4.7.8 (/usr/lib64/gap/cnf/config.guess)
sci-mathematics/gap-4.7.8 (/usr/lib64/gap/cnf/config.sub)
sci-mathematics/gap-4.7.8 (/usr/lib64/gap/cnf/configure.in)
sci-mathematics/gap-4.7.8 (/usr/lib64/gap/cnf/configure.out)
```
```
$ equery b /usr/lib64/gap/**/**/config*
 * Searching for /usr/lib64/gap/bin/x86_64-pc-linux-gnu-x86_64-pc-linux-gnu-gcc-default64/config.h,/usr/lib64/gap/bin/x86_64-pc-linux-gnu-x86_64-pc-linux-gnu-gcc-default64/config.log,/usr/lib64/gap/bin/x86_64-pc-linux-gnu-x86_64-pc-linux-gnu-gcc-default64/config.status,/usr/lib64/gap/bin/x86_64-pc-linux-gnu-x86_64-pc-linux-gnu-gcc-default64/configure ...
sci-mathematics/gap-4.7.8 (/usr/lib64/gap/bin/x86_64-pc-linux-gnu-x86_64-pc-linux-gnu-gcc-default64/config.h)
sci-mathematics/gap-4.7.8 (/usr/lib64/gap/bin/x86_64-pc-linux-gnu-x86_64-pc-linux-gnu-gcc-default64/config.status)
sci-mathematics/gap-4.7.8 (/usr/lib64/gap/bin/x86_64-pc-linux-gnu-x86_64-pc-linux-gnu-gcc-default64/configure)
sci-mathematics/gap-4.7.8 (/usr/lib64/gap/bin/x86_64-pc-linux-gnu-x86_64-pc-linux-gnu-gcc-default64/config.log)
```
```
$ equery b /usr/lib64/gap/**/*.bat
 * Searching for /usr/lib64/gap/bin/gap.bat,/usr/lib64/gap/bin/gapcmd.bat,/usr/lib64/gap/bin/gaprxvt.bat,/usr/lib64/gap/bin/usemem.bat ...
sci-mathematics/gap-4.7.8 (/usr/lib64/gap/bin/gapcmd.bat)
sci-mathematics/gap-4.7.8 (/usr/lib64/gap/bin/usemem.bat)
sci-mathematics/gap-4.7.8 (/usr/lib64/gap/bin/gap.bat)
sci-mathematics/gap-4.7.8 (/usr/lib64/gap/bin/gaprxvt.bat)
```
Also many, many *.o files under bin/$GAPARCH and some under small/ dir,
autom4te.cache/ dir, extern/ dir, bin/$GAPARCH/extern/ dir, cnf/ dir.

All of these files should not be installed IMHO.

**Comment by kiwifb** [comment]
I wish. Hopefully that will change soon. Basically if you need to install/compile some gap package a number of these files will be required. I remember asking, Burcin I think, if upstream knew what a library is and his answer: "yes, they do. It's a place where you can borrow books."

**Comment by kiwifb** [comment]
I did quite a lot of work in a new `gap` branch. Along with `gap` packages. I will probably merge it today and post something on the science mailing list. Eventually I think it should migrate to at least the science overlay.

**Comment by Coacher** [comment]
That's good to hear. Thank you.

I can help you with GAP things as I use it quite regularly if you'd like. Also I use several packages you've added in `gap` branch, so I can help with those as well.

**Comment by kiwifb** [comment]
Cool. I will proceed with merging then.

**Comment by kiwifb** [comment]
Issue I need help/info: testing of `gap` and of the packages. I noticed quite a few `tst` folders which look like they hold tests. It would be good to be able to run tests in the ebuilds automatically.

**Comment by Coacher** [comment]
Yes. I also noticed that many GAP packages don't ship any sources that require compilation and src_install() is pretty much the same. I was thinking maybe a minimalistic eclass would be a good solution here. Testing support can be added to this eclass as well.

For painless testing we need >=gap-4.8.3, see http://www.gap-system.org/Manuals/doc/changes/chap2.html#X87956276873C1BB4. But I don't see this as a problem.

I can start working on this eclass and port existing GAP packages' ebuilds when it's ready.
Shouldn't take too much time. I think a week would be enough to do this.

What do you think?

**Comment by kiwifb** [comment]
Would be good. I thought about an `eclass` but didn't commit to that. Most install are indeed the same compilation are rare. Although I started looking at `gac` because one of the package can be pre-compiled. And I am looking at `guava` right now and wondering how to attack it properly.

But minimal eclass for install and possibly testing for starter is good.

Branch merged.

**Comment by Coacher** [comment]
I have guava packaged for a while now. I can share ebuild with you.

**Comment by Coacher** [comment]
See #410 for my guava ebuild.

**Comment by kiwifb** [comment]
OK I think we can say the initial intent of the ticket has been addressed. Other related issues like eclass should be the object of a different issue.
