### ISSUE TITLE
How to install spkg?

### ISSUE THREAD

**Issue by veelai** [cschwan/sage-on-gentoo#382]
Hi,

I want to install an additional sage package [1] which tells me to do
<pre>
sage -i http://users.minet.uni-jena.de/cohomology/p_group_cohomology-2.1.5.spkg
</pre>
but this doesn't work and I found issue #321 where it's stated that this is by design. Now my question is: How do I get the package to install? This is probably worth a somewhat general answer.

My favourite way would be, that I can add one line to the ebuild and have that in my local overlay.

Thanks a lot. :)

[1] http://users.minet.uni-jena.de/cohomology/documentation/

**Comment by kiwifb** [comment]
The only way to solve this is to provide an ebuild for this particular package. There is currently no way to install an optional `sage` package in a user location like you can in `R` for example.

**Comment by kiwifb** [comment]
You'll note that I already provide useflags for a number of packages that require re-building of sage to work properly. Additional package that can be used in or with sage need their own ebuild until such a time, if ever, sage gets an internal package manager. The trend is in the opposite direction.
For `p_group_cohomology` that spkg is actually three different things packed together that would need three different ebuild. meataxe, "john's programs" and p_group_cohomology proper. You'll note that meataxe distributed in the spkg is a version from 2009 and the latest version is from 2011. No idea if the latest would work.

**Comment by veelai** [comment]
Hm, I went the quick and dirty road. The following worked, despite being seriously ugly.

<pre>
EAPI="5"

DESCRIPTION="Software for computing the cohomology of finite p-groups."
HOMEPAGE="http://users.minet.uni-jena.de/cohomology/documentation/"
SRC_URI="http://users.minet.uni-jena.de/cohomology/p_group_cohomology-2.1.5.spkg -> p_group_cohomology-2.1.5.tar.bz2"
KEYWORDS="~amd64 ~x86 ~amd64-linux ~x86-linux ~ppc-macos ~x86-macos ~x64-macos"

LICENSE="GPL-2"
SLOT="0"
IUSE="doc"

DEPEND=""
RDEPEND=""
S="${WORKDIR}/${P}/src"

src_prepare() {
	export SAGE_LOCAL="/usr/"
	sed -i -e 's|$(SAGE_LOCAL)/|$(D)/$(SAGE_LOCAL)/|' Makefile
	sed -i -e 's|#Cleaning|echo $(SAGE_LOCAL) #Cleaning|' Makefile
	sed -i -e "s|os.path.join(\"mtx2.2.4\",\"src\"),|\"${D}/${SAGE_LOCAL}/lib/\", os.path.join(\"mtx2.2.4\",\"src\"),|" setup.py
	sed -i -e "s|extra_compile_args=\[\"-O3\"\],|library_dirs=[\"${D}/${SAGE_LOCAL}/lib/\"], extra_compile_args=[\"-O3\"],|" setup.py
	sed -i -e "s|name = \"pGroupCohomology\",|options = {\"install\": {\"root\": \"${D}\"}}, name = \"pGroupCohomology\",|" setup.py
	sed -i -e "s|tar_base = os.path.join(SAGE_LOCAL,'pGroupCohomology')|tar_base = os.path.join('${D}', SAGE_LOCAL[1:],'pGroupCohomology')|" setup.py
	sed -i -e "s|data_base = os.path.join(SAGE_SHARE,'pGroupCohomology')|data_base = os.path.join('${D}', SAGE_SHARE[1:],'pGroupCohomology')|" setup.py
	sed -i -e "s|os.mkdir(data_base)|os.makedirs(data_base)|" setup.py
}

src_compile() {
	mkdir lib
	mkdir bin
	export RANLIB="ranlib"
	export SAGE_LOCAL="/usr/"
	emake
}

src_install() {
	export CP="cp"
	export D="${D}"
	export SAGE_LOCAL="/usr/"
	export SINGULARPATH="${D}/usr/share/singular/LIB"
	mkdir -p "${D}/${SAGE_LOCAL}/lib"
	mkdir -p "${D}/${SAGE_LOCAL}/bin"
	mkdir -p "${D}/usr/share/singular/LIB"
	emake install
	python2 setup.py install || die
	# FIXME add doc support
}
</pre>

**Comment by kiwifb** [comment]
It is indeed quite ugly. The good news is that some work is underway to port it to the new `sage` git layout and in the process a number of thing will be taken care off. I have seen some code, Once it is done it will be much more palatable to make ebuild and I'll be ready to make them. Including the ~37MB database.

**Comment by veelai** [comment]
That sounds good. :)
