### ISSUE TITLE
Error compiling sage docs with sphinx-1.3.1

### ISSUE THREAD

**Issue by WPettersson** [cschwan/sage-on-gentoo#392]
I'm trying to upgrade to the last version of sage, and I get the following error repeated many times when building the documentation.

```
Building reference manual, first pass.

[tensor_fr] Extension error:
[tensor_fr] Could not import extension sage_autodoc (exception: cannot import name safe_repr)
[polynomia] Extension error:
[polynomia] Could not import extension sage_autodoc (exception: cannot import name safe_repr)
```

This comes from /tmp/portage/sci-mathematics/sage-7.0/work/sage-7.0/src/doc/common/sage_autodoc.py, which on line 40 says
`from sphinx.util.inspect import getargspec, isdescriptor, safe_getmembers, safe_getattr, safe_repr, is_builtin_class_method`

However, safe_repr has been renamed to object_description by https://github.com/sphinx-doc/sphinx/commit/d24bd73d0ce8071459a1056691a1934e1ca12194 so it can't be found. Best I can tell, this was stabilised with Sphinx-1.3.1, in November last year.

I tried removing references to safe_repr, but now I'm getting
```
Traceback (most recent call last):
  File "doc/common/builder.py", line 1641, in <module>
    getattr(get_builder(name), type)()
  File "doc/common/builder.py", line 302, in _wrapper
    getattr(get_builder(document), 'inventory')(*args, **kwds)
  File "doc/common/builder.py", line 513, in _wrapper
    x.get(99999)
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
OSError: [repl     ] WARNING: the config value 'nitpick_ignore' has type `tuple', defaults to `list.'
```

At this point, I need to get some sleep, but I'll keep digging through this in the morning.

**Comment by kiwifb** [comment]
`sage`'s doc unfortunately has to be built with `sphinx` 1.2.x. I recommend you to use the useflags provided in `package.use/99sage-bin-doc` that will allow you to pull pre-built documentation instead of building your own. Unless you are trying to use `sage-9999` that's the recommended way to install.

**Comment by kiwifb** [comment]
Of course they'll appreciate help upstream at http://trac.sagemath.org/ticket/18497 to move to `sphinx` 1.3.x.

**Comment by WPettersson** [comment]
Thanks, that fixed it. What are your thoughts on adding
`pdf? ( <dev-python/sphinx-1.3.1-r1 )` to sage-7.0.ebuild? It won't affect me, I'm happy to run bin-html and not have pdf documentation at all, but it might help others who also run into this issue.

**Comment by kiwifb** [comment]
Yes, that part of the dependency of the ebuild needs a bit more love one way or the other. Possibly `=dev-python/sphinx-1.2*` that would do it too.
