### ISSUE TITLE
Do we still need to keyword dev-python/service_identity?

### ISSUE THREAD

**Issue by WPettersson** [cschwan/sage-on-gentoo#397]
Running an update, emerge asked me to keyword dev-python/attrs, which I thought odd. It's required by service_identity-16.0.0. However, twisted-core-14.0.1 (which is the version unmasked by sage) just requires service_identity, not service_identity-16.0.0 specifically. All of these 3 packages exist in the regular Gentoo tree, not in sage-on-gentoo. The only thing sage-on-gentoo does is keyword these packages.

I've actually removed the keyword temporarily on my machine, and everything seems to compile and run fine.

**Comment by kiwifb** [comment]
Yes that kind of things happen. Keyword maintenance is hard, I actually unkeyworded some stuff for the same kind of reasons last week.

**Comment by kiwifb** [comment]
Actually https://github.com/cschwan/sage-on-gentoo/commit/f6d5ad11021b147a7d1a9f118975576a8814d61d did just that 5 days ago. Synchronize your overlay.
