### ISSUE TITLE
Circular dependencies

### ISSUE THREAD

**Issue by hungshihhan** [cschwan/sage-on-gentoo#404]
I followed the instruction to install sage with `emerge -av sage` but could not proceed due to circular dependencies. Here is the sequence:
```
 * Error: circular dependencies:

(dev-python/ipykernel-4.3.0:0/0::gentoo, ebuild scheduled for merge) depends on
 (dev-python/ipython-4.0.3:0/0::gentoo, ebuild scheduled for merge) (buildtime)
  (dev-python/qtconsole-4.2.0:0/0::gentoo, ebuild scheduled for merge) (runtime)
   (dev-python/ipykernel-4.3.0:0/0::gentoo, ebuild scheduled for merge) (buildtime)

It might be possible to break this cycle
by applying the following change:
- dev-python/ipython-4.0.3 (Change USE: -qt4)

Note that this change can be reverted, once the package has been installed.

```
I wonder if removing `qt4` USE flag causes any issue for KDE users. Thank you.

**Comment by kiwifb** [comment]
Doing
```
USE=-qt4 emerge -1v ipython
```
and then go 
```
emerge -uDNv sage
```
will work.
This not technically a bug with the overlay but one with the main tree. I filled a bug for it recently
https://bugs.gentoo.org/show_bug.cgi?id=576088
unfortunately jlec only fixed it in `ipython-4.1.1` and not in any 4.0.x ebuild.

**Comment by hungshihhan** [comment]
I tried to include `-qt4` for `dev-python/ipython`, but circular dependencies still happen:
```
 * Error: circular dependencies:

(dev-python/ipykernel-4.3.0:0/0::gentoo, ebuild scheduled for merge) depends on
 (dev-python/ipython-4.0.3:0/0::gentoo, ebuild scheduled for merge) (buildtime)
  (dev-python/notebook-4.0.6:0/0::science, ebuild scheduled for merge) (runtime)
   (dev-python/ipykernel-4.3.0:0/0::gentoo, ebuild scheduled for merge) (buildtime)

 * Note that circular dependencies can often be avoided by temporarily
 * disabling USE flags that trigger optional dependencies.
```

**Comment by kiwifb** [comment]
There must be a similar dependency on the notebook, although I thought I had fixed it before it was moved from the `science` overlay to the main tree. Try
```
USE="-qt4 -notebook" emerge -1v ipython
```

**Comment by ardok-m** [comment]
That solve the circular dependencies, but now I've got a blockage,
<pre>
<code>
[blocks B      ] app-eselect/eselect-blas ("app-eselect/eselect-blas" is blocking sci-libs/gsl-2.1, app-admin/eselect-1.4.5-r103)
[blocks B      ] app-eselect/eselect-lapack ("app-eselect/eselect-lapack" is blocking sci-libs/gsl-2.1, app-admin/eselect-1.4.5-r103)

 * Error: The above package list contains packages which cannot be
 * installed at the same time on the same system.

  (app-eselect/eselect-blas-0.1:0/0::gentoo, ebuild scheduled for merge) pulled in by
    app-eselect/eselect-blas required by (sci-libs/blas-reference-20070226-r4:0/0::gentoo, ebuild scheduled for merge)

  (app-eselect/eselect-lapack-0.1:0/0::gentoo, ebuild scheduled for merge) pulled in by
    app-eselect/eselect-lapack required by (sci-libs/lapack-reference-3.2.1-r4:0/0::gentoo, ebuild scheduled for merge)
</code>
</pre>

**Comment by kiwifb** [comment]
It looks like you haven't migrated from the main tree based blas/lapack to the science overlay one. Please follow the instructions at https://wiki.gentoo.org/wiki/User_talk:Houseofsuns

**Comment by ardok-m** [comment]
It worked. I didn't know I had migrate.
Thanks!

**Comment by kiwifb** [comment]
Your keywords probably did that to you.
