### ISSUE TITLE
mask doc use flag for sphinx 1.2*

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [cschwan/sage-on-gentoo#405]
See
https://bugs.gentoo.org/show_bug.cgi?id=577028

**Comment by kiwifb** [comment]
Thanks for the info. I think there may be something interesting for that case in `distutils-r1` eclass (build the doc only with python-2) but it may be easier to just do the trivial patch.

**Comment by kiwifb** [comment]
Hum patching this would be ambitious, there is a lot of `print` all over the place in `sphinx`.

**Comment by kiwifb** [comment]
Is your default `python` a `python-3`?

**Comment by kiwifb** [comment]
This is text book application of https://wiki.gentoo.org/wiki/Project:Python/distutils-r1#DISTUTILS_SINGLE_IMPL

**Comment by Alessandro-Barbieri** [comment]
I have python 2.7 as default

**Comment by kiwifb** [comment]
Irrelevant in the end. Please test the revised ebuild.

**Comment by kiwifb** [comment]
No feedback. Closing.
