### ISSUE TITLE
Installing sage-7.1 yields slot conflict 

### ISSUE THREAD

**Issue by ardok-m** [cschwan/sage-on-gentoo#408]
<pre><code>emerge sage --verbose-conflicts

These are the packages that would be merged, in order:

Calculating dependencies... done!
[ebuild  N    ~] sci-mathematics/nauty-2.6.1 
[ebuild     U ~] dev-libs/ntl-9.6.4 [9.6.2]
[ebuild     U ~] sci-mathematics/arb-2.8.1 [2.7.0-r1]
[ebuild     U ~] sci-libs/pynac-0.6.2 [0.6.0]
[ebuild     UD~] dev-python/sympy-0.7.6.1-r1 [1.0]
[ebuild     U ~] sci-mathematics/pari-2.8_pre20160209 [2.8_pre20151201]
[ebuild  N    ~] dev-python/cysignals-1.0.1  PYTHON_TARGETS="python2_7 python3_4 -python3_5" 
[ebuild     U ~] sci-mathematics/sage-notebook-0.11.7 [0.11.6.1]
[ebuild  N    #] sci-mathematics/sage-7.1-r1  USE="X bin-html latex manifolds -bin-pdf -bliss -debug -html -modular_decomposition -pdf -testsuite" LINGUAS="en -ca -de -fr -hu -it -ja -pt -ru -tr" PYTHON_TARGETS="python2_7" 

!!! Multiple package instances within a single package slot have been pulled
!!! into the dependency graph, resulting in a slot conflict:

dev-libs/ntl:0

  (dev-libs/ntl-9.6.4:0/9.6.4::sage-on-gentoo, ebuild scheduled for merge) pulled in by
    >=dev-libs/ntl-9.6.2-r1:= required by (sci-mathematics/sage-7.1-r1:0/0::sage-on-gentoo, ebuild scheduled for merge)
    ^^             ^^^^^^^^                                                                                                                                                                      

  (dev-libs/ntl-9.6.2:0/9.6.2::sage-on-gentoo, installed) pulled in by
    dev-libs/ntl:0/9.6.2= required by (sci-libs/linbox-1.3.2-r2:0/0::sage-on-gentoo, installed)
                ^^^^^^^^^                                                                                                          
    dev-libs/ntl:0/9.6.2=[-threads] required by (sci-libs/libsingular-3.1.7_p1-r6:0/0::sage-on-gentoo, installed)
                ^^^^^^^^^                                                                                                                            
    >=dev-libs/ntl-5.4.2:0/9.6.2= required by (sci-mathematics/eclib-20150827:0/2::sage-on-gentoo, installed)
                        ^^^^^^^^^                                                                                                                
    dev-libs/ntl:0/9.6.2= required by (sci-mathematics/flint-2.5.2:0/13::gentoo, installed)
                ^^^^^^^^^                                                                                                      
    dev-libs/ntl:0/9.6.2=[-threads] required by (sci-mathematics/singular-3.1.7_p1-r4:0/0::sage-on-gentoo, installed)</code></pre>

Here I tried to install 7.1-rc1, but it is also reproducible for 7.1

**Comment by kiwifb** [comment]
I am not sure why you get `ntl-9.6.4` pulled instead of `9.7.0`. What does 
```
eix dev-libs/ntl
```
reports? It is otherwise a bit annoying you may have to first update `ntl` in a forced way and then rebuild its dependencies. I am not sure why it is not automatically happening. I certainly do what I can to make it happen as automatic rebuilds.

**Comment by ardok-m** [comment]
Sorry, it pulled <code>ntl-9.6.4</code> because I tried to solve the conflict masking some versions and I forgot to remove the file before reporting. Nevertheless, the conflict continues when <code>ntl-9.7.0</code> is pulled.
<pre><code>emerge sage --verbose-conflicts

These are the packages that would be merged, in order:

Calculating dependencies... done!
[ebuild  N    ~] sci-mathematics/nauty-2.6.1 
[ebuild     U ~] dev-libs/ntl-9.7.0 [9.6.2] USE="-bindist%" 
[ebuild     U ~] sci-mathematics/arb-2.8.1 [2.7.0-r1]
[ebuild     U ~] sci-libs/pynac-0.6.2 [0.6.0]
[ebuild     UD~] dev-python/sympy-0.7.6.1-r1 [1.0]
[ebuild     U ~] sci-mathematics/pari-2.8_pre20160209 [2.8_pre20151201]
[ebuild  N    ~] dev-python/cysignals-1.0.1  PYTHON_TARGETS="python2_7 python3_4 -python3_5" 
[ebuild     U ~] sci-mathematics/sage-notebook-0.11.7 [0.11.6.1]
[ebuild  N    #] sci-mathematics/sage-7.1-r1  USE="X bin-html latex manifolds -bin-pdf -bliss -debug -html -modular_decomposition -pdf -testsuite" LINGUAS="en -ca -de -fr -hu -it -ja -pt -ru -tr" PYTHON_TARGETS="python2_7" 

!!! Multiple package instances within a single package slot have been pulled
!!! into the dependency graph, resulting in a slot conflict:

dev-libs/ntl:0

  (dev-libs/ntl-9.7.0:0/9.7.0::sage-on-gentoo, ebuild scheduled for merge) pulled in by
    >=dev-libs/ntl-9.6.2-r1:= required by (sci-mathematics/sage-7.1-r1:0/0::sage-on-gentoo, ebuild scheduled for merge)
    ^^             ^^^^^^^^                                                                                                                                                                      

  (dev-libs/ntl-9.6.2:0/9.6.2::sage-on-gentoo, installed) pulled in by
    dev-libs/ntl:0/9.6.2= required by (sci-libs/linbox-1.3.2-r2:0/0::sage-on-gentoo, installed)
                ^^^^^^^^^                                                                                                          
    dev-libs/ntl:0/9.6.2=[-threads] required by (sci-libs/libsingular-3.1.7_p1-r6:0/0::sage-on-gentoo, installed)
                ^^^^^^^^^                                                                                                                            
    >=dev-libs/ntl-5.4.2:0/9.6.2= required by (sci-mathematics/eclib-20150827:0/2::sage-on-gentoo, installed)
                        ^^^^^^^^^                                                                                                                
    dev-libs/ntl:0/9.6.2= required by (sci-mathematics/flint-2.5.2:0/13::gentoo, installed)
                ^^^^^^^^^                                                                                                      
    dev-libs/ntl:0/9.6.2=[-threads] required by (sci-mathematics/singular-3.1.7_p1-r4:0/0::sage-on-gentoo, installed)
</code></pre>

**Comment by kiwifb** [comment]
There must something funny going on with the subslot dependency. I need to check the doc but a rebuild should be triggered not a conflict.

**Comment by kiwifb** [comment]
Note that masking `dev-libs/ntl-9.7.0` should solve your problem since you already have a suitable version of `ntl`.

**Comment by kiwifb** [comment]
Version of `portage` I will want to be explained why it is not a bug if it isn't.

**Comment by ardok-m** [comment]
Masking <code>dev-libs/ntl-9.7.0</code> doesn't solve the conflict. I think because <code>sci-mathematics/sage-7.1-r1</code> requires <code>>=dev-libs/ntl-9.6.2-r1</code> while the other packages need <code>=dev-libs/ntl-9.6.2</code>. Or I'm misreading the output. 

<pre><code>emerge sage --verbose-conflicts

These are the packages that would be merged, in order:

Calculating dependencies... done!
[ebuild  N    ~] sci-mathematics/nauty-2.6.1 
[ebuild     U ~] dev-libs/ntl-9.6.4 [9.6.2]
[ebuild     U ~] sci-mathematics/arb-2.8.1 [2.7.0-r1]
[ebuild     U ~] sci-libs/pynac-0.6.2 [0.6.0]
[ebuild     UD~] dev-python/sympy-0.7.6.1-r1 [1.0]
[ebuild     U ~] sci-mathematics/pari-2.8_pre20160209 [2.8_pre20151201]
[ebuild  N    ~] dev-python/cysignals-1.0.1  PYTHON_TARGETS="python2_7 python3_4 -python3_5" 
[ebuild     U ~] sci-mathematics/sage-notebook-0.11.7 [0.11.6.1]
[ebuild  N    #] sci-mathematics/sage-7.1-r1  USE="X bin-html latex manifolds -bin-pdf -bliss -debug -html -modular_decomposition -pdf -testsuite" LINGUAS="en -ca -de -fr -hu -it -ja -pt -ru -tr" PYTHON_TARGETS="python2_7" 

!!! Multiple package instances within a single package slot have been pulled
!!! into the dependency graph, resulting in a slot conflict:

dev-libs/ntl:0

  (dev-libs/ntl-9.6.4:0/9.6.4::sage-on-gentoo, ebuild scheduled for merge) pulled in by
    >=dev-libs/ntl-9.6.2-r1:= required by (sci-mathematics/sage-7.1-r1:0/0::sage-on-gentoo, ebuild scheduled for merge)
    ^^             ^^^^^^^^                                                                                                                                                                      

  (dev-libs/ntl-9.6.2:0/9.6.2::sage-on-gentoo, installed) pulled in by
    dev-libs/ntl:0/9.6.2= required by (sci-libs/linbox-1.3.2-r2:0/0::sage-on-gentoo, installed)
                ^^^^^^^^^                                                                                                          
    dev-libs/ntl:0/9.6.2=[-threads] required by (sci-libs/libsingular-3.1.7_p1-r6:0/0::sage-on-gentoo, installed)
                ^^^^^^^^^                                                                                                                            
    >=dev-libs/ntl-5.4.2:0/9.6.2= required by (sci-mathematics/eclib-20150827:0/2::sage-on-gentoo, installed)
                        ^^^^^^^^^                                                                                                                
    dev-libs/ntl:0/9.6.2= required by (sci-mathematics/flint-2.5.2:0/13::gentoo, installed)
                ^^^^^^^^^                                                                                                      
    dev-libs/ntl:0/9.6.2=[-threads] required by (sci-mathematics/singular-3.1.7_p1-r4:0/0::sage-on-gentoo, installed)
                ^^^^^^^^^                                                                                                      
</code></pre>

Just in case you need it 
<pre><code>eix dev-libs/ntl

[U] dev-libs/ntl
     Available versions:  5.5.2 ~6.1.0 9.3.0 ~9.6.2(0/9.6.2)[1] (~)9.6.2-r1(0/9.6.2)[1] (~)9.6.4 (~)9.6.4(0/9.6.4)[1] [m](~)9.7.0(0/9.7.0)[1] {bindist doc static-libs test threads}
     Installed versions:  9.6.2(0/9.6.2)[1](10:20:28 PM 03/13/2016)(-doc -static-libs -test -threads)
     Homepage:            http://shoup.net/ntl/
     Description:         High-performance and portable Number Theory C++ library

[1] "sage-on-gentoo" /var/lib/layman/sage-on-gentoo</code></pre>

**Comment by ardok-m** [comment]
<pre><code>emerge --version
Portage 2.2.26 (python 2.7.10-final-0, default/linux/amd64/13.0/no-multilib, gcc-4.9.3, glibc-2.21-r2, 4.5.0-gentoo x86_64)</code></pre>

**Comment by kiwifb** [comment]
The problem may be that `9.6.2` and `9.6.2-r1` share the same slot/subslot. It is however strange none of these have an `=` on the left.

**Comment by kiwifb** [comment]
I'll have to dig it up with portage devs because it shouldn't be that way.
```
emerge -uv --nodeps dev-libs/ntl
```
should update `ntl` and then you may have to run `emerge @preserved-libraries` or something but it shouldn't be the case.

**Comment by ardok-m** [comment]
That workaround did the trick. Sage is being compiled at this moment.
Thanks!

**Comment by kiwifb** [comment]
Still it annoys me. As far as I can see I did everything right for it to "magically" work.

**Comment by ardok-m** [comment]
I can't help with that, sorry. But if you need someone to test something, just say it.

**Comment by kiwifb** [comment]
I have a felling that for some reason the subslot dependency may be broken at the overlay border. Now that I have a `flint` ebuild in the overlay I am curious to see if the problem will go away at the next `ntl` bump.

**Comment by ardok-m** [comment]
It seems not.
<pre><code>emerge -uDNv --verbose-conflicts @world

These are the packages that would be merged, in order:

Calculating dependencies... done!
[ebuild     U ~] sci-mathematics/flint-2.5.2-r1:0/13::sage-on-gentoo [2.5.2:0/13::gentoo] USE="ntl -doc -gc -static-libs (-test%)" 0 KiB
[ebuild     U ~] dev-libs/ntl-9.8.1:0/9.8.1::sage-on-gentoo [9.7.0:0/9.7.0::sage-on-gentoo] USE="-bindist -doc -static-libs {-test} -threads" 928 KiB
[ebuild     U ~] sci-libs/libsingular-3.1.7_p1-r7::sage-on-gentoo [3.1.7_p1-r6::sage-on-gentoo] USE="flint -boost -debug" 0 KiB
[ebuild     U ~] dev-python/cython-0.24::sage-on-gentoo [0.23.5::sage-on-gentoo] USE="-doc -emacs -examples {-test}" PYTHON_TARGETS="python2_7 python3_4 -python3_3 -python3_5" 1,633 KiB

Total: 4 packages (4 upgrades), Size of downloads: 2,561 KiB

!!! Multiple package instances within a single package slot have been pulled
!!! into the dependency graph, resulting in a slot conflict:

dev-libs/ntl:0

  (dev-libs/ntl-9.8.1:0/9.8.1::sage-on-gentoo, ebuild scheduled for merge) pulled in by
    (no parents that aren't satisfied by other packages in this slot)

  (dev-libs/ntl-9.7.0:0/9.7.0::sage-on-gentoo, installed) pulled in by
    >=dev-libs/ntl-9.6.2-r1:0/9.7.0= required by (sci-mathematics/sage-7.1-r1:0/0::sage-on-gentoo, installed)
                           ^^^^^^^^^                                                                                                             
    dev-libs/ntl:0/9.7.0= required by (sci-libs/linbox-1.3.2-r2:0/0::sage-on-gentoo, installed)
                ^^^^^^^^^                                                                                                          
    dev-libs/ntl:0/9.7.0=[-threads] required by (sci-mathematics/singular-3.1.7_p1-r4:0/0::sage-on-gentoo, installed)
                ^^^^^^^^^                                                                                                                                
    >=dev-libs/ntl-5.4.2:0/9.7.0= required by (sci-mathematics/eclib-20150827:0/2::sage-on-gentoo, installed)
                        ^^^^^^^^^      
</code></pre>

Doing the trick, <code>emerge -uv1 --nodeps dev-libs/ntl</code> I get, when running <code>emerge @preserved-rebuild</code>
<pre><code>emerge @preserved-rebuild

These are the packages that would be merged, in order:

Calculating dependencies... done!
[ebuild     U ~] sci-mathematics/flint-2.5.2-r1 [2.5.2]
[ebuild     U ~] sci-libs/libsingular-3.1.7_p1-r7 [3.1.7_p1-r6]
[ebuild   R   ~] sci-mathematics/singular-3.1.7_p1-r4 
[ebuild   R   ~] sci-libs/linbox-1.3.2-r2 
[ebuild   R   ~] sci-mathematics/eclib-20150827 
[ebuild   R   #] sci-mathematics/sage-7.1-r1 

WARNING: One or more updates/rebuilds have been skipped due to a dependency conflict:

sci-mathematics/singular:0

  (sci-mathematics/singular-4.0.2:0/0::gentoo, ebuild scheduled for merge) conflicts with
    ~sci-mathematics/singular-3.1.7_p1 required by (sci-mathematics/sage-7.1-r1:0/0::sage-on-gentoo, ebuild scheduled for merge)
    ^                         ^^^^^^^^
</code></pre>

It is now emerging everything. I suppose it will work.

**Comment by kiwifb** [comment]
It is very strange. The problem seems to be solved on some of my machines but not some other.

**Comment by kiwifb** [comment]
With my push to 7.2, `ecls` will behave the same way at least.

**Comment by ardok-m** [comment]
Yes, I found the same behavior for <code>ecls</code>. No other package has complained.
