### ISSUE TITLE
sandbox violation in sage-9999 when building doc for non english languages

### ISSUE THREAD

**Issue by kiwifb** [cschwan/sage-on-gentoo#416]
This is related to the `sphinx` upgrade. This is probably a `sphinx` upstream issue rather than a sage one but that cannot be dismissed.
```
VERSION 1.0
FORMAT: F - Function called
FORMAT: S - Access Status
FORMAT: P - Path as passed to function
FORMAT: A - Absolute Path (not canonical)
FORMAT: R - Canonical Path
FORMAT: C - Command Line

F: open_wr
S: deny
P: /usr/lib64/python2.7/site-packages/sphinx/locale/fr/LC_MESSAGES/sphinx.mo
A: /usr/lib64/python2.7/site-packages/sphinx/locale/fr/LC_MESSAGES/sphinx.mo
R: /usr/lib64/python2.7/site-packages/sphinx/locale/fr/LC_MESSAGES/sphinx.mo
C: /usr/bin/python2.7 sage_setup/docbuild/__main__.py --no-pdf-links all html 
```
The sphinx error log is:
```
# Sphinx version: 1.4.1
# Python version: 2.7.10 (CPython)
# Docutils version: 0.12 release
# Jinja2 version: 2.7.3
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/sphinx/cmdline.py", line 243, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/usr/lib64/python2.7/site-packages/sphinx/application.py", line 189, in __init__
    self._init_i18n()
  File "/usr/lib64/python2.7/site-packages/sphinx/application.py", line 214, in _init_i18n
    charset=self.config.source_encoding)
  File "/usr/lib64/python2.7/site-packages/sphinx/locale/__init__.py", line 217, in init
    catinfo.write_mo(language)
  File "/usr/lib64/python2.7/site-packages/sphinx/util/i18n.py", line 58, in write_mo
    with io.open(self.mo_path, 'wb') as mo:
IOError: [Errno 13] Permission denied: '/usr/lib64/python2.7/site-packages/sphinx/locale/fr/LC_MESSAGES/sphinx.mo'
```
note that sphinx is trying to open one of its own files in write mode which is of course forbidden but would go unnoticed in vanilla sage since there is no such controls. IT would be interesting to see if it affects other packages.

**Comment by strogdon** [comment]
What `LINGUAS` do you have set in `make.conf` so I can try this. I have only `en`. Apparently you have at least `en fr`.

**Comment by kiwifb** [comment]
I reproduced this with `fr` and `de`, I presume any non `en` will do.

**Comment by kiwifb** [comment]
Also, I disabled all `LINGUAS` apart from `en` in the master branch. You may have to use the `vbraun` branch or put the ebuild in a private overlay.

**Comment by strogdon** [comment]
Yes, I noticed that. However I'm unable to even start the build unless I remove the `f` 
```
raise OverflowError(f"
raise ValueError(f"
```
that appears in `sage/arith/multi_modular.pyx`. I didn't notice this when testing vanilla. And it was used in testing the `sphinx` upgrade. Is there some upgrade of something I've missed?

**Comment by kiwifb** [comment]
`cysignals`?

**Comment by kiwifb** [comment]
It looks like you company with that problem on sage-release. That file has been recently moved from another location and "cleaned up"

**Comment by strogdon** [comment]
Which version of `cython` are you using? Here I have `0.23.4-r2`. Sage does build once I get rid of the `f`.

**Comment by kiwifb** [comment]
I moved to 0.24 but I wouldn't think that's the issue but I cannot dismiss it.

**Comment by strogdon** [comment]
Relative to the sandbox problem, it seems that `sphinx` thinks there are some out of date files. I noticed on a vanilla sage install that the files under `sphinx/locale/*` all have the same time-stamp as the parent folder. Not so with gentoo install. Could this be the issue? If so, this was the case with the older sphinx but I don't recall a doc-build issue.

**Comment by strogdon** [comment]
Things are working with `cython-0.24`. So, unless something is flaky with my machine there may be a bug in the `cython-0.23.4-r2` parser. Although, I don't believe the syntax that's used in `multi_modular.pyx` is strictly correct.

**Comment by shimizukawa** [comment]
Sphinx compiles gettext `po` files if `mo` file has older timestamp than `po` file. This mechanism effects for under directory that is specified at `locale_dirs` of conf.py. I guess, If `/usr/lib64/python2.7/site-packages/sphinx/locale/` absolute path is set instead of document locale directory, the issue will be happened.

Please let me know the value of `locale_dirs` in your conf.py.

**Comment by kiwifb** [comment]
Thanks for the commenting. I have been through the Sphinx documentation and learned about locale_dirs and it isn't set at all in conf.py it must get a default value from somewhere else.

**Comment by kiwifb** [comment]
Here is a link to the `conf.py` where I first seemed to have encountered the problem
https://github.com/sagemath/sage/blob/develop/src/doc/fr/a_tour_of_sage/conf.py

**Comment by kiwifb** [comment]
And now I noticed that it import this `conf.py`:
https://github.com/sagemath/sage/blob/develop/src/doc/common/conf.py

**Comment by strogdon** [comment]
Is it possible that the sphinx install is to blame? If I touch all files under `/usr/lib/python2.7/site-packages/sphinx/locale/` on the live system then I'm able to build the french docs.

**Comment by kiwifb** [comment]
That's weird but at least that could be a solution.

**Comment by kiwifb** [comment]
Hum... the ebuild does strange manipulation with the `Grammar*.pickle` file(s). Could that be related?

**Comment by strogdon** [comment]
The following from the sphinx portage work folder after `ebuild sphinx-1.4.1.ebuild prepare`
```
python ./setup.py compile_catalog
python ./setup.py update_catalog
python ./setup.py build
```
adjusts the timestamp on all the `.js, .mo` and `.po` files under `build/lib/sphinx/locale`. I don't know how to do this from the ebuild nor if it's the correct thing to do, but seems to be what is done when all the live system `locale` files are touched. If required then why isn't this automatic?

**Comment by kiwifb** [comment]
I do, in `python_compile()` put
```
esetup.py compile_catalog
esetup.py update_catalog
```
before `distutils-r1_python_compile` (which does the build).

**Comment by kiwifb** [comment]
That didn't work. Do you have the `doc` useflag for sphinx enabled?

**Comment by strogdon** [comment]
No I don't have `doc` enabled.

**Comment by kiwifb** [comment]
I have tried variation of those commands in the ebuild but it never solved my problem, plus the first one breaks with python3.4 so I have to isolate it to run only on python2.7.

**Comment by strogdon** [comment]
Yes, once I disable `python3_{3,4,5}` in the ebuild then I get
```
open_wr
S: deny
P: /usr/lib64/python2.7/site-packages/Sphinx-1.4.1-py2.7.egg/sphinx/pycode/Grammar-py2-sphinx1.4.pickle
A: /usr/lib64/python2.7/site-packages/Sphinx-1.4.1-py2.7.egg/sphinx/pycode/Grammar-py2-sphinx1.4.pickle
R: /usr/lib64/python2.7/site-packages/Sphinx-1.4.1-py2.7.egg/sphinx/pycode/Grammar-py2-sphinx1.4.pickle
C: /usr/bin/python2.7 sage_setup/docbuild/__main__.py --no-pdf-links all html
```
which is worse than before - no docs at all.

**Comment by kiwifb** [comment]
That's different. I will have to poke that `Grammar*` pickle logic I have a hunch that it is the source of the problem.

**Comment by strogdon** [comment]
Vanilla Sage does install `local/lib/python2.7/site-packages/Sphinx-1.4.1-py2.7.egg/sphinx/pycode/Grammar-py2-sphinx1.4.pickle`. The ebuild does install a `.pickle` file `/usr/lib/python2.7/site-packages/sphinx/pycode/Grammar-py2-sphinx1.4.pickle` but not under the `egg` folder.

**Comment by strogdon** [comment]
So forget what I said about the `.pickle` stuff. The `Sphinx-1.4.1-py2.7.egg` folder should not even be present, gentoo doesn't install it. It must have gotten installed on my system when I was experimenting with the python setup.py file in the portage folder as root. Now with the changes to sphinx that involve `compile_catalog` and `update_catalog` I get a sandbox violation in building the french docs. You must have wondered `what in the world` am I doing? Sorry for the misinformation.

**Comment by jdemeyer** [comment]
> raise OverflowError(f"

This is [new Python syntax](https://www.python.org/dev/peps/pep-0498/) supported by Cython 0.24 but not Cython 0.23.x.

**Comment by strogdon** [comment]
OK, another try. The problem seems to be (at least partially) with:
```
    # compile mo files if po file is updated
    # TODO: remove circular importing
    from sphinx.util.i18n import find_catalog_source_files
#    for catinfo in find_catalog_source_files(locale_dirs, language, domains=[catalog],
#                                             charset=charset):
#        catinfo.write_mo(language)
```
in `sphinx/locale/__init__py`. The `#` in the first column are mine and with them I'm able to build the french docs. Apparenly, `locale_dirs` is being set to `${PYTHON_SITEDIR}/sphinx`, but why?

**Comment by kiwifb** [comment]
IT is probably a default value somehow. I inspected the source of `sage` for `locale_dirs` and it is not defined anywhere. Which is why I suspect it is a `sphinx` default value and that it is possibly an upstream issue.

**Comment by kiwifb** [comment]
From `sphinx/application.py`
```
    def _init_i18n(self):
        """Load translated strings from the configured localedirs if enabled in
        the configuration.
        """
        if self.config.language is not None:
            self.info(bold('loading translations [%s]... ' %
                           self.config.language), nonl=True)
            locale_dirs = [None, path.join(package_dir, 'locale')] + \
                [path.join(self.srcdir, x) for x in self.config.locale_dirs]
        else:
            locale_dirs = []
```
so `${PYTHON_SITEDIR}/sphinx/locale` is always on the list and it is not necessarily a bad thing - you may want the strings in the default file. But you shouldn't be trying to update it at runtime. So either something as to be done carefully at install time or it should be excluded of the list of things that can be updated.

**Comment by kiwifb** [comment]
I think I got something in `sphinx/util/i18n.py` in the function `find_catalog_source_files`:
```
    catalogs = set()
    for locale_dir in locale_dirs:
        if not locale_dir:
            continue  # skip system locale directory
```
That doesn't skip the system locale directory as far as I understand. `local_dirs` is a list of directories and `local_dir` takes a value in that list. You only skip for `local_dir` being `None` you need to skip also if the value is `path.join(package_dir, 'locale')` which is a system directory.

**Comment by strogdon** [comment]
Yes, `from sphinx import package_dir` and then skip over `locale_dir` when `locale_dir == path.join(package_dir, 'locale')` in the `if` test will work. I think this is an upstream issue. I don't see why one would want to modify any `sphinx` installed file at runtime.

**Comment by kiwifb** [comment]
Testing now, I don't like the test, I feel like it will miss stuff.

**Comment by kiwifb** [comment]
Success...

**Comment by kiwifb** [comment]
@shimizukawa do you have any comment on it being a real `sphinx` issue? The construction and parsing of `locale_dirs` has some strange bits in it and I don't really know the reasons behind the design. At the moment it seems to be constructed with:
* None
* site installation
* user defined location(s)
At the moment `find_catalog_source_files` skip over the first one calling it the "system locale directory", in truth the system locale directory is the second item and is not currently skipped.
The basic questions I have, are:
1) do we need `None`
2) should we skip the "system locale directory" or will it have unintended consequence in some scenario?

**Comment by strogdon** [comment]
Someone else (apparently unrelated to Sage) now has this issue https://github.com/sphinx-doc/sphinx/issues/2522

**Comment by kiwifb** [comment]
Thanks for that otherwise I would have opened a new one since the nice `sphinx` dev is not responsive here.

**Comment by shimizukawa** [comment]
@kiwifb I think it's a issue of Sphinx. sphinx.po under installed sphinx/locale directory have to be excluded from `compile_catalogs` target.
I'll fix it on https://github.com/sphinx-doc/sphinx/issues/2522.

**Comment by kiwifb** [comment]
Upstream fix in overlay. Closing,
