### ISSUE TITLE
Circular dependencies

### ISSUE THREAD

**Issue by Armoken** [cschwan/sage-on-gentoo#417]
Hi. I followed the instractions at [ https://wiki.gentoo.org/wiki/User_talk:Houseofsuns]( https://wiki.gentoo.org/wiki/User_talk:Houseofsuns) but anyway see the next:

` * Error: The above package list contains packages which cannot be
 * installed at the same time on the same system.

  (app-eselect/eselect-lapack-0.1:0/0::gentoo, installed) pulled in by
    app-eselect/eselect-lapack required by (sci-libs/lapack-reference-3.2.1-r4:0/0::gentoo, installed)

  (app-eselect/eselect-blas-0.1:0/0::gentoo, installed) pulled in by
    app-eselect/eselect-blas required by (sci-libs/blas-reference-20070226-r4:0/0::gentoo, installed)

  (sci-libs/gsl-2.1:0/19::science, ebuild scheduled for merge) pulled in by
    sci-libs/gsl[-cblas-external] required by (virtual/cblas-1.0:0/0::gentoo, installed)
    >=sci-libs/gsl-1.16 required by (sci-mathematics/sage-7.1:0/0::sage-on-gentoo, ebuild scheduled for merge)
    sci-libs/gsl required by (sci-mathematics/gmp-ecm-6.4.4-r2:0/0::sage-on-gentoo, ebuild scheduled for merge)

  (app-admin/eselect-1.4.5-r103:0/0::science, ebuild scheduled for merge) pulled in by
    app-admin/eselect required by (app-eselect/eselect-java-0.1.0:0/0::gentoo, installed)
    >=app-admin/eselect-1.2.6 required by (app-eselect/eselect-emacs-1.18:0/0::gentoo, installed)
    >=app-admin/eselect-1.2.4 required by (app-eselect/eselect-opencl-1.1.0-r1:0/0::gentoo, installed)
    app-admin/eselect required by (app-eselect/eselect-lib-bin-symlink-0.1.1:0/0::gentoo, installed)
    >=app-admin/eselect-1.2.4 required by (app-eselect/eselect-qtgraphicssystem-1.1.1:0/0::gentoo, installed)
    >=app-admin/eselect-1.2.4 required by (app-eselect/eselect-mesa-0.0.10:0/0::gentoo, installed)
    >=app-admin/eselect-1.2 required by (sys-apps/portage-2.2.26:0/0::gentoo, installed)
    >=app-admin/eselect-1.2.4 required by (app-eselect/eselect-opengl-1.3.1-r4:0/0::gentoo, installed)
    app-admin/eselect required by (app-eselect/eselect-lcdfilter-1:0/0::gentoo, installed)
    >=app-admin/eselect-1.2.3 required by (app-eselect/eselect-fontconfig-1.1:0/0::gentoo, installed)
    >=app-admin/eselect-1.2.3 required by (app-eselect/eselect-ctags-1.18:0/0::gentoo, installed)
    app-admin/eselect required by (app-eselect/eselect-wxwidgets-20140423:0/0::gentoo, installed)
    >=app-admin/eselect-1.0.2 required by (app-eselect/eselect-ruby-20131227:0/0::gentoo, installed)
    app-admin/eselect required by (app-eselect/eselect-infinality-1:0/0::gentoo, installed)
    >=app-admin/eselect-1.2.3 required by (app-eselect/eselect-python-20111108:0/0::gentoo, installed)
    >=app-admin/eselect-1.0.5 required by (app-eselect/eselect-blas-0.1:0/0::gentoo, installed)
    >=app-admin/eselect-1.4.5-r103 required by (sci-libs/gsl-2.1:0/19::science, ebuild scheduled for merge)
    >=app-admin/eselect-1.0.5 required by (app-eselect/eselect-lapack-0.1:0/0::gentoo, installed)
`

**Comment by kiwifb** [comment]
1) this is an issue for the science overlay.
2) you still have bits from the main tree that should be removed before you proceed.
Remove `blas-reference` and `lapack-reference` at least and then start again.

**Comment by Armoken** [comment]
Thank you. I remove blas-reverence, lapack-reference and unmask virtual/blas virtual/cblas virtual/lapack. And now all is prefect.
