### ISSUE TITLE
useflag of sage: both 'pdf' and 'html' means the documentation?

### ISSUE THREAD

**Issue by rtlix** [cschwan/sage-on-gentoo#421]
```
rt ~ # equery u sage
[ Legend : U - final flag setting for installation]
[        : I - package is installed with flag     ]
[ Colors : set, unset                             ]
 * Found these USE flags for sci-mathematics/sage-7.1:
 U I
 + + X                        : Add support for X11
 + - bin-html                 : install pre-built html documentation 
 + - bin-pdf                  : install pre-built pdf documentation 
 - - bliss                    : build the bindings to the bliss library 
 - - debug                    : Enable extra debug codepaths, like asserts and extra output.
                                If you want to get meaningful backtraces see https://wiki.gent
                                oo.org/wiki/Project:Quality_Assurance/Backtraces
 - - html                     : build and install html documentation 
 + + latex                    : Add support for LaTeX (typesetting package)
 - - linguas_ca               : Catalan locale
 - - linguas_de               : German locale
 + + linguas_en               : English locale
 - - linguas_fr               : French locale
 - - linguas_hu               : Hungarian locale
 - - linguas_it               : Italian locale
 - - linguas_ja               : Japanese locale
 - - linguas_pt               : Portuguese locale
 - - linguas_ru               : Russian locale
 - - linguas_tr               : Turkish locale
 - - modular_decomposition    : build the bindings to the modular_decomposition library 
 - + pdf                      : Add general support for PDF (Portable Document Format), this
                                replaces the pdflib and cpdflib flags
 + + python_targets_python2_7 : Build with Python 2.7
 - - testsuite                : If activated installs Sage's sources into
                                /usr/share/sage/devel/sage to enable testing 

```
from the use description, I guess pdf is not meant for compiling and install documentation of pdf type.
however :
```
rt ~ # emerge -qavDuN sage


!!! Problem resolving dependencies for sci-mathematics/sage

!!! The ebuild selected to satisfy "sage" has unmet requirements.
- sci-mathematics/sage-7.1::sage-on-gentoo USE="X bin-html bin-pdf latex pdf -bliss -debug -html -modular_decomposition -testsuite" LINGUAS="en -ca -de -fr -hu -it -ja -pt -ru -tr" PYTHON_TARGETS="python2_7"

  The following REQUIRED_USE flag constraints are unsatisfied:
    bin-html? ( !pdf ) bin-pdf? ( !pdf )

  The above constraints are a subset of the following complete expression:
    html? ( linguas_en ) testsuite? ( any-of ( bin-html html ) ) bin-html? ( !html !pdf linguas_en ) bin-pdf? ( !html !pdf linguas_en ) any-of ( python_targets_python2_7 )

```
the pdf useflag seems to be similar to html and is thus conflict of bin-pdf

**Comment by kiwifb** [comment]
Basically yes. `html` is for the building the doc in `html` format. `pdf` is to build it in `pdf` format. I recommend you to use `package.use/99sage-bin-doc` to set sane useflags to get the documentation in binary format.
I don't recommend user of `sage-7.1` and under to build the documentation - in either format - but to use the binary form.

The building of the documentation has made a leap in sanity in the upcoming `7.2`, `bin-html` and `bin-pdf` may be removed for that one. Still thinking about it.

**Comment by rtlix** [comment]
I think it's no necessary to build doc yourself, so useflags 'html' and 'pdf' can be removed, and the description of useflag 'pdf' in `equery u`  output is misleading as I see

**Comment by kiwifb** [comment]
Hum... You are right, in this case the output is misleading. The description is the default description of the useflag and doesn't represent the use I make of it. I could add a more appropriate description in `metadata.xml`.
Offering pre-built documentation started because building the documentation in sage-on-gentoo was broken. It is not anymore but requires a specific version of `sphinx`, when a more recent version is stable. Building the documentation yourself in 7.1 and under may mean that you have to downgrade your `sphinx` install.
Upcoming sage 7.2 will use `sphinx` 1.4 which isn't in the main tree yet but already present in this overlay.
When 7.2 comes out, getting the doc won't be a building problem anymore, just a time problem.

**Comment by kiwifb** [comment]
`equery -u sage` should now report something more sensible, I also updated other entries in the last 24hours.
