### ISSUE TITLE
Unsatisfied REQUIRED_USE constraints: bin-html? ( !pdf )

### ISSUE THREAD

**Issue by Pastafarianist** [cschwan/sage-on-gentoo#423]
```
!!! The ebuild selected to satisfy "sage" has unmet requirements.
- sci-mathematics/sage-7.2::sage-on-gentoo USE="X bin-html pdf -bin-pdf -bliss -debug -html -latex -modular_decomposition -sagenb -testsuite" ABI_X86="64" LINGUAS="en fr ru -ca -de -hu -it -ja -pt -tr" PYTHON_TARGETS="python2_7"

  The following REQUIRED_USE flag constraints are unsatisfied:
    bin-html? ( !pdf )

  The above constraints are a subset of the following complete expression:
    html? ( linguas_en ) testsuite? ( any-of ( bin-html html ) ) bin-html? ( !html !pdf linguas_en ) bin-pdf? ( !html !pdf linguas_en ) any-of ( python_targets_python2_7 )
```

This is the first time I'm installing Sage. I'm not sure what extra information I can provide to help debugging this.

**Comment by kiwifb** [comment]
No extra info needed. You should also use `package.use/99sage-bin-doc` to have sane flags for the documentation. There is a small note about it in the README but it should be updated.

**Comment by Pastafarianist** [comment]
Thank you, it worked.
(although I'm not actually an ~arch user)

**Comment by kiwifb** [comment]
If you think it is for ~arch user the README definitely needs rewriting.

**Comment by Pastafarianist** [comment]
I have some packages `~amd64` unmasked, but I'm mostly using stable versions. And I'm not sure if I understand correctly what you mean.

**Comment by kiwifb** [comment]
I pointed you to use `package.use/99sage-bin-doc` and you answered
```
Thank you, it worked.
(although I'm not actually an ~arch user)
```
So if you think that this file is for ~arch users, I have some writing to do.

**Comment by Pastafarianist** [comment]
I said this because the README says:

> This is recommended for ~arch users.

**Comment by kiwifb** [comment]
Right. It really need updating.
