### ISSUE TITLE
pdf docs fail to build (prefix) sage-9999 (7.3.beta4)

### ISSUE THREAD

**Issue by strogdon** [cschwan/sage-on-gentoo#427]
Initially with `sphinx-1.4.1-r3` I get failures similar to https://github.com/cschwan/sage-on-gentoo/issues/418

```
pdfTeX warning: pdflatex (file ./graph_plot-19.pdf): PDF inclusion: invalid oth
er resource which is no dict (key 'XObject', type <null>); ignored.


pdfTeX warning: pdflatex (file ./graph_plot-19.pdf): PDF inclusion: invalid oth
er resource which is no dict (key 'Pattern', type <null>); ignored.


pdfTeX warning: pdflatex (file ./graph_plot-19.pdf): PDF inclusion: invalid oth
er resource which is no dict (key 'ExtGState', type <null>); ignored.


pdfTeX warning: pdflatex (file ./graph_plot-19.pdf): PDF inclusion: invalid oth
er resource which is no dict (key 'Shading', type <null>); ignored.

!pdfTeX error: pdflatex (file ./graph_plot-19.pdf): PDF inclusion: invalid font
 resources dict type <null>
 ==> Fatal error occurred, no output PDF file produced!
```

and after upgrading to sphinx to 1.4.2 I now have

```
LaTeX Warning: Hyper reference `sage/rings/asymptotic/growth_group::doc' on pag
e 8 undefined on input line 435.

! Missing \endcsname inserted.
<to be read again>
                   \let
l.445 \begin{Verbatim}[commandchars=\\\{\}]

?
! Emergency stop.
<to be read again>
                   \let
l.445 \begin{Verbatim}[commandchars=\\\{\}]

End of file on the terminal!


Here is how much of TeX's memory you used:
 13315 strings out of 494915
 185646 string characters out of 3923905
 264669 words of memory out of 5212653
 16250 multiletter control sequences out of 15000+600000
 60343 words of font info for 77 fonts, out of 8000000 for 9000
 37 hyphenation exceptions out of 8191
 36i,15n,45p,389b,382s stack positions out of 5000i,500n,10000p,200000b,50000s
!  ==> Fatal error occurred, no output PDF file produced!
```

from `build_doc/latex/en/reference/asymptotic/asymptotic.log`, which may indicate incorrect `latex` generation.

**Comment by kiwifb** [comment]
`1.4.2` and `1.4.3` are no good to build pdf doc. I will put 1.4.4 when it is out, which should be much better. Now "invalid font...." we should be able to get something out of that.

**Comment by kiwifb** [comment]
Is it all with `en`?

**Comment by strogdon** [comment]
yes

**Comment by kiwifb** [comment]
Hum.... Upstream may have an idea but first I should prepare a live ebuild so we are sure things are still broken after their big latex re-org (which breaks things in 1.4.2 - what you saw - and is still present in 1.4.3).

**Comment by kiwifb** [comment]
1.4.4 is out! So I will ship that.

**Comment by kiwifb** [comment]
OK 1.4.4 is in the overlay and I will test it on my side too.

**Comment by strogdon** [comment]
OK, rebuilt sage with `sphinx-1.4.1-r3` and now no errors. Perhaps a parallel build thingy? So I'm wondering if https://github.com/cschwan/sage-on-gentoo/issues/418 was really due to the `fix` for that issue.

**Comment by kiwifb** [comment]
Parallel build is a possibility. Does it happen with vanilla or you don't know?

**Comment by strogdon** [comment]
vanilla builds just fine, but vanilla is on a machine with 4 cores. the prefix machine has 12 cores.

**Comment by strogdon** [comment]
Builds and installs with `sphinx-1.4.4`. Clearly the issue is not sphinx-related.

**Comment by kiwifb** [comment]
Lets keep it open until we have more clues.

**Comment by kiwifb** [comment]
Is this over?

**Comment by strogdon** [comment]
I had to manually upgrade to `sphinx-1.4.4-r1`. Useflags had changed and I had not updated mine, so I hadn't built the pdf docs since  https://github.com/cschwan/sage-on-gentoo/issues/427#issuecomment-226070995 -  something I had overlooked. Here the pdf docs do build and install with `1.4.4-r1` and `L10N=en`. So perhaps the `phantom` had moved on.

**Comment by kiwifb** [comment]
And we are moving to `sphinx-1.5.3` in the next snapshot, all the legwork upstream should pay off. And 1.4.1 is gone from the overlay. Closing.
