### ISSUE TITLE
sci-mathematics/maxima-5.37.3-r4 stabilised on amd64

### ISSUE THREAD

**Issue by WPettersson** [cschwan/sage-on-gentoo#430]
Gentoo has stabilised maxima 5.37.3-r4 (see https://bugs.gentoo.org/show_bug.cgi?id=573544) but sage-on-gentoo only has 5.35.1-r2, which means I'm now getting

```
!!! Multiple package instances within a single package slot have been pulled
!!! into the dependency graph, resulting in a slot conflict:


sci-mathematics/maxima:0

  (sci-mathematics/maxima-5.37.3-r4:0/0::gentoo, ebuild scheduled for merge) pulled in by
    (no parents that aren't satisfied by other packages in this slot)

  (sci-mathematics/maxima-5.35.1-r2:0/0::sage-on-gentoo, ebuild scheduled for merge) pulled in by
    ~sci-mathematics/maxima-5.35.1[ecls] required by (sci-mathematics/sage-7.2:0/0::sage-on-gentoo, ebuild scheduled for merge)
    ^                       ^^^^^^                                                                                                                                                    
```

eix output

```
# eix sci-mathematics/maxima
[U] sci-mathematics/maxima
     Available versions:  5.34.1 (~)5.35.1-r2[1] 5.37.3-r4 ~5.38.1 {X clisp clozurecl cmucl ecls emacs gcl latex nls sbcl tk unicode xemacs LINGUAS="de es pt pt_BR"}
     Installed versions:  5.35.1-r2[1](17:23:56 20/12/15)(X ecls latex nls tk unicode -clisp -clozurecl -cmucl -emacs -gcl -sbcl -xemacs LINGUAS="-es -pt -pt_BR")
     Homepage:            http://maxima.sourceforge.net/
     Description:         Free computer algebra environment based on Macsyma

[1] "sage-on-gentoo" /var/lib/layman/sage-on-gentoo
```

It's fairly easy for me to work around personally, but should something be done about this?

**Comment by kiwifb** [comment]
It doesn't prevent you from upgrading anything does it? I have lived with a version of that message for a while now. Nothing much you can do about it.

**Comment by WPettersson** [comment]
It does stop the upgrade from going through on my system, but I just masked sci-mathematics/maxima::gentoo and that ensures that I'll stick to the sage-on-gentoo version.

**Comment by kiwifb** [comment]
OK that's not normal, we should try to get to the bottom of that. What does `equery d maxima` report.

**Comment by WPettersson** [comment]
$ equery d maxima
     * These packages depend on maxima:
    sci-mathematics/sage-7.2 (~sci-mathematics/maxima-5.35.1[ecls])

Just sage, it appears.

**Comment by strogdon** [comment]
The same  here. I've had to mask `=sci-mathematics/maxima-5.37.3-r4` to accommodate a recent system upgrade.

**Comment by kiwifb** [comment]
I have not been hit yet. It may be possible to move to a 5.38.1 build (with appropriate patches) I'll need a bit of time to investigate.
In the mean time which version of portage do you have?

**Comment by strogdon** [comment]
```
[I] sys-apps/portage
     Available versions:  2.2.8-r2 2.2.24 2.2.26 2.2.28 ~2.3.0_rc1-r1 ~2.3.0 **9999 {build doc epydoc +ipc python2 python3 selinux xattr LINGUAS="ru" PYTHON_TARGETS="pypy python2_7 python3_3 python3_4 python3_5"}
     Installed versions:  2.2.28(02:47:05 AM 06/28/2016)(ipc xattr -build -doc -epydoc -selinux LINGUAS="-ru" PYTHON_TARGETS="python2_7 python3_3 -pypy -python3_4 -python3_5")
     Homepage:            https://wiki.gentoo.org/wiki/Project:Portage
     Description:         Portage is the package management and distribution system for Gentoo
```
In my prefix I don't seem to have any conflicts.

**Comment by kiwifb** [comment]
Hum. Would removing it and then re-installing solve the problem?

**Comment by strogdon** [comment]
I presume you meant `maxima`. Removing `portage` is probably not a good idea. After removing `maxima` and re-installing and then unmasking version `5.37.3-r4`:

emerge -puDN world (sage not in world file)
```
Calculating dependencies... done!
[ebuild     U  ] sci-mathematics/maxima-5.37.3-r4 [5.35.1-r2] LINGUAS="-de%" 
[blocks B      ] app-emacs/imaxima ("app-emacs/imaxima" is blocking sci-mathematics/maxima-5.37.3-r4)

 * Error: The above package list contains packages which cannot be
 * installed at the same time on the same system.

  (sci-mathematics/maxima-5.37.3-r4:0/0::gentoo, ebuild scheduled for merge) pulled in by
    sci-mathematics/maxima required by (sci-mathematics/wxmaxima-15.08.2:0/0::gentoo, installed)
    >=sci-mathematics/maxima-5.29 required by (app-emacs/imaxima-1.0-r3:0/0::gentoo, installed)

  (app-emacs/imaxima-1.0-r3:0/0::gentoo, installed) pulled in by
    app-emacs/imaxima required by @selected
```

emerge -puDN world (sage in world file)
```
Calculating dependencies... done!
[ebuild     U ~] sci-mathematics/rw-0.7-r1 [0.7]
[ebuild  N    #] sci-mathematics/sage-9999  USE="X debug html latex sagenb testsuite -bliss -modular_decomposition -pdf" L10N="en fr -ca -de -hu -it -ja -pt -ru -tr" PYTHON_TARGETS="python2_7" 

WARNING: One or more updates/rebuilds have been skipped due to a dependency conflict:

sci-mathematics/maxima:0

  (sci-mathematics/maxima-5.37.3-r4:0/0::gentoo, ebuild scheduled for merge) conflicts with
    ~sci-mathematics/maxima-5.35.1[ecls] required by (sci-mathematics/sage-9999:0/0::sage-on-gentoo, ebuild scheduled for merge)
    ^                       ^^^^^^     
```
In this latter case the merge proceeds. It was perhaps in the former case (sage not in world file) that I encountered the issue. I usually don't have sage in my world file, so this may not be what @WPettersson has.

**Comment by kiwifb** [comment]
Yes, you are not in the case where `sage` is the only dependency of `maxima`. It looks like you have `imaxima` and `wxmaxima` also present and complicating the mix. You may need a very specific version of `wxmaxima` to match your version of `maxima` if I remember well.

**Comment by WPettersson** [comment]
Uninstalling and reinstalling maxima does work fine on my system, so I can't reproduce this any more. It had been a month or so since I updated due to a recent move, that may have been part of the issue.

**Comment by kiwifb** [comment]
I think sometimes there is cached data from the current install that gets in the way. When you install something a "copy" of the ebuild and some cache data about the package are stored. It helps with removal in the future when an ebuild is not in the tree anymore and so forth. 
I think sometimes those cached copy can get out of sync with what happens in portage internally and causes these kind of issues.
