### ISSUE TITLE
dev-python/sympy-1.0-r1: missing Python-3.5 support

### ISSUE THREAD

**Issue by Coacher** [cschwan/sage-on-gentoo#432]
Hello.

sympy-1.0-r1 in the main tree has Python 3.5 support.

Please add it in your overlay as well.

**Comment by kiwifb** [comment]
Thanks for the head up. I'll have to remember why I am carrying a copy.

**Comment by kiwifb** [comment]
And done.

**Comment by Coacher** [comment]
Thank you.
