### ISSUE TITLE
sci-mathematics/optimal no longer available?

### ISSUE THREAD

**Issue by liuexp** [cschwan/sage-on-gentoo#434]
It looks like the website has gone down: http://www.permutationpuzzles.org/rubik/

Anyone has a local cache? Thanks!

**Comment by kiwifb** [comment]
OK I will host tarballs on a mirror ASAP Do report if anything else is missing.

**Comment by kiwifb** [comment]
sync and try again please.

**Comment by liuexp** [comment]
Thanks! Build successful this time.
