### ISSUE TITLE
sci-mathematics/singular-4.0.3_p3 fails to build with USE +emacs

### ISSUE THREAD

**Issue by veelai** [cschwan/sage-on-gentoo#440]
On my hardened ~amd64 machine I see the following error.

<pre>
/var/tmp/portage/sci-mathematics/singular-4.0.3_p3/temp/environment: line 4508: cd: /var/tmp/portage/sci-mathematics/singular-4.0.3_p3/work/share/singular/emacs/: No such file or directory
 * Compiling GNU Emacs Elisp files ...
>>Error occurred processing *.el: File error (("Opening input file" "no such file or directory" "/var/tmp/portage/sci-mathematics/singular-4.0.3_p3/work/singular-4.0.3/*.el"))
 * elisp-compile: batch-byte-compile failed
 [ !! ]
</pre>

If I change the relevant src_compile bit to the following this vanishes.

<pre>
	if use emacs; then
		cd "${S}"/emacs/
		elisp-compile *.el || die "elisp-compile failed"
	fi
</pre>

**Comment by kiwifb** [comment]
Thanks for the report. I have a bunch of stuff to update all over the place, but that should be one of the first in line.

**Comment by kiwifb** [comment]
Try this one.

**Comment by veelai** [comment]
Works like a charm.
