### ISSUE TITLE
Cubex 404 once again

### ISSUE THREAD

**Issue by sonOfRa** [cschwan/sage-on-gentoo#446]
Portage tries to download file http://sagetrac.lipn.univ-paris13.fr/sage/solver.tar.xz, which is not present, however, http://sagetrac.lipn.univ-paris13.fr/sage/cubex-20060128.tar.xz seems to be present. Placing that file in /usr/portage/distfiles makes emerging of cubex work.

**Comment by kiwifb** [comment]
fixed by 8bdc813367c06597fd872327fa596827ce6163dc thanks for pointing it out.
