### ISSUE TITLE
`sci-mathematics/sage` fails with "internal compiler error"

### ISSUE THREAD

**Issue by dlahoti** [cschwan/sage-on-gentoo#448]
trying to build sage, I get the following error:

`InternalError: Internal compiler error: 'cysignals/memory.pxi' not found`

I have `dev-python/cysignals` installed, and the file `/usr/lib64/python2.7/site-packages/cysignals/memory.pxi` exists, so I'm not sure what is causing the error. If I copy the `cysignals` directory into the `src-python2_7` directory, I don't get this error, but I get another error later saying `'_add_' already defined` while compiling `sage/matrix/matrix0.pyx`.

**Comment by kiwifb** [comment]
Which version of the following do you have: cysignals, cython and python:2.7?

**Comment by kiwifb** [comment]
I am fairly sure that it is caused by using the wrong version of `cython`

**Comment by dlahoti** [comment]
You were right, updating `cython` fixed this problem. Thanks!
