### ISSUE TITLE
sage-7.5.1 docs - more than one target found for cross-reference u'tuple'

### ISSUE THREAD

**Issue by gagern** [cschwan/sage-on-gentoo#450]
Sage fails to build its documentation for me.

```
Error building the documentation.
Traceback (most recent call last):
  File "sage_setup/docbuild/__main__.py", line 2, in <module>
    main()
  File "/var/tmp/portage/sci-mathematics/sage-7.5.1/work/sage-7.5.1/src-python2_
7/sage_setup/docbuild/__init__.py", line 1667, in main
    builder()
  File "/var/tmp/portage/sci-mathematics/sage-7.5.1/work/sage-7.5.1/src-python2_
7/sage_setup/docbuild/__init__.py", line 316, in _wrapper
    getattr(get_builder(document), 'inventory')(*args, **kwds)
  File "/var/tmp/portage/sci-mathematics/sage-7.5.1/work/sage-7.5.1/src-python2_
7/sage_setup/docbuild/__init__.py", line 510, in _wrapper
    build_many(build_ref_doc, L)
  File "/var/tmp/portage/sci-mathematics/sage-7.5.1/work/sage-7.5.1/src-python2_
7/sage_setup/docbuild/__init__.py", line 252, in build_many
    ret = x.get(99999)
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
OSError: [homology ] /var/tmp/portage/sci-mathematics/sage-7.5.1/work/sage-7.5.1/src-python2_7/build/lib/sage/homology/simplicial_complex.py:
docstring of sage.homology.simplicial_complex.Simplex:None:
WARNING: more than one target found for cross-reference u'tuple':
sage.homology.simplicial_complex.Simplex.tuple, sage.homology.cubical_complex.Cube.tuple
```

Is this an upstream issue, or something at the ebuild level?

**Comment by kiwifb** [comment]
I should have done a better job. I was on the sphinx bug so I knew it would hit the tree and potentially affect you people on ~arch. You have `sphinx-1.5.1` don't you?

**Comment by gagern** [comment]
1.5.1-r1, yes.

**Comment by kiwifb** [comment]
I'll have to look into the changes needed for `1.5.x` in the meantime I will pin the sphinx dependency a bit better.

**Comment by kiwifb** [comment]
Ok, sage should now pull `sphinx-1.4.4` and the problem shouldn't happen.

**Comment by gagern** [comment]
I'm in the process of downgrading sphinx and building sage with that, but it will take a while to complete. Will close this issue once that succeeds. Thanks for the quick reaction!

**Comment by gagern** [comment]
I had a look at the file, and can't see why sphinx would consider `tuple` a reference there. I don't see any special markup to make it that. The line most likely to trigger this would be

    :type X: integer or list, tuple, or other iterable

but on the one hand that looks like plain text, not links, and on the other hand even if the words were to denote types, they should refer to classes or built-in types, not methods. Strange, but feels like a bug in sphinx.

Do you have any idea of how to invoke sphinx in order to reproduce the kind of invocation Sage does? If so, it might be worth bisecting this in [the sphinx repo](https://github.com/sphinx-doc/sphinx).

**Comment by kiwifb** [comment]
Not directly. The recipe I have in the ebuild is the best thing I have:
```
"${PYTHON}" sage_setup/docbuild/__main__.py --no-pdf-links all html
```

**Comment by gagern** [comment]
OK, I got past the error I originally reported, but now I encounter [a different error](https://github.com/cschwan/sage-on-gentoo/issues/451). Probably unrelated, though, so I'll close this one here.

**Comment by gagern** [comment]
Yes, after fixing #451 the build succeeded, so the sphinx version was indeed the problem.
