### ISSUE TITLE
Pynac dependency not in ebuild

### ISSUE THREAD

**Issue by soleera** [cschwan/sage-on-gentoo#453]
Noticed sci-libs/pynac-0.7.3-r1 has a dependency on sci-libs/libfac from the science overlay, but this is not in the ebuild; if libfac is missing the emerge will fail at the configure stage.

**Comment by kiwifb** [comment]
You are right about a missing dependency, but it is not libfac but singular (libfac is technically inside singular I believe).

**Comment by kiwifb** [comment]
Fixed, you should unmerge libfac if you had it. It is likely to conflict with singular.

**Comment by kiwifb** [comment]
unmerge factory too.

**Comment by soleera** [comment]
thanks for that :)
