### ISSUE TITLE
Python 3.6 targets

### ISSUE THREAD

**Issue by TheJJ** [cschwan/sage-on-gentoo#455]
Please add `python_targets_python3_6` to the python ebuilds, for example to `cython`, `numpy`, ...

**Comment by kiwifb** [comment]
Point. I'll do that ASAP where appropriate.

**Comment by kiwifb** [comment]
Massively added python3_6 to most ebuild compatible to python3 with 5a2b82902614919e3f28ae9c7e47a1e2af8a17ae. I left `sympy` out for now as I haven't seen it in the main tree yet. Not sure they'll all work ;)
