### ISSUE TITLE
threejs viewer is broken as of 7.6.beta6

### ISSUE THREAD

**Issue by strogdon** [cschwan/sage-on-gentoo#456]
Prior to `7.6.beta6` this
```
show(sphere(), viewer='threejs')
```
would work both from the command line and from the sage and jupyter notebooks since s-o-g used online `threejs` resources. However, with `7.6.beta6` https://trac.sagemath.org/ticket/22389 introduce the `online` parameter that broke the above `show` with vanilla sage in the notebooks - the command line would work. To get s-o-g to work one now has to type
```
show(sphere(), viewer='threejs', online=True)
```
since the default is `online=False` which forces use of locally installed `threejs` resources. The ticket 
https://trac.sagemath.org/ticket/22488 is supposed to correct the failures in the notebooks but as near as I can determine the changes will not work on s-o-g unless the `online=True` option is used since local `threejs` resources are not installed?

**Comment by kiwifb** [comment]
Yes, at the moment it is broken. I am not happy about doing packaging of stuff like threejs. I should at least change the default.

**Comment by strogdon** [comment]
Yes, I agree. But there does seem to be a push to make `threejs` the default to replace `jmol` ? I don't know how wise this is, see https://trac.sagemath.org/ticket/22408.

**Comment by kiwifb** [comment]
I won't be sorry to leave jmol behind. But technically if I want to create a source package of threejs for off-line use it may be just as bad. I probably should change the default and provide an "offline" use flag.

**Comment by strogdon** [comment]
This is perhaps not as bad as I had thought. With `7.6.rc0` from both notebooks `online=True` is always what is used regardless of what `online` was set in the `show()`. The only failure is from the command prompt where to get things to work with s-o-g one must use `online=True`.

**Comment by strogdon** [comment]
Well, I must be missing something. From `sage/plot/plot3d/base.pyx` it would appear that `online` should not always be `True`? Not sure why `online` is always set to `True`. In fact it appears that `online` is not even being used. Perhaps somthingelse? For whatever reason the `show()` works in both notebooks regardless of whether `online` is or is not set.

**Comment by strogdon** [comment]
Reading things a little more carefully, it would appear that the `online=True` option is indeed what is used if local stuff is not available.

**Comment by kiwifb** [comment]
Good since I was thinking of pushing something like that. Saves me some work.

**Comment by strogdon** [comment]
However, the command-line will fail unless `online=True` is explicitly set.

**Comment by kiwifb** [comment]
OK that needs fixing.

**Comment by strogdon** [comment]
Taking a clue from what appears in `sage/plot/plot3d/base.pyx` I believe, still keeping the provided `/usr/share/threejs` path, that the following will work
```
diff --git a/src/sage/plot/plot3d/base.pyx b/src/sage/plot/plot3d/base.pyx
index 688dfbd..a861e99 100644
--- a/src/sage/plot/plot3d/base.pyx
+++ b/src/sage/plot/plot3d/base.pyx
@@ -398,6 +398,11 @@ cdef class Graphics3d(SageObject):
                 scripts = ( """
 <script src="{0}/threejs/three.min.js"></script>
 <script src="{0}/threejs/OrbitControls.js"></script>
+<script>
+  if ( !window.THREE ) document.write('\
+<script src="https://cdn.rawgit.com/mrdoob/three.js/r80/build/three.min.js"><\/script>\
+<script src="https://cdn.rawgit.com/mrdoob/three.js/r80/examples/js/controls/OrbitControls.js"><\/script>');
+</script>
                 """.format( SAGE_SHARE ) )
 
         b = self.bounding_box()
```
I tried with vanilla and moving `local/share/threejs` out of the way and it seemed to work. In any event this points to where modifications may be in order. It's a bummer to check since Sage has to be rebuilt.

**Comment by kiwifb** [comment]
So you are basically checking if it working and then fall back. I am thinking of something a bit earlier than that. I cannot match your line number but I would act at `options[`online`]`.

**Comment by kiwifb** [comment]
I should have put something in 7.6, this escaped.

**Comment by strogdon** [comment]
This is in a state of flux (see https://trac.sagemath.org/ticket/21258).

**Comment by strogdon** [comment]
corrected ticket above!

**Comment by kiwifb** [comment]
Using `installed_packages` not good.

**Comment by strogdon** [comment]
I hope they don't create a maintainer's nightmare.

**Comment by kiwifb** [comment]
I have stated my dislike on the ticket and put on opener on possible solutions. One of the advantage to go to a web app is that it can always be up to date. The only problem here is whether the interface is stable enough, backward enough, to just go latest or to a max.

**Comment by kiwifb** [comment]
OK, in 8.0.beta2 available now, there is a band aid.

**Comment by strogdon** [comment]
So here the following
```
show(sphere(), viewer='threejs')
show(sphere(), viewer='threejs', online=True)
show(sphere(), viewer='threejs', online=False)
```
all work from the `sagenb`. Only `show(sphere(), viewer='threejs', online=True)` works from the command line as well as the `jupyter` notebook.

One seeming disadvantage of the `threejs` viewer is that one cannot run Sage remotely and get graphics (3D) objects to display at all, from the command line or the notebooks. Apparently, `threejs` uses local display resources and I haven't found a work-around that will allow objects to be displayed. This is not a problem with the `jmol` viewer.

**Comment by strogdon** [comment]
Probably `local` resources is not the correct way to express it, but there seems to be a problem with how `webgl` works. On my local machine https://get.webgl.org/ works just fine. But when I log onto my machine remotely and open the same browser it fails, complaining that video drivers are old.

**Comment by kiwifb** [comment]
Since threejs seems to be replacing jmol in the near future I may package a version for gentoo. What is the current status of this particular problem?

**Comment by kiwifb** [comment]
Starting with 8.3.rc1 I am shipping an offline component for threejs. I will probably split it out during the 8.4 cycle. But it won't be named threejs but something like threejs-nbextension.

**Comment by strogdon** [comment]
The `show` commands in https://github.com/cschwan/sage-on-gentoo/issues/456#issuecomment-293930643 do now work. I'm unable to test the remote viewing presently due to limited bandwidth.

**Comment by strogdon** [comment]
Something must be missing in my Prefix. None of the `show` commands in https://github.com/cschwan/sage-on-gentoo/issues/456#issuecomment-293930643 work, not even in the `online` case. `viewer='jmol'` does display correctly. As far as I can determine the generated `html` file with paths looks correct. I am using the host-installed `firefox`.

**Comment by strogdon** [comment]
In inspecting the browser Console I see
```
Error: WebGL: Disallowing antialiased backbuffers due to blacklisting. three.min.js:152:233
Error: WebGL: Refused tthree.min.jso create native OpenGL context because of blacklisting. three.min.js:152:233
Error: WebGL: WebGL creation failed. three.min.js:152:233
Error: WebGL: Disallowing antialiased backbuffers due to blacklisting. three.min.js:152:258
Error: WebGL: Refused to create native OpenGL context because of blacklisting. three.min.js:152:258
Error: WebGL: WebGL creation failed. three.min.js:152:258
Error: WebGL: Disallowing antialiased backbuffers due to blacklisting. three.min.js:152:318
Error: WebGL: Refused to create native OpenGL context because of blacklisting. three.min.js:152:318
Error: WebGL: WebGL creatithree.min.json failed. three.min.js:152:318
TypeError: a is null
 three.min.js:112:223three.min.js
THREE.WebGLRenderer: Error creating WebGL context. three.min.js:153:110
```
I'm not sure how to disable `blacklisting`.

**Comment by kiwifb** [comment]
The interesting question here is, would it work with vanilla sage - if it was possible to install. I am wondering if there are mismatch between mesa component installed in the prefix and in the host. That may be a hard basket to fix, a problem way beyond just sage-on-gentoo to fix.

**Comment by strogdon** [comment]
Displaying `show(sphere(), viewer='threejs')` remotely from vanilla 8.3.rc1 on my gentoo box and the same command remotely from vanilla 8.2 on the debian prefix box gives:
```
THREE.WebGLRenderer 80 three.min.js:149:242
THREE.WebGLRenderer: Error creating WebGL context. three.min.js:153:110
rd() three.min.js:153
<anonymous>
```
There is no `blacklisting` issue but nothing is displayed. I have very little bandwidth here at home and that may be a problem. To compound things, the `show` command works correctly when run remotely under s-o-g 8.3.rc1 between two laptops on my home network. So, something is missing. Perhaps you can try displaying things remotely to see if you have any issues.

**Comment by strogdon** [comment]
The remote machine.

**Comment by kiwifb** [comment]
Hum... the remote machine is not doing the displaying so in a way the nvidia driver should be irrelevant as all the rendering is done on the local machine. Now there may need to be something installed on the remote machine for opengl to work properly. What driver do you have on the remote machine?

**Comment by strogdon** [comment]
On the remote machine, nvidia video card using nouveau driver. I don't think the driver is the complete issue since when my gentoo box is the remote machine I have the same response as in https://github.com/cschwan/sage-on-gentoo/issues/456#issuecomment-405441688. And that gentoo box has nvidia video with closed source nvidia drivers.

**Comment by kiwifb** [comment]
Are you still looking into this?

**Comment by strogdon** [comment]
This is old. As far as I can remember it may have been a corner case when accessing Prefix remotely. I no longer have that capability, at least until the Prefix machine in online again. I'm find with closing this. No one else has mentioned this.

**Comment by kiwifb** [comment]
OK, closing.
