### ISSUE TITLE
nauty new version with free license

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [cschwan/sage-on-gentoo#459]
see https://bugs.gentoo.org/show_bug.cgi?id=614702

**Comment by kiwifb** [comment]
Understood. Once we have an ebuild for a newer version of `nauty` than currently in tree or overlay we change the license. I don't believe it can be applied retro-actively on previous versions.

**Comment by kiwifb** [comment]
Acted upon in `nauty-2.6.7` ebuild.
