### ISSUE TITLE
Better download link for sci-mathematics/giac-1.2.3.25, is it available?

### ISSUE THREAD

**Issue by fusion809** [cschwan/sage-on-gentoo#460]
Hi,

I was just trying to install `sci-mathematics/sage` from this overlay and it fails at the `sci-mathematics/giac-1.2.3.25` ebuild and the reason it fails is because it can't seem to download it from http://www-fourier.ujf-grenoble.fr/~parisse/debian/dists/stable/main/source/giac_1.2.3-25.tar.gz. Does anyone have a better download link for this package? If anyone has a copy of this package locally it'd be great if they could upload it to dropbox or some other site so I can use it to build this package. 

Thanks for your time,
Brenton

**Comment by kiwifb** [comment]
OK the site is currently down, I will provide you with an alternate download link.

**Comment by fusion809** [comment]
OK. Thanks. I'm going to be napping soon so it'd be good to get my PC to compile the last few packages so when I awake SageMath is ready to be used.

**Comment by kiwifb** [comment]
http://sagetrac.lipn.univ-paris13.fr/sage/giac_1.2.3-25.tar.gz
