### ISSUE TITLE
Sage-7.6 needs keywording still

### ISSUE THREAD

**Issue by WPettersson** [cschwan/sage-on-gentoo#465]
Commit c7e9a1f8594d1e917c5033d7d8244508a441503a updated the `sage` symlink to point to the new `sage-7.6` but at the same time replaced the line `~sci-mathematics/sage-7.4` with `~sci-mathematics/sage-9999 **`

I'm guessing this was a typo.

**Comment by kiwifb** [comment]
Sorry about that. I usually remember to do the change but it looks like this time I forgot and no one noticed. When sage-x.y is released I copy `package.keywords/sage-9999` to `package.keywords/sage-x.y` and then I had to change `sage-9999 **` to `sage-x.y` in the copy. Sometimes I forget. I think that's the record in terms of how long it stayed incorrect.
