### ISSUE TITLE
can't emerge sage-7.6

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [cschwan/sage-on-gentoo#467]
https://gist.github.com/ec7a2faebd07034c05d0e50b21639511

I get `InternalError: Internal compiler error: 'cysignals/memory.pxi' not found`
but
```
locate cysignals/memory.pxi
/usr/lib64/python2.7/site-packages/cysignals/memory.pxi
/usr/lib64/python3.4/site-packages/cysignals/memory.pxi
/usr/lib64/python3.5/site-packages/cysignals/memory.pxi
```

**Comment by kiwifb** [comment]
version of cysignals and cython please. I think you may have to nudge cython up.

**Comment by Alessandro-Barbieri** [comment]
dev-python/cysignals-1.4.0::sage-on-gentoo
dev-python/cython-0.25.2::gentoo

**Comment by kiwifb** [comment]
You need cython from sage-on-gentoo. I will have to tweak the dependency. Is this an upgrade from 7.5 or 7.4?

**Comment by Alessandro-Barbieri** [comment]
No, it's not an upgrade, first time installing on this machine

**Comment by kiwifb** [comment]
OK, but somehow `cython` must have been installed before you started installing sage otherwise the sage-on-gentoo version should have been picked up (provided you use `package.keywords/sage-7.6` in `/etc/portage/package.accept_keywords`).

**Comment by Alessandro-Barbieri** [comment]
I had that symlink missing

**Comment by Alessandro-Barbieri** [comment]
Now I added it, but cython from the overlay is not pulled in by portage (it differ only by a -r version and portage thinks that the tree version satisfies the dependency)

**Comment by kiwifb** [comment]
Yes that's why I mentioned earlier that I should tweak the dependency.

**Comment by kiwifb** [comment]
If you sync the overlay it should pull the right cython now.
