### ISSUE TITLE
question about 99sage-doc-bin

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [cschwan/sage-on-gentoo#473]
Is `99sage-doc-bin` deprecated?
I'm working on the profile and I need to know if is needed or not.

**Comment by kiwifb** [comment]
It is not deprecated. It is a sane default for documentation on the "stable" branch. Sage documentation requires a lot of memory and not everyone has the capacity to build it. It was a mistake on my part to try to do away with it in 7.5.

On the "unstable" branch you have to build your own doc, it is too costly to provide some at each beta release (or even every snapshot on the vbraun branch of the overlay).

**Comment by Alessandro-Barbieri** [comment]
I was asking only because in https://github.com/cschwan/sage-on-gentoo/blob/master/README.rst line 98 is mentioned sage 6.8

**Comment by kiwifb** [comment]
I see, I should have future proofed that statement. Actually I may reword that now that it is the norm.

**Comment by kiwifb** [comment]
I have pushed a new version of the readme file if you want to comment on it.

**Comment by Alessandro-Barbieri** [comment]
It's fine.
