### ISSUE TITLE
Missing dependency in dev-tex/sage-latex

### ISSUE THREAD

**Issue by strogdon** [cschwan/sage-on-gentoo#479]
This is a build of `sage-9999` from scratch on a new laptop with useflags
```
sci-mathematics/sage debug doc-html doc-pdf testsuite -doc-bin-html -doc-bin-pdf latex sagenb
```
which fails with
```
! LaTeX Error: File `makecmds.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: 
! Emergency stop.
<read *> 
         
l.78 \RequirePackage
                    {ifpdf}^^M
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on sagetex.log.
 * pdflatex failed, trying texi2dvi
/usr/bin/texi2dvi: latex exited with bad status, quitting.
```
`makecmds.sty` is provided by `dev-texlive/texlive-latexextra-2016` which is pulled in by `app-text/texlive-2016[extra]`. I don't know whether `sage-latex` should depend on `texlive[extra]` or directly on `texlive-latexextra`. Just prior to the attempt to build `sage-latex` a bunch of `texlive/latex` stuff is installed but `app-text/texlive` has yet to be installed.

**Comment by kiwifb** [comment]
I will look into that.

**Comment by kiwifb** [comment]
Ok the only real dependencies in the ebuild are provided by the latex-package eclass. We can definitely improve on that.

**Comment by kiwifb** [comment]
Re-open if needed.
