### ISSUE TITLE
cpari2 does not build without USE=doc for pari

### ISSUE THREAD

**Issue by mekosmowski** [cschwan/sage-on-gentoo#484]
I had to manually add the USE flag of "doc" for pari in order to get cypari2 to build.  Neither version 1.0.0 nor 1.1.1 of cypari2 would build before I added this USE flag to pari.

Here is a link to the suggested failed build info: https://paste.pound-python.org/show/l4Xs0PasUl3dDwj8ByuO/

Here are emerge --info for the two packages after success: https://paste.pound-python.org/show/G85aVYNnQVGbG6ujfxxp/

I was unable to figure out why the cypari2 build failed from the emerge related information.  I read about using dev-python/pip to install cypari2 (I think from upstream); that also failed to install cypari2, but informed that the missing file was gphelp.  On a whim, I built pari with USE=doc, confirmed (with equery f) that gphelp now existed, and then cypari2 built without issue.

**Comment by kiwifb** [comment]
This is not a new requirement, but I probably forgot to transfer that particular use dependency when `cypari2` became the main way for sage to consume `pari`.

Note however, that if you had used the file `package.use/sage` from the overlay as noted on step 4 of the `README` on the landing page of the overlay, you would had the right useflags in the first place.

But I will make sure `cypari2` has the right useflag dependency as this is clearly an issue.

**Comment by mekosmowski** [comment]
I manually added the USE flags from copy and pasting the emerge message into /etc/portage/package.use .
