### ISSUE TITLE
sci-mathematics/sage-8.0 - QA Notice: Symbolic link /usr/share/jupyter/nbextensions/jsmol points to /usr/share/jsmol which does not exist.

### ISSUE THREAD

**Issue by devurandom** [cschwan/sage-on-gentoo#492]
After building sci-mathematics/sage-8.0, emerge prints following QA notice:
```
QA Notice: Symbolic link /usr/share/jupyter/nbextensions/jsmol points to /usr/share/jsmol which does not exist.
```

The setup / use-flags are the same as reported in #490.

**Comment by kiwifb** [comment]
You don't have `sage-jmol-bin` installed I guess. Hum... I guess that symlink doesn't technically belong to this ebuild. I may have trouble convincing upstream that it doesn't belong where they've put it either.

**Comment by strogdon** [comment]
@kiwifb 
Perhaps `sage-jmol-bin` should be installed by default even when `USE=-sagenb`. The `jupyter` notebook stuff is installed by default and there are some things that won't work without `jmol`.
```
sage: show(sphere())
/storage/strogdon/gentoo-rap/usr/lib64/python2.7/site-packages/sage/repl/rich_output/display_manager.py:590: RichReprWarning: Exception in _rich_repr_ while displaying object: Jmol failed to create file '/storage/strogdon/gentoo-rap/.sage/temp/blitzen/13208/dir_LPpLbv/preview.png', see '/storage/strogdon/gentoo-rap/.sage/temp/blitzen/13208/tmp_hmX_aV.txt' for details
  RichReprWarning,
\newcommand{\Bold}[1]{\mathbf{#1}}\verb|Graphics3d|\phantom{\verb!x!}\verb|Object|
```
which also fails from the `jupyter` notebook. The contents of the `.txt` file is
```
Error: Unable to access jarfile /storage/strogdon/gentoo-rap/usr/share/sage-jmol-bin/lib/JmolData.jar
```
all of which is technically a `Warning`. I suppose
```
sage: show(sphere(), viewer='threejs', online=True)
```
will work, although I'm unable to test it properly.

**Comment by kiwifb** [comment]
Yes, I was thinking of making it a dependency to solve the problem. You are just giving me more arguments for it. I just wish `jmol` would go completely away.
Do you have link problems on prefix for that? There are more links that should just be relative, and of course I have learned a new trick that I am eager to use :)

**Comment by strogdon** [comment]
After removing `sage-jmol-bin` and `sage-notebook` the only `QA` I have is the one reported above except relative to prefix
```
QA Notice: Symbolic link /storage/strogdon/gentoo-rap/usr/share/jupyter/nbextensions/jsmol points to /storage/strogdon/gentoo-rap/usr/share/jsmol which does not exist.
```

**Comment by kiwifb** [comment]
Ok, ready for testing. I am just worried that runtime dependency may not be enough.

**Comment by strogdon** [comment]
I have no `QA Notice` and `show(sphere())` works from the sage prompt as well as from the `sage -n jupyter`, jupyter notebook. I usually build `sage-9999` so I could have some needed runtime dependencies already installed, but I'm not aware of any. Have a nice time away!

**Comment by kiwifb** [comment]
Re-open if you find that the fix is not sufficient.
