### ISSUE TITLE
ebuild built html-docs do not display inline math formulas

### ISSUE THREAD

**Issue by strogdon** [cschwan/sage-on-gentoo#496]
I discovered this while investigating the same issue on vanilla Sage. It may not be worth resolving, but to see the issue load the file
```
/usr/share/doc/sage/html/en/reference/plotting/sage/plot/plot.html
```
in a browser and search for `plotjoined is false`. There should be `\((0,1)\)` instead of its mathjax equivalent. I'm not sure how to resolve it. Doing 
```
--- a/sci-mathematics/sage/sage-9999.ebuild
+++ b/sci-mathematics/sage/sage-9999.ebuild
@@ -405,6 +405,7 @@ python_compile() {
 
        if ! python_is_python3; then
                if use doc-html ; then
+                       export SAGE_DOC_MATHJAX=True
                        "${PYTHON}" sage_setup/docbuild/__main__.py --no-pdf-links all html || die "failed to produce html doc"
                fi
                if use doc-pdf ; then
```
did not resolve things. This is supposedly taken care of in `src/doc/common/conf.py`, but the mathjax stuff is not being found. Looking a little more closely it is probably because `SAGE_SHARE` is `/usr/share/sage` instead of `/usr/share`.

**Comment by kiwifb** [comment]
I saw your posts on sage-devel. The location bit should be taken care of in `sage/env.py` but there may be a corner case at build time.

**Comment by kiwifb** [comment]
I think a small adjustment is needed and I think I know where.

**Comment by kiwifb** [comment]
Can you try the following
```
diff --git a/doc/common/conf.py b/doc/common/conf.py
index c4dfbf5..897d41a 100644
--- a/doc/common/conf.py
+++ b/doc/common/conf.py
@@ -219,7 +219,7 @@ if (os.environ.get('SAGE_DOC_MATHJAX', 'no') != 'no'
     from sage.misc.latex_macros import sage_mathjax_macros
     html_theme_options['mathjax_macros'] = sage_mathjax_macros()
 
-    mathjax_relative = 'mathjax'
+    mathjax_relative = '../mathjax'
 
     # It would be really nice if sphinx would copy the entire mathjax directory,
     # (so we could have a _static/mathjax directory), rather than the contents of the directory
```

**Comment by strogdon** [comment]
Yes this works.

**Comment by kiwifb** [comment]
OK, I'll add this everywhere ASAP.

**Comment by kiwifb** [comment]
Fixing only sage-9999 at this stage. `conf.py` had a recent makeover since 8.1 and the patch for 9999 won't apply to 8.1. I'll have to check if 8.1 has the same issue.

**Comment by kiwifb** [comment]
8.1 uses a completely different path relative to sagenb. Probably safe.
