### ISSUE TITLE
sci-mathematics/lcalc-1.23-r7 fetch failed

### ISSUE THREAD

**Issue by devurandom** [cschwan/sage-on-gentoo#502]
It appears that oto.math.uwaterloo.ca is no more: Connection timed out, when portage tries to download L-1.23.tar.gz.

**Comment by kiwifb** [comment]
OK I will change the file SRC_URI and point it to a sage mirror ASAP. Thanks for the ping.

**Comment by kiwifb** [comment]
Fixed, sync and report back please :)

**Comment by devurandom** [comment]
Fixed, thanks!
