### ISSUE TITLE
sage-8.1-r2, Cython, and keywords

### ISSUE THREAD

**Issue by WGH-** [cschwan/sage-on-gentoo#503]
Currently stable Cython version in mainline Gentoo portage tree is 0.25.2, which is inadequate for Sage because (at very least) the latter has `from Cython.Build.Dependencies import default_create_extension`, which appeared only somewhere in 0.26 (cython/cython@9797efe065d50638b0cd19219e6b1f3f5edaddab).

However, sage ebuilds only has an upper bound on Cython version (`<=dev-python/cython-0.28[${PYTHON_USEDEP}]`), but no lower bound, which means old Cython will not lead to conflicts/upgrades, but to compile time failure.

This very overlay has an appropriate version of Cython included, but it's keyworded unstable. `package.keywords/sage-8.1` file has `~dev-python/cython-0.26` line, but there's no such ebuild, only newer versions. Presumably, Cython ebuild was bumped with older versions removed, but keyword file was forgotten about.

So I believe 1) sage ebuild itself should be changed to include Cython version lower bound as well, 2) corresponding keyword file line should be changed to `~dev-python/cython-0.27.3-r2`.

**Comment by kiwifb** [comment]
Thanks for the report, I will fix that as soon as possible. The main sage-on-gentoo dev machine is under wrap for a move so there may be a 24 hours delay.

**Comment by kiwifb** [comment]
Should be sane now.
