### ISSUE TITLE
ecl sources not found

### ISSUE THREAD

**Issue by jfjhh** [cschwan/sage-on-gentoo#505]
The ebuild for `dev-lisp/ecls` needs its SRC_URI changed from `https://common-lisp.net/project/ecl/files/release/${PV}/${MY_P}.tgz` to `https://common-lisp.net/project/ecl/static/files/release/${MY_P}.tgz`, as the sources to not exist at the previous URL.

**Comment by kiwifb** [comment]
Thank you for the report. I will push the fix shortly.

**Comment by kiwifb** [comment]
Fix in overlay feel free to re-open if I made a mistake.
