### ISSUE TITLE
dev-gap/GAPDoc-1.5.1 sources not found

### ISSUE THREAD

**Issue by jfjhh** [cschwan/sage-on-gentoo#506]
The `SRC_URI` that becomes `http://www.gap-system.org/pub/gap/gap4/tar.bz2/packages/GAPDoc-1.5.1.tar.bz2` in the GAPDoc ebuild does not exist and has been replaced by the `1.6.1` version at that address. A copy of the `1.5.1` sources exists on the Internet Archive [here](https://web.archive.org/web/20170711235042/http://www.gap-system.org/pub/gap/gap4/tar.bz2/packages/GAPDoc-1.5.1.tar.bz2).

**Comment by kiwifb** [comment]
Hum that's pretty annoying. I will probably mirror it, but that may say something bad about other gap packages.

**Comment by kiwifb** [comment]
I may have to think of some longer term strategies if gap packages are not preserved properly outside of the gap distribution tarballs. 

Again feel free to re-open if I made a mistake.
