### ISSUE TITLE
sci-mathematics/sage depends: pycrypto -> pycryptodome

### ISSUE THREAD

**Issue by WGH-** [cschwan/sage-on-gentoo#510]
As per https://bugs.gentoo.org/611568, 
> dev-python/pycryptodome is a fork of discontinued dev-python/pycrypto. Since the latter is dead since 2014, it'd be reasonable to replace its uses with the former.

Dead pycrypto is known to contain unfixed security bugs (dlitz/pycrypto#176), so it would make sense to switch to the maintained fork.

**Comment by kiwifb** [comment]
I am not even sure it is a real dependency anymore. I'll have to check.

**Comment by kiwifb** [comment]
I am removing this dependency, I'll see what other people are doing but removing doesn't affect sage or sagenb in the slightest.
