### ISSUE TITLE
sci-libs/linbox-1.5.2: Fix sci-mathematics/sage compilation issue when using sys-devel/gcc-8.1

### ISSUE THREAD

**Issue by devurandom** [cschwan/sage-on-gentoo#511]
GCC 8.1 complains when compiling sci-mathematics/sage-8.2-r1: `linbox/matrix/densematrix/blas-transposed-matrix.h:74:8: error: too many template-parameter-lists`. linbox-team/linbox@56be8673613fff87fb2329f71bceb0c793c00b82 fixes this.

See-Also: https://github.com/linbox-team/linbox/issues/116
See-Also: https://trac.sagemath.org/ticket/25353

**Comment by kiwifb** [comment]
Thanks for the heads up. I need to start worrying about the patches for gcc-8 I have seen go past.

**Comment by kiwifb** [comment]
Fixed by 59a048a9ec1ccbf36db0d7e76643fbc7ce5109bd
