### ISSUE TITLE
Recent Twisted versions

### ISSUE THREAD

**Issue by gagern** [cschwan/sage-on-gentoo#513]
**Summary:** Please support dev-python/twisted as a dependency for sci-mathematics/sage-notebook.

sci-mathematics/sage-notebook only works with [modularized dependencies for twisted-{core,mail,web}](https://github.com/cschwan/sage-on-gentoo/blob/00f60f0664b5a47df817ea020f7f8966af8848b2/sci-mathematics/sage-notebook/sage-notebook-1.0.3-r1.ebuild#L26-L28). Apparently the main portage tree switched from these modularized ebuilds to a single dev-python/twisted ebuild starting with twisted 16, with 18 being the current major version. So being restricted to twisted 15 feels a bit backwards. [Gentoo bug 605084](https://bugs.gentoo.org/605084) tracks the effort of migrating from split ebuilds to monolithic one, clearly considering the former deprecated. The [SageNB metadata](https://github.com/sagemath/sagenb/blob/9a99b4e361821eca4c6157a7e7fdaf465356e0c7/setup.py#L33) requests `twisted>=11.0.0` with no further restrictions documented anywhere I could find them.

I would *assume* that you can use a dependency disjunction like the following (inspired by [www-servers/tornado-5.0.2](https://github.com/gentoo/gentoo/blob/3c554d94e471d473a8c42f6edcfc2e6b0eb8c7bd/www-servers/tornado/tornado-5.0.2.ebuild#L23-L28)). But I haven't gotten round to actually test this (as in giving various notebook setups a reasonably thorough test run), and likely won't in the near future.

```diff
 DEPEND=">=dev-python/pexpect-4.0.1-r1[${PYTHON_USEDEP}]
-	>=dev-python/twisted-core-14.0.0[${PYTHON_USEDEP}]
-	>=dev-python/twisted-mail-14.0.0[${PYTHON_USEDEP}]
-	>=dev-python/twisted-web-14.0.0[${PYTHON_USEDEP}]
+	|| (	>=dev-python/twisted-14.0.0[${PYTHON_USEDEP}]
+		(	>=dev-python/twisted-core-14.0.0[${PYTHON_USEDEP}]
+			>=dev-python/twisted-mail-14.0.0[${PYTHON_USEDEP}]
+			>=dev-python/twisted-web-14.0.0[${PYTHON_USEDEP}]
+		)
+	)
 	!dev-python/twisted-web2
```

**Comment by kiwifb** [comment]
Unfortunately I will have to drag sageNB for a little while longer. Your suggested approach is totally reasonable and I will just adopt it.

**Comment by kiwifb** [comment]
Hum, that looks like it is working but considering 16 is stable I may just bump the dependency to that.

**Comment by gagern** [comment]
Hard depending on the monolithic ebuild might cause issues for co-existence with other packages that haven't migrated yet, but personally I have no objections.

**Comment by kiwifb** [comment]
I hadn't considered that. In that case, what is in now, is good enough.
