### ISSUE TITLE
QA Notice: missing threejs symlink

### ISSUE THREAD

**Issue by strogdon** [cschwan/sage-on-gentoo#515]
@kiwifb 
Do you see the following:
```
>>> Installing (1 of 1) sci-mathematics/sage-9999::sage-on-gentoo
 * QA Notice: Symbolic link /usr/share/jupyter/nbextensions/threejs points to /usr/sage/threejs which does not exist.
```
I don't remember seeing this on the release-candidates.

**Comment by kiwifb** [comment]
I'll have a look but this should be a relative symlink. The only thing I can think of is that one is merged before the other and it triggers the QA warning. That will go away once I decouple threejs but that's a pain.

**Comment by strogdon** [comment]
Here it appears that the `threejs` is installed under
```
/usr/share/sage/threejs
```
So maybe
```
dosym ../../../sage/threejs /usr/share/jupyter/nbextensions/threejs
```
should be
```
dosym ../../../sage/threejs /usr/share/sage/threejs
```
Or perhaps the installation folder is not correct, unless I'm missing something.

**Comment by kiwifb** [comment]
Curious that it wasn't picked up in 9999, I think there is one level `..` too many now that I woken up and read the initial report properly.

**Comment by strogdon** [comment]
What I said about symlinks is of course not correct. Your are correct there is one too many `..`.

**Comment by kiwifb** [comment]
There is another bit I have missed for the 8.3 release so I will have a revbump.

**Comment by kiwifb** [comment]
OK, there was also a missing link in case `doc-html-bin` was used instead of `doc-html`. Should be fixed now.

**Comment by strogdon** [comment]
This look good.
