### ISSUE TITLE
Jupyter notebook in Prefix

### ISSUE THREAD

**Issue by strogdon** [cschwan/sage-on-gentoo#519]
My prefix with `8.4.beta2` installed is on a remote machine and I'm viewing things locally. After 
`sage --notebook=jupyter` and loading a `.ipynb` notebook I see repeatedly the following:
```
[I 16:45:18.595 NotebookApp] Adapting to protocol v5.1 for kernel e0790615-24a7-4d4f-b7d6-4cb67ee281e8
[E 16:45:18.596 NotebookApp] Uncaught exception GET /api/kernels/e0790615-24a7-4d4f-b7d6-4cb67ee281e8/channels?session_id=79BC2588CEF344D28FD3CBC5905ADCFB (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/api/kernels/e0790615-24a7-4d4f-b7d6-4cb67ee281e8/channels?session_id=79BC2588CEF344D28FD3CBC5905ADCFB', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/storage/strogdon/gentoo-rap/usr/lib64/python2.7/site-packages/tornado/websocket.py", line 546, in _run_callback
        result = callback(*args, **kwargs)
      File "/storage/strogdon/gentoo-rap/usr/lib64/python2.7/site-packages/notebook/services/kernels/handlers.py", line 258, in open
        super(ZMQChannelsHandler, self).open()
      File "/storage/strogdon/gentoo-rap/usr/lib64/python2.7/site-packages/notebook/base/zmqhandlers.py", line 168, in open
        self.send_ping, self.ping_interval, io_loop=loop,
    TypeError: __init__() got an unexpected keyword argument 'io_loop'
```
Installed `eix -I tornado && eix -I pyzmq && eix -I dev-python/notebook`
```
[I] www-servers/tornado
     Available versions:  4.4.2-r1 4.5.1 4.5.3 [m]5.0.2 5.1 {doc examples test PYTHON_TARGETS="python2_7 python3_4 python3_5 python3_6 python3_7"}
     Installed versions:  5.1(11:50:26 AM 08/24/2018)(-doc -examples -test PYTHON_TARGETS="python2_7 python3_6 -python3_4 -python3_5 -python3_7")
     Homepage:            http://www.tornadoweb.org/
     Description:         Python web framework and asynchronous networking library

[I] dev-python/pyzmq
     Available versions:  16.0.2 17.1.0 {doc test PYTHON_TARGETS="python2_7 python3_4 python3_5 python3_6"}
     Installed versions:  17.1.0(11:47:53 AM 08/24/2018)(-doc -test PYTHON_TARGETS="python2_7 python3_6 -python3_4 -python3_5")
     Homepage:            http://www.zeromq.org/bindings:python https://pypi.org/project/pyzmq/
     Description:         Lightweight and super-fast messaging library built on top of the ZeroMQ library

[I] dev-python/notebook
     Available versions:  4.0.6[1] 5.0.0 5.2.1 **9999[1] {doc test PYTHON_TARGETS="python2_7 python3_4 python3_5 python3_6"}
     Installed versions:  5.2.1(12:22:29 PM 08/24/2018)(-doc -test PYTHON_TARGETS="python2_7 python3_6 -python3_4 -python3_5")
     Homepage:            http://jupyter.org
     Description:         Jupyter Interactive Notebook

[1] "science" /storage/strogdon/gentoo-rap/var/lib/layman/science
```
Oddly here it would appear that `pyzmq-17.1.0` requires `>=tornado-5.0.2` where vanilla has `pyzmq-17.1.0` with `tornado-4.5.2`. I have had issues with `tornado-5.0.2` in the past. The same issue may be on gentoo, but unable to test at the moment.

**Comment by kiwifb** [comment]
Yes that looks suspiciously like #508 there may be a bit more to it.

**Comment by kiwifb** [comment]
I haven't looked at those dependencies yet so someone may have been overeager. I have just look at the changes for notebook 5.5.0 (there is a tag for 5.6.0 but it says 5.5.0 is the latest release) and there is that bit:
Get tests running with tornado 5 (#3398).
It also require pyzmq-17+ could you run the notebook testsuite to see if the problem show up in that?

**Comment by strogdon** [comment]
I'm assuming you want the tests for `notebook-5.2.1`. Here the tests will not run from the ebuild
```
nosetests: error: Error reading config file 'setup.cfg': no such option 'warningfilters'
```
`warningfilters` is in `setup.cfg`? The same issue with `notebook-5.0.0`.

From the command line `nosetests --verbosity=3 notebook` gives
```
======================================================================
ERROR: test_connections (notebook.services.kernels.tests.test_kernels_api.KernelAPITest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/storage/strogdon/gentoo-rap/usr/lib64/python2.7/site-packages/notebook/services/kernels/tests/test_kernels_api.py", line 172, in test_connections
    ws = self.kern_api.websocket(kid)
  File "/storage/strogdon/gentoo-rap/usr/lib64/python2.7/site-packages/notebook/services/kernels/tests/test_kernels_api.py", line 60, in websocket
    f = websocket_connect(req, io_loop=loop)
TypeError: websocket_connect() got an unexpected keyword argument 'io_loop'
```

**Comment by strogdon** [comment]
On gentoo with `sage-8.3` with `notebook-5.2.1` no `notebook` test failures. If course `tornado-4.5.3` and `pyzmp-16.0.2` are installed.

**Comment by strogdon** [comment]
I think we have to somehow force `<tornado-5`.

**Comment by kiwifb** [comment]
I have just upgraded pyzmq to 17.1.0 without having to upgrade tornado on my gentoo box. The dependency on tornado-5+ is only enforced for running the tests.

**Comment by kiwifb** [comment]
And that means tornardo-5.0.2+ is pulled when pyzmq has the "test" useflag on.

**Comment by kiwifb** [comment]
It is probably because on prefix you are ~arch by default. The only way to avoid pulling it, is hard dependencies or masking. I could put `<www-servers/tornado-5.0.0` in the sage ebuild I guess. Someone on ~arch will probably complain if I go that way.

**Comment by strogdon** [comment]
Leave it. I now know what to do.

**Comment by strogdon** [comment]
I do think this can be closed. It's only a potential ~arch issue. And those situations are up to the user. But we know where to look if tornado-5 becomes stable.
