### ISSUE TITLE
Errors building 8.4.beta3

### ISSUE THREAD

**Issue by strogdon** [cschwan/sage-on-gentoo#520]
On gentoo:
```
sage-9999/work/sage-9999/src-python2_7/build/lib/sage/symbolic/ring.so
x86_64-pc-linux-gnu-g++ -shared -Wl,-O1 -Wl,--as-needed -march=native -O2 -pipe /var/tmp/portage/sci-mathematics/sage-9999/work/sage-9999/src-python2_7/build/temp.linux-x86_64-2.7/var/tmp/portage/sci-mathematics/sage-9999/work/sage-9999/src-python2_7/build/cythonized/sage/symbolic/expression.o -L/usr/lib -L/usr/lib64 -lgmp -lpynac_python2_7 -lstdc++ -lpython2.7 -o /var/tmp/portage/sci-mathematics/sage-9999/work/sage-9999/src-python2_7/build/lib/sage/symbolic/expression.so
Time to execute 488 commands: 1018.88 seconds.
Total time spent compiling C/C++ extensions: 1018.94 seconds.
Setting permissions of DOT_SAGE directory so only you can read and write it.
Traceback (most recent call last):
  File "sage_setup/docbuild/__main__.py", line 1, in <module>
    from sage_setup.docbuild import main
  File "/var/tmp/portage/sci-mathematics/sage-9999/work/sage-9999/src-python2_7/sage_setup/docbuild/__init__.py", line 54, in <module>
    import sage.all
  File "/var/tmp/portage/sci-mathematics/sage-9999/work/sage-9999/src-python2_7/build/lib/sage/all.py", line 98, in <module>
    from sage.symbolic.all   import *
...
cysignals.signals.SignalError: Segmentation fault
```
I also had build errors in Prefix but the build order was different as well as the terminating failure.
Build order for emerge -C sage && emerge -1 sage.
Gentoo:
pari-2.11.0
sage-9999 (which fails)

Prefix:
pari-2.11.0
eclib-20180815
giac-1.4.9.69-r1
lcalc-1.23-r7
cypari2-1.2.1-r1 (cypari2 failed to build. Something to do with incorrect pari-gmp libs)

In Prefix manually upgraded to `cysignals-1.7.2-r1` and then `cypari2-1.2.1-r1` and then `sage-9999`. I'm not sure the order was necessary but sage did build in Prefix. I suspect something similar can be done on Gentoo.

**Comment by kiwifb** [comment]
I tried to have this handled more or less automatically by bumping version of anything that needed rebuilding with soname bump in pari. I haven't experienced that failure though.

But the pari upgrade means that both cypari and cysignals have to be rebuilt and all the pari dependencies too.

**Comment by strogdon** [comment]
On Gentoo manually upgraded to `cyignals-1.7.2-r1` then `cypari2-1.2.1-r1` which required `emerge @preserved-rebuild`. And now `sage-9999` (sage.4.beta3) builds. This is strange.

**Comment by kiwifb** [comment]
sub-slots are supposed to handle this but if something wasn't at the right version to begin with there could have been trouble. I should make sure pari dependencies have subslots and ntl ones too.

**Comment by strogdon** [comment]
I don't know about Gentoo (the build order there was very strange)  but in Prefix it appeared that packages were being built in the correct order. Could parallel build have been the show stopper? In the build of `cypari2` could there have been some linking to `libpari-gmp` before the new `pari` had been installed? But usually preserved-libs would handle this, right?

**Comment by kiwifb** [comment]
If by parallel build you mean, parallel build of packages (sage style), rather than parallel build inside a single package, then yes it is possible that portage did something wrong to the build order and then it is a bug. And again yes preserved-libs should have kicked in.

**Comment by kiwifb** [comment]
I think everything I can do for this, is done. So I will close this for now.
