### ISSUE TITLE
cvxopt installs unexpected paths

### ISSUE THREAD

**Issue by strogdon** [cschwan/sage-on-gentoo#524]
Installing `cvxopt-1.1.9` I see
```
 * The ebuild is installing to one or more unexpected paths:
 * 
 *   /usr/cvxopt
 * 
 * Please fix the ebuild to use correct FHS/Gentoo policy paths.
```
and sure enough I have an empty `/usr/cvxopt` folder on the live system. It's not a big deal but I don't see exactly where the source of that install is?

**Comment by kiwifb** [comment]
Hum I see the main tree has copied my ebuild now, so they would have the exact same problem. This is a weird one. Investigating.

**Comment by kiwifb** [comment]
That's interesting because I don't have it right now. But I can see the ebuild creating it now. So I think it reflects a change in distutils/setuptools since last time I installed (2018-08-28). It is done during install_data which is a big clue and I think I can see stuff but why now and what is wrong with that setting...

**Comment by strogdon** [comment]
I installed on `2018-8-25` on Gentoo and on `2018-08-26` in Prefix and the folder appears on both systems.

**Comment by kiwifb** [comment]
1.2.1 now in the overlay and doesn't have the problem. 1.1.9 still has the problem in the main tree though. Testing with sage now.

**Comment by kiwifb** [comment]
1.2.1 doesn't break doctests. All clear.

**Comment by slel** [comment]
Would it be easy to fix https://trac.sagemath.org/ticket/22380
along the same lines?

**Comment by kiwifb** [comment]
The problem in sage is to package suitesparse. I totally benefit from the fact that it is already packaged and up to date enough in Gentoo. Note that I am already copied on that ticket, kiwifb and fbissey are the same person.
