### ISSUE TITLE
Emerge error

### ISSUE THREAD

**Issue by dhalsimax** [cschwan/sage-on-gentoo#527]
Hi, command:
>emerge sage 
reports:
* ERROR: sci-mathematics/sage-8.4::sage-on-gentoo failed (prepare phase):
 *   python_export called without a python implementation and EPYTHON is unset

**Comment by kiwifb** [comment]
Fixed in overlay. Sync and try again. I have done some backporting from sage-9999 and I forgot a bit of cleaning in the process. My apologies.

**Comment by kiwifb** [comment]
Just found and fixed another broken bit. Hope it's the last one.

**Comment by dhalsimax** [comment]
Ok works, thanks.
