### ISSUE TITLE
New gap script needs to be eprefixied to locate /bin/env in Prefix

### ISSUE THREAD

**Issue by strogdon** [cschwan/sage-on-gentoo#531]
In Prefix:
```
$ gap
bash: /storage/strogdon/gentoo-rap/usr/bin/gap: /bin/env: bad interpreter: No such file or directory
```
My host does not know about `/bin/env`.

**Comment by kiwifb** [comment]
That's concerning. Do you have `/usr/bin/env`? There is a limit to the length of that first line, eprefixing it could be dangerous, there must be a better way.

**Comment by strogdon** [comment]
Yes, `/usr/bin/env` is on the host. But `/usr/bin/env`, I guess, may not exit on some hosts?

**Comment by kiwifb** [comment]
I don't know for sure. I seem to remember prefix does something about some `#!` does it just eprefix them?

**Comment by kiwifb** [comment]
ubuntu has `/usr/bin/env` so probably debian too. Gentoo has both `/bin/env` and `/usr/bin/env` (symlink to the first). redhat6 has `/bin/env` but not the other. redhat7:  `/bin` is a link to `/usr/bin`. SLES11 has `/usr/bin/env` but not the other.
I'll say it is unsafe to use.

**Comment by strogdon** [comment]
Is the `/bin/env` necessary? Could one just have `EPREFIX/bin/bash`? But then again this assumes a location for `bash`.

**Comment by kiwifb** [comment]
Then there is little amusing thing to try. That create its own problems at install but it may be interesting to try. In the latest versions of the ebuild I put the real `gap` executable in `usr/share/gap/bin/${GAParch}`, as it happens most of the script is to get `gap` to find its stuff in `GAPROOT`. But without the definition for `GAPROOT` the `gap` executable looks at folders above it in order (I straced it at the beginning of development). Making `usr/bin/gap` a link to `../share/gap/bin/${GAParch}/gap` seem to works. 

I'll have to doctest sage with it.

The danger with `EPREFIX/bin/bash` is that if your prefix is too long the `#!` will break. I think the limit is ~130 characters. Hum... prefix seems to naturally eprefix standard `!#/bin/bash` so may be there are work arounds for those limitations in prefix.

**Comment by strogdon** [comment]
Changing to a  symlink `gap` starts but
```
sage -t --long ~/usr/lib/python2.7/site-packages/sage/geometry/polyhedron/library.py
```
fails for a multitude of reasons, mainly `cannot import name libgap`.

**Comment by kiwifb** [comment]
I forgot, sage cannot work without a `GAP_ROOT` variable of some kind being defined. Thinking cap on.

**Comment by kiwifb** [comment]
If I eliminate `GAP_ROOT` from the script (and I have all reasons to do so really even if I keep it as a script to get the `-m64m`) I have to give a definition in `sage/env.py`. I may go for that since it is a much better standard location than it was before.

**Comment by kiwifb** [comment]
I am testing stuff. That's the kind of issue that makes me sit down for a minute and re-think a few of the things I have been doing, and sometimes insisting on doing, for a little while. I think the end result will be better overall.

**Comment by kiwifb** [comment]
OK it should all be in order now. You need to rebuild sage and it should pull the new revision of gap with it.

**Comment by strogdon** [comment]
Yes, things are now good here.
