### ISSUE TITLE
update requires dev-lisp/ecls-16.1.3-r100?

### ISSUE THREAD

**Issue by strogdon** [cschwan/sage-on-gentoo#534]
Updating a Gentoo box with s-o-g 8.6 installed. The update requires  the subject `ecls`
```
These are the packages that would be merged, in order:

Calculating dependencies... done!
[ebuild  r  U ~] dev-lisp/ecls-16.1.3-r100 [16.1.2-r1]
[ebuild     U  ] dev-libs/expat-2.2.6 [2.2.5]
[ebuild     U  ] net-misc/curl-7.64.0 
...
```
Is this safe? Is it possible that `>=dev-lisp/ecls-16.0.0::sage-on-gentoo` in `package.keywords/sage-8.6` is overriding `~dev-lisp/ecls-16.1.2` in the ebuild?

**Comment by strogdon** [comment]
sage was installed with `emerge --oneshot` so perhaps that's why the newer `ecl` is being pulled in.

**Comment by kiwifb** [comment]
Not safe yet. sage does hard depend on 16.1.2 - We may be able to move with sage 8.7 the tiket should have positive review.

**Comment by strogdon** [comment]
So is it because I did a `emerge --oneshot` in installing sage that now the subject `ecls` is being pulled in. Or do I just need to mask it (which is what I have done).

**Comment by kiwifb** [comment]
Honestly I am not sure. oneshot doesn't prevent portage to look at dependencies of the stuff in your list of software. It may have fallen in a hole in the dependency graph. What did trigger the ecls rebuild?

**Comment by strogdon** [comment]
I'm not sure what triggered it.
```
equery d ecls
 * These packages depend on ecls:
sci-mathematics/maxima-5.41.0-r3 (ecls ? dev-lisp/ecls)
sci-mathematics/sage-8.6 (~dev-lisp/ecls-16.1.2)
virtual/commonlisp-1 (dev-lisp/ecls)
```
so I don't think it should have been pulled in. I stopped the build when I noticed the newer `ecls` was being installed. `ecls` was in my world file. I removed it but that didn't affect which `ecls` was built. It's now masked so I'm good.

**Comment by strogdon** [comment]
closing. this must be something on my end?

**Comment by kiwifb** [comment]
Not sure really. The "r" tag can mean that something is causing a rebuild but at the start like here it is more likely that it the cause of re-builds. Usually the rebuild is to do with subslots. So a sage rebuild may not have been triggered because it is the same subslot. If it had been triggered then sage reverse dependency would have been taken into account. I am wondering about the `virtual/commonlisp` and whether that was the cause.

**Comment by strogdon** [comment]
This fixed things here
```
#>=dev-lisp/ecls-16.0.0::sage-on-gentoo
~dev-lisp/ecls-16.1.2::sage-on-gentoo
```
in `sage-on-gentoo/package.keywords/sage-8.6`. But this change is not needed in my Prefix (sage-9999 installed). Strange? I removed the `virtual/commonlisp` - no change.

**Comment by kiwifb** [comment]
That wouldn't help people on `~arch` and they haven't complained with that particular problem (at least it hasn't reached me). And of course your prefix is basically `~arch`. I'll have a closer later when I am properly back from my conference.
