### ISSUE TITLE
giac-1.5.0.47 and igraph-0.7.1-r2 fail to build with openblas-0.3.5 [threads]

### ISSUE THREAD

**Issue by strogdon** [cschwan/sage-on-gentoo#538]
This may be prefix related. Without the threads useflag there is no issue. The failure is
```
/storage/strogdon/gentoo-rap/usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lopenblas_openmp
```
and the linking failure is easiest to see from the giac build
```
libtool: link: x86_64-pc-linux-gnu-g++  -fPIC -DPIC -shared -nostdlib /storage/strogdon/gentoo-rap/usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/../../../../lib64/crti.o /storage/strogdon/gentoo-rap/usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/crtbeginS.o  .libs/input_lexer.o .libs/sym2poly.o .libs/gausspol.o .libs/threaded.o .libs/moyal.o .libs/maple.o .libs/ti89.o .libs/mathml.o .libs/misc.o .libs/permu.o .libs/quater.o .libs/desolve.o .libs/input_parser.o .libs/symbolic.o .libs/index.o .libs/modpoly.o .libs/modfactor.o .libs/ezgcd.o .libs/derive.o .libs/solve.o .libs/intg.o .libs/intgab.o .libs/risch.o .libs/lin.o .libs/series.o .libs/subst.o .libs/vecteur.o .libs/sparse.o .libs/csturm.o .libs/tex.o .libs/global.o .libs/ifactor.o .libs/alg_ext.o .libs/gauss.o .libs/isom.o .libs/plot.o .libs/plot3d.o .libs/rpn.o .libs/prog.o .libs/pari.o .libs/cocoa.o .libs/unary.o .libs/usual.o .libs/identificateur.o .libs/gen.o .libs/tinymt32.o .libs/first.o .libs/TmpLESystemSolver.o .libs/TmpFGLM.o .libs/help.o .libs/lpsolve.o .libs/optimization.o .libs/signalprocessing.o .libs/graphe.o .libs/graphtheory.o .libs/nautywrapper.o   -Wl,-rpath -Wl,/storage/strogdon/gentoo-rap/usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/../../../../lib64 -Wl,-rpath -Wl,/storage/strogdon/gentoo-rap/usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/../../../../lib64 -Wl,--as-needed -lntl -lpari /storage/strogdon/gentoo-rap/usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/../../../../lib64/libgsl.so -lopenblas_openmp -lreflapack -lpthread -lcurl /storage/strogdon/gentoo-rap/usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/../../../../lib64/libglpk.so -lz /storage/strogdon/gentoo-rap/usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/../../../../lib64/libcolamd.so /storage/strogdon/gentoo-rap/usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/../../../../lib64/libamd.so -ldl /storage/strogdon/gentoo-rap/usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/../../../../lib64/libecm.so -lrt /storage/strogdon/gentoo-rap/usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/../../../../lib64/libmpfi.so -lmpfr -lgmp -L/storage/strogdon/gentoo-rap/usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0 -L/storage/strogdon/gentoo-rap/usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/../../../../lib64 -L/storage/strogdon/gentoo-rap/lib/../lib64 -L/storage/strogdon/gentoo-rap/usr/lib/../lib64 -L/storage/strogdon/gentoo-rap/usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/../../../../x86_64-pc-linux-gnu/lib -L/storage/strogdon/gentoo-rap/usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/../../.. -L/storage/strogdon/gentoo-rap/lib -L/storage/strogdon/gentoo-rap/usr/lib -lstdc++ -lm -lc -lgcc_s /storage/strogdon/gentoo-rap/usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/crtendS.o /storage/strogdon/gentoo-rap/usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/../../../../lib64/crtn.o  -march=native -O0 -g -ggdb -Wl,-O1   -Wl,-soname -Wl,libgiac.so.0 -o .libs/libgiac.so.0.0.0
```
The libs are installed
```
ls -al ~/usr/lib/libopenblas_openmp*
lrwxrwxrwx 1 strogdon math       41 Mar 29 14:20 /storage/strogdon/gentoo-rap/usr/lib/libopenblas_openmp.so.0 -> libopenblas_openmp_sandybridgep-r0.3.5.so
```
Perhaps the `-L ...` is missing in locating `libopenblas_openmp`?

**Comment by strogdon** [comment]
```
eix -I openblas
[I] sci-libs/openblas
     Available versions:  0.2.14-r1[2] 0.2.15-r1[2] 0.2.19-r1[2] 0.2.20[2] 0.3.5[1] **9999[2] {dynamic int64 openmp static-libs threads ABI_MIPS="n32 n64 o32" ABI_PPC="32 64" ABI_S390="32 64" ABI_X86="32 64 x32"}
     Installed versions:  0.3.5[1](02:26:39 PM 03/29/2019)(openmp threads -dynamic -int64 -static-libs ABI_MIPS="-n32 -n64 -o32" ABI_PPC="-32 -64" ABI_S390="-32 -64" ABI_X86="64 -32 -x32")
     Homepage:            http://xianyi.github.com/OpenBLAS/
     Description:         Optimized BLAS library based on GotoBLAS2

[1] "sage-on-gentoo" /storage/strogdon/gentoo-rap/var/lib/layman/sage-on-gentoo
[2] "science" /storage/strogdon/gentoo-rap/var/lib/layman/science
```

**Comment by kiwifb** [comment]
But why aren't ntl and pari in the same boat? I'd like to see the compilation line for the successful linking without thread.

**Comment by strogdon** [comment]
Is `openblas_openmp` even to be used with `threads`? With a `dummy.c`
```
gcc -o dummy dummy.c -lopenblas_threads
```
and `dummy` is created. But
```
gcc -o dummy dummy.c -lopenblas_openmp
```
returns
```
/storage/strogdon/gentoo-rap/usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lopenblas_openmp
```

**Comment by kiwifb** [comment]
To be honest I am not sure. But that implies the message is misleading. Try adding `-Wl,--verbose` to your failing compilation line.

**Comment by strogdon** [comment]
Ahh, There is no `libopenblas_openmp.so`! There is
```
/storage/strogdon/gentoo-rap/usr/lib/libopenblas_openmp.so.0
/storage/strogdon/gentoo-rap/usr/lib/libopenblas_openmp_sandybridgep-r0.3.5.so
```
Without `threads` the `.so` link is created.

**Comment by kiwifb** [comment]
I'll investigate the openblas ebuild. If it was working before then it is not on purpose.

**Comment by strogdon** [comment]
I don't know if it was working previously. I don't usually build openblas with threads. I was only testing https://trac.sagemath.org/ticket/27565 for possible failures.

**Comment by kiwifb** [comment]
I am using openblas with threads and I haven't seen this. I am not sure it is a good idea to build openblas with both openmp and threads. I guess if you can eselect between them it is ok. I really have to re-read that stuff closely.

**Comment by strogdon** [comment]
When I build openblas with both openmp and threads I have from `eselect blas list`
```
Available providers for blas:
  [1]   openblas-threads *
  [2]   reference
```
So there is no openmp option. If you have no problem on your end then maybe it's Prefix. I will check on my Gentoo later this evening.

**Comment by kiwifb** [comment]
You shouldn't even have any openmp stuff. I wonder if they are left over from a previous install that wasn't cleaned well. From the ebuild
```
        # choose posix threads over openmp when the two are set
        # yet to see the need of having the two profiles simultaneously
        if use threads; then
                openblas_flags+=( USE_THREAD=1 USE_OPENMP=0 )
        elif use openmp; then
                openblas_flags+=( USE_OPENMP=1 )
        else
            	openblas_flags+=( USE_THREAD=0 ) # single-threaded
        fi
```
So if you enable threads you won't get any openmp.

**Comment by strogdon** [comment]
I was wondering about that since I saw that in the ebuild. But the timestaps on `openblas_openmp` and `openblas_threads` libs were nearly the same. I should have built in the portage image folder to confirm.

**Comment by kiwifb** [comment]
Well I couldn't build both on my gentoo box. The only thing I can think of is that you have `USE_THREAD=1` somewhere in the environment.

**Comment by strogdon** [comment]
Rebuilt `openblas` with threads on this slow Gentoo box. The `openblas_openmp` libs are present but not rebuilt. I suspect they are present because of `preserved-libs`. But this doesn't explain the `giac` and `igraph` failures.

**Comment by strogdon** [comment]
Yes, in prefix with `openmp` and `threads` only the `openblas_threads` libs are built. The `openblas_openmp` libs (the .so symlink has been removed) that are present are from a previous build, probably for `@preserved-rebuild`? 

Now on my Gentoo I installed openblas with openmp and threads and then did
```
ebuild giac-1.5.0.47.ebuild clean install
```
and giac failed just like in prefix. From the giac Makefile there is
```
GSL_LIBS = -lgsl -lopenblas_openmp -lm
```
This is coming from (I suppose)
```
pkg-config --libs gsl
-lgsl -lopenblas_openmp -lm
```
Am I missing something?

**Comment by kiwifb** [comment]
It looks like `gsl` needs rebuilding after changing the type of `openblas` because it uses it as an external cblas.

**Comment by strogdon** [comment]
I was wondering?

**Comment by strogdon** [comment]
Now on Gentoo `emerge @preserved-rebuild` does pull in `gsl` before rebuilding `giac` and `igraph`, but not so in Prefix. I think it's a `preserved-rebuild` issue with Prefix. I've seen this before!

**Comment by strogdon** [comment]
OK rebuilding `gsl` does fix the building of `giac`, but `igraph` still fails. There must be another dependency that has to be rebuilt for `igraph` to build. In prefix all I have from `emerge -p @preserved-rebuild` is
```
Calculating dependencies... done!
[ebuild   R    ] dev-libs/igraph-0.7.1-r2 
[ebuild   R    ] sci-libs/linbox-1.5.2 
[ebuild   R    ] sci-mathematics/giac-1.5.0.47
```
Not very helpful. The build of `giac` links against both `openblas_openmp` and `openblas_threads`. Strange.

**Comment by kiwifb** [comment]
Well igraphs dependencies
```
RDEPEND="
	dev-libs/libxml2
        >=sci-libs/arpack-3
        virtual/blas
        virtual/lapack
        >=sci-libs/cxsparse-3
        sci-mathematics/glpk
        gmp? ( dev-libs/gmp:0 )"
```
arpack would need rebuilding as well as a number of deps of glpk and glpk itself. It's almost as bad as a change of gfortran runtime.

**Comment by kiwifb** [comment]
It may be advisable to rebuild everything given by the output of
```
equery d virtual/blas virtual/cblas
```

**Comment by strogdon** [comment]
Taking my cue from what is needed on Gentoo I tried
```
emerge -1 iml gsl umfpack cblas-reference lapack-reference numpy arpack fflas-ffpack dsdp scipy linbox igraph
```
which revealed that `cholmod` could no be found? Adding it to the list allowed `igraph` to build. I don't know which was the real culprit.

**Comment by kiwifb** [comment]
If you are using suite sparse from the sage-on-gentoo overlay, `cholmod` is now a defaut use for `umfpack`.

**Comment by strogdon** [comment]
Reversing the process (building openblas [-threads]) gives now  when building `igraph` that `openblas_threads` libs cannot be found? Using the above emerge list allowed igraph to build. Something is clearly broken in Prefix. And I don't know how to quantify it. On Gentoo the following list is needed to satisfy `preserved libs`
```
Calculating dependencies... done!
[ebuild   R   ~] sci-libs/lapack-reference-3.8.0-r100 
[ebuild   R   ~] sci-libs/iml-1.0.5 
[ebuild   R   ~] sci-libs/gsl-2.5 
[ebuild   R    ] sci-libs/umfpack-5.6.2 
[ebuild   R    ] sci-libs/arpack-3.1.5 
[ebuild   R   ~] sci-libs/fflas-ffpack-2.3.2-r1 
[ebuild   R   ~] dev-python/numpy-1.16.1 
[ebuild   R    ] sci-libs/qrupdate-1.1.2-r1 
[ebuild   R   ~] sci-libs/dsdp-5.8-r3 
[ebuild   R   ~] sci-libs/linbox-1.5.2 
[ebuild   R   ~] sci-libs/scipy-1.2.1 
[ebuild   R   ~] dev-libs/igraph-0.7.1-r2
```
while in Prefix I have
```
Calculating dependencies... done!
[ebuild   R    ] sci-libs/cblas-reference-20161223-r101 
[ebuild   R    ] sci-libs/lapack-reference-3.8.0-r100 
[ebuild   R    ] sci-libs/fflas-ffpack-2.3.2-r1 
[ebuild   R    ] dev-libs/igraph-0.7.1-r2 
```
`grumpdate` is not installed in Prefix but all others are important. Once I'm satisfied here I will close. This is not an overlay issue.

**Comment by strogdon** [comment]
I went through the emerge list (https://github.com/cschwan/sage-on-gentoo/issues/538#issuecomment-478201817) one by one and it appears that `gsl` and `arpack` are the ones preventing building of `igraph`. I hope I remember what to do in the future. `arpack` depends on `virtual/blas` and `virtual/lapack` so perhaps these two (and maybe `virtual/cblas`) should control rebuilds.

**Comment by kiwifb** [comment]
Just a note that I am skipping 8.8.beta0. Next time sage-9999 will be in sync will be for 8.8.beta1.
