### ISSUE TITLE
Mirror download issues

### ISSUE THREAD

**Issue by dhalsimax** [cschwan/sage-on-gentoo#544]
--2019-07-27 17:49:38--  (try: 3)  http://sagetrac.lipn.univ-paris13.fr/sage/sage-8.7-doc-html.tar.xz
Connecting to sagetrac.lipn.univ-paris13.fr (sagetrac.lipn.univ-paris13.fr)|194.254.163.85|:80... failed: Connection timed out.

Any other mirror out here ?

**Comment by kiwifb** [comment]
Not at the moment. This is a sore issue, that I have been spending time minimising. I'll contact the server owner ASAP to see what's happening.

**Comment by dhalsimax** [comment]
I have a spare server i can mirror please feel free to contact me

**Comment by kiwifb** [comment]
That's helpful but that's only pushing the issue until you bail out for whatever reason.

**Comment by kiwifb** [comment]
The good news is that I have all the files on hand.

**Comment by kiwifb** [comment]
OK, I created a new mirror and put it first for now. Was good experience. Try now.

**Comment by dhalsimax** [comment]
Thanks I'm downloading, still there if you want the spare mirror

**Comment by slel** [comment]
Sorry to say this so late: there's a mirror at https://github.com/sagemath/sagetrac-mirror

**Comment by kiwifb** [comment]
@slel the issues is referring to files that are specific to sage-on-gentoo.
* split autotooled tarballs for suitesparse
* pre-built html and pdf docs for the last two sage release
* miscellaneous files
