### ISSUE TITLE
sage --optional

### ISSUE THREAD

**Issue by strogdon** [cschwan/sage-on-gentoo#548]
This is more of a request than a defect. Presently, vanilla uses `sage --optional` to provide a list of option packages. Some of these packages are relevant to sage-on-gentoo and some aren't. I think it would be nice, for testing purposes, to know which optional packages are provided by sage-on-gentoo so they could be installed and used in doctesting through
```
sage -t <location/file> --optional=<packages>
```
This sort of thing is usually controlled through useflags but that approach may be overwhelming.

**Comment by kiwifb** [comment]
I want to limit the use flags to stuff that requires some compilation in sage - with exceptions if there is a good argument. For the rest there is the possibility of listing interesting packages in post-install. Some other packages have been doing that and I have been thinking about adding it for some time but never got around it.

Some packages are also not supported at the moment like `coin-or`, and saying it, may also be useful.

**Comment by kiwifb** [comment]
Upstream is thinking hard about this. I think some of the evolution sage is going through will make it go away.
