### ISSUE TITLE
Remove science overlay from README

### ISSUE THREAD

**Issue by sandwm** [cschwan/sage-on-gentoo#550]
As far as I see, since the science overlay was removed as a dependency in #546, this could also be removed from the README. It currently states to do
```
layman -a science
```

(By the way: I had to `emerge -a1 sci-libs/iml::gentoo` by hand to migrate.)

**Comment by kiwifb** [comment]
Yes, I need to fix that. That kind of migration is always manual. It usually doesn't hurt not to migrate until necessary (full rebuild or upgrade).

**Comment by kiwifb** [comment]
Fixed.
