### ISSUE TITLE
sci-libs/brial-1.2.5 fails with configure: error: Could not find a version of the library!

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [cschwan/sage-on-gentoo#551]
Tested with sane CFLAGS

```
checking whether x86_64-pc-linux-gnu-g++ supports C++11 features by default... yes
checking for long long... yes
checking size of void *... 8
checking size of int... 4
checking size of long... 8
checking for boostlib >= 1.58.0... yes
checking whether the Boost::Unit_Test_Framework library is available... yes
configure: error: Could not find a version of the library!

!!! Please attach the following file when seeking support:
!!! /var/tmp/portage/sci-libs/brial-1.2.5/work/brial-1.2.5/config.log
 * ERROR: sci-libs/brial-1.2.5::sage-on-gentoo failed (configure phase):
 *   econf failed
```

[config.log](https://gist.github.com/Alessandro-Barbieri/cd8eae5a6a6fffd0cff9d6595f1c19ab)

**Comment by kiwifb** [comment]
Which version of boost?

**Comment by Alessandro-Barbieri** [comment]
I have `dev-libs/boost-1.70.0::gentoo` `USE="bzip2 context icu lzma mpi nls numpy python threads tools zlib zstd -debug -doc -static-libs"` `PYTHON_TARGETS="python2_7 python3_6 python3_7 -python3_5"`
and
`dev-util/boost-build-1.70.0::gentoo` `USE="python -examples -test"` `PYTHON_TARGETS="python2_7"`

**Comment by kiwifb** [comment]
There has been some major changes in boost in the last few versions. So it isn't completely surprising. I'll look into ASAP.

**Comment by Alessandro-Barbieri** [comment]
Sorry, I had old boost libraries still installed (I don't know why weren't cleaned on upgrade)

**Comment by kiwifb** [comment]
Boost is a red herring. The problem is with `pkg-config` which one are you using?

**Comment by kiwifb** [comment]
Somehow your message about old boost libraries has been lost on github. Do you still have the issue?

**Comment by Alessandro-Barbieri** [comment]
I have
```
dev-python/pkgconfig 1.4.0
dev-util/pkgconfig 0.29.2
```
BTW I had to manually delete old `.so` from boost 1.65.0
I tried to emerge after but the same error happens

**Comment by kiwifb** [comment]
something strange. It looks like autoconf has been re-run. Can you post the full build log?

**Comment by kiwifb** [comment]
ping?

**Comment by Alessandro-Barbieri** [comment]
https://gist.github.com/6628c59a3b60913627363bee10da599c

**Comment by kiwifb** [comment]
OK, what I find really curious is that the line numbers in your `config.log` don't match mine. That should indicate that your `configure` is different from the one upstream [I am upstream in this case]. That's just odd.

**Comment by Alessandro-Barbieri** [comment]
My [configure](https://gist.github.com/b0e0c4159abf744d84990d6a035b93f1) file

**Comment by kiwifb** [comment]
Your `config.log` do not match with your `configure` file. The line number in `config.log` should correspond to the one executed in `configure` but in your case they don't. I am at a loss about what's happening on your system.

**Comment by Alessandro-Barbieri** [comment]
I entered the workdir then run
`autoreconf -fiv`
`./configure`
and the configure succeeded

**Comment by kiwifb** [comment]
Well it shouldn't. The eclass is only for when you need to regenerate `configure` and the `Makefile.in` files - and it shouldn't be the case here. Why your configure is different and why the tarball still pass the manifest is a mystery to me. I generated that tarball as upstream and it shouldn't need any of this. What you have is not what I put out.

**Comment by Alessandro-Barbieri** [comment]
Debian suggest to run autoreconf before packaging
https://wiki.debian.org/Autoreconf

**Comment by Alessandro-Barbieri** [comment]
my workdir after the build failure
```
-rw-r--r-- 1 root root  54K  5 giu   23:59   aclocal.m4
-rwxr-xr-x 1 root root 5,7K 14 ott    2017   ar-lib
-rw-r--r-- 1 root root  189 13 ott    2017   common.mk
-rwxr-xr-x 1 root root 7,2K 14 ott    2017   compile
-rwxr-xr-x 1 root root  44K 12 set   05:27   config.guess
-rw-r--r-- 1 root root  38K 12 set   05:27   config.log
-rwxr-xr-x 1 root root  37K 12 set   05:27   config.sub
-rwxr-xr-x 1 root root 646K  6 giu   00:20   configure
-rw-r--r-- 1 root root 3,0K  5 giu   23:59   configure.ac
drwxr-xr-x 2 root root  340  6 giu   02:04   cudd
-rwxr-xr-x 1 root root  24K 14 ott    2017   depcomp
drwxr-xr-x 4 root root  120  6 giu   02:04   groebner
-rwxr-xr-x 1 root root  15K 14 ott    2017   install-sh
drwxr-xr-x 4 root root  120  6 giu   02:04   libbrial
-rw-r--r-- 1 root root  18K 13 ott    2017   LICENSE
-rw-r--r-- 1 root root 318K 14 ott    2017   ltmain.sh
drwxr-xr-x 2 root root  220  6 giu   02:04   m4
-rw-r--r-- 1 root root  444 13 ott    2017   Makefile.am
-rw-r--r-- 1 root root  33K  6 giu   00:20   Makefile.in
-rwxr-xr-x 1 root root 6,8K 14 ott    2017   missing
-rw-r--r-- 1 root root  606 16 ott    2017   README
drwxr-xr-x 3 root root  100  7 mar    2018   sage-brial
-rwxr-xr-x 1 root root 4,6K  6 giu   00:20   test-driver
drwxr-xr-x 2 root root  640  6 giu   02:04   tests
```

**Comment by strogdon** [comment]
I find this interesting. Could the hardened profile be doing something `spooky`? My build works here.

**Comment by kiwifb** [comment]
OK, so I made checks that where cursory before. https://gist.githubusercontent.com/Alessandro-Barbieri/b0e0c4159abf744d84990d6a035b93f1/raw/4a00bd262dd4fdd80987996fc66c9d1036a40c52/configure is identical to what is comming out of the tarball. But https://gist.github.com/Alessandro-Barbieri/cd8eae5a6a6fffd0cff9d6595f1c19ab#file-config-log doesn't match that configure. I am not aware of hardened doing anything to configure scripts.

**Comment by Alessandro-Barbieri** [comment]
If it builds on your setup, what version of boost, gnuconfig, do you have?
If you configure, configure and config.log lines will match? I tried configuring manually after the unpack but the lines doesn't match

**Comment by kiwifb** [comment]
Currently boost 1.70.0, gnuconfig 20180101. Yes config.log lines matches my configure.

**Comment by Alessandro-Barbieri** [comment]
I can't reproduce for now on the new chroot but I found that the problem is here:
https://gist.github.com/Alessandro-Barbieri/c999f92412424dcda7f8fee7ed362b49#file-config-log
line 674
https://gist.github.com/Alessandro-Barbieri/c999f92412424dcda7f8fee7ed362b49#file-configure
line 17920
https://gist.github.com/Alessandro-Barbieri/c999f92412424dcda7f8fee7ed362b49#file-configure-ac
line 40

**Comment by kiwifb** [comment]
Still this weird numbering offset. Are you in a prefix?
```
BOOST_CPPFLAGS='-I/usr/include'
BOOST_LDFLAGS='-L/usr/lib/x86_64-linux-gnu'
```
that last one feels like a debian based system rather than a gentoo system.

**Comment by Alessandro-Barbieri** [comment]
Before (6 months ago) I was on a gentoo system but now I've migrated the files in a chroot inside a debian system because the HDD was failing.

**Comment by kiwifb** [comment]
OK, this is weird, you shouldn't be able to see outside of the chroot, but the evidence is that you do and that the boost m4 macros are picking up a boost install on the host. Or the macro is confused because your system identifies as debian
```
hostname = server-NAS
uname -m = x86_64
uname -r = 4.19.0-8-amd64
uname -s = Linux
uname -v = #1 SMP Debian 4.19.98-1 (2020-01-26)
```
I'll dig a bit but I think that is the right track. The macro is completely confused by your chroot.

**Comment by kiwifb** [comment]
Do you have `/usr/lib/x86_64-linux-gnu` in your chroot?

**Comment by Alessandro-Barbieri** [comment]
Yes and it only contains a `perl-base` folder

**Comment by kiwifb** [comment]
OK it looks like `perl` may have been confused by your setup and created that folder. Now that the folder exist, the boost m4 macro check that it exist before anything else and goes on to assume that's where your boost libraries live and is getting confused when they don't. A cure for that would be to pass `--with-boost-libdir="${EPREFIX}"/usr/$(get_libdir)` to `configure` in the ebuild - just for you.

**Comment by kiwifb** [comment]
sync the overlay and try again.

**Comment by kiwifb** [comment]
ping?

**Comment by Alessandro-Barbieri** [comment]
It worked!
