### ISSUE TITLE
sci-mathematics/giac-1.5.0.63 -- undefined reference to 'dgemm_'

### ISSUE THREAD

**Issue by sheerluck** [cschwan/sage-on-gentoo#552]
If I open giac-1.5.0/src/Makefile and change line 420 from
```
LAPACK_LIBS = -llapack
```
to 
```
LAPACK_LIBS = -llapack -lblas
```
then everything works

**Comment by kiwifb** [comment]
Hum... That's curious unless dgemm is being called from libgiac. In any case how do you get that message? The `Makefile` is absolutely not the place to put a change. Also which blas and lapack are you using?

**Comment by sheerluck** [comment]
I use sci-libs/lapack-3.8.0 and three virtuals:
virtual/blas
virtual/cblas
virtual/lapack
I get that message after ```sudo emerge giac```

**Comment by kiwifb** [comment]
OK, after code inspection direct linking with blas is needed. I will fix this shortly.

**Comment by kiwifb** [comment]
Synchronize and emerge goac again. It should work nicely out of the box for you now.

**Comment by sheerluck** [comment]
Thank you

**Comment by kiwifb** [comment]
Please leave a comment if it works, so the issue can be closed.

**Comment by sheerluck** [comment]
It works! Thank you!
