### ISSUE TITLE
sci-mathematics/eclib-20190226 missing source code

### ISSUE THREAD

**Issue by marcvinyals** [cschwan/sage-on-gentoo#553]
It seems that the source code for sci-mathematics/eclib-20190226 is no longer hosted at the url provided by the ebuild:

```
>>> Downloading 'http://homepages.warwick.ac.uk/staff/J.E.Cremona/ftp/eclib-20190226.tar.bz2'
--2019-09-17 20:45:18--  http://homepages.warwick.ac.uk/staff/J.E.Cremona/ftp/eclib-20190226.tar.bz2
Resolving homepages.warwick.ac.uk... 137.205.28.73
Connecting to homepages.warwick.ac.uk|137.205.28.73|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-09-17 20:45:19 ERROR 404: Not Found.

!!! Couldn't download 'eclib-20190226.tar.bz2'. Aborting.
```

The sources for eclib-20190909 are still there. Maybe it would be more reliable to pick the sources from [github](https://github.com/JohnCremona/eclib)? After all, this is where the [eclib website](http://homepages.warwick.ac.uk/~masgaj/mwrank/index.html) points to these days.

**Comment by kiwifb** [comment]
It seems that may be the better option for the long term. There is a fundamental difference between the stuff you get from github and eclib's webiste. On github you just get a tarball of the tagged source. On the eclib website, you get a `sdist` tarball generated by autotools. With the github stuff you have to run the `eautoreconf` and `elibtoolize` to prepare the source. Not so for the stuff from the eclib website, it has already be prepared.

I will make the source available on a mirror shortly.

**Comment by kiwifb** [comment]
Sync, the sources should now be fetched from a mirror. There is actually a better mirror option in the future and I should prepare for it.
