### ISSUE TITLE
sci-mathematics/giac-1.5.0.67

### ISSUE THREAD

**Issue by welele08** [cschwan/sage-on-gentoo#554]
Try to install giac on a clean sabayon distribution.
Installation failed with :

configure: error: Package requirements (lapack) were not met:

No package 'lapack' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables LAPACK_CFLAGS
and LAPACK_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

Looking in /var/tmp/portage/.../work/config.log. It show the ebuild search without succes for lapack.pc

Is there something i do wrong or something i forgot?

Thanks

**Comment by kiwifb** [comment]
This is strange. A lapack should have been pulled by `virtual/lapack`. Do you have a lapack installed? And if so why don't you have a `lapack.pc` in `/usr/lib64/pkgconfig`?

**Comment by welele08** [comment]
I have a virtual/lapack and sci-libs/lapack-reference-3.7.0 installed.
I have a lapack.rc file in /usr/lib64/lapack/reference/ but non in /usr/lib64/pkgconfig.

**Comment by kiwifb** [comment]
I would say that it means that your lapack is not eselect-ed. What does `eselect lapack show` says?

**Comment by welele08** [comment]
Thank for help.

eselect lapack show give me : 
lib64: reference

**Comment by kiwifb** [comment]
Hum, looking at lapack-reference-3.7.0 from the main tree, `lapack.pc` should be shipped in the right place. Do you have `virtual/lapack-3.8` available, or are you stuck at `3.7`?

**Comment by welele08** [comment]
I'm running a sabayon system, with precompiled gentoo package. I try a "pkgconfig --libs lapack" which give a 

Package lapack was not found in the pkg-config search path.
Perhaps you should add the directory containing `lapack.pc'
to the PKG_CONFIG_PATH environment variable
No package 'lapack' found

I try to recompile lapack-reference ("merge lapack-reference"). After install, still no /usr/lib64/pkgconfig/lapack.pc. 
eselect didn't find lapack anymore 
"eselect lapakc list" => 
Available LAPACK (lib32) candidates:
  (none found)
Available LAPACK (lib64) candidates:
  (none found)

**Comment by kiwifb** [comment]
Which version of `eselect-lapack` is this? I think you may have a mismatch between the eselect module and the lapack version.

**Comment by welele08** [comment]
eselect-lapack-0.2

**Comment by kiwifb** [comment]
Yes, that's the trouble. `eselect-lapack-0.2` should be used with `virtual/lapack-3.8`, lapack-3.7 should be using `eselect-lapack-0.1`.  And similarly for `eselect-blas` (by design there is no `eselect-cblas-0.2`). They have incompatible selection mechanism.

**Comment by welele08** [comment]
Thank you so much! 
Downgrading eselect-lapack form 0.2 to 0.1 solve the problem.
