### ISSUE TITLE
ExportSageNB requires ipython2

### ISSUE THREAD

**Issue by gordon-quad** [cschwan/sage-on-gentoo#556]
It seems to be that in sage installation ExportSageNB is the only non-optional dependency of sage that is python2-only and pulls it ipython which blocks installation of >=ipython-6 since it is python3-only.

Correct me if I wrong but it doesn't seem that ExportSageNB is part of core functionality and sage can function perfectly fine without it.

Can we have ExportSageNB as optional dependency or possibly upgrade it to python3 if upstream supports it?

**Comment by kiwifb** [comment]
I am surprised it is python2 only. Quite possibly something I forgot when I started to enable python3. Checking upstream.

**Comment by kiwifb** [comment]
Yes, it is my mistake to have left it python2. Fixing ASAP.

**Comment by kiwifb** [comment]
Fixed. There is a good chance of me dropping python 2.7 altogether in the next version of sage.

**Comment by gordon-quad** [comment]
great, thanks!
