### ISSUE TITLE
sci-mathematics/eclib-20190909 points to a file that does not exist.

### ISSUE THREAD

**Issue by jokleinn** [cschwan/sage-on-gentoo#557]
The SRC_URI of sci-mathematics/eclib-20190909 points to a file in [this directory](http://homepages.warwick.ac.uk/staff/J.E.Cremona/ftp/) that no longer exists. There is a [github repository](https://github.com/JohnCremona/eclib) that has eclib on it. Perhaps the ebuild could be changed to point to a specific commit on the github repository?

At the current moment, it is impossible to depclean my system or update world, because of dependencies involving eclib, ntl, and sage -- the root cause of this is eclib being unable to be updated.

Let me know if you want me to take a shot at updating the ebuild myself.

Thanks,
J

**Comment by kiwifb** [comment]
We had that discussion before. The github source would need to be "eautoconfigured". Something I used to do and would like to avoid if possible. I pointed `SRC_URI` to a lasting mirror maintained by sagemath itself.
