### ISSUE TITLE
potential race condition when building pdf docs (9.0.beta4)

### ISSUE THREAD

**Issue by strogdon** [cschwan/sage-on-gentoo#558]
I'm assuming a race condition because after a failure an `ebuild sage-9999.ebuild install` usually completes the build. The failure from build.log
```
! Emergency stop.
<read 0>

l.35 \externalcitedocument
                          [../references/]{../references/references}
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on sets.log.
```
and from `sets.log`
```
Package xr Info: IMPORTING LABELS FROM ../references/references.aux on input li
ne 35.

Runaway definition?
->\bibcite {index:bm2
! File ended within \read.
<read 0>

l.35 \externalcitedocument
                          [../references/]{../references/references}
?
! Emergency stop.
<read 0>

l.35 \externalcitedocument
                          [../references/]{../references/references}
End of file on the terminal!


Here is how much of TeX's memory you used:
 6083 strings out of 494459
 85499 string characters out of 6171841
 166389 words of memory out of 5000000
 9645 multiletter control sequences out of 15000+600000
 4403 words of font info for 15 fonts, out of 8000000 for 9000
 37 hyphenation exceptions out of 8191
 37i,0n,45p,276b,48s stack positions out of 5000i,500n,10000p,200000b,80000s
!  ==> Fatal error occurred, no output PDF file produced!
```
Relative to the `sets` folder `../references/references.aux` exists. I can't test on vanilla without updating my `latex` install.

**Comment by kiwifb** [comment]
Probably a race condition indeed. Are you still on texlive 2017? 2019 is stable now.

**Comment by strogdon** [comment]
This was in Prefix with texlive 2019.

**Comment by kiwifb** [comment]
I understand better the comment about upgrading now. I cannot reproduce it, but yes it smells of race condition, it's trying to read a file that is not closed for writing with another process.

**Comment by strogdon** [comment]
This [commit](https://git.sagemath.org/sage.git/diff/src/sage_setup/docbuild/__init__.py?id=2eff516090a8c057e6601887fd9dae00f34ec73f) from ticket [28059](https://trac.sagemath.org/ticket/28059) was to insure the necessary `.aux` files are generated first. I don't know how to insure the created file has been closed before reading is attempted.

**Comment by kiwifb** [comment]
I wouldn't think the situation improved with beta5 but it should be checked.

**Comment by strogdon** [comment]
Still failed with beta5, different location.

from build.log
```
Runaway definition?
->\bibcite {index:epp200
! File ended within \read.
<read 0>

l.35 ...[../references/]{../references/references}

?  [359
! Emergency stop.
<read 0>

l.35 ...[../references/]{../references/references}

!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on rings_standard.log.
```
and from rings_standard.log
```
(/storage/strogdon/gentoo-rap/usr/share/texmf-dist/tex/latex/xcite/xcite.sty
Package: xcite 2011/09/02 v1.0 eXternal Citations (EG)
)
(/storage/strogdon/gentoo-rap/usr/share/texmf-dist/tex/latex/hyperref/xr-hyper.
sty
Package: xr-hyper 2000/03/22 v6.00beta4 eXternal References (DPC)
)
Package xr Info: IMPORTING LABELS FROM ../references/references.aux on input li
ne 35.
Package xc Info: IMPORTING LABELS FROM ../references/references.aux on input li
ne 35.

Runaway definition?
->\bibcite {index:epp200
! File ended within \read.
<read 0>

l.35 ...[../references/]{../references/references}

?
! Emergency stop.
<read 0>

l.35 ...[../references/]{../references/references}

End of file on the terminal!
```
So I suspect `references.aux` has been created first but a process requests a read from it before is has been closed by another process. I am using python-3.7.5-r1. I don't suspect that could be causing this? With the existing build folder, an `ebuild sage-9999.ebuild install` produced a second failure, still in `rings_standard`.
```
Runaway definition?
->\bibcite {index:bm2
! File ended within \read.
<read 0>

l.35 \externalcitedocument
                          [../references/]{../references/references}
?
! Emergency stop.
<read 0>

l.35 \externalcitedocument
                          [../references/]{../references/references}
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on rings_standard.log.
```
A second `ebuild sage-9999.ebuild install` attempt failed with
```
Runaway definition?
->\bibcite {index
! File ended within \read.
<read 0>

l.35 \externalcitedocument
                          [../references/]{../references/references}
?
! Emergency stop.
<read 0>

l.35 \externalcitedocument
                          [../references/]{../references/references}
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on valuations.log.
```
A third attempt failed with
```
Runaway definition?
->\bibcite {index
! File ended within \read.
<read 0>

l.35 \externalcitedocument
                          [../references/]{../references/references}
?
! Emergency stop.
<read 0>

l.35 \externalcitedocument
                          [../references/]{../references/references}
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on number_fields.log.
```
I have not been able to get this to build. I will try from scratch with a smaller MAKEOPTS. I have been using MAKEOPTS="-j13" with 12 cores.

**Comment by strogdon** [comment]
It built from scratch with MAKEOPTS="-j6".

**Comment by strogdon** [comment]
Getting this same issue on a Gentoo machine with 4 cores using python-3.6.9. However, upon continuing the build using `ebuild ... install` I get:
```
Writing index file schemes.idx
(./schemes.aux)
Runaway argument?
{{16.10}{325}{Weierstrass form of a toric elliptic cu
! File ended while scanning use of \@newl@bel.
<inserted text>
                \par
l.213 \begin{document}

?
! Emergency stop.
<inserted text>
                \par
l.213 \begin{document}

End of file on the terminal!
```
which suggests a LaTeX problem. Perhaps unrelated to the `bibcite` issue.

**Comment by strogdon** [comment]
From `scheme.aux` it appears something isn't completed
```
\newlabel{sage/schemes/toric/weierstrass:sage.schemes.toric.weierstrass.WeierstrassForm_P1xP1}{{16.10}{325}{Weierstrass form of a toric elliptic cu
```
which is the last line in the file.

**Comment by kiwifb** [comment]
Rather abrupt. PDF doc parallel building feels broken in multiple places now.

**Comment by strogdon** [comment]
I suspect this `scheme.aux` issue was related to the `bibcite` problem. I did `make clean` in the `scheme` folder then `ebuild ... install` completed the build. Apparently, the original `bibcite` issue left the `scheme` folder in an incomplete state.

**Comment by strogdon** [comment]
Fixed with Sage trac [commit](https://git.sagemath.org/sage.git/commit?id=7b3f429848d4d67dfb826d57838416907bd3100d)
