### ISSUE TITLE
Gentoo dropped python2.7 support for ipython

### ISSUE THREAD

**Issue by ngg** [cschwan/sage-on-gentoo#561]
https://github.com/gentoo/gentoo/pull/13771 removed python 2.7 support from ipython-related packages, breaking sage as well :(

I assume more and more packages will be python3-only in the main overlay, so the easiest way to handle this would be to remove python2 support entirely.

**Comment by kiwifb** [comment]
Not just that. I'll need to use some patch to use ipython-7. I was planning the drop in the upcoming sage-9.0.

**Comment by kiwifb** [comment]
OK now I have seen the details. Tree as been updated to remove python 2.7 from sage. The recommended version to run is 3.7. 

Some further cleaning is probably coming.
