### ISSUE TITLE
package.use needs `=dev-python/sympy-1.4-r100 -python_targets_python2_7`

### ISSUE THREAD

**Issue by zx2c4** [cschwan/sage-on-gentoo#564]
Gentoo unstable. Should this be in package.use/sage-unstable?

```
The following USE changes are necessary to proceed:
 (see "package.use" in the portage(5) man page for more details)
# required by sci-mathematics/sage-9.0::sage-on-gentoo
# required by sage (argument)
=dev-python/sympy-1.4-r100 -python_targets_python2_7
```

**Comment by kiwifb** [comment]
That shouldn't be necessary. This is actually curious, on the other hand the file `package.use/sage-unstable` is outdated and should be removed. I should clean `package.use/sage` as well. Here unstable was supposed to refer to sage-9999.

**Comment by kiwifb** [comment]
OK I have done some clean up of package.use. It feels unlikely it will an impact but if you are using any of it, I'd like you to sync the overlay and retry. Worse come to the worse, I'll update sympy-1.4 to a python3 only version.

**Comment by zx2c4** [comment]
Nope, the issue still remains.

**Comment by kiwifb** [comment]
I have to make a py3 only ebuild of that version of sympy. That is the real issue, same reason people who currently have matplotlib-2.x installed (with py2) cannot install numpy-1.17.x which is py3 only. I will fix this ASAP.

**Comment by kiwifb** [comment]
I have pushed a new py3 only sympy-1.4. It should fix your dependency issue.

**Comment by kiwifb** [comment]
No feedback. Closing.
