### ISSUE TITLE
downgrade of sphinx

### ISSUE THREAD

**Issue by zx2c4** [cschwan/sage-on-gentoo#565]
sage wants to downgrade sphinx:

```
[ebuild     UD ] dev-python/sphinx-1.8.5::sage-on-gentoo [2.0.1::gentoo] USE="-doc -latex -net% -test" PYTHON_TARGETS="python2_7%* python3_6 -pypy3 -python3_7 (-python3_8%)" 5,622 KiB
```

![image](https://user-images.githubusercontent.com/10643/72821545-f0ab8e00-3c70-11ea-9226-b1357b654cb2.png)

This obviously isn't ideal.

**Comment by kiwifb** [comment]
Nope. I changed the way I expressed the dependency to that version of sphinx and I don't like the result. Portage shouldn't upgrade you to sphinx-2.x in the first place. I have to fix that.

**Comment by kiwifb** [comment]
Could use a second opinion there. The ebuild already has
```
	>=dev-python/sphinx-1.8.5[${PYTHON_USEDEP}]
	<dev-python/sphinx-2.0.0
```
in `RDEPEND`. Why is portage upgrading sphinx to 2.0.1 at all?

**Comment by kiwifb** [comment]
It actually behaves properly on my system now.
