### ISSUE TITLE
sci-mathematics/arb-2.17

### ISSUE THREAD

**Issue by mbuzdalov** [cschwan/sage-on-gentoo#573]
emerge says:

```
These are the packages that would be merged, in order:

Calculating dependencies... done!

emerge: there are no ebuilds to satisfy "~sci-mathematics/arb-2.16.0".
(dependency required by "sci-mathematics/sage-9.0::sage-on-gentoo" [ebuild])
(dependency required by "sage" [argument])
```

There is apparently only arb-2.17 at the time of writing. Can Sage live with that?

**Comment by kiwifb** [comment]
Technically it will build and mostly run I think. But some results will be different and some computations may crash. Has `arb-2.16.0` been purged from the tree? That would have been a mistake.

**Comment by mbuzdalov** [comment]
As long as I see it in my own copy of Portage, they indeed removed 2.16 from the tree:

```
$ ls /usr/portage/sci-mathematics/arb/
arb-2.17.0.ebuild  Manifest  metadata.xml
```

**Comment by kiwifb** [comment]
<insert your favorite swearing> Ok i'll restore a copy in the overlay. I am quite busy today so it may take up to 24hours.

**Comment by mbuzdalov** [comment]
Thank you very much!

**Comment by kiwifb** [comment]
`arb` is back in the overlay. I'll prune 2.17.0 later.
