### ISSUE TITLE
maxima question

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [cschwan/sage-on-gentoo#576]
Which version is needed for sage: `maxima::sage-on-gentoo` or `maxima::gentoo`?

**Comment by kiwifb** [comment]
Technically you can build sage with both. But at this point in time some particular things may crash if you don't use the sage-on-gentoo version. And some results will be incorrect if you use a higher version.

**Comment by kiwifb** [comment]
For the crash the key is this patch https://github.com/cschwan/sage-on-gentoo/blob/master/sci-mathematics/maxima/files/maxima-5.39.0-0001-taylor2-Avoid-blowing-the-stack-when-diff-expand-isn.patch

**Comment by Alessandro-Barbieri** [comment]
I asked because I can't build `maxima::sage-on-gentoo`

**Comment by kiwifb** [comment]
I'll confess that I only really test ecl-16.1.2.
