### ISSUE TITLE
maxima malformed UTF-8 character

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [cschwan/sage-on-gentoo#577]
See build log here
https://gist.github.com/Alessandro-Barbieri/226329100db0ade15152f881ee06884f

**Comment by kiwifb** [comment]
Sorry, is this the full log? I cannot see the error you quote in the issue title in there. Or any errors at all for that matter. And it looks incomplete.

**Comment by Alessandro-Barbieri** [comment]
I think it's truncated by github ... because it's too long

**Comment by Alessandro-Barbieri** [comment]
I have the compressed log but I don't know where/how to upload it (headless machine)

**Comment by kiwifb** [comment]
I have the interesting bit from the start so can you post a config.log and what you judge to be adequate of the end of the log. Because there is no parallel building in lisp there shouldn't be issues.

**Comment by Alessandro-Barbieri** [comment]
The full log always was there
https://gist.github.com/Alessandro-Barbieri/226329100db0ade15152f881ee06884f/raw/fe2025565381b9630cb2b97978c7041dbd14ceba/maxima-5.43.2:20200329-074405.log

**Comment by kiwifb** [comment]
That's documentation stuff. And you say the matching ebuild in the main tree has no issues? I will have to check for a divergence from it if that's the case.

**Comment by kiwifb** [comment]
I am missing a texinfo patch from the main tree, that's probably the issue, I'll synchronize ASAP.

**Comment by kiwifb** [comment]
Sync and retry please.

**Comment by Alessandro-Barbieri** [comment]
Thanks
