### ISSUE TITLE
dev-python/networkx-2.2 was removed from gentoo

### ISSUE THREAD

**Issue by ngg** [cschwan/sage-on-gentoo#578]
Removed in https://github.com/gentoo/gentoo/commit/eac8d91c7aa31ed3bfd701285781fb39f0e40ba1
The only version available is 2.4 now, but sage 9.0 depends on `~dev-python/networkx-2.2` Shouldn't the 2.4 version simply work (maybe with the doctest fix in networkx-2.4.patch)?

**Comment by kiwifb** [comment]
You are likely correct. I also have an extra patch somewhere to fix issues with networkx 2.4 and scipy-1.4+. I should formally put it out.

**Comment by kiwifb** [comment]
Sorry about the new revision bump. Re-open in case there is a problem.
