### ISSUE TITLE
sci-mathematics/sage-9.0-r3.ebuild requires ~sci-libs/m4ri-20140914 which doesn't exist

### ISSUE THREAD

**Issue by ss23** [cschwan/sage-on-gentoo#581]
From what I can see, the required package version ~sci-libs/m4ri-20140914 is not included in this overlay, nor in the main Gentoo packages.

**Comment by kiwifb** [comment]
You are right. I removed it too hastily when the latest m4ri has been included in the tree. Let me check if later m4ri would do before restoring it.

**Comment by kiwifb** [comment]
Hey, we are comparatively neighbours (I live in Christchurch). Most issues are posted from the northern hemisphere.

**Comment by ss23** [comment]
@kiwifb No better time to learn Sage than during a mandatory lockdown 😎

**Comment by kiwifb** [comment]
OK, there is no apparent reason for not being able to use the version from the tree. Fixing the overlay ASAP.

**Comment by ss23** [comment]
This particular issue is fixed. It's still not the easiest install I've done, but I'll work away at it and report more bugs if I need to. Thanks :)

**Comment by kiwifb** [comment]
The timing is bad, we are in transition and elimination of python2. And sage upstream is a bit lagging. You may be hit by the fact sage requires an old sphinx. I may have to do something drastic about that.
