### ISSUE TITLE
QA Notice: installing sage in Prefix

### ISSUE THREAD

**Issue by strogdon** [cschwan/sage-on-gentoo#583]
I see these:
```
 * QA Notice: Symbolic link /storage/strogdon/gentoo-rap/usr/share/jupyter/kernels/sagemath/logo.svg points to /storage/strogdon/gentoo-rap/storage/strogdon/gentoo-rap/usr/lib/python3.7/site-packages/sage/ext_data/notebook-ipython/logo.svg which does not exist.
>>> /storage/strogdon/gentoo-rap/usr/share/jupyter/kernels/sagemath/logo.svg -> ../../../../..//storage/strogdon/gentoo-rap/usr/lib/python3.7/site-packages/sage/ext_data/notebook-ipython/logo.svg
 * QA Notice: Symbolic link /storage/strogdon/gentoo-rap/usr/share/jupyter/kernels/sagemath/logo-64x64.png points to /storage/strogdon/gentoo-rap/storage/strogdon/gentoo-rap/usr/lib/python3.7/site-packages/sage/ext_data/notebook-ipython/logo-64x64.png which does not exist.
>>> /storage/strogdon/gentoo-rap/usr/share/jupyter/kernels/sagemath/logo-64x64.png -> ../../../../..//storage/strogdon/gentoo-rap/usr/lib/python3.7/site-packages/sage/ext_data/notebook-ipython/logo-64x64.png
```
The `logo` files are located:
```
$ find ~/usr/lib/python3.7/site-packages/sage | grep logo
/storage/strogdon/gentoo-rap/usr/lib/python3.7/site-packages/sage/ext_data/notebook-ipython/logo-64x64.png
/storage/strogdon/gentoo-rap/usr/lib/python3.7/site-packages/sage/ext_data/notebook-ipython/logo.svg
/storage/strogdon/gentoo-rap/usr/lib/python3.7/site-packages/sage/ext_data/images/sagelogo.png
```

The installed symlinks:
```
$ ls -al ~/usr/share/jupyter/kernels/sagemath/logo*
lrwxrwxrwx 1 strogdon math 121 Apr 26 18:56 /storage/strogdon/gentoo-rap/usr/share/jupyter/kernels/sagemath/logo-64x64.png -> ../../../../..//storage/strogdon/gentoo-rap/usr/lib/python3.7/site-packages/sage/ext_data/notebook-ipython/logo-64x64.png
lrwxrwxrwx 1 strogdon math 115 Apr 26 18:56 /storage/strogdon/gentoo-rap/usr/share/jupyter/kernels/sagemath/logo.svg -> ../../../../..//storage/strogdon/gentoo-rap/usr/lib/python3.7/site-packages/sage/ext_data/notebook-ipython/logo.svg
```

**Comment by strogdon** [comment]
Just for info, I see a similar thing in `kpathsea-6.3.2_p20200406.ebuild`
```
    dosym /../../../../etc/texmf/web2c/fmtutil.cnf ${TEXMF_PATH}/web2c/fmtutil.cnf
    dosym /../../../../etc/texmf/web2c/texmf.cnf ${TEXMF_PATH}/web2c/texmf.cnf
```
that breaks the install of `kpathsea` in my Prefix.

**Comment by kiwifb** [comment]
Double prefix. Investigating. Do report the `kpathsea` on bugzilla.

**Comment by kiwifb** [comment]
In our case, it would be because `$(python_get_sitedir)` contains the prefix. Would it be correct if it was `../../../../../usr/lib/python3.7/site-packages/sage/ext_data/notebook-ipython/logo-64x64.png` instead?

**Comment by kiwifb** [comment]
If I am right on https://github.com/cschwan/sage-on-gentoo/blob/master/sci-mathematics/sage/sage-9999.ebuild#L493 and https://github.com/cschwan/sage-on-gentoo/blob/master/sci-mathematics/sage/sage-9999.ebuild#L495 if you replace `$(pythin_get_sitedir)` with `${$(python_get_sitedir)#"${EPREFIX}"}` it should be correct.

**Comment by kiwifb** [comment]
May need an intermediate variable to store the value of `python_get_sitedir` (which is a bash function) actually.

**Comment by strogdon** [comment]
This works here
```
    dosym $(python_get_sitedir)/sage/ext_data/notebook-ipython/logo-64x64.png \
        /usr/share/jupyter/kernels/sagemath/logo-64x64.png
    dosym $(python_get_sitedir)/sage/ext_data/notebook-ipython/logo.svg \
        /usr/share/jupyter/kernels/sagemath/logo.svg
```
```
$ ls -al ~/usr/share/jupyter/kernels/sagemath/logo*
lrwxrwxrwx 1 strogdon math 106 Apr 26 23:58 /storage/strogdon/gentoo-rap/usr/share/jupyter/kernels/sagemath/logo-64x64.png -> /storage/strogdon/gentoo-rap/usr/lib/python3.7/site-packages/sage/ext_data/notebook-ipython/logo-64x64.png
lrwxrwxrwx 1 strogdon math 100 Apr 26 23:58 /storage/strogdon/gentoo-rap/usr/share/jupyter/kernels/sagemath/logo.svg -> /storage/strogdon/gentoo-rap/usr/lib/python3.7/site-packages/sage/ext_data/notebook-ipython/logo.svg
```
Curious, the target doesn't need the `EPREFIX` but the actual  l$(python_get_sitedir)ink does which is included in `$(python_get_sitedir)`.

**Comment by strogdon** [comment]
Close in error!

**Comment by kiwifb** [comment]
The way you describe creates absolute links. Which is ok for some things but not others. Did it give you any QA or warning about it not being relative? I am fairly sure I switched from absolute to relative because of some guideline or QA warning.

**Comment by strogdon** [comment]
No QA Notice or warnings. Now I didn't emerge directly. I used `ebuild ... install` and then `ebuild ... qmerge`. It was easier to test that way. I suspect that using absolute paths will not work. That explains what was being used in `kpathsea` which broke things (https://bugs.gentoo.org/719272). My Prefix isn't funky is it?

**Comment by kiwifb** [comment]
I don't think your prefix is funky (at least location wise). For absolute link like in `kpathsea-6.3.1_p20190410` you should have a prefix included as you pointed out. In the second case, it is pretty much what I am suggesting above, the prefix has to be subtracted from `TEXMF_PATH` for things to work - everything is relative and stays inside the prefix.

**Comment by strogdon** [comment]
I meant relative above instead of absolute. I never did try what you had originally suggested.

**Comment by strogdon** [comment]
I will run again with your suggestion.

**Comment by strogdon** [comment]
Perhaps a syntax problem. I didn't trouble shoot things first. I get
```
/storage/strogdon/gentoo-rap/var/tmp/portage/sci-mathematics/sage-9999/work/sage-9999/src-python3_7
/storage/strogdon/gentoo-rap/var/tmp/portage/sci-mathematics/sage-9999/temp/environment: line 4416: ../../../../../${$(python_get_sitedir)#"${EPREFIX}"}/sage/ext_data/notebook-ipython/logo-64x64.png: bad substitution
```

**Comment by strogdon** [comment]
This is line 4416
```
    dosym ../../../../../${$(python_get_sitedir)#"${EPREFIX}"}/sage/ext_data/notebook-ipython/logo-64x64.png /usr/share/jupyter/kernels/sagemath/logo-64x64.png;
```

**Comment by kiwifb** [comment]
Yes, that's what I said just after it should be something like this
```
P_SITEDIR=$(python_get_sitedir)
dosym ../../../../../${P_SITEDIR#"${EPREFIX}"}/sage/ext_data/notebook-ipython/logo-64x64.png /usr/share/jupyter/kernels/sagemath/logo-64x64.png;
```
because you are supposed to do it on a variable. Not the result of bash function. There may be another way for that (you could do it with `sed` I am sure).

**Comment by kiwifb** [comment]
I have just gone ahead and made what I think is a fix in sage-9999. Let me know if it works for you.

**Comment by strogdon** [comment]
I should have tried using a variable for `$(python_get_sitedir)` but wasn't absolutely sure a variable was needed (actually I believe I've dealt with this sort of things previously). This now works. I suppose absolute paths could break things, especially in Prefix. Just FYI, with this COVID thing I may loose access to the machine that hosts Prefix. So far I have been lucky. But if it goes down due to whatever I will not be able to reboot it. And, as far as I know, no one is able to access it. If someone does have access it will probably be a custodial individual who won't have a clue about things. I'm surprised they haven't turned the power off.

**Comment by strogdon** [comment]
Just a cosmetic thing that I don't believe would ever cause an issue. There is an extra `/` before `usr`.
```
$ ls -al ~/usr/share/jupyter/kernels/sagemath/logo-*
lrwxrwxrwx 1 strogdon math 93 Apr 27 11:41 /storage/strogdon/gentoo-rap/usr/share/jupyter/kernels/sagemath/logo-64x64.png -> ../../../../..//usr/lib/python3.7/site-packages/sage/ext_data/notebook-ipython/logo-64x64.png
```

**Comment by kiwifb** [comment]
Yes, it is hard to get rid of that one extra `/`. For the record, the main development machine for sage-on-gentoo is on campus and I have been confined since March 25. Of course, I have some machines at home that could be used to take over. But yes it is lucky we didn't have a power cut.
