### ISSUE TITLE
package.use/sage is missing gcc[fortran] useflag

### ISSUE THREAD

**Issue by ss23** [cschwan/sage-on-gentoo#586]
I'm doing a install from scratch, and gcc requires the fortran useflag for the installation to proceed. I imagine if it's required in the default setting, it might be useful to add it to `package.use/sage`.

I've created this as an issue rather than a pull request because I'm not really sure if that really is the case though.

**Comment by kiwifb** [comment]
I installed a system from scratch last month (lost a disk) and `fortran` was on by default. However it doesn't hurt. You cannot do any lapack stuff without fortran.

**Comment by ss23** [comment]
@kiwifb My system is quite old, so it may have different defaults, but this is my first time installing sage.
Would you like me to make a quick PR for this?

**Comment by kiwifb** [comment]
I'll add it myself. Don't worry.

**Comment by kiwifb** [comment]
And done.
