### ISSUE TITLE
Compile errors during installation of sage

### ISSUE THREAD

**Issue by ss23** [cschwan/sage-on-gentoo#587]
During installation of Sage, I recieve an error during compilation. Due to the large amount of output, I've attached a file with the build log. I'm not sure which part(s) are relevant.
They all seem to be related to cypari2, e.g.: `'cypari2/paridecl/hyperellratpoints.pxd' not found`.
[build.log.txt](https://github.com/cschwan/sage-on-gentoo/files/4539061/build.log.txt)

**Comment by kiwifb** [comment]
This starts much earlier. Is `auto_paridecl.pxd` properly installed in `cypari2`? If it is, there is something preventing it from being found.

**Comment by ss23** [comment]
`/usr/lib64/python3.6/site-packages/cypari2` on my system contains `paridecl.pxd`, but not `auto_paridecl.pxd`. I presume that's where it's looking?

**Comment by kiwifb** [comment]
Yes.

**Comment by ss23** [comment]
I can take a look at how `cypari2` works, but I'm not sure I'm well positioned to be able to investigate it. Is there anything else that you might find useful to help determine what's going on? I'm happy to provide further output/logs if it'll help.

**Comment by kiwifb** [comment]
First is `pari[doc]` installed. If so, then rebuild cypari2 and send me a log.

**Comment by ss23** [comment]
`[ebuild   R   ~] sci-mathematics/pari-2.11.4:0/6::gentoo  USE="data doc gmp -X -fltk -test -threads" 0 KiB`

I'll get the logs for cypari2 now.

**Comment by ss23** [comment]
[cypari2-build.log](https://github.com/cschwan/sage-on-gentoo/files/4539133/cypari2-build.log)

**Comment by kiwifb** [comment]
No need, I can reproduce it. I bet it is a recent changes that already caused problem with numpy. Some files are not shipped when they shouldn't.

**Comment by ss23** [comment]
@kiwifb Thanks for all your help on this. This should be the last thing to get fixed before my sage install is working. And to think, on the last night of level 4 lockdown! I appreciate all the effort you're putting in maintaining sage on Gentoo 😄

**Comment by kiwifb** [comment]
Was hoping to steal the fix from numpy but it doesn't work. I believe it may be a recent change in python build system or setuptools. I may not be able to fix it during level 4 lock down :(

**Comment by kiwifb** [comment]
There is a subtle packaging mistake that I have to find out how to fix. The file is not moved to the build location by "build", only during "install" if you don't use "--skip-build". Which is obviously silly. On the other hand it worked fine with setuptools 40. It seems to have broken with either version 42 or 44.

**Comment by kiwifb** [comment]
And after digging around I found what I think is the easiest way to achieve things. Sync and merge cypari2 again and it should be right.

**Comment by ss23** [comment]
Perfect! Sage is working and installed now. Thanks for all your help.
