### ISSUE TITLE
Stable cython update is blocked by sage

### ISSUE THREAD

**Issue by ngg** [cschwan/sage-on-gentoo#592]
Upstream Gentoo has stabilized `=dev-python/cython-0.29.20-r2`, but sage requires `<dev-python/cython-0.29.20` :(

**Comment by kiwifb** [comment]
Yes, getting support for that version of cython requires a patch that is not in any released version of sage - yet (coming in the next beta). Is it that important that I should include it in 9.1?

**Comment by kiwifb** [comment]
I'll be away until Monday (New Zealand time). Don't expect any action until then.

**Comment by dimpase** [comment]
Sage upstream is still on Cython 0.29.17.  (only since May, https://trac.sagemath.org/ticket/29480)
You are welcome to open a Sage ticket (you can use your GitHub account to log in) to ask for an update, and
please leave a note on https://trac.sagemath.org/ticket/29480 if you did.

**Comment by kiwifb** [comment]
@dimpase he complains that it cannot use cython-0.29.20 with the sage ebuilds I have in overlay. I haven't allowed the use of cython-0.29.20 because of https://trac.sagemath.org/29867. Without it sage doesn't even start if you use cython-0.29.20. 

Allowing it would mean for me to backport trac#29867 to 9.1. It should be in 9.2.beta4.

**Comment by ngg** [comment]
I think it would be great to include the patch from https://trac.sagemath.org/ticket/29867 in the sage ebuild. `=dev-python/pandas-1.0.4` is also stable now and explicitly requires `>=dev-python/cython-0.29.20-r1`, making these requirements conflict.

**Comment by major-profundis** [comment]
Portage will try to install `=dev-python/pandas-0.24.2` when you try to do a fresh install of sage, which will break things (it doesn't even compile on my machine). You have to unmask `=dev-python/pandas-1.0.1` and mask `>=dev-python/pandas-1.0.4` until this is fixed if you want to install sage.

**Comment by kiwifb** [comment]
I am back. I will backport because I have a lot of catch up to do in the 9999 branch. Not unexpected but it all happened, almost all at once, very suddenly while I was away.

**Comment by kiwifb** [comment]
OK, re-open if there is a problem. Sorry for the long delay.

**Comment by ngg** [comment]
Seems to work for me, thanks for the fix.
