### ISSUE TITLE
!!! ERROR: No module named 'portage_dep' when installing sage-jmol-bin

### ISSUE THREAD

**Issue by strogdon** [cschwan/sage-on-gentoo#594]
I see this for all available `sage-jmol-bin`. Everything does install, apparently correctly. Any idea the source?

**Comment by kiwifb** [comment]
It has to come from the java-pkg-2 eclass or one of the eclasses it inherits from. Looking into it ASAP.

**Comment by kiwifb** [comment]
I cannot seem to reproduce it. Portage version? Does it happen with anything else that you can easily test? Full log of the install please.

**Comment by strogdon** [comment]
```
eix -I sys-apps/portage
[I] sys-apps/portage
     Available versions:  2.3.99-r2 2.3.103 ~3.0.0-r1 **9999*l {apidoc build doc gentoo-dev +ipc +native-extensions +rsync-verify selinux xattr KERNEL="linux" PYTHON_TARGETS="pypy3 python3_6 python3_7 python3_8 python3_9"}
     Installed versions:  2.3.103(02:22:11 AM 07/26/2020)(ipc native-extensions rsync-verify xattr -apidoc -build -doc -gentoo-dev -selinux KERNEL="linux" PYTHON_TARGETS="python3_7 -pypy3 -python3_6 -python3_8 -python3_9")
     Homepage:            https://wiki.gentoo.org/wiki/Project:Portage
     Description:         Portage is the package management and distribution system for Gentoo
```
The `build.log` is unremarkable.
```
 * Package:    sci-chemistry/sage-jmol-bin-14.29.52
 * Repository: sage-on-gentoo
 * Maintainer: frp.bissey@gmail.com
 * USE:        abi_x86_64 amd64 elibc_glibc kernel_linux userland_GNU
 * FEATURES:   network-sandbox preserve-libs sandbox userpriv usersandbox
 * Package:    sci-chemistry/sage-jmol-bin-14.29.52
 * Repository: sage-on-gentoo
 * Maintainer: frp.bissey@gmail.com
 * USE:        abi_x86_64 amd64 elibc_glibc kernel_linux userland_GNU
 * FEATURES:   network-sandbox preserve-libs sandbox userpriv usersandbox
>>> Unpacking source...
>>> Unpacking Jmol-14.29.52-binary.tar.gz to /var/tmp/portage/sci-chemistry/sage-jmol-bin-14.29.52/work
>>> Source unpacked in /var/tmp/portage/sci-chemistry/sage-jmol-bin-14.29.52/work
>>> Preparing source in /var/tmp/portage/sci-chemistry/sage-jmol-bin-14.29.52/work/jmol-14.29.52 ...
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/sci-chemistry/sage-jmol-bin-14.29.52/work/jmol-14.29.52 ...
>>> Source configured.
>>> Compiling source in /var/tmp/portage/sci-chemistry/sage-jmol-bin-14.29.52/work/jmol-14.29.52 ...
>>> Source compiled.
>>> Test phase [not enabled]: sci-chemistry/sage-jmol-bin-14.29.52

>>> Install sci-chemistry/sage-jmol-bin-14.29.52 into /var/tmp/portage/sci-chemistry/sage-jmol-bin-14.29.52/image/
!!! ERROR: No module named 'portage_dep'
!!! ERROR: No module named 'portage_dep'
>>> Completed installing sci-chemistry/sage-jmol-bin-14.29.52 into /var/tmp/portage/sci-chemistry/sage-jmol-bin-14.29.52/image/

 * Final size of build directory: 152440 KiB (148.8 MiB)
 * Final size of installed tree:   98108 KiB ( 95.8 MiB)
```

**Comment by kiwifb** [comment]
I thought it was the eclass but it looks more like something happening in portage itself.

**Comment by strogdon** [comment]
On Wed, 12 Aug 2020 16:17:41 -0700
François Bissey <notifications@github.com> wrote:

> I cannot seem to reproduce it. Portage version? Does it happen with
> anything else that you can easily test? Full log of the install
> please.
> 

This is the first time I have ever seen this.

**Comment by kiwifb** [comment]
This is weird, I see this post forum: https://forums.gentoo.org/viewtopic-t-673844-start-0.html which looks exactly like your error but portage doesn't have a file `portage_dep.py` anymore as far as I know and it is from 2008. And there is no such file on my system. All I can think after that is an issue in java-config.

**Comment by strogdon** [comment]
Are you able to build `commons-cli-1.3.1`? It fails here with `Failed to determine VM for building` and with the same error
```
 * commons-cli-1.3.1-src.tar.gz BLAKE2B SHA512 size ;-) ...              [ ok ]
 * checking ebuild checksums ;-) ...                                     [ ok ]
 * checking miscfile checksums ;-) ...                                   [ ok ]
!!! ERROR: No module named 'portage_dep'
 * Unable to determine VM for building from dependencies:
```

**Comment by kiwifb** [comment]
Here I have
```
 * commons-cli-1.3.1-src.tar.gz BLAKE2B SHA512 size ;-) ...                                                                                                                 [ ok ]
 * checking ebuild checksums ;-) ...                                                                                                                                        [ ok ]
 * checking miscfile checksums ;-) ...                                                                                                                                      [ ok ]
 * Using: icedtea-bin-8
>>> Unpacking source...
```
so your java install is somehow broken.

**Comment by strogdon** [comment]
That's what I suspected.

**Comment by kiwifb** [comment]
```
java-config -L
The following VMs are available for generation-2:
*)      IcedTea JDK 3.16.0 [icedtea-bin-8]
```
?

**Comment by strogdon** [comment]
java-config -L
The following VMs are available for generation-2:
*)      AdoptOpenJDK 8.252_p09 [openjdk-bin-8]

but  openjdk-bin-8 line "flashes".

**Comment by kiwifb** [comment]
Hum, feels like a broken symlink. eix tells me the only version currently available in that slot is 8.265_p01 may be just updating openjdk-bin will fix it.

**Comment by strogdon** [comment]
Everything is fine with `icedtea-bin-3.16.0`. I still get the "flashing" running `java-config -L` so it must not be important. Something is buggy with `openjdk-bin`. I did upgrade to `8.265_p01` without success. Not really a s-o-g issue. I'll leave open for a day or so. Perhaps I'll resolve things.

**Comment by strogdon** [comment]
Perhaps a linking issue? Installed `icedtea-bin`, switched `java-vm` to it and all was well. I then switched `java-vm` to `openjdk-bin` and now it works? Strange. When `openjdk-bin` did not work without `icedtea-bin` installed I unstalled it and reinstalled without success. So maybe `eselect java-vm` needs companion `java-vm` in order to properly set the `java-vm`?
