### ISSUE TITLE
sage-9.1-r2 and sympy

### ISSUE THREAD

**Issue by welele08** [cschwan/sage-on-gentoo#598]
sage-9.1-r2 depends on simply-1.5*, which is removed from gentoo official portage tree

emerge sage end with an unresolved dependancy to sympy-1.5*.

**Comment by kiwifb** [comment]
Thanks for the notice. I have to check if anything needs backporting for sympy 1.6.

**Comment by kiwifb** [comment]
It needs a couple of things but nothing too complicated.

**Comment by kiwifb** [comment]
Fixed by 7981be2da636d5d6bf99fdb2cd0474a9e0d74818

**Comment by welele08** [comment]
you're welcome!
