### ISSUE TITLE
sci-mathematics/singular and PYTHON_COMPAT=( python2_7 )

### ISSUE THREAD

**Issue by welele08** [cschwan/sage-on-gentoo#599]
sci-mathematics/singular Ebuild use a PYTHON_COMPAT=( python2_7 ) while python2_7 is currently getting away from gentoo. Is a python3_7 possible?

**Comment by kiwifb** [comment]
Not currently. Note that building python (2.7) bindings is not useful to sage. It is perfectly OK to build singular with `USE=-python`. I will probably just disable the flag at some point.

**Comment by kiwifb** [comment]
I have now removed the flag in all the most recent version of singular (4.1.3_p2+). There is currently no obvious effort upstream to move to a more recent version of python.
