### ISSUE TITLE
sci-mathematics/sage-9.1-r3 and sci-mathematics/giac-1.6.0.7 ?

### ISSUE THREAD

**Issue by welele08** [cschwan/sage-on-gentoo#600]
Is giac 1.5 a hard needed dependancy (as stated in ebuild) or can sage be built over giac 1.6.0.7?

**Comment by kiwifb** [comment]
There are various issues with 1.6. It technically builds - I think. Runtime is when things get fun. I also have an issue where giac-1.6 fails its test suite when calling pari in one test. Upstream is investigating.

**Comment by welele08** [comment]
Thanks for you're quick answer!

**Comment by kiwifb** [comment]
Question answered, and the answer holds for now. Closing.
