### ISSUE TITLE
Use of deprecated API for dev-python/jedi-0.17.2-r1 in sage-9.1-r3 (python 3.7.8)

### ISSUE THREAD

**Issue by g-regex** [cschwan/sage-on-gentoo#606]
Hi!

I am running sage version 9.1-r3 (compiled quite recently) and I am getting Deprecation Warnings, when trying to use autocomplete. E.g. when typing a-TAB, I get the following error:

```
/usr/lib/python3.7/site-packages/jedi/api/__init__.py:859: DeprecationWarning: Providing the line is now done in the functions themselves like `Script(...).complete(line, column)`
  project=Project(os.getcwd()), **kwds)
/usr/lib/python3.7/site-packages/jedi/api/__init__.py:859: DeprecationWarning: Providing the column is now done in the functions themselves like `Script(...).complete(line, column)`
  project=Project(os.getcwd()), **kwds)
/usr/lib/python3.7/site-packages/jedi/cache.py:111: DeprecationWarning: Deprecated since version 0.16.0. Use get_signatures()[...].params
  result = method(self, *args, **kwargs)
```

When turning off the warnings everything (including autocompletion) works just fine though:
```
sage: warnings.simplefilter("ignore", category=DeprecationWarning)
```

Sage was compiled with python 3.7 support only and the following USE-flags:
```
[ebuild   R   ~] sci-mathematics/sage-9.1-r3::sage-on-gentoo  USE="X doc-html-bin jmol -bliss -debug -doc-html -doc-pdf -doc-pdf-bin -latex -testsuite" L10N="en -ca -de -es -fr -hu -it -ja -pt -ru -tr" PYTHON_TARGETS="python3_7 -python3_6" 0 KiB
```
jedi was compiled with the following USE-flags:
```
[ebuild   R    ] dev-python/jedi-0.17.2-r1::gentoo  USE="-doc -test" PYTHON_TARGETS="python3_6 python3_7 -python3_8 (-python3_9)" 0 KiB
```

I've been searching through the known issues, but I couldn't find anything related to this. Any idea, whether there is a fix for this?

**Comment by kiwifb** [comment]
It has been noted by Antonio rojas from Arch on the sage tracker, I am sure. Those are caused by using jedi 0.17 over previous jedi. jedi was introduced by the use of ipython 7. I cannot really figure which follow up ticket dealt with that right now.

Fortunately, sage 9.2 is finally coming soon and will take care of many such issues.

**Comment by kiwifb** [comment]
Currently sage just turn off the warnings https://trac.sagemath.org/ticket/29774

**Comment by slel** [comment]
For more possibly related tickets:
- https://trac.sagemath.org/query?order=id&desc=1&summary=~jedi
- https://trac.sagemath.org/query?order=id&desc=1&description=~jedi

**Comment by kiwifb** [comment]
Thanks @slel but there is nothing new in there. No one seems to currently work on fixing this properly.

**Comment by g-regex** [comment]
Thanks for the replies. Since everything seems to work fine for the moment I will also just turn off the warnings for now and wait for sage 9.2.

**Comment by g-regex** [comment]
Upgrading to Sage 9.2 fixed this.
