### ISSUE TITLE
arb-2.17.0 fails to build: fatal error: flint/config.h: No such file or directory

### ISSUE THREAD

**Issue by strogdon** [cschwan/sage-on-gentoo#611]
This is for `arb-2.17.0` from either portage or sage-on-gentoo. `flint-2.6.3` is installed. `flint-2.5.2-r1` does provide `config.h` but not `flint-2.6.3`. There a `config.h.in` but perhaps configure in not generating `config.h`?

**Comment by kiwifb** [comment]
I am fairly sure you need `arb-2.18+` for `flint-2.6+`. I'll fix keywords ASAP.

**Comment by kiwifb** [comment]
Ok keywording of arb-2.18* and making sure sage-9999 depends on it done. Sync and try again.

**Comment by strogdon** [comment]
OK, `arb-2.18` does install. Thanks
