### ISSUE TITLE
Update README to include directions for eselect/repository

### ISSUE THREAD

**Issue by derekperrin** [cschwan/sage-on-gentoo#621]
From what I can tell, the preferred way of adding overlays in Gentoo is to use eselect/repository if possible. Is it worth updating the documentation to include how to do this using eselect in addition to layman?

**Comment by kiwifb** [comment]
I have been using Gentoo for a long time time, which means I tend to be old school :) do go ahead with this. A spruce up to current trends is nice.

**Comment by kiwifb** [comment]
Well, there is a bit more work to do on the Readme itself but I hope my recent changes cover exactly what you asked :)
