### ISSUE TITLE
JRE "Out of Memory Error" when running doctests

### ISSUE THREAD

**Issue by strogdon** [cschwan/sage-on-gentoo#622]
I have lots of Jave Runtime errors when testing sog `9.3.beta5`. They were not present, as far as I  know, with `9.3.beta4`. I also have this with vanilla and it's been present there for some time. I hadn't noticed it because there was no apparent failure. In any event this is fairly new. The head of `hs_err_pidxxxxx.log`
```
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (malloc) failed to allocate 32744 bytes for ChunkPool::allocate
# Possible reasons:
#   The system is out of physical RAM or swap space
#   The process is running with CompressedOops enabled, and the Java Heap may be blocking the growth of the native heap
# Possible solutions:
#   Reduce memory load on the system
#   Increase physical memory or swap space
#   Check if swap backing store is full
#   Decrease Java heap size (-Xmx/-Xms)
#   Decrease number of Java threads
#   Decrease Java thread stack sizes (-Xss)
#   Set larger code cache with -XX:ReservedCodeCacheSize=
#   JVM is running with Unscaled Compressed Oops mode in which the Java heap is
#     placed in the first 4GB address space. The Java Heap base address is the
#     maximum limit for the native heap growth. Please use -XX:HeapBaseMinAddress
#     to set the Java Heap base and to place the Java Heap above 4GB virtual address.
# This output file may be truncated or incomplete.
#
#  Out of Memory Error (allocation.cpp:272), pid=10038, tid=0x00007fac05265640
#
# JRE version: OpenJDK Runtime Environment (8.0_272-b10) (build 1.8.0_272-b10)
# Java VM: OpenJDK 64-Bit Server VM (25.272-b10 mixed mode linux-amd64 compressed oops)
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
```

**Comment by kiwifb** [comment]
The only thing I know for sure that calls java is our friend `jmol`. If it is new, then some new plots must be involved. I'll note that vanilla is seriously working on dumping `jmol`, I wouldn't even be too surprised if we got it optional in 9.3.

**Comment by strogdon** [comment]
I know you are officially away so no need to answer. I thought of `jmol` and I knew it could possibly be optional, but if I recall, it's needed for the pdf docs?

**Comment by kiwifb** [comment]
Yes, I gave myself until tomorrow to answer :) anyway most 3D plots in html and pdf doc are done through jmol which is the default plotter. threejs has a problem that you cannot do non interactive saving to a file. But jsmol may just bring all the functionality of jmol without java - although since it is javascript I am not sure how it works without at least a web-broswer in the background.

**Comment by strogdon** [comment]
This is preliminary, I need to run the full doctests again. There is a JRE issue somewhere in `sage/categories` with `tp -2`. I have 4 threads. There are no issue with `tp -1`. This is with `openjdk-bin:8`. I switched to `icedtea-bin:3` and there are no JRE issue with `tp -5`.

**Comment by strogdon** [comment]
Corrected: above it should have been `icedtea-bin:8`. Doctests completed using `tp -5` without a JRE issue when selecting `java-vm` to be `icedtea-bin-8`. Not sure what has changed. I wonder what other distos use?

**Comment by kiwifb** [comment]
I believe there is a slow move to `openjdk` but debian may still be shipping `icedtea` by default since they tend to stick to their own produced binaries.

**Comment by strogdon** [comment]
`icedtea-bin` is not the complete solution with `vanilla` sage, although there appears to be fewer failures than with `openjdk-bin`. From the failure log
```
Internal exceptions (2 events):
Event: 0.072 Thread 0x00007fa65000a000 Exception <a 'java/lang/NoSuchMethodError': Method sun.misc.Unsafe.defineClass(Ljava/lang/String;[BII)Ljava/lang/Class; name or signature does not match> (0x00000000dda07cc8) thrown at [/var/tmp/portage/dev-java/icedtea-3.16.0/work/icedtea-3.16.0/openjdk/
Event: 0.072 Thread 0x00007fa65000a000 Exception <a 'java/lang/NoSuchMethodError': Method sun.misc.Unsafe.prefetchRead(Ljava/lang/Object;J)V name or signature does not match> (0x00000000dda07fb0) thrown at [/var/tmp/portage/dev-java/icedtea-3.16.0/work/icedtea-3.16.0/openjdk/hotspot/src/share/
```
Not sure what the following means
```
vm_info: OpenJDK 64-Bit Server VM (25.252-b09) for linux-amd64 JRE (1.8.0_252-b09), built on May 10 2020 20:29:23 by "portage" with gcc 9.2.0
```

**Comment by kiwifb** [comment]
Feels like a language version mismatch. That kind of error is usually thrown when the arguments of a function are not the expected number, or the expected type. Because java, like C++ is object oriented, you can have function polymorphism, a same name can refer to slightly different methods depending on the arguments and the return type. The way to figure out which method is used is to compare so called "signature" of the different methods and the one you are trying to call.

So, because java is based on a runtime, I think something is missing compared to the version the program was written for.

**Comment by strogdon** [comment]
Installed `openjdk` instead of `openjdk-bin` and I see no `JRE` failures when testing vanilla. I'll now try with s-o-g. It was a chore to build `openjdk`. There was a filesize mismatch in downloading `openjdk-8.272_p10.tar.bz2`.

**Comment by kiwifb** [comment]
That was brave to build `openjdk`. The fact that the errors are linked to minor version differences is also quite worrying.

**Comment by strogdon** [comment]
It's taken a while. Testing s-o-g with `openjdk` seems good. No `JRE` issues. The `openjdk-bin` above seems to have been build with `gcc-9.2`? That plus your comments prompted the build of `openjdk`. Since `openjdk` seems to work here for now (cross fingers) I will not try to build `icedtea` since it is not stable.

**Comment by strogdon** [comment]
When s-o-g `9.3.beta6` is available I will run doctests with system built `openjdk`. But on vanilla `9.3.beta6` I get
```
----------------------------------------------------------------------
All tests passed!
----------------------------------------------------------------------
Total time for all tests: 7022.5 seconds
    cpu time: 24431.2 seconds
    cumulative wall time: 34315.8 seconds
```
which is encouraging.

**Comment by kiwifb** [comment]
I cannot currently build sage from sage-on-gentoo because of sandbox violation from jmol.
```
F: mkdir
S: deny
P: /var/lib/portage/home/.java
A: /var/lib/portage/home/.java
R: /var/lib/portage/home/.java
C: /opt/icedtea-bin-3.16.0/bin/java -Xmx512m -Djava.awt.headless=true -jar /usr/share/sage-jmol-bin/lib/JmolData.jar -iox -g 500x500 -J set defaultdirectory "/dev/shm/portage/sci-mathematics/sage-9999/homedir/.sage/temp/localhost/6946/dir_jizvbnht/scene.spt.zip"
script SCRIPT
 -j write PNG '/dev/shm/portage/sci-mathematics/sage-9999/homedir/.sage/temp/localhost/6946/dir_jizvbnht/preview.png'
```
times as many 3D plots probably. This is probably a bug in the java handling mechanism or something that need to be set.

**Comment by strogdon** [comment]
Which branch are you using?

**Comment by kiwifb** [comment]
vbraun, so I am a bit ahead but I suspect the issue is outside sage-on-gentoo and it has actually been going for a while but this is the first time I have been affected as root. So I suspect this is a java configuration problem, I have seen similar issues in bugzilla, https://bugs.gentoo.org/762619 has a strikingly similar sandbox problem.

**Comment by strogdon** [comment]
I tried to build the `vbraun` branch and `dev-python/cypari2-2.1.2` would not build. Problems locating a bunch of `.pxd` files as
```
from __future__ import absolute_import, division, print_function

from cysignals.signals cimport sig_on, sig_off, sig_block, sig_unblock, sig_error
^
------------------------------------------------------------

cypari2/closure.pyx:36:0: 'cysignals/signals.pxd' not found
```
Did you do anything special? Perhaps I should just wait.

**Comment by kiwifb** [comment]
I'll need a more complete log. And no, I didn't need to do anything special.

**Comment by strogdon** [comment]
Are you using just `python3.8`? The failure here is with `python3.9`. The build using `python3.8`, I suppose for building in parallel, did not complete.

**Comment by kiwifb** [comment]
I have built with python 3.7, 3.8 and 3.9. It shouldn't build in parallel.

**Comment by strogdon** [comment]
I tried separately with each python (3.8 and 3.9). It builds with `python3.8` but not with `python3.9`. The parallel build terminated because of the `python3.9` failure and the build with `python3.8` was not complete. I'll send the build log which is not very long.

**Comment by strogdon** [comment]
I think `cysignals` was not built for `python3.9`!

**Comment by kiwifb** [comment]
That would explain it. But why did it not build it as a dependency. Looking at the ebuild.

**Comment by kiwifb** [comment]
Hum, dependencies in the cypari2 ebuilds are not correct and I am not sure why. I'll get it fixed shortly.

**Comment by kiwifb** [comment]
Dependency problems in cypari2 fixed. Inspecting others.

**Comment by kiwifb** [comment]
OK, embarrassing missing python dependencies have been fixed.

**Comment by strogdon** [comment]
I've been able to build the `vbraun` branch without issue.

**Comment by strogdon** [comment]
I should mention that the `html-doc` and `pdf-docs` were also built.

**Comment by kiwifb** [comment]
Whatever I try, I still get sandbox violations around here. I wonder if I got cruft somewhere causing this.

**Comment by strogdon** [comment]
I'm not using a ramdisk. I don't have enough ram. I wouldn't think that would be an issue?

**Comment by kiwifb** [comment]
That would be a new one. I am going to try openjdk to see if it behaves better.

**Comment by strogdon** [comment]
Of topic, not JRE related:

I have one doctest failure with `9.3.beta6` (vbraun branch) that was not in `9.3.beta5` that seems odd
```
sage -t --long --random-seed=0 usr/lib/python3.8/site-packages/sage/libs/ecl.pyx  # Timed out (and interrupt failed)
```
When run individually, it runs `forever` and just fails.

**Comment by kiwifb** [comment]
Definitely odd.

**Comment by kiwifb** [comment]
Using `--verbose` may help figure out where it stops.

**Comment by strogdon** [comment]
I think the location of the failure varies. When doctesting I see
```
sage -t --long --random-seed=0 usr/lib/python3.8/site-packages/sage/libs/ecl.pyx
    Timed out (and interrupt failed)
**********************************************************************
Tests run before process (pid=26592) timed out:
sage: from sage.libs.ecl import test_sigint_before_ecl_sig_on ## line 121 ##
sage: test_sigint_before_ecl_sig_on() ## line 122 ##
sage: sig_on_count() # check sig_on/off pairings (virtual doctest) ## line 126 ##
0
sage: from sage.libs.ecl import test_ecl_options ## line 143 ##
sage: test_ecl_options() ## line 144 ##
ECL_OPT_INCREMENTAL_GC = 0
ECL_OPT_TRAP_SIGSEGV = 1
ECL_OPT_TRAP_SIGFPE = 1
ECL_OPT_TRAP_SIGINT = 1
ECL_OPT_TRAP_SIGILL = 1
ECL_OPT_TRAP_SIGBUS = 1
ECL_OPT_TRAP_SIGPIPE = 1
ECL_OPT_TRAP_INTERRUPT_SIGNAL = 1
ECL_OPT_SIGNAL_HANDLING_THREAD = 0
ECL_OPT_SIGNAL_QUEUE_SIZE = 16
ECL_OPT_BOOTED = 1
ECL_OPT_BIND_STACK_SIZE = 8192
ECL_OPT_BIND_STACK_SAFETY_AREA = 1024
ECL_OPT_FRAME_STACK_SIZE = 2048
ECL_OPT_FRAME_STACK_SAFETY_AREA = 128
ECL_OPT_LISP_STACK_SIZE = 32768
ECL_OPT_LISP_STACK_SAFETY_AREA = 128
ECL_OPT_C_STACK_SIZE = 0
ECL_OPT_C_STACK_SAFETY_AREA = 32768
ECL_OPT_HEAP_SIZE = 4294967296
ECL_OPT_HEAP_SAFETY_AREA = 1048576
ECL_OPT_THREAD_INTERRUPT_SIGNAL = 36
ECL_OPT_SET_GMP_MEMORY_FUNCTIONS = 0
sage: sig_on_count() # check sig_on/off pairings (virtual doctest) ## line 168 ##
0
sage: from sage.libs.ecl import * ## line 226 ##
sage: init_ecl() ## line 231 ##
sage: sig_on_count() # check sig_on/off pairings (virtual doctest) ## line 235 ##
0
sage: from sage.libs.ecl import * ## line 321 ##
sage: from cysignals.tests import interrupt_after_delay ## line 322 ##
sage: ecl_eval("(setf i 0)") ## line 323 ##
<ECL: 0>
sage: inf_loop = ecl_eval("(defun infinite() (loop (incf i)))") ## line 325 ##
sage: interrupt_after_delay(1000) ## line 326 ##
sage: inf_loop() ## line 327 ##

**********************************************************************
```
I don't have the result when doctesting individually, but was at a different location.

**Comment by strogdon** [comment]
It may be an obscure failure. I just tested again and the doctest passed
```
sage -t --long --warn-long 132.3 --random-seed=0 usr/lib/python3.8/site-packages/sage/libs/ecl.pyx
    [204 tests, 1.74 s]
----------------------------------------------------------------------
All tests passed!
----------------------------------------------------------------------
Total time for all tests: 1.8 seconds
    cpu time: 2.1 seconds
    cumulative wall time: 1.7 seconds
```
It is strange.

**Comment by strogdon** [comment]
Running the `ecl.pyx` doctest  a number of times it eventually hangs. When that happens I have several `sage` processes
```
terry     7101     1  0 21:56 pts/25   00:00:00 /storage/strogdon/gentoo-rap/usr/bin/python3.8 /storage/strogdon/gentoo-rap/usr/lib/python-exec/python3.8/sage-cleaner
terry     7282  6719  1 21:57 pts/25   00:00:02 /storage/strogdon/gentoo-rap/usr/bin/python3.8 /storage/strogdon/gentoo-rap/usr/lib/python-exec/python3.8/sage-runtests --long --warn-long 132.3 --random-seed=0 usr/lib/python3.8/site-packages/sage/libs/ecl.pyx
terry     7284  7282  0 21:57 pts/25   00:00:00 [sage-cleaner] <defunct>
terry     7293  7282  1 21:57 pts/25   00:00:01 /storage/strogdon/gentoo-rap/usr/bin/python3.8 /storage/strogdon/gentoo-rap/usr/lib/python-exec/python3.8/sage-runtests --long --warn-long 132.3 --random-seed=0 usr/lib/python3.8/site-packages/sage/libs/ecl.pyx
```
Perhaps `sage-cleaner` is not doing its job.

**Comment by kiwifb** [comment]
What about `ecl` processes? There could be a lisp instance hanging for whatever reason.

**Comment by strogdon** [comment]
It takes a number of tries before it hangs and I don't see any `ecl` processes. Only that the doctest appears twice as above. And when it finally exits it is as [above](https://github.com/cschwan/sage-on-gentoo/issues/622#issuecomment-764440941)

**Comment by strogdon** [comment]
This has all been with the current `vbraun` branch. Is `master` in sync with `9.3.beta6`?

**Comment by kiwifb** [comment]
Yes, master is in sync with 9.3.beta6 with the exception to the cypari2 dependency I think. Which shouldn't have any impact.

**Comment by kiwifb** [comment]
For the record, I have now enabled py3.9 in the vbrun branch and I am able to build the documentation as a user again. Hopefully that will stick when using emerge rather than ebuild. But that definitely stinks.

**Comment by strogdon** [comment]
I just noticed that about an hour ago. I'm now trying to build sage using py3.9 on the `master` branch in prefix. The html-docs are now building.

**Comment by kiwifb** [comment]
Still failing as root :(

**Comment by strogdon** [comment]
With building `openjdk`?

**Comment by kiwifb** [comment]
No just building sage, still those sandbox violations.
```
* ACCESS DENIED:  mkdir:        /var/lib/portage/home/.java/fonts
 ```

**Comment by strogdon** [comment]
Not very clear was I. Was sage built with `openjdk` or `openjdk-bin`.

**Comment by kiwifb** [comment]
This time it was `openjdk-bin`.

**Comment by strogdon** [comment]
Sage and all docs build here with py3.9 on Prefix and on Gentoo as root. I'm using `openjdk`.

**Comment by strogdon** [comment]
If fonts need to be generated during the build of Sage where will they be located? I don't see any generated fonts here. I guess they could have been deleted.

**Comment by kiwifb** [comment]
In the normal process of things, `HOME` is set to `${PORTAGE_BUILDDIR}/homedir` during a build. So it all disappear once merged. The issue I have is that java is using `portage`'s normal home instead of following the `HOME` variable.

Do you have systemd on your gentoo system? And `acct-group/portage` and `acct-user/portage`?

**Comment by strogdon** [comment]
I do not have `systemd` installed. So `${PORTAGE_BUILDDIR}/homedir` should be something like `/var/tmp/portage/sci-mathematics/sage-9999/work/sage-9999/src-python3_9/homedir`? If so, I see no `homedir`. I still have the `work` folder available.

**Comment by kiwifb** [comment]
`/var/tmp/portage/sci-mathematics/sage-9999/homedir` actually.

**Comment by strogdon** [comment]
Ah yes, of course. However, that folder here contains no `.java` stuff.
```
# ls -al /var/tmp/portage/sci-mathematics/sage-9999/homedir
total 20
drwxr-xr-x 5 portage portage 4096 Jan 29 12:22 .
drwx------ 8 portage portage 4096 Jan 29 12:24 ..
drwxr-xr-x 3 portage portage 4096 Jan 29 11:23 .gap
drwxr-xr-x 3 portage portage 4096 Jan 29 11:22 .maxima
drwxr-xr-x 6 portage portage 4096 Jan 29 11:23 .sage
```

**Comment by kiwifb** [comment]
Anything in `/var/lib/portage/home/`?

**Comment by strogdon** [comment]
Just the hidden empty file `.keep_acct-user_portage-0`. I had, at one time, move it out of the way to see if there was a difference, but didn't notice anything.

**Comment by kiwifb** [comment]
Let's just try something different what is the output of `eselect fontconfig list`?

**Comment by strogdon** [comment]
OK. From `temp/environment`
```
declare -x SANDBOX_DEBUG="0"
declare -x SANDBOX_DENY=""
declare -x SANDBOX_PREDICT="/var/tmp/portage/sci-mathematics/sage-9999/homedir:/dev/crypto:/var/cache/man:/proc/self/coredump_filter:/dev/random:/proc/self/coredump_filter:/dev/random:/proc/self/coredump_filter:/var/cache/fontconfig:/usr/lib/python3.8:/usr/lib64/python3.8:/usr/lib/pypy2.7:/usr/lib/pypy3.6:/usr/lib/portage/pym:/usr/local:/usr/lib/python3.9:/usr/lib64/python3.9:/usr/lib/pypy2.7:/usr/lib/pypy3.6:/usr/lib/portage/pym:/usr/local"
declare -x SANDBOX_READ="/:/var/tmp/portage"
declare -x SANDBOX_VERBOSE="1"
declare -x SANDBOX_WRITE=":/dev/console:/dev/fd:/dev/full:/dev/null:/dev/ptmx:/dev/pts/:/dev/pty:/dev/shm:/dev/tts:/dev/tty:/dev/vc/:/dev/zero:/proc/self/fd:/tmp/:/usr/lib/cf:/usr/lib/conftest:/usr/lib32/cf:/usr/lib32/conftest:/usr/lib64/cf:/usr/lib64/conftest:/usr/portage/distfiles/git3-src:/usr/tmp/cf:/usr/tmp/conftest:/var/tmp/:/var/tmp/portage:/var/tmp/portage/sci-mathematics/sage-9999/homedir/.bash_history"
```
And a `.java` folder exists under `/var/tmp/portage`
```
# ls -al /var/tmp/portage/.java/fonts/
total 28
drwxr-xr-x 7 portage portage 4096 Jan 29 18:22 .
drwxr-xr-x 3 portage portage 4096 Aug 25  2017 ..
drwxr-xr-x 2 portage portage 4096 Apr 11  2018 1.8.0_144
drwxr-xr-x 2 portage portage 4096 Aug  2 22:15 1.8.0_172
drwxr-xr-x 2 portage portage 4096 Aug 10 20:06 1.8.0_252
drwxr-xr-x 2 portage portage 4096 Oct 19 00:49 1.8.0_265
drwxr-xr-x 2 portage portage 4096 Jan 29 18:23 1.8.0_272
```

**Comment by strogdon** [comment]
`eselect fontconfig list` on Gentoo
```
  [1]   09-texlive.conf *
  [2]   10-autohint.conf *
  [3]   10-hinting-full.conf *
  [4]   10-hinting-medium.conf *
  [5]   10-hinting-none.conf *
  [6]   10-hinting-slight.conf *
  [7]   10-no-sub-pixel.conf
  [8]   10-scale-bitmap-fonts.conf *
  [9]   10-sub-pixel-bgr.conf *
  [10]  10-sub-pixel-rgb.conf *
  [11]  10-sub-pixel-vbgr.conf *
  [12]  10-sub-pixel-vrgb.conf *
  [13]  10-unhinted.conf *
  [14]  11-lcdfilter-default.conf *
  [15]  11-lcdfilter-legacy.conf *
  [16]  11-lcdfilter-light.conf *
  [17]  20-unhint-small-dejavu-sans.conf
  [18]  20-unhint-small-dejavu-sans-mono.conf
  [19]  20-unhint-small-dejavu-serif.conf
  [20]  20-unhint-small-vera.conf *
  [21]  25-unhint-nonlatin.conf
  [22]  30-metric-aliases.conf *
  [23]  40-nonlatin.conf *
  [24]  42-luxi-mono.conf *
  [25]  45-generic.conf *
  [26]  45-latin.conf *
  [27]  49-sansserif.conf *
  [28]  50-user.conf *
  [29]  51-local.conf *
  [30]  57-dejavu-sans.conf
  [31]  57-dejavu-sans-mono.conf
  [32]  57-dejavu-serif.conf
  [33]  60-generic.conf *
  [34]  60-latin.conf *
  [35]  60-liberation.conf *
  [36]  61-stix.conf *
  [37]  65-fonts-persian.conf *
  [38]  65-khmer.conf *
  [39]  65-nonlatin.conf *
  [40]  69-unifont.conf *
  [41]  70-no-bitmaps.conf
  [42]  70-yes-bitmaps.conf
  [43]  80-delicious.conf *
  [44]  90-synthetic.conf *
```

**Comment by strogdon** [comment]
`eselect fontconfig list` on Prefix
```
  [1]   09-texlive.conf
  [2]   10-autohint.conf
  [3]   10-hinting-full.conf
  [4]   10-hinting-medium.conf
  [5]   10-hinting-none.conf
  [6]   10-hinting-slight.conf *
  [7]   10-no-sub-pixel.conf
  [8]   10-scale-bitmap-fonts.conf *
  [9]   10-sub-pixel-bgr.conf
  [10]  10-sub-pixel-rgb.conf
  [11]  10-sub-pixel-vbgr.conf
  [12]  10-sub-pixel-vrgb.conf
  [13]  10-unhinted.conf
  [14]  11-lcdfilter-default.conf
  [15]  11-lcdfilter-legacy.conf
  [16]  11-lcdfilter-light.conf
  [17]  20-unhint-small-dejavu-sans.conf
  [18]  20-unhint-small-dejavu-sans-mono.conf
  [19]  20-unhint-small-dejavu-serif.conf
  [20]  20-unhint-small-vera.conf *
  [21]  25-unhint-nonlatin.conf
  [22]  30-metric-aliases.conf *
  [23]  40-nonlatin.conf *
  [24]  45-generic.conf *
  [25]  45-latin.conf *
  [26]  49-sansserif.conf *
  [27]  50-user.conf *
  [28]  51-local.conf *
  [29]  57-dejavu-sans.conf
  [30]  57-dejavu-sans-mono.conf
  [31]  57-dejavu-serif.conf
  [32]  60-generic.conf *
  [33]  60-latin.conf *
  [34]  61-stix.conf
  [35]  65-fonts-persian.conf *
  [36]  65-khmer.conf
  [37]  65-nonlatin.conf *
  [38]  69-unifont.conf *
  [39]  70-no-bitmaps.conf
  [40]  70-yes-bitmaps.conf
  [41]  80-delicious.conf *
  [42]  90-synthetic.conf *
```

**Comment by kiwifb** [comment]
`/var/tmp/portage/.java` now that's different. fonconfig is a wild shot but who knows I may end up finding something in there.

I believe it works when I build as a user because somehow I have this
```
ll .java/fonts/1.8.0_272/
total 160K
drwxr-xr-x  2 fbissey fbissey 4.0K Jan 22 17:20  .
drwxr-xr-x 20 fbissey fbissey 4.0K Jan 22 17:20  ..
-rw-------  1 fbissey fbissey 152K Jan 22 17:20 'fcinfo-1-moonloop-"Gentoo"-null-en.properties'
```

**Comment by strogdon** [comment]
Can you change the protections and ownership to see if that works? For reference I have
```
ls -al .java/fonts/1.8.0_272/
total 88
drwxr-xr-x 2 portage portage  4096 Jan 29 18:32 .
drwxr-xr-x 7 portage portage  4096 Jan 29 18:22 ..
-rw------- 1 portage portage 79238 Dec  7 15:18 fcinfo-1-localhost-Linux-5.4.38-gentoo-en.properties
```
Timestamps seem a bit weird.

**Comment by kiwifb** [comment]
Yes I am trying to put it inside the portage user to see what happens.

**Comment by kiwifb** [comment]
Nope. Trying to write temporary file in the location.

**Comment by strogdon** [comment]
I don't know how Prefix deals with the `java font` issue, but I have rebuilt s-o-g and no `.java` folder is created anywhere. I have searched the entire Prefix tree.

**Comment by kiwifb** [comment]
I have patched around my issue and I am hopeful that it will be short lived as we move away from jmol.

**Comment by strogdon** [comment]
It appears, unless I read things incorrectly, that going forward (your forcejavatmp.patch) `jmol` with write temp stuff to `.sage`. If so, any idea where this is now being done? It seems that `jmol` is somewhat inconsistent. I'm just curious.

**Comment by kiwifb** [comment]
During build that would go in `/var/tmp/portage/sci-mathematics/sage-9999/homedir/.sage`. I could have made it `HOME` one way or another.

**Comment by strogdon** [comment]
OK, on Prefix with your patch a `fcinfo-1-...` file is written to `homedir/.sage/.java/fonts/1.8.0_272` which was not there previously. Apparently, not needed on vanilla or Prefix where `sandbox` may be vaguely defined.

**Comment by strogdon** [comment]
I'm not sure what component generates the `fcinfo-1-...` file but on Prefix the generation is not quite correct in that some fonts from the host appear in the file. I'm wondering whether this file is ever used.

**Comment by kiwifb** [comment]
It is supposed to be an index of fonts. But that's not obviously used by jmol when building the doc. I don't know that jmol creates it, all I know is plenty of .tmp are created and destroyed in the same folder during doc building.

**Comment by strogdon** [comment]
The `.tmp` files are interesting. Your patch can be applied to vanilla sage. The only file I see that is created is `~/.sage/.java/fonts/1.8.0_272/fcinfo-1-hp-envy-Linux-5.4.38-gentoo-en.properties`. During building the html-docs if I delete the file it is immediately recreated. But no `.tmp` files. And I have watched in `~/.sage`, `~/.sage/.java`, `~/.sage/.java/fonts` and in `~/.sage/.java/fonts/1.8.0_272` during the build. But of course this does not use portage.

**Comment by strogdon** [comment]
There are a bunch of folders created under `~/.sage/temp/'computer-name'/` that contain numerous `tmp_*` files, some of which are `.png`s.

**Comment by kiwifb** [comment]
I think we should close this now.
