### ISSUE TITLE
<sci-mathematics/gap-4.11.0" is blocking sci-mathematics/gap-core-4.11.0

### ISSUE THREAD

**Issue by derekperrin** [cschwan/sage-on-gentoo#623]
There seems to be some problem with trying to pull in multiple versions of gap. The workaround seems to be to set `backtrack=300`, but I realize that's not a permanent solution. It also causes a bunch of packages to not be installed. Unfortunately I'm not great at resolving portage errors, or I'd fix this and submit a pull request. I've attached text files of the output with and without `backtrack=300`.
[emerge_sage_with_backtrack.txt](https://github.com/cschwan/sage-on-gentoo/files/5824710/emerge_sage_with_backtrack.txt)
[emerge_sage.txt](https://github.com/cschwan/sage-on-gentoo/files/5824711/emerge_sage.txt)

Edit: This is on Gentoo unstable.

**Comment by kiwifb** [comment]
`gap` upgrades have been an issue for awhile and I have done a lot to fix it. I am hopeful that the next upgrade will be smoother (so I say at each release since `gap-4.10.1`).
That being said it feels to me that the issue is that you installed `gap` before installing sage. So you got gap-4.11.0 installed. Unfortunately, sage-9.2 is locked onto gap-4.10.2 which means you actually have to downgrade gap. A scenario I haven't planned for (hopefully it will get better).
The best way is probably to uninstall gap completely before installing sage. The instructions from https://github.com/cschwan/sage-on-gentoo/blob/master/metadata/news/2019-04-08-gap-upgrade/2019-04-08-gap-upgrade.en.txt should be helpful for that.

**Comment by derekperrin** [comment]
Unfortunately I'm getting this problem without even having gap installed. I uninstalled sage and all of its dependencies (including gap) because I was having some problems doing a world update. When trying to re-emerge sage in, I ran into the above problems. I tried to uninstall gap and gap packages using the instructions you provided there and then install sage, but I still ran into the same problem.

**Comment by kiwifb** [comment]
OK, I didn't look closely enough. The curious bits are why gap-core-4.11.0 and gap-4.10.2 both pulled. I guess it is complicated cross-dependencies in dev-gap packages even though I tried to be careful on what to depend in there.

Could you try to put `sci-mathematics/gap-core` in package.mask to see if that helps.

**Comment by derekperrin** [comment]
Here's the result of that

```
emerge -av sage

These are the packages that would be merged, in order:

Calculating dependencies... done!

!!! All ebuilds that could satisfy ">=sci-mathematics/gap-core-4.11.0" have been masked.
!!! One of the following masked packages is required to complete your request:
- sci-mathematics/gap-core-4.11.0::sage-on-gentoo (masked by: package.mask)

(dependency required by "dev-gap/tomlib-1.2.9::sage-on-gentoo" [ebuild])
(dependency required by "sci-mathematics/gap-4.10.2-r1::sage-on-gentoo[recommended_pkgs]" [ebuild])
(dependency required by "sci-mathematics/sage-9.2-r1::sage-on-gentoo" [ebuild])
(dependency required by "sage" [argument])
For more information, see the MASKED PACKAGES section in the emerge
man page or refer to the Gentoo Handbook.
```

**Comment by kiwifb** [comment]
OK, I got it now. I will have to bump gap-4.10.2 and put some limits on the values for minimal and recommended packages. portage is not smart enough to pick lower versions that satisfy all the runtime dependencies.

**Comment by kiwifb** [comment]
As a temporary work around all the ebuilds below can be put in package.mask
```
aclib/aclib-1.3.2.ebuild:RDEPEND=">=sci-mathematics/gap-core-4.11.0"
Alnuth/Alnuth-3.1.2.ebuild:RDEPEND=">=sci-mathematics/gap-core-4.11.0
AutoDoc/AutoDoc-2019.09.04.ebuild:RDEPEND=">=sci-mathematics/gap-core-4.11.0
autpgrp/autpgrp-1.10.2.ebuild:RDEPEND=">=sci-mathematics/gap-core-4.11.0"
corelg/corelg-1.54.ebuild:RDEPEND=">=sci-mathematics/gap-core-4.11.0
crypting/crypting-0.10.ebuild:DEPEND=">=sci-mathematics/gap-core-4.11.0"
digraphs/digraphs-1.1.1.ebuild:DEPEND=">=sci-mathematics/gap-core-4.11.0
factint/factint-1.6.3.ebuild:RDEPEND=">=sci-mathematics/gap-core-4.11.0
GAPDoc/GAPDoc-1.6.3.ebuild:	>=sci-mathematics/gap-core-4.11.0"
genss/genss-1.6.6.ebuild:RDEPEND=">=sci-mathematics/gap-core-4.11.0
grape/grape-4.8.3.ebuild:RDEPEND=">=sci-mathematics/gap-core-4.11.0
guava/guava-3.15.ebuild:DEPEND=">=sci-mathematics/gap-core-4.11.0"
hap/hap-1.26.ebuild:RDEPEND=">=sci-mathematics/gap-core-4.11.0
HAPcryst/HAPcryst-0.1.13.ebuild:RDEPEND=">=sci-mathematics/gap-core-4.11.0
hecke/hecke-1.5.3.ebuild:RDEPEND=">=sci-mathematics/gap-core-4.11.0"
io/io-4.7.0.ebuild:DEPEND=">=sci-mathematics/gap-core-4.11.0"
liealgdb/liealgdb-2.2.1.ebuild:RDEPEND=">=sci-mathematics/gap-core-4.11.0"
orb/orb-4.8.3.ebuild:DEPEND=">=sci-mathematics/gap-core-4.11.0"
polenta/polenta-1.3.9.ebuild:RDEPEND=">=sci-mathematics/gap-core-4.11.0
polycyclic/polycyclic-2.15.1.ebuild:RDEPEND=">=sci-mathematics/gap-core-4.11.0
primgrp/primgrp-3.4.0.ebuild:RDEPEND=">=sci-mathematics/gap-core-4.11.0
qpa/qpa-1.30.ebuild:RDEPEND=">=sci-mathematics/gap-core-4.11.0
quagroup/quagroup-1.8.2.ebuild:RDEPEND=">=sci-mathematics/gap-core-4.11.0"
semigroups/semigroups-3.2.3.ebuild:DEPEND=">=sci-mathematics/gap-core-4.11.0
sla/sla-1.5.3.ebuild:RDEPEND=">=sci-mathematics/gap-core-4.11.0
SmallGrp/SmallGrp-1.4.1.ebuild:RDEPEND=">=sci-mathematics/gap-core-4.11.0"
tomlib/tomlib-1.2.9.ebuild:RDEPEND=">=sci-mathematics/gap-core-4.11.0
toric/toric-1.9.5.ebuild:RDEPEND=">=sci-mathematics/gap-core-4.11.0"
transgrp/transgrp-3.0.ebuild:RDEPEND=">=sci-mathematics/gap-core-4.11.0"
transgrp/transgrp-2.0.5.ebuild:RDEPEND=">=sci-mathematics/gap-core-4.11.0"
utils/utils-0.69.ebuild:RDEPEND=">=sci-mathematics/gap-core-4.11.0
```
Sorry for the messy format.

**Comment by derekperrin** [comment]
That looks like it more or less did the trick. Here's my new output:

```
emerge -av sage

These are the packages that would be merged, in order:

Calculating dependencies... done!
[ebuild  N     ] sci-mathematics/gap-4.10.2-r1:0/4.10.2::sage-on-gentoo  USE="readline recommended_pkgs -emacs -vim-syntax" 0 KiB
[ebuild  N     ] dev-gap/fga-1.4.0-r3::sage-on-gentoo  0 KiB
[ebuild  N     ] dev-gap/SmallGrp-1.3-r2::sage-on-gentoo  0 KiB
[ebuild  N     ] dev-gap/irredsol-1.4-r2:0/4.10.2::sage-on-gentoo  0 KiB
[ebuild  N     ] dev-gap/transgrp-2.0.4-r2:0/4.10.2::sage-on-gentoo  0 KiB
[ebuild  N     ] dev-gap/crisp-1.4.4-r2:0/4.10.2::sage-on-gentoo  0 KiB
[ebuild  N     ] dev-gap/autpgrp-1.10-r2::sage-on-gentoo  0 KiB
[ebuild  N     ] dev-gap/sophus-1.24-r3::sage-on-gentoo  0 KiB
[ebuild  N     ] dev-gap/GAPDoc-1.6.2-r2::sage-on-gentoo  0 KiB
[ebuild  N     ] dev-gap/ctbllib-1.2_p2-r6::sage-on-gentoo  0 KiB
[ebuild  N     ] dev-gap/primgrp-3.3.2-r2::sage-on-gentoo  0 KiB
[ebuild  N     ] dev-gap/factint-1.6.2-r2::sage-on-gentoo  0 KiB
[ebuild  N     ] dev-gap/laguna-3.9.3-r1::sage-on-gentoo  0 KiB
[ebuild  N     ] dev-gap/polycyclic-2.14-r2::sage-on-gentoo  0 KiB
[ebuild  N     ] dev-gap/Alnuth-3.1.1::sage-on-gentoo  0 KiB
[ebuild  N     ] dev-gap/radiroot-2.8-r3::sage-on-gentoo  0 KiB
[ebuild  N     ] dev-gap/polenta-1.3.8-r2::sage-on-gentoo  0 KiB
[ebuild  N     ] dev-gap/io-4.6.0::sage-on-gentoo  0 KiB
[ebuild  N     ] dev-gap/atlasrep-2.1_p0-r2::sage-on-gentoo  0 KiB
[ebuild  N     ] dev-gap/tomlib-1.2.8::sage-on-gentoo  0 KiB
[ebuild  N     ] dev-gap/AutoDoc-2019.05.20::sage-on-gentoo  0 KiB
[ebuild  N     ] dev-gap/utils-0.63::sage-on-gentoo  0 KiB
[ebuild  N     ] dev-gap/resclasses-4.7.2-r1::sage-on-gentoo  0 KiB
[ebuild  N     ] sci-mathematics/sage-9.2-r1::sage-on-gentoo  USE="X doc-html-bin -bliss -debug -doc-html -doc-pdf -doc-pdf-bin -jmol -latex -testsuite" L10N="en -ca -de -es -fr -hu -it -ja -pt -ru -tr" PYTHON_TARGETS="python3_8 -python3_7" 0 KiB

Total: 24 packages (24 new), Size of downloads: 0 KiB

!!! The following update(s) have been skipped due to unsatisfied dependencies
!!! triggered by backtracking:

dev-gap/irredsol:0
dev-gap/crisp:0

Would you like to merge these packages? [Yes/No]```

Is it okay that those two packages are being skipped though?

**Comment by kiwifb** [comment]
Yes those two should be OK, notice that there is a version already listed for install. Those two are in a different slot, which will be useful once we move to gap-4.11.0 in sage 9.3 and I completely get rid of the slotting.

That was some quick editing on your part from the list I gave.

**Comment by derekperrin** [comment]
Okay, thanks for your help and fast responses! Things look like they're emerging in just fine. Is there anything that can be done before sage 9.3? Is there anything I can do to help out?

I'm pasting the masked packages here in case they're of use to someone else who comes across this
```
>=dev-gap/aclib-1.3.2
>=dev-gap/Alnuth-3.1.2
>=dev-gap/AutoDoc-2019.09.04
>=dev-gap/autpgrp-1.10.2
>=dev-gap/corelg-1.54
>=dev-gap/crypting-0.10
>=dev-gap/digraphs-1.1.1
>=dev-gap/factint-1.6.3
>=dev-gap/GAPDoc-1.6.3
>=dev-gap/genss-1.6.6
>=dev-gap/grape-4.8.3
>=dev-gap/guava-3.15
>=dev-gap/hap-1.26
>=dev-gap/HAPcryst-0.1.13
>=dev-gap/hecke-1.5.3
>=dev-gap/io-4.7.0
>=dev-gap/liealgdb-2.2.1
>=dev-gap/orb-4.8.3
>=dev-gap/polenta-1.3.9
>=dev-gap/polycyclic-2.15.1
>=dev-gap/primgrp-3.4.0
>=dev-gap/qpa-1.30
>=dev-gap/quagroup-1.8.2
>=dev-gap/semigroups-3.2.3
>=dev-gap/sla-1.5.3
>=dev-gap/SmallGrp-1.4.1
>=dev-gap/tomlib-1.2.9
>=dev-gap/toric-1.9.5
>=dev-gap/transgrp-3.0
>=dev-gap/transgrp-2.0.5
>=dev-gap/utils-0.69
```

**Comment by kiwifb** [comment]
OK, I have done work on fixing the dependencies in gap-4.10.2 so primary dependencies don't pull gap-core. But there may be some more work needed on any dependency pulled by those primary dependencies.

**Comment by Alessandro-Barbieri** [comment]
I still don't know how I'm supposed to upgrade when:
`gap-core-4.11.0` (the only version available) has `RDEPEND="!<sci-mathematics/gap-4.11.0"`
`sage-9.2-r3` (the only keyworded version available) has `DEPEND="~sci-mathematics/gap-4.10.2"`

**Comment by kiwifb** [comment]
gap-core is only available for gap-4.11.0 onwards, gap-4.11.0 is to be used by sage-9.3 not yet released. Why are you insisting on using it? You should emerge gap and not worry about gap-core, you are not supposed to. Can you give me the full emerge output of what you are trying to do.

**Comment by Alessandro-Barbieri** [comment]
ok, I've solved

**Comment by kiwifb** [comment]
Because 4.11.1 is out I'll probably start the decoupling when I deal with that release. I probably will keep gap-core around for a couple of releases until I can easily switch some dependencies by dropping old versions of gap.
