### ISSUE TITLE
Tries to get package =dev-python/sympy-1.6* but it does not exist

### ISSUE THREAD

**Issue by robert17171** [cschwan/sage-on-gentoo#624]
Exactly as the title says. I found that a newer version of sympy is available in the main gentoo repository.

```
emerge: there are no ebuilds to satisfy "=dev-python/sympy-1.6*[python_targets_python3_7(-)?,python_targets_python3_8(-)?,-python_single_target_python3_7(-),-python_single_target_python3_8(-)]".
(dependency required by "sci-mathematics/sage-9.2-r1::sage-on-gentoo" [ebuild])
(dependency required by "sage" [argument])
```

**Comment by kiwifb** [comment]
Some people are flushing things too fast. I'll get some fix or an in overlay ebuild ASAP.

**Comment by kiwifb** [comment]
I have imported sympy-1.6.2 in the overlay. Synchronize and it should be OK.

**Comment by robert17171** [comment]
Ok thank you. It is now compiling. I will let you know if there are any other problems.
