### ISSUE TITLE
R-3.4.1 fails to build with gcc-10

### ISSUE THREAD

**Issue by strogdon** [cschwan/sage-on-gentoo#627]
The current `sage-9999` (sage-9.3.beta9) requires `>=dev-lang/R-3.2.0`. The stable `R` is  `R-3.4.1` which fails to build here, at least with gcc-10, (see https://bugs.gentoo.org/776781). I'm wondering if an unstable `R` should be keyworded to build s-o-g? For whatever reason I've been using `R-4.x.x` in building s-o-g. The failure documented at https://bugs.gentoo.org/776781 resulted when s-o-g was installed on a new laptop.

**Comment by kiwifb** [comment]
Yes, from what I see a newer version of dev-lang/R should have been stabilised during the gcc-10 porting effort. @orlitzky how do we organise that? We probably should go at least to 4.0.2 since it's been in tree for more than a month. There is an issue with hppa though.

**Comment by orlitzky** [comment]
In progress now: https://bugs.gentoo.org/765361

**Comment by kiwifb** [comment]
"code execution via malicious CRAN package" why I am absolutely not surprised or chocked.

**Comment by kiwifb** [comment]
R-4.0.4 stable on amd64 but not on other archs so far. So I am leaving this open for now.

**Comment by kiwifb** [comment]
x86 done so the two main arch are done. Closing.
