### ISSUE TITLE
PYTHON_COMPAT in three ebuild files  

### ISSUE THREAD

**Issue by sheerluck** [cschwan/sage-on-gentoo#630]
Is it possible to set 
```
PYTHON_COMPAT=( python3_{7..9} )
```
in
1) ExportSageNB-3.3.ebuild
2) sage-data-conway_polynomials-0.5.ebuild
3) sage-data-elliptic_curves-0.8.ebuild

**Comment by kiwifb** [comment]
Absolutely. It must have slipped out of my mind. I'll do it ASAP.

**Comment by kiwifb** [comment]
OK, that's those sorted. There are a few more ebuild not supporting py3.9 but they are either broken or depend on sage. And sage-9.2 doesn't support py3.9 that's coming in 9.3.
