### ISSUE TITLE
gap-core useflag constraints

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [cschwan/sage-on-gentoo#632]
gap-core[valgrind,memcheck] doesn't build for me. Configure says that both can't be enabled at the same time.
Suggested change: `REQUIRED_USE="?? ( memcheck valgrind )"`

**Comment by kiwifb** [comment]
OK, I have taken those option from the last version in the science overlay. It was obviously not tested. I'll get your required changes in ASAP.

**Comment by kiwifb** [comment]
Done. Hopefully that take care of your issues.
