### ISSUE TITLE
sympy-1.7

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [cschwan/sage-on-gentoo#636]
sage depend on sympy-1.7 that just got removed
https://github.com/gentoo/gentoo/commit/68c82ea6767a43dff644f699794a4db25275388c#diff-339b863ab020ef4adbc1b3cc5ad4a9ccbc402e57f64ce36c59d4f3e1068b31ff

**Comment by kiwifb** [comment]
Argh.... I have not tested 1.8, I'll have to check it first. Some packages get removed to fast for me these days. Thanks for the head up.

**Comment by kiwifb** [comment]
OK there is just a minor patch to add, I should have done it already. https://trac.sagemath.org/ticket/31647

**Comment by kiwifb** [comment]
And done.
