### ISSUE TITLE
Inconsistent GAP versions are keyworded

### ISSUE THREAD

**Issue by ngg** [cschwan/sage-on-gentoo#640]
Since https://github.com/cschwan/sage-on-gentoo/commit/b1c221653b588d19ffb1f9a094b0306853d2d6a4 `ctbllib-1.3.2` depends on GAP `>=4.11.1`.

In the `keywords` file https://github.com/cschwan/sage-on-gentoo/blob/master/package.keywords/sage-9.3#L111 this new version of ctbllib is enabled because `>=dev-gap/ctbllib-1.2_p2-r5`, but only an older GAP is enabled because `~sci-mathematics/gap-4.11.0`, which causes a conflict.

**Comment by kiwifb** [comment]
Yes, I will fix that keyword. I found that using that new gap package with gap-4.11.0 and sage 9.3 lead to failures to build doc, which is why I pushed it so it can only be used with gap 4.11.1 (which comes with ctbllib-1.3.1 I think).

**Comment by kiwifb** [comment]
It should be better now. I am a bit surprised that it was the only conflict you reported in fact.
