### ISSUE TITLE
sync libraries useflags with gentoo

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [cschwan/sage-on-gentoo#650]
`sci-libs/spqr` in gentoo has the `doc tbb partition` use while this has `doc metis static-libs tbb`
`sci-libs/cholmod` in gentoo has the `cuda matrixops modify partition doc lapack` use while this has `cuda doc lapack metis minimal static-libs`

the differences here are causing me alot of headcache while trying to upgrade world

**Comment by kiwifb** [comment]
I'll just remove the sage-on-gentoo ebuilds for now. There is currently nothing special in those sage-on-gentoo ebuilds compared to the main tree version.
When I finally get to do some serious rework of suitesparse, I may get something back in the overlay again, and use the same flags.

**Comment by kiwifb** [comment]
OK, those ebuilds are out of the overlay. I'll probably do something about the other suitesparse ones later.

**Comment by Alessandro-Barbieri** [comment]
thanks
