### ISSUE TITLE
EGIT_REPO_URI in both sage_setup-9999.ebuild and sage-9999.ebuild

### ISSUE THREAD

**Issue by sheerluck** [cschwan/sage-on-gentoo#656]
When `sage-9999.ebuild` has `EGIT_REPO_URI="https://github.com/sagemath/sage.git"` 
while `sage_setup-9999.ebuild` has `EGIT_REPO_URI="https://github.com/vbraun/sage.git"`
funny thing can happen: https://trac.sagemath.org/ticket/32373 merged in sage_setup-9999 but not in sage-9999.ebuild :)

so right now it is impossible to `emerge =sci-mathematics/sage-9999`

**Comment by kiwifb** [comment]
Apologies for that. I need to find something better to switch between the vbraun and master branch now that I am splitting the ebuilds again.
