### ISSUE TITLE
primecount/primesieve are in ::gentoo

### ISSUE THREAD

**Issue by orlitzky** [cschwan/sage-on-gentoo#666]
I imported these and tried to get `USE=doc` working for primesieve. It should be safe to drop them from the overlay.

**Comment by kiwifb** [comment]
Cool, I must say I didn't really look at the doc at all. It looks relatively trivial.

**Comment by kiwifb** [comment]
Can you have a look at https://bugs.gentoo.org/829029 / https://github.com/gentoo/gentoo/pull/23281 ? Singular 4.1.2p3 may very well make it to 9.5 and I don't know that base 4.1.2 is compatible.

**Comment by kiwifb** [comment]
All removed in 06de7e3d1c9721ccfc5674410ba67e7947207d3c
