### ISSUE TITLE
sage-doc-9999 installs symlink "_static" that points to a portage folder

### ISSUE THREAD

**Issue by strogdon** [cschwan/sage-on-gentoo#668]
I suspect the `_static` folder isn't needed, but I'm not sure.
```
$ ls -al /usr/share/doc/sage-doc-9999/pdf/en/reference/_static 
lrwxrwxrwx 1 root root 85 Dec 23 21:46 /usr/share/doc/sage-doc-9999/pdf/en/reference/_static -> /var/tmp/portage/sci-mathematics/sage-doc-9999/work/build_doc/html/en/website/_static
```

**Comment by strogdon** [comment]
Vanilla does have the `_static` folder as a symlink under `local/share/doc/sage/pdf/en/reference`, so It's probably needed.
```
$ ls -al /local/sage-git/sage/local/share/doc/sage/pdf/en/reference/_static
lrwxrwxrwx 1 steven steven 65 Jan  3 12:51 /local/sage-git/sage/local/share/doc/sage/pdf/en/reference/_static -> /local/sage-git/sage/local/share/doc/sage/html/en/website/_static
```

**Comment by kiwifb** [comment]
Hum, that would be an issue upstream. I would have to inspect things to see if it has really any purpose. If there is no html around there shouldn't be any point. pdf are supposed to be self contained, but there could be an index somewhere.

**Comment by strogdon** [comment]
```
/usr/share/doc/sage-doc-9999/pdf/en/reference/index.html 
```
seems to be missing some icons.

**Comment by strogdon** [comment]
icons and page formatting.

**Comment by kiwifb** [comment]
OK so it is broken. Is the `_static` folder full of broken links?

**Comment by strogdon** [comment]
In portage
```
/var/tmp/portage/sci-mathematics/sage-doc-9999/work/build_doc/html/en/website/_static/
```
contains broken links because they are all relative links.

**Comment by kiwifb** [comment]
before or after the install phase is ran? I do replace stuff by relative links during the install phase, the links are supposed to work once installed, so it is not abnormal for them to be broken in the build directory at that stage.

https://github.com/cschwan/sage-on-gentoo/blob/master/sci-mathematics/sage/sage-9.4-r2.ebuild#L347

**Comment by strogdon** [comment]
The relative links appear to be those created during the install phase. Notice from https://github.com/cschwan/sage-on-gentoo/issues/668#issue-1096987882 that the system link points to a portage `html` folder. From the ebuild I don't see any relative links created when the pdf docs are installed. That system link should be something like
```
/usr/share/doc/sage-doc-9999/pdf/en/reference/_static -> ../../../html/en/website/_static
```

**Comment by kiwifb** [comment]
Yes, I never did the pdf folder. I will add stuff for it since it seems needed.

**Comment by kiwifb** [comment]
Just to save me time, is it the only `_static` folder present?

**Comment by strogdon** [comment]
I have all the language pdfs built under `work/build_doc/pdf` and from this `pdf` folder I get
```
# find ./ | grep _static
./en/reference/_static
```
So I find only one such folder.

**Comment by kiwifb** [comment]
That makes things easier.

**Comment by kiwifb** [comment]
Now I have re-read your stuff from the start and paid more attention to your first post. It implies that pdf-doc installation needs the html one. This is something I will check as it has implication for `REQUIRED_USE` settings and so on. It may also enable code/flag simplifications if doc-html is always needed.

**Comment by strogdon** [comment]
It also looks like the `en/website/` could be eliminated in https://github.com/cschwan/sage-on-gentoo/issues/668#issuecomment-1008149729 since the `_static` is directly under the `html` folder.

**Comment by kiwifb** [comment]
Interesting building only pdf-doc led to https://github.com/cschwan/sage-on-gentoo/issues/667#issuecomment-1003882877

**Comment by kiwifb** [comment]
In the branch vbraun at https://github.com/cschwan/sage-on-gentoo/commit/1e2e36e77c2be83119a537e5c624bacf7ca81210 I remove `doc-html`. Building pdf documentation without html doesn't appear to be possible. Although we could argue that it doesn't matter for binary packages, your initial post shows installing binary pdf-doc without the html one would lead to a dangling link. The branch above should fix the dangling link of your first post, I still have to fully test it though.

Note that it comes on top of other changes for handling the documentation. In the vbraun branch the sage ebuild only have a `doc` use flag. The handling of html/pdf was already moving away from it. After resurrecting `sage-doc` I may very well resurrect `sage-doc-bin`.

**Comment by kiwifb** [comment]
New code seems to do the job
```
$ ll /usr/share/doc/sage-doc-9999/pdf/en/reference/_static
lrwxrwxrwx 1 root root 21 Jan  9 13:40 /usr/share/doc/sage-doc-9999/pdf/en/reference/_static -> ../../../html/_static
```

**Comment by strogdon** [comment]
Looks good on Prefix
```
ls -al ~/usr/share/doc/sage-doc-9999/pdf/en/reference/_static
lrwxrwxrwx 1 terry terry 21 Jan  8 20:12 /storage/strogdon/gentoo-rap/usr/share/doc/sage-doc-9999/pdf/en/reference/_static -> ../../../html/_static
```

**Comment by kiwifb** [comment]
vbraun branch merged into master just now for 9.5.rc0. It took a bit of time because I was finishing enabling python 3.10 everywhere. But the merge should fix this issue in the master branch. Seems I forgot something about python 3.10 that still need fixing though.

**Comment by strogdon** [comment]
Noticed that on the `file:///usr/share/doc/sage-doc-9999/pdf/en/reference/index.html` page the `index` in the upper right and bottom right which points to `file:///usr/share/doc/sage-doc-9999/pdf/en/reference/genindex.html` is broken. `genindex.html` does not exist. This is also broken on vanilla for the same reason.

**Comment by kiwifb** [comment]
Could be a build dependency issue. It probably should be generated but isn't.

**Comment by strogdon** [comment]
I believe the `_static` symlink issue has been fixed. And, as far as I can tell, the `index.html` issue is fixed by https://trac.sagemath.org/ticket/33309.
