### ISSUE TITLE
links to pdf docs in jupyter notebook are broken

### ISSUE THREAD

**Issue by strogdon** [cschwan/sage-on-gentoo#669]
This is relative to the `master` branch.

* start the jupyter notebook
```
sage -n jupyter
```
*  open a `New` SageMath 9999 notebook
*  go to `Help -> Sage Documentation`
*  mouse click on any of the PDF icons
I get a `404 : Not Found` error. The html documentation seems fine.

Now I may be doing something wrong since vanilla sage behaves exactly the same. So, if I have set up the notebook correctly then pdf links are broken in vanilla as well.

**Comment by kiwifb** [comment]
OK, I'll need to inspect that.

**Comment by kiwifb** [comment]
Looks like to be correct in my last vbraun branch build, However, I have an idea on how it could be broken in jupyter. For example
```
fbissey@tarazed /usr/share/doc/sage-doc-9999/html/en $ grep SageTutorial.pdf index.html 
        <a title="Download PDF" class="pdf" href="../../pdf/en/tutorial/SageTutorial.pdf">
fbissey@tarazed /usr/share/doc/sage-doc-9999/html/en $ ll ../../pdf/en/tutorial/SageTutorial.pdf
-rw-r--r-- 1 root root 560K Jan  9 13:40 ../../pdf/en/tutorial/SageTutorial.pdf
```
but jupyter gets the documentation via a link `/usr/share/jupyter/kernels/sagemath/doc -> ../../../doc/sage-doc-9999/html/en`, if you walk back through `/usr/share/jupyter/kernels/sagemath/doc` instead of `/usr/share/doc/sage-doc-9999/html/en` then you'll get into trouble. Can you get to html doc in other languages from jupyter? If my theory is correct it will also be broken.

**Comment by strogdon** [comment]
I'm not quite clear on this but I have:
*  main documentation page
```
http://localhost:8888/kernelspecs/sagemath/doc/index.html?v=20220108203502
```
*  Tutorial html page
```
http://localhost:8888/kernelspecs/sagemath/doc/tutorial/index.html
```
which works.
*  Tutorial pdf page
```
http://localhost:8888/kernelspecs/pdf/en/tutorial/SageTutorial.pdf
```
which is broken. If I replace `en` with `fr` then that link is also broken. I'm not sure what `kernelspecs` refers to. Perhaps there is a `sagemath` that's missing somewhere?

**Comment by strogdon** [comment]
The s-o-g pdf pages are broken. However, I think that the vanilla jupyter kernel is somehow tapping into the s-o-g one, thus giving broken results. I'm speculating here.

**Comment by kiwifb** [comment]
Yes, now that you show the html addresses it is plain to see. The html pages are displayed relative to `kernelspecs` which correspond to `/usr/share/jupyter/kernels` on the file system. The addresses in `index.html` will be taken relative to what is shown in the URL bar rather than their file-system location. And because links are used there is a mismatch when you go up (but not down) the tree.

Everything will work properly if you open your web browser at `file:///usr/share/doc/sage-doc-9999/html/en/index.html` rather than going through jupyter.

I don't think there is a way to fix this because of the way things are served by the web server behind jupyter.

**Comment by kiwifb** [comment]
Oh, that is an interesting issue there on which jupyter kernel is started by that command when you have both vanilla and s-o-g installed. However, the breakage of pdf links should be the same on both. The pdf are outside of the root of what the jupyter web server is serving, that is not good.

**Comment by strogdon** [comment]
And I believe vanilla is perhaps serving up stuff relative to the s-o-g `kernelspecs`?With vanilla
*  the document page
```
http://localhost:8888/kernelspecs/sagemath/doc/index.html
```
which is correct because there the actual version `9.5.beta9`
*  the html tutorial page
```
http://localhost:8888/kernelspecs/sagemath/doc/tutorial/index.html
```
which is also correct because there is the version `9.5.beta9`
*  the pdf tutorial page
```
http://localhost:8888/kernelspecs/pdf/en/tutorial/SageTutorial.pdf
```
which is broken and I don't know what is being served up here.

**Comment by kiwifb** [comment]
And that's the scary bit, from the url in the browser bar, you have no way of knowing where the root of the webserver is. The only way to know if it is s-o-g or vanilla is to go on the terminal and use something like `ps` to figure it out.

**Comment by strogdon** [comment]
In the terminal when I `click` on the tutorial pdf for vanilla I get
```
404 GET /kernelspecs/pdf/en/tutorial/SageTutorial.pdf (::1) 1.710000ms referer=http://localhost:8888/kernelspecs/sagemath/doc/index.html
```
while with s-o-g I get
```
404 GET /kernelspecs/pdf/en/tutorial/SageTutorial.pdf (::1) 2.290000ms referer=http://localhost:8888/kernelspecs/sagemath/doc/index.html?v=20220108213702
```
A slight difference. I see nothing revealing using `ps`.

**Comment by strogdon** [comment]
Removed `notebook`  from my system and `sage -n jupyter` fails to start. The vanilla notebook will start with
```
[I 21:45:18.847 NotebookApp] Creating new notebook in 
[W 21:45:19.743 NotebookApp] 404 GET /nbextensions/jupyter_jsmol/extension.js (::1) 6.690000ms referer=http://localhost:8888/notebooks/Untitled4.ipynb?kernel_name=sagemath
[W 21:45:19.924 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js (::1) 1.860000ms referer=http://localhost:8888/notebooks/Untitled4.ipynb?kernel_name=sagemath
[I 21:45:19.932 NotebookApp] Kernel started: 03d6b655-bff3-4145-bfda-f7ee4c6f5246, name: sagemath
[IPKernelApp] WARNING | debugpy_stream undefined, debugging will not be enabled
[W 21:45:27.688 NotebookApp] Kernelspec name pdf cannot be found!
[W 21:45:27.688 NotebookApp] 404 GET /kernelspecs/pdf/en/tutorial/SageTutorial.pdf (::1): Kernel spec pdf not found
[W 21:45:27.690 NotebookApp] 404 GET /kernelspecs/pdf/en/tutorial/SageTutorial.pdf (::1) 2.870000ms referer=http://localhost:8888/kernelspecs/sagemath/doc/index.html
```
when I `click` the tutorial pdf page. Maybe the vanilla notebook is not set up correctly?

**Comment by kiwifb** [comment]
Nope, this is exactly what I expect. The pdf documentation cannot be accessed from jupyter in this layout. The next to last line is telling, it is actually trying to access `${SAGE_VENV}/share/jupyter/kernels/pdf` and rightly complains that there are no pdf kernelspecs.

**Comment by strogdon** [comment]
See https://doc.sagemath.org/html/en/installation/launching.html#setting-up-sagemath-as-a-jupyter-kernel-in-an-existing-jupyter-notebook-or-jupyterlab-installation
to set up `kernelspecs`. So far I haven't been successful.

**Comment by kiwifb** [comment]
Do you want a recipe to start a vanilla sage kernel from system jupyter? That documentation, needs updating with recent beta. It is likely nothing will be in `$SAGE_LOCAL/share/jupyter/kernels/sagemath`, if system python is used, a venv is created and this is where the kernel specs are stored.
```
fbissey@tarazed ~/sandbox/git-personal/sage $ ll local/share/
total 92K
drwxr-xr-x 23 fbissey fbissey 4.0K Dec 20 14:17 .
drwxr-xr-x  9 fbissey fbissey 4.0K Dec 20 14:17 ..
drwxr-xr-x  2 fbissey fbissey 4.0K Dec 13 12:03 applications
drwxr-xr-x  3 fbissey fbissey 4.0K Dec 13 12:03 bash-completion
drwxr-xr-x  2 fbissey fbissey 4.0K Dec 13 11:59 combinatorial_designs
drwxr-xr-x  2 fbissey fbissey 4.0K Dec 13 11:59 conway_polynomials
drwxr-xr-x  2 fbissey fbissey 4.0K Dec 13 11:59 cremona
drwxr-xr-x  5 fbissey fbissey 4.0K Dec 20 14:17 doc
drwxr-xr-x  2 fbissey fbissey 4.0K Dec 13 11:59 ellcurves
drwxr-xr-x  3 fbissey fbissey 4.0K Dec 13 12:03 emacs
drwxr-xr-x 10 fbissey fbissey 4.0K Dec 13 12:01 gap
drwxr-xr-x  2 fbissey fbissey 4.0K Dec 13 11:59 graphs
drwxr-xr-x  2 fbissey fbissey 4.0K Dec 13 12:03 info
drwxr-xr-x  4 fbissey fbissey 4.0K Dec 13 11:59 jmol
drwxr-xr-x  5 fbissey fbissey 4.0K Dec 20 14:17 man
drwxr-xr-x  7 fbissey fbissey 4.0K Dec 13 11:59 mathjax
drwxr-xr-x  3 fbissey fbissey 4.0K Dec 13 12:03 maxima
drwxr-xr-x  2 fbissey fbissey 4.0K Dec 13 12:03 metainfo
drwxr-xr-x  3 fbissey fbissey 4.0K Dec 13 12:03 mime
drwxr-xr-x  2 fbissey fbissey 4.0K Dec 13 12:03 pixmaps
drwxr-xr-x  4 fbissey fbissey 4.0K Dec 13 11:59 reflexive_polytopes
drwxr-xr-x  2 fbissey fbissey 4.0K Dec 13 11:59 thebe
drwxr-xr-x  3 fbissey fbissey 4.0K Dec 13 11:59 threejs-sage
fbissey@tarazed ~/sandbox/git-personal/sage $ ll venv/share/jupyter/kernels/
total 16K
drwxr-xr-x 4 fbissey fbissey 4.0K Dec 13 12:11 .
drwxr-xr-x 5 fbissey fbissey 4.0K Dec 13 12:01 ..
drwxr-xr-x 2 fbissey fbissey 4.0K Dec 13 12:01 python3
drwxr-xr-x 2 fbissey fbissey 4.0K Dec 13 12:11 sagemath
```
Because the `jupyter` at the start of the command line is the system one, you will need to manually expand `SAGE_LOCAL`/`SAGE_VENV` as needed. On my system I just did
```
 fbissey@tarazed ~/sandbox/git-personal/sage $ jupyter kernelspec install --user /home/fbissey/sandbox/git-personal/sage/venv/share/jupyter/kernels/sagemath --name vanilla-sage
[InstallKernelSpec] Installed kernelspec vanilla-sage in /home/fbissey/.local/share/jupyter/kernels/vanilla-sage
```
and it even tells you where it is located. We can inspect it
```
ll /home/fbissey/.local/share/jupyter/kernels/vanilla-sage
total 40K
drwxr-xr-x  3 fbissey fbissey 4.0K Dec 13 12:11 .
drwxr-xr-x  3 fbissey fbissey 4.0K Jan  9 19:17 ..
drwxr-xr-x 14 fbissey fbissey 4.0K Dec 13 12:17 doc
-rw-r--r--  1 fbissey fbissey  227 Dec 13 12:11 kernel.json
-rw-r--r--  1 fbissey fbissey 3.4K Jun 16  2021 logo-64x64.png
-rw-r--r--  1 fbissey fbissey  19K Jun 16  2021 logo.svg
fbissey@tarazed ~/sandbox/git-personal/sage $ cat /home/fbissey/.local/share/jupyter/kernels/vanilla-sage/kernel.json 
{"argv": ["/home/fbissey/sandbox/git-personal/sage/local/var/lib/sage/venv-python3.9/bin/sage", "--python", "-m", "sage.repl.ipython_kernel", "-f", "{connection_file}"], "display_name": "SageMath 9.5.beta8", "language": "sage"}
```
as pointed out in the manual, no link - everything is copied. And there is definitely no way to access the pdf doc from that install
```
fbissey@tarazed ~/sandbox/git-personal/sage $ ll /home/fbissey/.local/share/jupyter/kernels/vanilla-sage/doc/
total 108K
drwxr-xr-x 14 fbissey fbissey 4.0K Dec 13 12:17 .
drwxr-xr-x  3 fbissey fbissey 4.0K Dec 13 12:11 ..
-rw-r--r--  1 fbissey fbissey  230 Dec 13 12:17 .buildinfo
drwxr-xr-x  2 fbissey fbissey 4.0K Dec 13 12:17 _sources
drwxr-xr-x  7 fbissey fbissey 4.0K Dec 13 12:17 _static
drwxr-xr-x  5 fbissey fbissey 4.0K Dec 13 12:17 a_tour_of_sage
drwxr-xr-x  5 fbissey fbissey 4.0K Dec 13 12:17 constructions
drwxr-xr-x  5 fbissey fbissey 4.0K Dec 13 12:17 developer
drwxr-xr-x  4 fbissey fbissey 4.0K Dec 13 12:17 faq
-rw-r--r--  1 fbissey fbissey 6.1K Dec 13 12:17 genindex-all.html
-rw-r--r--  1 fbissey fbissey 6.3K Dec 13 12:17 genindex.html
-rw-r--r--  1 fbissey fbissey  13K Dec 13 12:17 index.html
drwxr-xr-x  4 fbissey fbissey 4.0K Dec 13 12:17 installation
-rw-r--r--  1 fbissey fbissey  257 Dec 13 12:17 objects.inv
drwxr-xr-x  6 fbissey fbissey 4.0K Dec 13 12:17 prep
drwxr-xr-x 82 fbissey fbissey 4.0K Dec 13 12:16 reference
-rw-r--r--  1 fbissey fbissey 6.6K Dec 13 12:17 search.html
-rw-r--r--  1 fbissey fbissey  619 Dec 13 12:17 searchindex.js
drwxr-xr-x 11 fbissey fbissey 4.0K Dec 13 12:17 thematic_tutorials
drwxr-xr-x  4 fbissey fbissey 4.0K Dec 13 12:17 tutorial
drwxr-xr-x  4 fbissey fbissey 4.0K Dec 13 12:17 website
```

**Comment by strogdon** [comment]
I was more interested in implementing things from the s-o-g side since folders `jupyter/kernels/sagemath` were all missing under `$SAGE_LOCAL/share` but no go. I tried
```
$ ls -al ~/.local/share/jupyter/sagemath
lrwxrwxrwx 1 steven steven 35 Jan  8 22:51 /home/steven/.local/share/jupyter/sagemath -> /usr/share/jupyter/kernels/sagemath
```
but the `kernelspec` from the browser is still incorrect.

**Comment by kiwifb** [comment]
```
jupyter kernelspec install --user /usr/share/jupyter/kernels/sagemath 
```
should do it properly, but it will start s-o-g. I hope that's what you are after.

**Comment by strogdon** [comment]
I had not done that but had created the symlink
```
ln -s /usr/share/jupyter/kernels/sagemath ~/.local/share/jupyter
```
as indicated in the documentation. This did not work. I think there is something wrong with 
```
<a title="Download PDF" class="pdf" href="../../pdf/en/tutorial/SageTutorial.pdf">
```
in
```
/usr/share/doc/sage-doc-9999/html/en/index.html
```
that does not allow loading the pdf docs from the notebook. If 
```
http://localhost:8888/kernelspecs/sagemath/doc/index.html?v=20220109001539
```
is the sage documentation page then
```
view-source:http://localhost:8888/kernelspecs/sagemath/doc/index.html?v=20220109001539
```
is the source. All the links in the source file work except those that point to `pdf`s.

**Comment by kiwifb** [comment]
> I had not done that but had created the symlink
> 
> ```
> ln -s /usr/share/jupyter/kernels/sagemath ~/.local/share/jupyter
> ```
> 
> as indicated in the documentation. This did not work. I think there is something wrong with
> 
> ```
> <a title="Download PDF" class="pdf" href="../../pdf/en/tutorial/SageTutorial.pdf">
> ```
> 
> in
> 
> ```
> /usr/share/doc/sage-doc-9999/html/en/index.html
> ```
> 
> that does not allow loading the pdf docs from the notebook. If
> 
> ```
> http://localhost:8888/kernelspecs/sagemath/doc/index.html?v=20220109001539
> ```
> 
> is the sage documentation page then
> 
> ```
> view-source:http://localhost:8888/kernelspecs/sagemath/doc/index.html?v=20220109001539
> ```
> 
> is the source. All the links in the source file work except those that point to `pdf`s.

And I keep telling you **_they cannot possibly work from jupyter_**. They'd need to be moved under `html/en` and the relative path changed accordingly. The only way they'll work is to change the layout of the doc so that everything is under where `share/jupyter/kernels/sagemath/doc` points too.

**Comment by strogdon** [comment]
I realize that. But I believe the intention was that they should work. I find nothing that indicates things were not to work from jupyter. The icons and links are present. The intention was that they should work. Isn't this a vanilla issue? I can't find documentation that indicates one must use an appropriate url to load pdf documentation. Perhaps I'm wrong.

**Comment by kiwifb** [comment]
Well, it definitely need to be changed in vanilla. But like I said earlier you don't have to access the documentation via jupyter, The html/pdf stuff existed before jupyter was a thing to be opened directly in a web-browser. Since it is just navigating the file system and not serving files it does work. You could say that adding it to jupyter was a bit of an after thought. To make it work and especially to enable other languages - which would be cool, you'd have to redesign the layout a bit and possibly put pdf next to html.

**Comment by kiwifb** [comment]
python 3.10 needed a newer rpy keyworded :)

**Comment by strogdon** [comment]
Maybe this is a new issue and I'll be glad to open a new one. I built s-o-g `9.5.rc0` with `python3.10`. The `html` documentation are not visible from the jupyter notebook. Procedure:
* sage -n jupyter
* select a new SageMath 9999
* Help -> Sage Documentation

In the terminal
```
[W 13:20:10.397 NotebookApp] 404 GET /kernelspecs/sagemath/doc/index.html?v=20220110131159 (::1) 2.530000ms referer=http://localhost:8888/notebooks/Untitled1.ipynb?kernel_name=sagemath
```
I don't think I messed things up (but who knows) since the `html` documentation was working with `9.5.beta9`.

**Comment by strogdon** [comment]
Under `/usr/share/jupyter/kernels/sagemath` there should be a `doc` symlink to the `html` doc location. Adding the symlink fixes the above. I have now
```
# ls -al /usr/share/jupyter/kernels/sagemath
total 5
drwxr-xr-x 2 root root 1024 Jan 10 17:25 .
drwxr-xr-x 4 root root 1024 Jan  9 13:15 ..
lrwxrwxrwx 1 root root   34 Jan 10 17:25 doc -> ../../../doc/sage-doc-9999/html/en
-rw-r--r-- 1 root root  134 Jan 10 09:08 kernel.json
lrwxrwxrwx 1 root root   94 Jan 10 09:08 logo-64x64.png -> ../../../../..//usr/lib/python3.10/site-packages/sage/ext_data/notebook-ipython/logo-64x64.png
lrwxrwxrwx 1 root root   88 Jan 10 09:08 logo.svg -> ../../../../..//usr/lib/python3.10/site-packages/sage/ext_data/notebook-ipython/logo.svg
```

**Comment by kiwifb** [comment]
Oh great. I must have messed up when I removed the doc-html flag. Inspecting.

**Comment by kiwifb** [comment]
Not sure why it was missing from my install too. I just tweaked the line creating it because EAPI=8 makes it easier to create symlinks and after emerge the link is present again.

**Comment by kiwifb** [comment]
Change is now reflected in master branch.

**Comment by strogdon** [comment]
Unable to sync overlay. I did this yesterday.
```
 * Syncing selected overlay(s)...
 * Running Git... # ( cd /var/lib/layman/sage-on-gentoo  && /usr/bin/git pull )
fatal: remote error: 
  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
 * Failure result returned from Git
 * 
 * Errors:
 * ------
 * Failed to sync overlay "sage-on-gentoo".
 * Error was: Syncing overlay "sage-on-gentoo" returned status 1!
 * db.sync()
 * 
```
Is this on my end?

**Comment by strogdon** [comment]
OK had to re-add the overlay.

**Comment by strogdon** [comment]
Relative to the original issue, I believe there is a work-around. In `/usr/share/doc/sage-doc-9999/htm/en` create the symlink `web_pdf`
```
# ls -al /usr/share/doc/sage-doc-9999/html/en/web_pdf
lrwxrwxrwx 1 root root 6 Jan 10 20:28 /usr/share/doc/sage-doc-9999/html/en/web_pdf -> ../..
```
and then in `/usr/share/doc/sage-doc-9999/html/en/index.html` replace every `../..` in the href for the pdfs with `../.. -> web_pdf`.

Of course the `index.html` is autogenerated and I'm not sure at this point how to do that. This doesn't seem to interfere with loading the `index.html` directly.

**Comment by strogdon** [comment]
This is now fixed by https://trac.sagemath.org/ticket/33206. My original branch there used a relative symlink to fix things while the now proposed branch uses an absolute link. The absolute link requires SAGE_DOC to be available. Both work. Perhaps one is easier to maintain from s-o-g? Perhaps you could take a look. I will give it a positive if you have no issue.

**Comment by kiwifb** [comment]
I have no idea how it will turn in a system wide install. I need to test it but I suspect adjustment will be needed at install time.

**Comment by kiwifb** [comment]
Actually in a vanilla build what does the html code to link to pdf looks like after this ticket is applied?

**Comment by strogdon** [comment]
From vanilla SAGE_ROOT (/local/sage-git/sage)
```
ls -al local/share/doc/sage/html/en
total 58
drwxr-xr-x 14 steven steven  1024 Jan 21 18:49 .
drwxr-xr-x 13 steven steven  1024 Jan 21 18:33 ..
drwxr-xr-x  5 steven steven  1024 Jan 21 18:33 a_tour_of_sage
-rw-r--r--  1 steven steven   230 Jan 21 18:33 .buildinfo
drwxr-xr-x  5 steven steven  3072 Jan 21 18:33 constructions
drwxr-xr-x  5 steven steven  1024 Jan 21 18:33 developer
drwxr-xr-x  4 steven steven  1024 Jan 21 18:33 faq
-rw-r--r--  1 steven steven  6268 Jan 21 18:33 genindex-all.html
-rw-r--r--  1 steven steven  6428 Jan 21 18:33 genindex.html
-rw-r--r--  1 steven steven 12567 Jan 21 18:33 index.html
drwxr-xr-x  4 steven steven  1024 Jan 21 18:33 installation
-rw-r--r--  1 steven steven   255 Jan 21 18:33 objects.inv
lrwxrwxrwx  1 steven steven    45 Jan 21 18:49 pdf -> /local/sage-git/sage/local/share/doc/sage/pdf
drwxr-xr-x  6 steven steven  1024 Jan 21 18:33 prep
drwxr-xr-x 82 steven steven  4096 Jan 21 18:33 reference
-rw-r--r--  1 steven steven  6820 Jan 21 18:33 search.html
-rw-r--r--  1 steven steven   619 Jan 21 18:33 searchindex.js
drwxr-xr-x  2 steven steven  1024 Jan 21 18:33 _sources
drwxr-xr-x  7 steven steven  1024 Jan 21 18:33 _static
drwxr-xr-x 11 steven steven  3072 Jan 21 18:34 thematic_tutorials
drwxr-xr-x  4 steven steven  1024 Jan 21 18:33 tutorial
drwxr-xr-x  4 steven steven  1024 Jan 21 18:33 website
```
The `pdf` symlink is inserted after the PDF documentation has been built. No link if only html documentation build. This link could be `pdf -> ../../pdf`.

**Comment by strogdon** [comment]
fixed by https://trac.sagemath.org/ticket/33206
