### ISSUE TITLE
Cosmetic: Incorrect links in pdf/en/reference/index.html

### ISSUE THREAD

**Issue by strogdon** [cschwan/sage-on-gentoo#673]
The file
```
/usr/share/doc/sage-doc-9999/pdf/en/reference/index.html
``` 
when opened in a browser has `SAGE` icons at the upper and lower left of the browser page. These icons are links which point to
```
/var/tmp/portage/sci-mathematics/sage-doc-9999/work/build_doc/html/en/index.html
```
The links should point to
```
/usr/share/doc/sage-doc-9999/html/en/index.html
```
The corresponding `SAGE` icons/links on
```
/usr/share/doc/sage-doc-9999/html/en/reference/index.html
```
point to the correct location.

**Comment by kiwifb** [comment]
I should have expected some stuff like that after the chat we had with upstream for the pdf links. Would be nice if they were relative links too but I should be able to catch them and rewrite them at the very least.

**Comment by kiwifb** [comment]
I had not noticed that it was pdf. There is no issue in the html part, this is interesting.

**Comment by kiwifb** [comment]
So much fun. I cannot build the doc on the vbraun branch at the moment. Something tries to open `cremona_mini.db` read/write and I have no clue what.

**Comment by kiwifb** [comment]
For the record
```
 * --------------------------- ACCESS VIOLATION SUMMARY ---------------------------
 * LOG FILE: "/dev/shm/portage/sci-mathematics/sage-doc-9999/temp/sandbox.log"
 * 
VERSION 1.0
FORMAT: F - Function called
FORMAT: S - Access Status
FORMAT: P - Path as passed to function
FORMAT: A - Absolute Path (not canonical)
FORMAT: R - Canonical Path
FORMAT: C - Command Line

F: open_wr
S: deny
P: /usr/share/sage/cremona/cremona_mini.db
A: /usr/share/sage/cremona/cremona_mini.db
R: /usr/share/sage/cremona/cremona_mini.db
C: /usr/bin/python3.10 -m sage_docbuild --no-pdf-links reference/plotting inventory --no-prune-empty-dirs 

F: open_wr
S: deny
P: /usr/share/sage/cremona/cremona_mini.db
A: /usr/share/sage/cremona/cremona_mini.db
R: /usr/share/sage/cremona/cremona_mini.db
C: /usr/bin/python3.10 -m sage_docbuild --no-pdf-links reference/plotting inventory --no-prune-empty-dirs 

F: open_wr
S: deny
P: /usr/share/sage/cremona/cremona_mini.db
A: /usr/share/sage/cremona/cremona_mini.db
R: /usr/share/sage/cremona/cremona_mini.db
C: /usr/bin/python3.10 -m sage_docbuild --no-pdf-links reference/plotting inventory --no-prune-empty-dirs 
 * --------------------------------------------------------------------------------
```

**Comment by kiwifb** [comment]
```
fbissey@tarazed /dev/shm/portage/sci-mathematics/sage-doc-9999/image/usr/share/doc/sage-doc-9999 $ grep -rI build_doc *
pdf/en/reference/index.html:    <a href="/dev/shm/portage/sci-mathematics/sage-doc-9999/work/build_doc/html/en/index.html"><img src="_static/logo_sagemath_black.svg" height="28" style="vertical-align: middle" title="Sage Logo"></a>
pdf/en/reference/index.html:    <a href="/dev/shm/portage/sci-mathematics/sage-doc-9999/work/build_doc/html/en/index.html"><img src="_static/logo_sagemath_black.svg" height="28" style="vertical-align: middle" title="Sage Logo"></a>
```
So just two instances.

**Comment by kiwifb** [comment]
No idea where it is generated from. Must be a "sphinxism". Will have to add a catch on that before install.

**Comment by kiwifb** [comment]
Got a fix in the vbraun branch to be merged at the next release.

**Comment by strogdon** [comment]
I scoured around and couldn't find where the link was created.

**Comment by strogdon** [comment]
FWIW, here is the obscure location where the link is created
```
   628          # Now modify website's index.html page and write it to
   629          # output_dir.
   630          with open(os.path.join(website_dir, 'index.html')) as f:
   631              html = f.read().replace('Documentation', 'Reference')
   632          html_output_dir = os.path.dirname(website_dir)
   633          html = html.replace('http://www.sagemath.org',
   634                              '../../../html/en/index.html')
   635  #                            os.path.join(html_output_dir, 'index.html'))
   636          # From index.html, we want the preamble and the tail.
```
in `sage_docbuild/__init__.py`. But this may be more trouble than your workaround.

**Comment by strogdon** [comment]
Actually, after thinking about it, the above works on vanilla. I wonder if a change is needed there?

**Comment by strogdon** [comment]
And the original code fails on Gentoo because `SAGE_DOC` is different for compile time than for runtime.

**Comment by kiwifb** [comment]
Yes, the fact that vanilla build things in place hides many things. I like your change and I don't see why it couldn't be upstreamed.

**Comment by strogdon** [comment]
I was incorrect above. Line 634 should be
```
634                              '../../../index.html')
```
So I believe your sed at https://github.com/cschwan/sage-on-gentoo/commit/72b8ca4ff5c0f724c37076062176a3bfb5a93bd3 is not correct. The target should be `../../../index.html`. The `<a href="../../../html/en/index.html">` points to `/usr/share/doc/sage-doc-9999/html/en/html/en/index.html`

**Comment by kiwifb** [comment]
Are we talking about the same file/thing?
```
fbissey@tarazed /usr/share/doc/sage-doc-9999/pdf/en/reference $ grep html index.html 
<!DOCTYPE html>
<html>
    <link rel="index" title="Index" href="genindex.html" />
    <link rel="search" title="Search" href="search.html" />
          <a href="genindex.html" title="General Index"
    <a href="../../../html/en/index.html"><img src="_static/logo_sagemath_black.svg" height="28" style="vertical-align: middle" title="Sage Logo"></a>
<li> <a href="https://jupyter-notebook.readthedocs.io/en/latest/notebook.html">Jupyter Notebook Interface</a></li>
          <a href="genindex.html" title="General Index"
    <a href="../../../html/en/index.html"><img src="_static/logo_sagemath_black.svg" height="28" style="vertical-align: middle" title="Sage Logo"></a>
 * sage.misc.html.math_parse() eats jQuery's dollar-sign shortcut. */
</html>
fbissey@tarazed /usr/share/doc/sage-doc-9999/pdf/en/reference $ ll ../../../html/en/index.html
-rw-r--r-- 1 root root 13K Feb  2 14:58 ../../../html/en/index.html
fbissey@tarazed /usr/share/doc/sage-doc-9999/pdf/en/reference $ ll ../../../index.html
ls: cannot access '../../../index.html': No such file or directory
```

**Comment by strogdon** [comment]
In the browser one has to go through the `pdf` symlink. The webpage in question in
```
/usr/share/doc/sage-doc-9999/html/en/pdf/en/reference/index.html
```
Therefore
```
/usr/share/doc/sage-doc-9999/html/en/pdf/en/reference/../../../index.html
```
gets us to the correct page.

**Comment by strogdon** [comment]
This works on vanilla and Gentoo
```
diff --git a/src/sage_docbuild/__init__.py b/src/sage_docbuild/__init__.py
index 9160119baa..d33ae91239 100644
--- a/src/sage_docbuild/__init__.py
+++ b/src/sage_docbuild/__init__.py
@@ -630,8 +630,10 @@ class ReferenceTopBuilder(DocBuilder):
         with open(os.path.join(website_dir, 'index.html')) as f:
             html = f.read().replace('Documentation', 'Reference')
         html_output_dir = os.path.dirname(website_dir)
+        pdf_output_dir = os.path.join(SAGE_DOC, 'html', 'en', 'pdf', 'en', 'reference')
+        relpath=os.path.relpath(html_output_dir, pdf_output_dir)
         html = html.replace('http://www.sagemath.org',
-                            os.path.join(html_output_dir, 'index.html'))
+                            os.path.join(relpath, 'index.html'))
         # From index.html, we want the preamble and the tail.
         html_end_preamble = html.find('<h1>Sage Reference')
         html_bottom = html.rfind('</table>') + len('</table>')
```

**Comment by kiwifb** [comment]
I do like that :)

**Comment by strogdon** [comment]
OK, so I'm approaching this from viewing the pdf docs from the jupyter notebook. Opening
`/usr/share/doc/sage-doc-9999/pdf/en/reference/index.html` will work in which case your sed is correct. But from the notebook this won't work. We have to go through the `pdf` symlink as above. I don't know which is to be preferred. The same issue exists on vanilla. One can open the `pdf/en/reference/index.html` file directly. But the `SAGE` link is broken. However, if the page is opened through the notebook (this uses the `pdf` symlink) then the link works.

**Comment by kiwifb** [comment]
I am a bit confused but let's summarise
* my stuff doesn't work in the notebook
* my stuff works directly in the web browser
* your stuff works with the notebook
Question:
* does your stuff work directly in the web browser or is it broken?

**Comment by strogdon** [comment]
Probably if absolute paths instead of relative paths were used this would not be an issue. I believe the original code in `sage_docbuild/__init__.py` used absolute paths but SAGE_DOC gets in the way.

**Comment by kiwifb** [comment]
I could use absolute path if that is the solution.

**Comment by strogdon** [comment]
My icon links do not work if I load
```
/usr/share/doc/sage-doc-9999/pdf/en/reference/index.html
```
They do work if I load
```
/usr/share/doc/sage-doc-9999/html/en/pdf/en/reference/index.html
```
Your icon link should work from 
```
/usr/share/doc/sage-doc-9999/pdf/en/reference/index.html
```
The page you get by clicking the icon link should be
```
/usr/share/doc/sage-doc-9999/html/en/index.html
```
if you click the `PDF` icon next to `Reference Manual` you will get back to the original `PDF Reference Manual` index. The `SAGE` icon link on this page will be broken.

**Comment by strogdon** [comment]
If I use absolute links
```
grep 'en/index.html' /usr/share/doc/sage-doc-9999/pdf/en/reference/index.html
    <a href="/usr/share/doc/sage-doc-9999/html/en/index.html"><img src="_static/logo_sagemath_black.svg" height="28" style="vertical-align: middle" title="Sage Logo"></a>
    <a href="/usr/share/doc/sage-doc-9999/html/en/index.html"><img src="_static/logo_sagemath_black.svg" height="28" style="vertical-align: middle" title="Sage Logo"></a>
```
then everything works fine regardless of how I access the pdf doc reference index. So perhaps the original sed should insert an absolute path.

**Comment by kiwifb** [comment]
Seems the easy way out.

**Comment by strogdon** [comment]
Well It appears that absolute links (and this is what vanilla does) are broken from the notebook. They work fine when the `index.html` files are accessed directly. This is another vanilla bug. Absolute links won't work because the web server does know about things outside the server tree.

**Comment by kiwifb** [comment]
I am starting to think there is no real solution that work in every cases. The way it is structured may need to go back to the drawing board.

**Comment by strogdon** [comment]
On vanilla from SAGE_ROOT
```
grep 'en/index.html' local/share/doc/sage/pdf/en/reference/index.html
    <a href="/local/sage-git/sage/local/share/doc/sage/html/en/index.html"><img src="_static/logo_sagemath_black.svg" height="28" style="vertical-align: middle" title="Sage Logo"></a>
    <a href="/local/sage-git/sage/local/share/doc/sage/html/en/index.html"><img src="_static/logo_sagemath_black.svg" height="28" style="vertical-align: middle" title="Sage Logo"></a>
```
When I click the `SAGE` icon on the pdf reference doc index page I get in the browser window
```
http://localhost:8888/local/sage-git/sage/local/share/doc/sage/html/en/index.html
```
which is not found `404 : Not Found`.

**Comment by strogdon** [comment]
A new approach to resolve `pdf` and other links in the notebook (see https://trac.sagemath.org/ticket/33309#comment:39) is proposed. I can't see this would be a security issue on a vanilla install, but what about on distos? Basically the proposal is to change the `root` of the webserver tree.

**Comment by kiwifb** [comment]
Should be gone in 9.6.beta3 out now.

**Comment by strogdon** [comment]
This has been fixed. The `SAGE` icon links on documentation pages now point to [sagemath](https://www.sagemath.org)
