### ISSUE TITLE
PrimeCountPy Build Fails

### ISSUE THREAD

**Issue by robert2343** [cschwan/sage-on-gentoo#676]
When I run "emerge -qa sage" to install sagemath, PrimeCountPy fails. Here is the build info:
[emerge --info primecountpy](https://pastebin.com/SAgqcZCW)
[emerge -pqv primecountpy](https://pastebin.com/HxnLc2hz)
[build.log](https://pastebin.com/bFYDJC3F)

**Comment by kiwifb** [comment]
It looks like your `cysignals` is either missing or more likely too old. I'll check the version required in the ebuild.

**Comment by kiwifb** [comment]
That's embarrassing, it is missing from the ebuild as a dependency altogether. Let me fix that - a few minutes.

**Comment by robert2343** [comment]
It looks like PrimeCountPy does not pull in cysignals as a dependency.

**Comment by kiwifb** [comment]
OK, sync the overlay and re-try :) thanks for reporting.

**Comment by robert2343** [comment]
Ok I retried after emerge --sync. but it still fails.
[emerge --info primecountpy](https://pastebin.com/ViziXr5D)
[emerge -pqv primecountpy](https://pastebin.com/gzVW1uVZ)
[build.log](https://pastebin.com/g6TiYfQ9)
