### ISSUE TITLE
PermissionError: [Errno 1] Operation not permitted: when doctesting

### ISSUE THREAD

**Issue by strogdon** [cschwan/sage-on-gentoo#678]
I see numerous of the above `PermissionError:` when doctesting which after the failure often throws a `NameError: name 'rich_output' is not defined`. Something must be trying to write to a non-writeable location since I believe this is not a problem on Prefix. This is alarming since I don't know what is being written (if this is the case) and where the writing takes place.

**Comment by kiwifb** [comment]
Yes, I noticed that and I have a fix positively reviewed already at https://trac.sagemath.org/ticket/33256 some different fixes are at https://trac.sagemath.org/ticket/33141

**Comment by kiwifb** [comment]
Volker just merged 33256 so we shouldn't get those anymore in 9.6.beta2.
