### ISSUE TITLE
Problem building sci-mathematics/sage-doc-9.5

### ISSUE THREAD

**Issue by hackitforfun** [cschwan/sage-on-gentoo#680]
Fresh install. Package sci-mathematics/sage-doc-9.5 won't build (not sure if this is an upstream issue?).

The complete build log is attached.
[sage-doc.log](https://github.com/cschwan/sage-on-gentoo/files/8112507/sage-doc.log)

**Comment by kiwifb** [comment]
It is a sphinx 4.4 issue. I am working my ass off upstream to fix this https://trac.sagemath.org/ticket/33272. I should be able to backport something to 9.5 soon but some links in the doc may stay broken because of the amount of work involved to fix them.

**Comment by kiwifb** [comment]
I should mention that I already patched 9.5 to support sphinx 4.3 and then Gentoo just removed it from the main tree in favor of 4.4.0 that came quite quickly afterwards. The links I am mentioning may have actually been broken for a while.

**Comment by hackitforfun** [comment]
Thanks for the clarification and for all the hard work. I am sure there are many users, including me, would appreciate it. I guess for the moment, we just have to be a bit more patient then :)

**Comment by kiwifb** [comment]
OK, this is a bit too just in time for my liking :) but the fix for 9.5 is in the master branch of the overlay. Because there is a part in sage itself, the sage ebuild is bumped to 9.5-r1 and it has to be emerged first before sage-doc-9.5 - which is not bumped because it is not currently working anyway.

9999 version should be done shortly for anyone wanting to test 9.6.beta2.

**Comment by kiwifb** [comment]
9999 ebuilds fixed. Still plenty of ugly broken links :(

**Comment by kiwifb** [comment]
Looks like I missed at least one file in the patch for sage :(  I'll update everything to the latest upstream version in the morning.

**Comment by kiwifb** [comment]
OK this should now be completely fixed by ff5d0d3184cb9db756c385970ebe52774020a764 and 11719f7a022eb9a87686f422404050381bf66e5f sage is bumped to 9.5-r2 and needs to be rebuilt before sage-doc.

**Comment by strogdon** [comment]
prepare phase fails using `sphinx-4.4` with `sage-9999`.

**Comment by strogdon** [comment]
That is the `sphinx-4.4` patch.

**Comment by kiwifb** [comment]
One more stuff up on my part. I forgot to adjust the patch.

**Comment by kiwifb** [comment]
Should be fixed by 30cf304a57169385a5fc1146975aabce26fb6dce

**Comment by hackitforfun** [comment]
I can confirm that this is fixed now for 9.5-r2. Thanks!
