### ISSUE TITLE
/usr/share/doc/sage-doc-9999/html/en/index.html not accessible from jupyter notebook

### ISSUE THREAD

**Issue by strogdon** [cschwan/sage-on-gentoo#683]
To reproduce:
* sage -n jupyter
* select New -> SageMath 9999
* select Help -> Sage Documentation

The result is a `404 : Not Found`

The browser link that fails is
```
http://localhost:8888/kernelspecs/sagemath/doc/html/en/index.html?v=20220310224541
```

Now removing the `?v=20220310224541` works, i.e.
```
http://localhost:8888/kernelspecs/sagemath/doc/html/en/index.html
```
works.

**Comment by kiwifb** [comment]
Right. And where does that come from?

**Comment by strogdon** [comment]
Most of the menu items under Help -> ... have this `?v=xxxxx`. The `xxxxx` changes for each new notebook.

**Comment by kiwifb** [comment]
I am assuming they are some kind of time stamps. But I don't know what would put them there.

**Comment by strogdon** [comment]
Not the only issue. The `html` links on `sage-doc-9999/html/en/index.html` are broken from the notebook. They work when loaded in a browser as `/usr/share/doc/sage-doc-9999/htm/en/index.html`. However if I click the "languages are available" `here` link then the `html` links work from the notebook. But this `here` link does not go to the correct location. It also does not work on vanilla. I need to rebuild the vanilla docs from scratch to make sure I'm correct. At a minimum there is a missing `index.html` file that should be under `/usr/share/doc/sage-doc-9999`. The `here` link should point to this `index.html` file.

**Comment by kiwifb** [comment]
The missing file may be my fault, but it would also need a matching change in the sagemath kernel I think.

**Comment by strogdon** [comment]
The `here` link is broken on vanilla.

**Comment by kiwifb** [comment]
Speaking of vanilla. Where does `local/share/jupyter/kernel/sagemath/doc` link to these days? I am still pointing to `/usr/share/doc/sage-${PV}/html/en` when I probably should switch to `/usr/share/doc/sage-${PV}` to use the new `index.html` once it is in place.

**Comment by strogdon** [comment]
See https://trac.sagemath.org/ticket/33490 for the `here` link on vanilla.

**Comment by strogdon** [comment]
Here `local/share/jupyter/kernel/sagemath` is empty
```
ls -al local/share/jupyter/kernels/sagemath/
total 2
drwxr-xr-x 2 steven steven 1024 Jan  8 22:41 .
drwxr-xr-x 3 steven steven 1024 Jan  8 22:41 ..
```

**Comment by kiwifb** [comment]
OK, where is the kernel installed then? `~/.local/share/jupyter/kernels`?

**Comment by kiwifb** [comment]
OK it is now in `venv/share/jupyter/kernels/sagemath`. The folder you have comes from an install that wasn't cleaned properly.

**Comment by kiwifb** [comment]
OK just pushed the parallel fix and doc install and jupyter doc link tweaks to master.

**Comment by strogdon** [comment]
This now works on s-o-g. And vanilla now works. Is there something on s-o-g that could have messed up vanilla results?

**Comment by kiwifb** [comment]
Would have to be sure which kernel is used. It is not impossible that s-o-g kernel is used when launched from vanilla if it comes first in the paths that jupyter goes through for kernels.

**Comment by strogdon** [comment]
I'm going to close this. For me, things are fixed. Reopen if you think necessary.
