### ISSUE TITLE
curious build order

### ISSUE THREAD

**Issue by strogdon** [cschwan/sage-on-gentoo#684]
On two gentoo machines `emerge -1 @sagemath` builds in order
```
sympy-1.10
sage_setup-9999
sage-9999
sage_docbuild-9999
sage-doc-9999
```
But on prefix the same `emerge` builds
```
sympy-1.10
sage_setup-9999
sage_docbuild-9999
sage-9999
sage-doc-9999
```
Probably of no consequence but I thought curious.

**Comment by kiwifb** [comment]
Yes, the order in which `sage_docbuild` is done seems to be a bit random. I am not sure what is a good predictor of whether it will be before or after `sage`.

**Comment by strogdon** [comment]
Just curious.

**Comment by kiwifb** [comment]
Both order fully satisfy the dependencies I gave them. I do not see a reason to change it right now.
