### ISSUE TITLE
sage_docbuild question

### ISSUE THREAD

**Issue by strogdon** [cschwan/sage-on-gentoo#692]
Here it seems that after building the html and pdf docs that something is then run relative to `website`:
```
[reference] ... done (65021 js index entries)
[reference] dumping search index in English (code: en)... done
[reference] The HTML pages are in ../../../build_doc/html/en/reference.
Build finished. The built documents can be found in /storage/strogdon/gentoo-rap/var/tmp/portage/sci-mathematics/sage-doc-9999/work/build_doc/html/en/reference

PDF documents have been created in subdirectories of

  /storage/strogdon/gentoo-rap/var/tmp/portage/sci-mathematics/sage-doc-9999/work/build_doc/pdf/en/reference

Alternatively, you can open

  /storage/strogdon/gentoo-rap/var/tmp/portage/sci-mathematics/sage-doc-9999/work/build_doc/pdf/en/reference/index.html

for a webpage listing all of the documents.
make[1]: Leaving directory '/storage/strogdon/gentoo-rap/var/tmp/portage/sci-mathematics/sage-doc-9999/work/sage-doc-9999/src/doc'
/storage/strogdon/gentoo-rap/usr/bin/python3.10 -m sage_docbuild website html 
[website  ] building [html]: targets for 1 source files that are out of date
[website  ] updating environment: [config changed ('autodoc_builtin_argspec')] 1 added, 0 changed, 0 removed
[website  ] Merging environment/index files...
[website  ] ... done (0 todos, 1 index, 0 citations, 0 modules)
[website  ] Merging js index files...
[website  ] ... done (21 js index entries)
[website  ] dumping search index in English (code: en)... done
[website  ] The HTML pages are in ../../../build_doc/html/en/website.
Build finished. The built documents can be found in /storage/strogdon/gentoo-rap/var/tmp/portage/sci-mathematics/sage-doc-9999/work/build_doc/html/en/website
```
Is this due to how s-o-g handles the parallel build or to something else?

**Comment by kiwifb** [comment]
I am fairly sure that as part of the improvements to the documentations we requested about the landing page in the jupyter kernel a new "website" target has been added. And the html, or html and pdf, have to be completed first I think.

**Comment by kiwifb** [comment]
Right, it is actually a special that only happens with pdf documentation
```
doc-pdf: doc-pdf-reference doc-pdf-other doc-pdf-website
```
There is actually no reason for it to be built last from what I can see.

**Comment by strogdon** [comment]
OK, I do see it in vanilla but it doesn't appear at the end of the build.

**Comment by strogdon** [comment]
Not to mess around with something that's working but I believe the above `website` items at the end of the build can be removed by removing `doc-pdf-reference` and `doc-pdf-other` from the `doc-pdf-website` target. The website stuff is still built but early on. It is not as nicely present in the build.log as above. For reference
```
grep "\[website  \]" build.log | grep "building \[html\]"

[website  ] building [html]: targets for 1 source files that are out of date
[website  ] building [html]: targets for 1 source files that are out of date
```
Coloring makes searching difficult. So the website stuff is `built` twice, once for the `html` docs and once for the `pdf` docs. This is consistent with vanilla.

**Comment by kiwifb** [comment]
I see, this part is something I added in the current makefile patch which is nicely labelled as "parallel".  I will try without to see if the parallele issues are still present or not.

**Comment by kiwifb** [comment]
I now remember adding that bit in the makefile unilaterally because I thought it was needed. I need to remove it before the final release.

**Comment by kiwifb** [comment]
I think that take care of that issue.
