### ISSUE TITLE
s-o-g often generates pdf docs different from vanilla

### ISSUE THREAD

**Issue by strogdon** [cschwan/sage-on-gentoo#697]
This is the table of contents page for `combinat.pdf`. The formatting is not preserved in the attached but notice that the page numbering is different.

This is from s-o-g:
[s-o-g.pdf](https://github.com/cschwan/sage-on-gentoo/files/8751317/s-o-g.pdf)

This is from vanilla:
[vanilla.pdf](https://github.com/cschwan/sage-on-gentoo/files/8751352/vanilla.pdf)

Discovered this when investigating whether s-o-g had the same undefined reference (https://trac.sagemath.org/ticket/33885) as vanilla. They do have the undefined reference but it appears on different pages.

**Comment by kiwifb** [comment]
Are they both formatted in A4?

**Comment by strogdon** [comment]
No, my latex is suppose to produce `letterpaper` output.

**Comment by kiwifb** [comment]
So, it becomes, are both US letter :)

**Comment by strogdon** [comment]
Yes, I don't see how they could be different. The `vanilla` is clearly `letterpaper` since I can view the `tex` file. I don't immediately have the `s-o-g` `tex` file. The above referenced pages look identical in size when viewed with a pdf viewer.

**Comment by strogdon** [comment]
The spacing after a bold faced paragraph item is different. There is more space with the `s-o-g` result.

**Comment by strogdon** [comment]
Perhaps `sphinx` related. Vanilla uses `sphinx-4.4.0`.

**Comment by kiwifb** [comment]
Are you using sphinx 4.5.0 which is (on my system) in ~arch?

**Comment by strogdon** [comment]
yes

**Comment by strogdon** [comment]
On my system `4.5.0-r1` is stable.

**Comment by kiwifb** [comment]
I'll need to sync later then. I was expecting moving to 4.5.0 to be as troublesome as moving to 4.3 and 4.4 was.

**Comment by kiwifb** [comment]
Closing for now.
