### ISSUE TITLE
dev-gap/io-4.7.1 libtool: Version mismatch error.

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [cschwan/sage-on-gentoo#701]
```
>>> Compiling source in /var/tmp/portage/dev-gap/io-4.7.1/work/io-4.7.1 ...
/usr/bin/remake -j12 -l13
./config.status gen/pkgconfig.h
config.status: creating gen/pkgconfig.h
config.status: gen/pkgconfig.h is unchanged
echo > gen/pkgconfig.h.stamp
   GAC     src/io.c => gen/src/io.lo
/bin/dash /usr/share/gap/libtool --mode=compile x86_64-pc-linux-gnu-gcc -Os -pipe -march=native -fdiagnostics-color=always -frecord-gcc-switches -fexceptions -fstack-clash-protection -fcf-protection=full -fasynchronous-unwind-tables -ftree-vectorize -fplugin=annobin -Waddress -Waggressive-loop-optimizations -Warray-bounds -Wclobbered -Wdate-time -Wformat -Wformat-security -Wfree-nonheap-object -Wnonnull -Wparentheses -Wpointer-arith -Wreturn-local-addr -Wsizeof-pointer-memaccess -Wstrict-aliasing -Wuninitialized -Wunused-value -Wvolatile-register-var -Wno-error=implicit-function-declaration -Wimplicit-function-declaration -MQ gen/src/io.lo -MMD -MP -MF gen/src/io.d -Igen -Os -pipe -march=native -frecord-gcc-switches -fexceptions -fstack-clash-protection -fcf-protection=full -fasynchronous-unwind-tables -ftree-vectorize -fplugin=annobin -ftrivial-auto-var-init=zero -mharden-sls=all -Waddress -Waggressive-loop-optimizations -Warray-bounds -Wclobbered -Wdate-time -Wformat -Wformat-security -Wfree-nonheap-object -Wnonnull -Wparentheses -Wpointer-arith -Wreturn-local-addr -Wsizeof-pointer-memaccess -Wstrict-aliasing -Wuninitialized -Wunused-value -Wvolatile-register-var -Wodr -Wno-error=implicit-function-declaration -Wimplicit-function-declaration -o gen/src/io.lo -I/usr/include/gap -c src/io.c
libtool: Version mismatch error.  This is libtool 2.4.7, but the
libtool: definition of this LT_INIT comes from libtool 2.4.6.
libtool: You should recreate aclocal.m4 with macros from libtool 2.4.7
libtool: and run autoconf again.
remake: directory '/var/tmp/portage/dev-gap/io-4.7.1/work/io-4.7.1'
remake: *** [gen/src/io.lo] error 1
```

**Comment by kiwifb** [comment]
This has been seen before in some way at #690 - have you re-installed gap-core with the new libtool already? If yes, we'll have to see where in `io` there is hard-coding. My main dev machine is off and I won't be able to touch replacements before later today so it may take me until tomorrow before getting to the bottom of it if re-installing gap-core doesn't fix it.

**Comment by Alessandro-Barbieri** [comment]
Isn't a way to properly fix this? Maybe using some `:=`

**Comment by kiwifb** [comment]
Using `:=` on what? `libtools`? One of the issue is of course that upstream wants to use the `libtool` used for installing `gap`. If I could make that go away, there would not be an issue. I would have to look, there are a number of gap packages that use a proper configure that may be fixable by just adding the required stuff in `configure.ac`.

**Comment by kiwifb** [comment]
OK, I had to go and look back at it, `gac` is the component that wants `libtools`. Changing stuff there will require changes to every package using it. Exactly like I said in your commit comment. The only other serious option is to refuse to ship it.
I may have enough freedom to move thing to something like `/usr/lib/gap` similar to what `R` does. I'll look into that.

In any case, I am expecting re-installing `gap-core` would/has fixed your original issue. Right?

**Comment by Alessandro-Barbieri** [comment]
> Using `:=` on what? `libtools`? 

Yes


>One of the issue is of course that upstream wants to use the `libtool` used for installing `gap`. If I could make that go away, there would not be an issue. I would have to look, there are a number of gap packages that use a proper configure that may be fixable by just adding the required stuff in `configure.ac`.

Isn't possible to use the autotools/libtool eclass to force our libtool version?

**Comment by kiwifb** [comment]
It is not that simple. `libtools` has to be configured - as far as my understanding goes - so you would have to add it to `configure.ac` (`LT_INIT`) and then, yes, use the autotools eclass to regenerate things. Going that way suppose that all concerned packages have a `configure.ac` and if not, to provide a minimal one somehow.

**Comment by Alessandro-Barbieri** [comment]
> OK, I had to go and look back at it, `gac` is the component that wants `libtools`. Changing stuff there will require changes to every package using it. Exactly like I said in your commit comment. The only other serious option is to refuse to ship it. I may have enough freedom to move thing to something like `/usr/lib/gap` similar to what `R` does. I'll look into that.
> 
> In any case, I am expecting re-installing `gap-core` would/has fixed your original issue. Right?

Yes

**Comment by kiwifb** [comment]
> > Using `:=` on what? `libtools`?
> 
> Yes
> 

For the record, I just had a quick look. There is no adequate sublot on libtool to make it work. It also would prevent using slibtool instead (we'd probably need a virtual for that anyway).

**Comment by kiwifb** [comment]
Things may not be as bad as I think. But that would require an "artful" upgrade path - again.

**Comment by fingolfin** [comment]
`gac` is not using `libtool` anymore in current GAP versions (4.12.0 and upwards)

So I'd hope this issue here is resolved.

**Comment by kiwifb** [comment]
This definitely can be closed. Nice to know those mismatch will not happen anymore.
