### ISSUE TITLE
maxima version in sage-9999

### ISSUE THREAD

**Issue by strogdon** [cschwan/sage-on-gentoo#702]
Recently (https://github.com/cschwan/sage-on-gentoo/commit/cbcf48fda34a2e352caea6f5c12647caf49a0c13) changes were made to maxima and there was a rev bump from `5.45.1-r3 -> 5.45.1-r4`. Should this bump be reflected in the `sage-9999.ebuild`?

```
>=sci-mathematics/maxima-5.45.1-r3[ecls]
```
emerging `sage-9999` does not pull in the bumped `maxima`.
```
# eix -I maxima
[U] sci-mathematics/maxima
     Available versions:  5.42.1-r1 ~5.45.1-r2^t (~)5.45.1-r4^t[1] ~5.46.0^t ~5.46.0-r1^t[1] {X clisp clozurecl clozurecl64 cmucl ecls emacs gcl gui nls (+)sbcl test tk unicode vtk L10N="${lang/_/-} de es pt pt-BR" PYTHON_SINGLE_TARGET="python3_8 python3_9 python3_10"}
     Installed versions:  5.45.1-r3^t[1](09:40:05 AM 10/12/2021)(X ecls gui nls sbcl unicode -clisp -clozurecl -clozurecl64 -cmucl -emacs -gcl -test -vtk L10N="-de -es -pt -pt-BR" PYTHON_SINGLE_TARGET="python3_9 -python3_8")
     Homepage:            http://maxima.sourceforge.net/
     Description:         Free computer algebra environment based on Macsyma

[1] "sage-on-gentoo" /var/lib/layman/sage-on-gentoo
```
```
# emerge -p @sagemath

These are the packages that would be merged, in order:

Calculating dependencies... done!
[ebuild   R   *] sci-mathematics/sage_setup-9999 
[ebuild   R   #] sci-mathematics/sage-9999 
[ebuild   R   *] sci-mathematics/sage_docbuild-9999 
[ebuild   R   *] sci-mathematics/sage-doc-9999
```

**Comment by kiwifb** [comment]
I don't see it as compulsory but why not. The motivation for r4 was the fact that 5.45.1 uses python for a couple of things and 3.10 was not supported. I cut the bits limiting that use (bye bye vtk support early). That was issue #700 and I experienced it on one of my machine that was switched from python 3.9 to python 3.10 automatically after the 1st of July. I had to specially enable python_single 3.9 in maxima.
