### ISSUE TITLE
sci-mathematics/singular-4.2.1_p3-r2 fails to build

### ISSUE THREAD

**Issue by derekperrin** [cschwan/sage-on-gentoo#704]
Singular fails to build. I've tried `emerge -av @sagemath` after removing everything and starting fresh and I'm still running into this problem. Build log is attached.
[build.log](https://github.com/cschwan/sage-on-gentoo/files/9177262/build.log)

**Comment by kiwifb** [comment]
Are you using gcc-12 by any chance?

**Comment by derekperrin** [comment]
Looks like it. gcc-12.1.1.

**Comment by kiwifb** [comment]
There are fixes for that in later version. I need to check if enabling 4.3.0_p1 is OK with sage.

**Comment by kiwifb** [comment]
Yes, 4.3.0_p1 is safe. I will enable it shortly.

**Comment by derekperrin** [comment]
Thanks!

**Comment by kiwifb** [comment]
You can sync the overlay and try again. You may have to unmerge sage if it is already present to get the updated dependency.

**Comment by derekperrin** [comment]
That did the trick. Singular emerged and sage is in the process of emerging. Thanks again!
