### ISSUE TITLE
Missing "Build multiplication tables" step in shared_meataxe-1.0.1.ebuild

### ISSUE THREAD

**Issue by sheerluck** [cschwan/sage-on-gentoo#709]
According to https://github.com/archlinux/svntogit-community/blob/packages/shared_meataxe/trunk/PKGBUILD we need
```
for i in 2 3 4 5 7 8 9 11 13 16 17 19 23 25 27 29 31 32 37 41 43 47 49 53 59 \
           61 64 67 71 73 79 81 83 89 97 101 103 107 109 113 121 125 \
           127 128 131 137 139 149 151 157 163 167 169 173 179 181 \
           191 193 197 199 211 223 227 229 233 239 241 243 251
do
  LD_PRELOAD=/usr/lib64/libmtx.so /usr/bin/zcv  <(echo "matrix field=$i rows=0 cols=0") /dev/null
done
```

When I did that in `/usr/share/meataxe` I get
```
p002.zzz  p013.zzz  p031.zzz  p059.zzz  p083.zzz  p121.zzz  p151.zzz  p191.zzz  p233.zzz
p003.zzz  p016.zzz  p032.zzz  p061.zzz  p089.zzz  p125.zzz  p157.zzz  p193.zzz  p239.zzz
p004.zzz  p017.zzz  p037.zzz  p064.zzz  p097.zzz  p127.zzz  p163.zzz  p197.zzz  p241.zzz
p005.zzz  p019.zzz  p041.zzz  p067.zzz  p101.zzz  p128.zzz  p167.zzz  p199.zzz  p243.zzz
p007.zzz  p023.zzz  p043.zzz  p071.zzz  p103.zzz  p131.zzz  p169.zzz  p211.zzz  p251.zzz
p008.zzz  p025.zzz  p047.zzz  p073.zzz  p107.zzz  p137.zzz  p173.zzz  p223.zzz
p009.zzz  p027.zzz  p049.zzz  p079.zzz  p109.zzz  p139.zzz  p179.zzz  p227.zzz
p011.zzz  p029.zzz  p053.zzz  p081.zzz  p113.zzz  p149.zzz  p181.zzz  p229.zzz
``` 
and only after that I was able to `sage: M = MatrixSpace(GF(25, "z"), 2, 3)([1, 2, 3, 4, 5, 6])` from `src/sage/matrix/matrix_gfpn_dense.pyx` and finally
```
sage -t --long --random-seed=19 matrix/matrix_gfpn_dense.pyx
    0 tests not run because we ran out of time
    [275 tests, 2.92 s]
----------------------------------------------------------------------
All tests passed!
----------------------------------------------------------------------
```

**Comment by kiwifb** [comment]
I think an update for this has just been pushed. That could be the opportunity to do some more work on this. The whole meataxe thing is quite ugly. I am concerned that you must have executed that as 'root' and that this would need to be post-merge. If it doesn't depend on the architecture, the files could be generated once and shipped as a separate tarball. Otherwise we have to control where the output will land.

**Comment by kiwifb** [comment]
It is very much doing the post-install from sage. https://github.com/vbraun/sage/blob/develop/build/pkgs/meataxe/spkg-postinst.in - it looks like I can control where things go so it should be good.

**Comment by kiwifb** [comment]
I have pushed a 1.0.1-r1 ebuild which should install everything that is needed. Can you test and check it is behaving as you expect.

**Comment by sheerluck** [comment]
I tested it and problem is solved.

**Comment by kiwifb** [comment]
I noticed that in the last two versions of sage in the overlay, I dropped building options for meataxe and bliss bindings. This was not on purpose and will be restored in 9.7. I'll note that building against the latest bliss seems broken so it may need a dependency tweak.
