### ISSUE TITLE
dev-python/jupyter_jsmol-0.2.4-r1->2022.1.0 upgrade issue:

### ISSUE THREAD

**Issue by CaptainBloodz** [cschwan/sage-on-gentoo#712]
sage newcomer here...
First sage 9.6 install here < 1 week.

[dev-python:jupyter_jsmol-2022.1.0:20220922-035012.log.gz](https://github.com/cschwan/sage-on-gentoo/files/9625759/dev-python.jupyter_jsmol-2022.1.0.20220922-035012.log.gz)

What may I be missing?

**Comment by kiwifb** [comment]
Fiddly package that one. Let me see what hits you.

**Comment by kiwifb** [comment]
I happens because you have `yarn` installed I believe. I think there is something I can do about that and now I know why it fails for some people.

**Comment by kiwifb** [comment]
should be fixed by 0442b12d297e1b453ac0c398f0006ccb054dbc09 not that sage 9.6 has left the overlay, you'll be moved to 9.7.

**Comment by CaptainBloodz** [comment]
``edep yarn
 * These packages depend on yarn:
dev-db/pgadmin4-6.13-r1 (sys-apps/yarn)``
yarn is installed here only because of dependencies.

It should be a problem to backup it as binary package for latter restore after temporary removal.

**Comment by kiwifb** [comment]
I added some configuration to the ebuild so that yarn/npm are ignored so it should be OK now.

**Comment by CaptainBloodz** [comment]
> I added some configuration to the ebuild so that yarn/npm are ignored so it should be OK now.

Ya, I've noticed something about npm somewhere in your update:
Initially I enabled it for nodejs package to cancel some reported issue
Hopefully I'll be able to restore initial USE=-npm :).

sage 9.7 is currently upgrading fine :) :). with yarn package installed.
