### ISSUE TITLE
sage-doc-9.7 build fails here...

### ISSUE THREAD

**Issue by CaptainBloodz** [cschwan/sage-on-gentoo#714]
Here's MAKEOPTS="-j1"

`[ Legend : U - final flag setting for installation]
[        : I - package is installed with flag     ]
[ Colors : set, unset                             ]
 * Found these USE flags for sci-mathematics/sage-doc-9.7:
 U I
 "+ - doc-pdf : build and install documentation in pdf format"
 "- - l10n_ca : Catalan"
 "- - l10n_de : German"
 "- - l10n_es : Spanish"
 "+ + l10n_fr : French"
 "- - l10n_hu : Hungarian"
 "- - l10n_it : Italian"
 "- - l10n_ja : Japanese"
 "- - l10n_pt : Portuguese"
 "- - l10n_ru : Russian"
 "- - l10n_tr : Turkish"`

[sci-mathematics:sage-doc-9.7:20220923-165555.log.gz](https://github.com/cschwan/sage-on-gentoo/files/9636564/sci-mathematics.sage-doc-9.7.20220923-165555.log.gz)

**Comment by kiwifb** [comment]
Looks like I forgot something between 9.6 and 9.7. Let me check that.

**Comment by kiwifb** [comment]
Hum... I need to investigate deeper, that will take a bit as I have other things to do this morning. This looks stranger than I expected and why doesn't it fail for me in the development branch?

**Comment by CaptainBloodz** [comment]
Side note: 9.6 builds fine here.

**Comment by kiwifb** [comment]
Well that bit doesn't really make sense
```
FileNotFoundError: [Errno 2] No such file or directory: b'/var/no-tmpfs/portage/sci-mathematics/sage-doc-9.7/work/sage-doc-9.7/src/doc/common'
```
the folder should exist. the definition https://github.com/cschwan/sage-on-gentoo/blob/master/sci-mathematics/sage-doc/sage-doc-9.7.ebuild#L47 was the same in 9.6 I am sure.

**Comment by CaptainBloodz** [comment]
Currently testing:
`mrgp -v sage-doc

These are the packages that would be merged, in reverse order:

Calculating dependencies  ........ done!
[ebuild  N    ~] sci-mathematics/sage-doc-9.7::sage-on-gentoo  USE="doc-pdf" L10N="-ca -de -es -fr -hu -it -ja -pt -ru -tr" 0 KiB`

whereas USE=l10n_fr was set for the failing initial build attempt.

**Comment by CaptainBloodz** [comment]
`/var/no-tmpfs/portage/sci-mathematics/sage-doc-9.7/work/sage-doc-9.7/src/doc/common`
reported missing whereas
```
ll /var/no-tmpfs/portage/sci-mathematics/sage-doc-9.7/work/sage-9.7/src/doc/common/
total 112
-rw-r--r-- 1 portage portage 98082 sept. 20 01:38 python3.inv
drwxr-xr-x 2 portage portage  4096 sept. 20 01:38 static
drwxr-xr-x 3 portage portage  4096 sept. 20 01:38 templates-furo
drwxr-xr-x 3 portage portage  4096 sept. 20 01:38 themes
-rwxr-xr-x 1 portage portage   860 sept. 20 01:38 update-python-inv.sh
```

**Comment by CaptainBloodz** [comment]
```
HTML_DOCS="${WORKDIR}/build_doc/html/*"
DOCS=(
        "${WORKDIR}/build_doc/index.html"
        "${S}/src/doc/common"
)

S="${WORKDIR}/sage-${PV}"
```
Maybe last line is too late?

**Comment by kiwifb** [comment]
Interesting idea and certainly something that should be fixed for consistency. But it seems to end up with the right value in any case.

**Comment by kiwifb** [comment]
In any case, I updated the ebuild to move the definition of `S` just in case.

**Comment by CaptainBloodz** [comment]
Currently testing...
~ 90 mn waiting...

**Comment by kiwifb** [comment]
That's a long time for sage-doc.

**Comment by CaptainBloodz** [comment]
5400 rpm / 4 Gb ram / Dual Core 3.7Ghz
MAKEOPTS=-j1

Done, working better than 9.6 where tutorial failed.

**Comment by kiwifb** [comment]
> Interesting idea and certainly something that should be fixed for consistency. But it seems to end up with the right value in any case.

And now I see what was in front of my eyes and could not see. And I also understand why it doesn't happen in the dev branch. Moving that line was indeed the right fix.

**Comment by CaptainBloodz** [comment]
Like the elephant in the room? It could have been worse, lucky we are on the right hemisphere, 12S, 45E here.

**Comment by kiwifb** [comment]
I believe I am currently about 43S 175E but I was born about 48N 0 (Greenwich meridian pass right through a village near my birth town).
