### ISSUE TITLE
gap-pkg.eclass future features

### ISSUE THREAD

**Issue by kiwifb** [cschwan/sage-on-gentoo#718]
Just a reminder of possible extensions for the eclass.

- function to run the fake `configure` often found in gap packages and which always have the same argument
- function to copy `Makefile.gappkg` automatically and systematically during `src_prepare` 

In both case, the goal is to avoid errors by using boilerplate. Any typo in the boiler plate is reported as something unknown during ebuild/emerge.

**Comment by orlitzky** [comment]
> function to run the fake configure often found in gap packages and which always have the same argument

Done in ::gentoo.

> function to copy Makefile.gappkg automatically and systematically during src_prepare

I tried this but it caused as many new problems as it solved. Most of the Makefiles have been updated upstream instead.

Anyway, closable now.

**Comment by kiwifb** [comment]
It is not even in the overlay anymore :) closing.
