### ISSUE TITLE
No ebuild for Sympy1.10

### ISSUE THREAD

**Issue by n1ghtbyte** [cschwan/sage-on-gentoo#719]
Trying to install sageOnGentoo with profile -> /linux/amd64/17.1/desktop.
In order to install sage 9.7-r1 the ebuild requests for sympy 1.10,
Which is not supported by the gentoo repos (scr: https://packages.gentoo.org/packages/dev-python/sympy).

```
$ doas emerge sage

These are the packages that would be merged, in order:

Calculating dependencies  . .... done!

emerge: there are no ebuilds to satisfy "=dev-python/sympy-1.10*[python_targets_python3_9(-)?,python_targets_python3_10(-)?]".
(dependency required by "sci-mathematics/sage-9.7-r1::sage-on-gentoo" [ebuild])
(dependency required by "sage" [argument])
````
Right now have to unmask the package to get the 9999 version.

**Comment by kiwifb** [comment]
Right, I missed the dropping of sympy-1.10. Let me check if any patches are needed to support that.

**Comment by kiwifb** [comment]
It breaks the results of two doctests (answer formatting) but not any functionality. So, I'll just allow sympy 1.11* for 9.7.

**Comment by kiwifb** [comment]
You should be able to merge sage 9.7-r1 without problems now.

**Comment by n1ghtbyte** [comment]
All fine, thanks!
