### ISSUE TITLE
sphinx-5.2.patch fails (9.8.beta2)

### ISSUE THREAD

**Issue by strogdon** [cschwan/sage-on-gentoo#720]
```
 * Applying sphinx-5.2.patch ...
patching file sage_docbuild/ext/multidocs.py
Hunk #1 FAILED at 146.
1 out of 1 hunk FAILED -- saving rejects to file sage_docbuild/ext/multidocs.py.rej
```
I haven't investigated further.

**Comment by kiwifb** [comment]
That patch should not be there. Sphinx 5.2 has been merged upstream.

**Comment by kiwifb** [comment]
And it looks like I left it. Which is strange considering that I had no issue on the vbraun branch.

**Comment by kiwifb** [comment]
Was looking at DEPEND rather than PATCHES :P it is not there. You should not see that.

**Comment by strogdon** [comment]
I don't understand. Which `sphinx` should be used - `sphinx-5.2.3` was pulled in? And from `sage_docbuild` it appears the patch is to be applied.
```   # only apply for sphinx 5.2+ - there are incompatibilities with older versions
    if has_version -r ">=dev-python/sphinx-5.2.0" ; then
        PATCHES+=( "${FILESDIR}/sphinx-5.2.patch" )
    fi
```

**Comment by strogdon** [comment]
I see, it appear (vbraun branch) that the above `has_version` if block should be removed.

**Comment by kiwifb** [comment]
OK, I don't know why that part was not merged. Looking for other differences before doing anything.

**Comment by kiwifb** [comment]
This is so weird. Only half the commit is merged. Fixing.

**Comment by kiwifb** [comment]
Fixed. sync and check please.

**Comment by strogdon** [comment]
This works.
