### ISSUE TITLE
sci-mathematics/sage-doc-9.7 failed to build

### ISSUE THREAD

**Issue by hackitforfun** [cschwan/sage-on-gentoo#722]
It has been some time since the said package failed to build with each system update. It seems that the problem is the following line in the log file, which is also attached.

`[plotting ] TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''`
[build.log](https://github.com/cschwan/sage-on-gentoo/files/9852356/build.log)

**Comment by kiwifb** [comment]
Right. What version of matplotlib and numpy do you  have? Oh, I see indication of matplotlib 3.6, are you on ~amd64?

**Comment by hackitforfun** [comment]
Thanks for the fast response, my matplotlib version is 3.6.1, and yes, I am on ~amd64.

**Comment by kiwifb** [comment]
There may be incompatibilities with matplotlib 3.6, I will check ASAP.

**Comment by kiwifb** [comment]
https://trac.sagemath.org/ticket/34668 has some stuff but I am not sure it is enough for what I see. I will check once I am at my desk.

**Comment by kiwifb** [comment]
OK, cannot quite try it. So, I am counting on you :) I have pushed sage-9.7-r2 which includes the bits to support matplotlib 3.6. So, update sage and then try sage-doc again. If it still fails, I may have to ask upstream as it will almost certainly affect their building of the doc as well.

**Comment by kiwifb** [comment]
Actually ran the tests I could and it still fails with the current sage 9.8 beta. Trying to figure out which bits is causing the breakage.

**Comment by kiwifb** [comment]
I think I got the guilty bits. Further testing to be done.

**Comment by kiwifb** [comment]
Should be fixed by 2b422a66279c390433ca79ae66c343a3b17c6910 which update 9.7 to r3. Sorry for the rebuilds. Following up the fix upstream at https://trac.sagemath.org/ticket/34693

**Comment by hackitforfun** [comment]
I just updated the system, and can now confirm that everything works beautifully. Thank you :)
