### ISSUE TITLE
9.8.rc0 fails with 'sage/ext/interpreters/wrapper_rdf.pxd' not found

### ISSUE THREAD

**Issue by strogdon** [cschwan/sage-on-gentoo#729]
After dealing with `gap-core` and significant system updates I finally see
```
Error compiling Cython file:
------------------------------------------------------------
...
from memory_allocator cimport MemoryAllocator

from sage.rings.real_double import RDF
from sage.libs.gsl.all cimport *
from sage.misc.sageinspect import sage_getargspec
from sage.ext.interpreters.wrapper_rdf cimport Wrapper_rdf
^
------------------------------------------------------------

sage/calculus/integration.pyx:35:0: 'sage/ext/interpreters/wrapper_rdf.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...
from memory_allocator cimport MemoryAllocator

from sage.rings.real_double import RDF
from sage.libs.gsl.all cimport *
from sage.misc.sageinspect import sage_getargspec
from sage.ext.interpreters.wrapper_rdf cimport Wrapper_rdf
^
------------------------------------------------------------

sage/calculus/integration.pyx:35:0: 'sage/ext/interpreters/wrapper_rdf/Wrapper_rdf.pxd' not found
```
I haven't see this before.

**Comment by kiwifb** [comment]
I meant to write something about `gap-core`. At least it should have been much easier to deal with than previous gap upgrades. This I haven't seen before. I'll have to check whether I missed something in the last push.

**Comment by strogdon** [comment]
Surrounding `gap-core` I had to eventually do an `emerge @preserved-rebuild`  (or perhaps it was updating world?) and `giac` had to be rebuilt which couldn't be done until after I manually rebuilt `gmp-ecm`. I'm still not sure what was up.

**Comment by kiwifb** [comment]
Did it come with something more than `gap-core` being a blocker? I only had to do `emerge -C gap-core atlasrep` and it was all good.

**Comment by strogdon** [comment]
I'm sure it was unrelated to `gap-core`. I did `emerge -C gap-core` and later on updated `atlasrep`. After removing `gap-core` a  `preserved-rebuild` was required which I deferred until after I tried to build sage. Perhaps this was my pronlem.

**Comment by kiwifb** [comment]
I cannot reproduce the issue. What version of cython are you using?

**Comment by strogdon** [comment]
```
# eix -I cython
[I] dev-python/cython
     Available versions:  0.29.32^t ~0.29.33^t {doc emacs test PYTHON_TARGETS="pypy3 python3_9 python3_10 python3_11"}
     Installed versions:  0.29.32^t(11:28:26 PM 01/29/2023)(-doc -emacs -test PYTHON_TARGETS="python3_10 python3_11 -pypy3 -python3_9")
     Homepage:            https://cython.org/ https://github.com/cython/cython/ https://pypi.org/project/Cython/
     Description:         A Python to C compile
```

**Comment by kiwifb** [comment]
Ouch, an issue with giac and gmp-ecm while building documentation. This is new. It looks like the latest update of gmp may have broken some compatibility without a version bump.  There is a missing symbol.

For cython, can you try to upgrade, I may have to raise the dependency.

**Comment by strogdon** [comment]
Same problem with `cython-0.29.33`?

**Comment by strogdon** [comment]
Are both `wrapper_rdf.pxd` and `Wrapper_rdf.pxd` to be found under `work/sage-9999`?  If so, then I don't have them.

**Comment by kiwifb** [comment]
They should be generated by a call to sage_setup.

**Comment by strogdon** [comment]
The `vbraun` branch fails here as in  https://github.com/cschwan/sage-on-gentoo/issues/729#issue-1563022184

**Comment by kiwifb** [comment]
Could I have a full log? You can send it to me privately> These seems a bit strange, there is probably a dependency missing or the wrong level that interfere with autogen, but I need to see what happen at that level.

**Comment by strogdon** [comment]
log file sent. Let me know if not received.

**Comment by kiwifb** [comment]
Got it. And it is a change that was probably not in the previous beta. It didn't happen to me because it was finding it from a previous install. Which is why I should test install from scratch more often. After https://github.com/sagemath/sage/commit/2f4b0539a17cf2dd9ff53ccb85a3b7f8f218e6a8 `autogen_all()` is not run anymore for the `build_ext` target, which is what distutils-r1 does during compile. Fix coming.

**Comment by kiwifb** [comment]
Ready for testing.

**Comment by strogdon** [comment]
Sage now builds. I didn't see an issue with the documentation. It seems to build just fine.

**Comment by kiwifb** [comment]
For the doc I just had to rebuild gmp-ecm (and giac for safety).
