### ISSUE TITLE
Issues with sci-mathematics/sage-9.7-r4 upgrade

### ISSUE THREAD

**Issue by CaptainBloodz** [cschwan/sage-on-gentoo#731]
mrg sage

 * IMPORTANT: 4 config files in '/etc/portage' need updating.
 * See the CONFIGURATION FILES and CONFIGURATION FILES UPDATE TOOLS
 * sections of the emerge man page to learn how to update config files.

These are the packages that would be merged, in reverse order:

Calculating dependencies  . .......... . !!! /etc/portage/package.env references non-existent file: /etc/portage/env/unchecked
...... done!
[ebuild     U ~] sci-mathematics/sage-9.7-r4 [9.7-r3]
[ebuild     U ~]  dev-gap/gap-recommended-4.12.2 [4.11.1]
[ebuild     U ~]   dev-gap/polenta-1.3.10 [1.3.9]
[ebuild     U ~]    dev-gap/radiroot-2.9 [2.8-r3]
[ebuild     U ~]   dev-gap/resclasses-4.7.3 [4.7.2-r1]
[ebuild     U ~]    dev-gap/utils-0.81 [0.69]
[ebuild     U ~]   dev-gap/Alnuth-3.2.1 [3.1.2]
[ebuild     U ~]    dev-gap/polycyclic-2.16-r1 [2.16]
[ebuild     U ~]   dev-gap/tomlib-1.2.9-r1 [1.2.9]
[ebuild     U ~]   dev-gap/ctbllib-1.3.4 [1.2_p2-r6]
[nomerge       ] dev-gap/utils-0.81 [0.69]
[ebuild     U ~]  dev-gap/AutoDoc-2022.10.20 [2020.08.11]
[nomerge       ] dev-gap/gap-recommended-4.12.2 [4.11.1]
[ebuild     U ~]  dev-gap/sophus-1.27 [1.24-r3]
[ebuild     U ~]  dev-gap/laguna-3.9.5 [3.9.3-r1]
[ebuild     U ~]  dev-gap/irredsol-1.4.4 [1.4.2]
[ebuild     U ~]  dev-gap/fga-1.4.0-r4 [1.4.0-r3]
[ebuild     U ~]  dev-gap/factint-1.6.3-r1 [1.6.3]
[ebuild     U ~]  dev-gap/crisp-1.4.6 [1.4.5]
[ebuild     U ~]  dev-gap/autpgrp-1.11 [1.10.2]
[nomerge       ] dev-gap/tomlib-1.2.9-r1 [1.2.9]
[nomerge       ]  dev-gap/atlasrep-2.1_p0-r2 
[nomerge       ]   sci-mathematics/gap-core-4.11.1 
[ebuild     U ~]    dev-gap/SmallGrp-1.5.1 [1.4.2]
[ebuild     U ~]    dev-gap/primgrp-3.4.3 [3.4.1]
[ebuild     U ~]     dev-gap/GAPDoc-1.6.6 [1.6.4]
[ebuild     U ~]    dev-gap/transgrp-3.6.3 [3.5]
[ebuild     U ~]     sci-mathematics/gap-4.12.2-r1 [4.11.1] CPU_FLAGS_X86="popcnt%*" 
[blocks B      ] sci-mathematics/gap-core ("sci-mathematics/gap-core" is soft blocking sci-mathematics/gap-4.12.2-r1)

 * Error: The above package list contains packages which cannot be
 * installed at the same time on the same system.

  (sci-mathematics/gap-core-4.11.1:0/0::sage-on-gentoo, installed) pulled in by
    >=sci-mathematics/gap-core-4.11.1 required by (dev-gap/io-4.7.1:0/0::sage-on-gentoo, installed) USE="" ABI_X86="(64)"
    >=sci-mathematics/gap-core-4.11.0 required by (dev-gap/atlasrep-2.1_p0-r2:0/0::sage-on-gentoo, installed) USE="" ABI_X86="(64)"

  (sci-mathematics/gap-4.12.2-r1:0/8::sage-on-gentoo, ebuild scheduled for merge) pulled in by
    >=sci-mathematics/gap-4.12.0 required by (dev-gap/radiroot-2.9:0/0::sage-on-gentoo, ebuild scheduled for merge) USE="" ABI_X86="(64)"
    >=sci-mathematics/gap-4.12.0 required by (dev-gap/factint-1.6.3-r1:0/0::sage-on-gentoo, ebuild scheduled for merge) USE="" ABI_X86="(64)"
    >=sci-mathematics/gap-4.12.0 required by (dev-gap/laguna-3.9.5:0/0::sage-on-gentoo, ebuild scheduled for merge) USE="" ABI_X86="(64)"
    >=sci-mathematics/gap-4.12.0 required by (dev-gap/tomlib-1.2.9-r1:0/0::sage-on-gentoo, ebuild scheduled for merge) USE="" ABI_X86="(64)"
    >=sci-mathematics/gap-4.12.0 required by (dev-gap/GAPDoc-1.6.6:0/0::sage-on-gentoo, ebuild scheduled for merge) USE="" ABI_X86="(64)"
    ~sci-mathematics/gap-4.12.2 required by (dev-gap/gap-recommended-4.12.2:0/0::sage-on-gentoo, ebuild scheduled for merge) USE="" ABI_X86="(64)"
    >=sci-mathematics/gap-4.12.0 required by (dev-gap/ctbllib-1.3.4:0/0::sage-on-gentoo, ebuild scheduled for merge) USE="" ABI_X86="(64)"
    >=sci-mathematics/gap-4.12.0 required by (dev-gap/crisp-1.4.6:0/0::sage-on-gentoo, ebuild scheduled for merge) USE="" ABI_X86="(64)"
    >=sci-mathematics/gap-4.12.0 required by (dev-gap/sophus-1.27:0/0::sage-on-gentoo, ebuild scheduled for merge) USE="" ABI_X86="(64)"
    >=sci-mathematics/gap-4.12.0 required by (dev-gap/utils-0.81:0/0::sage-on-gentoo, ebuild scheduled for merge) USE="" ABI_X86="(64)"
    >=sci-mathematics/gap-4.12.0 required by (dev-gap/polenta-1.3.10:0/0::sage-on-gentoo, ebuild scheduled for merge) USE="" ABI_X86="(64)"
    >=sci-mathematics/gap-4.12.0 required by (dev-gap/AutoDoc-2022.10.20:0/0::sage-on-gentoo, ebuild scheduled for merge) USE="" ABI_X86="(64)"
    >=sci-mathematics/gap-4.12.0 required by (dev-gap/SmallGrp-1.5.1:0/0::sage-on-gentoo, ebuild scheduled for merge) USE="" ABI_X86="(64)"
    >=sci-mathematics/gap-4.12.0 required by (dev-gap/fga-1.4.0-r4:0/0::sage-on-gentoo, ebuild scheduled for merge) USE="" ABI_X86="(64)"
    >=sci-mathematics/gap-4.12.0 required by (dev-gap/resclasses-4.7.3:0/0::sage-on-gentoo, ebuild scheduled for merge) USE="" ABI_X86="(64)"
    >=sci-mathematics/gap-4.12.0 required by (dev-gap/polycyclic-2.16-r1:0/0::sage-on-gentoo, ebuild scheduled for merge) USE="" ABI_X86="(64)"
    ~sci-mathematics/gap-4.12.2 required by (sci-mathematics/sage-9.7-r4:0/0::sage-on-gentoo, ebuild scheduled for merge) USE="X bliss -debug doc jmol latex meataxe -test" ABI_X86="(64)" PYTHON_TARGETS="python3_10 -python3_9"
    >=sci-mathematics/gap-4.12.2 required by (dev-gap/primgrp-3.4.3:0/0::sage-on-gentoo, ebuild scheduled for merge) USE="" ABI_X86="(64)"
    >=sci-mathematics/gap-4.12.0 required by (dev-gap/irredsol-1.4.4:0/0::sage-on-gentoo, ebuild scheduled for merge) USE="" ABI_X86="(64)"
    >=sci-mathematics/gap-4.12.0 required by (dev-gap/Alnuth-3.2.1:0/0::sage-on-gentoo, ebuild scheduled for merge) USE="" ABI_X86="(64)"
    >=sci-mathematics/gap-4.12.0 required by (dev-gap/autpgrp-1.11:0/0::sage-on-gentoo, ebuild scheduled for merge) USE="" ABI_X86="(64)"
    >=sci-mathematics/gap-4.12.0 required by (dev-gap/transgrp-3.6.3:0/0::sage-on-gentoo, ebuild scheduled for merge) USE="" ABI_X86="(64)"

For more information about Blocked Packages, please refer to the following
section of the Gentoo Linux x86 Handbook (architecture is irrelevant):

https://wiki.gentoo.org/wiki/Handbook:X86/Working/Portage#Blocked_packages

**Comment by CaptainBloodz** [comment]
Manual

rgC sci-mathematics/gap-core
 * This action can remove important packages! In order to be safer, use
 * `emerge -pv --depclean <atom>` to check for reverse dependencies before
 * removing packages.

 sci-mathematics/gap-core
    selected: 4.11.1 
   protected: none 
     omitted: none 

All selected packages: =sci-mathematics/gap-core-4.11.1

>>> 'Selected' packages are slated for removal.
>>> 'Protected' and 'omitted' packages will not be removed.

>>> Unmerging (1 of 1) sci-mathematics/gap-core-4.11.1...
>>> needed   sym /usr/lib64/libgap.so.0
>>> needed   obj /usr/lib64/libgap.so.0.0.0
 * Regenerating site-gentoo.el for GNU Emacs (postrm) ...                                                                                [ ok ]
 * ... no changes.

 * GNU info directory index is up-to-date.

!!! existing preserved libs:
>>> package: sci-mathematics/gap-core-4.11.1
 *  - /usr/lib64/libgap.so.0
 *  - /usr/lib64/libgap.so.0.0.0
 *      used by /usr/lib/python3.10/site-packages/sage/coding/codecan/codecan.cpython-310-x86_64-linux-gnu.so (sci-mathematics/sage-9.7-r3)
 *      used by /usr/lib/python3.10/site-packages/sage/combinat/enumeration_mod_permgroup.cpython-310-x86_64-linux-gnu.so (sci-mathematics/sage-9.7-r3)
 *      used by /usr/lib/python3.10/site-packages/sage/combinat/root_system/reflection_group_c.cpython-310-x86_64-linux-gnu.so (sci-mathematics/sage-9.7-r3)
 *      used by 22 other files

did the trick.

**Comment by kiwifb** [comment]
On the machine I tested it, I had less gap packages installed and the upgrade did just go smoothly without needing to remove the blocker. On  a machine with the development branch (sage-9999) where I have many more gap packages installed
```
emerge -C gap-core atlasrep
```
was enough to get the update to go smoothly.

**Comment by CaptainBloodz** [comment]
One problem here:

amd64 ~ # eix sci-mathematics/eclib
[U] sci-mathematics/eclib
     Available versions:  20221012(0/11)^t {boost flint minimal test}
     Installed versions:  20220621(0/10)^t(14:11:15 19/12/2022)(flint minimal -boost -static-libs -test)
     Homepage:            https://github.com/JohnCremona/eclib
     Description:         Programs for elliptic curves defined over the rational numbers

amd64 ~ # emerge -1 sci-mathematics/eclib

 * IMPORTANT: 6 config files in '/etc/portage' need updating.
 * See the CONFIGURATION FILES and CONFIGURATION FILES UPDATE TOOLS
 * sections of the emerge man page to learn how to update config files.

These are the packages that would be merged, in reverse order:

Calculating dependencies  !!! /etc/portage/package.env references non-existent file: /etc/portage/env/unchecked
...... ... done!
[ebuild     U  ] sci-mathematics/eclib-20221012 [20220621]

!!! Multiple package instances within a single package slot have been pulled
!!! into the dependency graph, resulting in a slot conflict:

sci-mathematics/eclib:0

  (sci-mathematics/eclib-20221012:0/11::gentoo, ebuild scheduled for merge) USE="-boost flint minimal -test" ABI_X86="(64)" pulled in by
    sci-mathematics/eclib (Argument)

  (sci-mathematics/eclib-20220621:0/10::gentoo, installed) USE="-boost flint minimal -static-libs -test" ABI_X86="(64)" pulled in by
    ~sci-mathematics/eclib-20220621[flint] required by (sci-mathematics/sage-9.7-r4:0/0::sage-on-gentoo, installed) USE="X bliss -debug doc jmol latex meataxe -test" ABI_X86="(64)" PYTHON_TARGETS="python3_10 -python3_9"
    ^                      ^^^^^^^^                                                                                                                                                                                                                                                                                                                                                                                                                                                                


It may be possible to solve this problem by using package.mask to
prevent one of those packages from being selected. However, it is also
possible that conflicting dependencies exist such that they are
impossible to satisfy simultaneously.  If such a conflict exists in
the dependencies of two different packages, then those packages can
not be installed simultaneously. You may want to try a larger value of
the --backtrack option, such as --backtrack=30, in order to see if
that will solve this conflict automatically.

For more information, see MASKED PACKAGES section in the emerge man
page or refer to the Gentoo Handbook.

**Comment by kiwifb** [comment]
I have seen the stabilisation bug being opened but I haven't checked for compatibility yet. The current dependency in sage is
```
~sci-mathematics/eclib-20220621[flint]
```
so you cannot upgrade.
I will look to see if we can go "up".

**Comment by kiwifb** [comment]
It compile at least. Now I will test is a bit further at run time. If I allow the newer eclib, there will be a -r5 bump. If it doesn't work out, I'll import the old eclib in the overlay.

**Comment by kiwifb** [comment]
It looks OK, no new strange errors. Bump is coming shortly.

**Comment by kiwifb** [comment]
Should be fixed by 7afaa411da4217ed119174a718c9dc61b2a64fa3

**Comment by kiwifb** [comment]
9.8 is out. Please open new issues if you have trouble with it. One issue per problems thank you.

**Comment by CaptainBloodz** [comment]
seamless install 4 both rev-bump & release. Thks.
