### ISSUE TITLE
sage-conf-9.8 ebuild wants sage-conf-9.7.patch

### ISSUE THREAD

**Issue by dhalsimax** [cschwan/sage-on-gentoo#734]
This seems almost an oversight. There is a patch sage-conf-9.8.patch but the ebuild for 9.8 currently search for a version 9.7 patch. I've tried to modify the ebuild to choose the correct patch file sage-conf-9.8.patch provided with current version but it doesn't build. So I've recovered the old sage-conf-9.7.patch and added to files filder and I've been succesful building sage-conf 9.8. I'm curently re emerging sage 9.8 to check. However the issue is not if sage builds or wont builds  this should be fixed. Thanks for your patience.

**Comment by kiwifb** [comment]
You are right. The confusing naming must be because a change was reverted before the 9.8 release. I'll fix this ASAP. Thanks for reporting.

**Comment by kiwifb** [comment]
Fixed by 38764ef1e2667d0073a0b13cb6ebc797b33b784f
