### ISSUE TITLE
Python 3.11 and Maxima

### ISSUE THREAD

**Issue by kcning** [cschwan/sage-on-gentoo#738]
Hello, 

Thank you so much for maintaining this overlay.

A few days ago the default Python [target](https://www.gentoo.org/support/news-items/2023-04-02-python3-11.html) has become 3.11. It would be nice to only keep 1 Python version on a system.
Currently, the only dependency of sage-9.8 that isn't compatible with Python 3.11 is maxima-5.45.1-r4.

Would it be possible to:
1. either make maxima-5.45.1-r4 compatible with Python 3.11
2. or bump maxima version to 5.46.0-r1 maintained officially by Gentoo?

**Comment by kiwifb** [comment]
Fixed by ae9cc401d0df4a55528c623767b18c07e4a30c93 I am wondering if I had in fact sorted long ago and just forgot to bump PYTHON_COMPAT. Let me know if there are any issues.

**Comment by kcning** [comment]
So far no issues. Thank you!
