### ISSUE TITLE
Suiteparseconfid build error(cmake could not find blas)

### ISSUE THREAD

**Issue by 2403772980ygy** [cschwan/sage-on-gentoo#748]
Upon evoking `emerge --ask sage`, It fails with the following error.

```
-- Could NOT find BLAS (missing: BLAS_LIBRARIES) 
-- Looking for 32-bit Apple BLAS
-- Could NOT find BLAS (missing: BLAS_LIBRARIES) 
-- Looking for ARM 32-bit BLAS
-- Could NOT find BLAS (missing: BLAS_LIBRARIES) 
-- Looking for IBM ESSL 32-bit BLAS
-- Could NOT find BLAS (missing: BLAS_LIBRARIES) 
-- Looking for 32-bit OpenBLAS
-- Could NOT find BLAS (missing: BLAS_LIBRARIES) 
-- Looking for 32-bit FLAME (BLIS) BLAS
-- Could NOT find BLAS (missing: BLAS_LIBRARIES) 
-- Looking for any 32-bit BLAS
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find BLAS (missing: BLAS_LIBRARIES)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake/Modules/FindBLAS.cmake:1353 (find_package_handle_standard_args)
  cmake_modules/SuiteSparseBLAS.cmake:216 (find_package)
  CMakeLists.txt:65 (include)
```

I guess this can be fixed by adding blas and cblas to the BDEPS of the package,

**Comment by 2403772980ygy** [comment]
I guess running `emerge --resume` and then `emerge sage` can possibly solve the problem as it have a chance to postpone the installation of the failed package, in this case suiteparseconfig.

**Comment by 2403772980ygy** [comment]
A more direct fix can be `emerge -1 blas cblas`

**Comment by kiwifb** [comment]
Thanks for reporting. And yes it looks like a BDEPEND may be appropriate. I do not think the library links to blas but some headers may be enabled by it. I will check a few more things (and in particular, what other thing that cmake file checks for) before taking action.

**Comment by kiwifb** [comment]
I think blas should qualify as a RDEPEND because it ships headers relying on it. So, it will be DEPEND/RDEPEND.

**Comment by kiwifb** [comment]
Fixed by 25f2067307eb25f777a069ddf492d09df988ed83

**Comment by kiwifb** [comment]
Actually, after some thinking, your assessment of a BDEPEND is probably the way to go. Packages using the blas interface should depend on blas themselves.

**Comment by 2403772980ygy** [comment]
I perceived that the absence of BLAS causes build failure, so in package management it should be seen as a BDEPEND.

Anyways, thanks for the quick fix.(Although fixing it with `--oneshot` is not that hard, it's better that everything is automated.)

**Comment by kiwifb** [comment]
Further tracking of the issue with some of its more refined implication in bugzilla now that suitesparse 7 is being moved to the main tree.
https://bugs.gentoo.org/show_bug.cgi?id=908851
