### ISSUE TITLE
dev-python/lrcalc is in ::gentoo

### ISSUE THREAD

**Issue by orlitzky** [cschwan/sage-on-gentoo#757]
I just imported this and opened https://github.com/sagemath/sage/pull/36316 to let Sage use it.

**Comment by kiwifb** [comment]
I had a few clean up (nothing major) in the vbraun branch of the overlay waiting to be merged. Did you apply such corrections?

**Comment by kiwifb** [comment]
https://github.com/cschwan/sage-on-gentoo/blob/vbraun/dev-python/lrcalc/lrcalc-2.1.ebuild

**Comment by orlitzky** [comment]
> I had a few clean up (nothing major) in the vbraun branch of the overlay waiting to be merged. Did you apply such corrections?

I didn't check the vbraun branch, but it looks like I rediscovered the same set of changes. Here's what I remember doing:

* Set `DISTUTILS_EXT=1`
* Move cython to `BDEPEND`
* Dropped version constraint for cython
* Added `+` to the `LICENSE`
* Fixed `long_description_type` -> `long_description_content_type` in `setup.py` (and emailed Anders about it)

**Comment by kiwifb** [comment]
Removed from the overlay.
