### ISSUE TITLE
Invalid syntax (from merge conflict markers) in sci-mathematics/sage

### ISSUE THREAD

**Issue by thesamesam** [cschwan/sage-on-gentoo#758]
At https://github.com/cschwan/sage-on-gentoo/blob/master/sci-mathematics/sage/sage-10.1-r2.ebuild#L155, there's a bunch of merge conflict markers originating from c61428cdd42fd49b2066c828fad0c3468129788b.

Please fix these and ideally setup the pkgcheck CI action so you can try catch these too (see https://github.com/thesamesam/overlay/tree/master/.github/workflows for an example).

I've dropped the repo from api.git for now as it seems to be confusing our scripts. Please make a PR at https://github.com/gentoo/api-gentoo-org/ to restore it once fixed. Thanks!

**Comment by kiwifb** [comment]
Thanks for the heads up. I may have been inattentive to to the git message. It complained about there being multiple files I thought.

**Comment by kiwifb** [comment]
Fix by cb32ca1e7896ad0b5b9d2d3cd9104b66c2750031

**Comment by kiwifb** [comment]
And PR is waiting at https://github.com/gentoo/api-gentoo-org/pull/625

**Comment by kiwifb** [comment]
New PR at https://github.com/gentoo/api-gentoo-org/pull/626 should be better.

**Comment by thesamesam** [comment]
All sorted now - sorry for missing the 2nd PR. Thank you!
