### ISSUE TITLE
 MPL-3.8.0.patch fails with 10.2.beta4

### ISSUE THREAD

**Issue by strogdon** [cschwan/sage-on-gentoo#760]
```
 * Applying MPL-3.8.0.patch ...
patching file sage/plot/graphics.py
Hunk #1 FAILED at 36.
Hunk #2 FAILED at 2874.
2 out of 2 hunks FAILED -- saving rejects to file sage/plot/graphics.py.rej
 [ !! ]
```
It appears that the `graphics.py` patch in `MPL-3.8.0.patch` is in `graphics.py` source for `10.2.beta4`.

**Comment by strogdon** [comment]
It looks like the patch isn't needed at all since only `graphics.py` is patched.

**Comment by kiwifb** [comment]
Hum, that's a merge that did not. That line should have been gone. Let me check things.

**Comment by kiwifb** [comment]
Fixed in master.

**Comment by strogdon** [comment]
I still have this issue. master has
```
PATCHES=(
	"${FILESDIR}"/MPL-3.8.0.patch
	"${FILESDIR}"/${PN}-9.2-env.patch
	"${FILESDIR}"/sage_exec-9.3.patch
	"${FILESDIR}"/${PN}-9.3-forcejavatmp.patch
	"${FILESDIR}"/${PN}-10.1-neutering.patch
	"${FILESDIR}"/${PN}-9.8-build_ext.patch
)
```
while vbraun has
```
PATCHES=(
	"${FILESDIR}"/${PN}-9.2-env.patch
	"${FILESDIR}"/sage_exec-9.3.patch
	"${FILESDIR}"/${PN}-9.3-forcejavatmp.patch
	"${FILESDIR}"/${PN}-10.1-neutering.patch
	"${FILESDIR}"/${PN}-9.8-build_ext.patch
)
```

**Comment by kiwifb** [comment]
I think that's because, master is not synchronising at api-gentoo where repos are mirrored. This happened because of #758 and I have a PR to restore at https://github.com/gentoo/api-gentoo-org/pull/625

**Comment by kiwifb** [comment]
Embarrassingly, I may have forgotten to push. Anyway, 10.2.beta5 is moving to cython-3. Fasten your seatbelts.

**Comment by strogdon** [comment]
When I sync I'm assuming I sync with https://github.com/gentoo-mirror/sage-on-gentoo. If so then there may be an issue since the mirror hasn't been updated in 4 days.
