### ISSUE TITLE
Missing tdlib-related files with 10.2.beta5

### ISSUE THREAD

**Issue by strogdon** [cschwan/sage-on-gentoo#761]
Finally I was able to get an up to date s-o-g repo by a pull from https://github.com/cschwan/sage-on-gentoo and fixing the merge conflicts. I am able to build the subject beta. The following files

```
all__sagemath_tdlib.py
sage_tdlib.cpp
tdlib.pyx
```
which are located under `$WORKDIR/git-checkout/src/sage/graphs/graph_decompositions`
during the `prepare` phase are not copied to `$WORKDIR/sagemath-standard-9999/sage/graphs/graph_decompositions` during the `prepare` phase. This results in the following doctest failures
```
sage -t --long --random-seed=228840340721550587172536863901564969538 /usr/lib/python3.11/site-packages/sage_setup/find.py  # 2 doctests failed
sage -t --long --random-seed=228840340721550587172536863901564969538 /usr/lib/python3.11/site-packages/sage/misc/package_dir.py  # 1 doctest failed
```
If I copy the files manually to the desired location and proceed with the build the about doctests do not fail.

I also have numerous `QA Notices`. I don't know if they are new.

**Comment by kiwifb** [comment]
I am aware of these files being missing. It is a consequence of the work I pushed Matthias to do about making proper sdist. I was more focused about the various sage package building properly out of the box than I was about the doctesting and I discovered those after the fact. It is harmless in and of itself and is in the category "should not be tested" in sage-on-gentoo/sage-on-distro.

We have had QA warnings about compilation of cython generated code for a long time.

**Comment by strogdon** [comment]
I believe I have seen something about making proper sdist. I get similar failures here when doctesting `misc/lazy_import.pyx` and `features/pkg_systems.py` since I do not have `pip` installed. `pip` is not needed. Importantly, I was able to build Sage. I don't usually do a build where I keep the `build.log` so I hadn't seen the QA warnings.
