### ISSUE TITLE
dev-python/pandas-1.5.2 conflict with cython-3.0.0-r1

### ISSUE THREAD

**Issue by strogdon** [cschwan/sage-on-gentoo#762]
Unless I'm missing something there is the above conflict. I built Sage with the above cython
```
[I] dev-python/cython
     Available versions:  0.29.36^t 3.0.0-r1^t ~3.0.2^t ~3.0.2-r1^t {debug doc emacs test PYTHON_TARGETS="pypy3 python3_10 python3_11 python3_12"}
     Installed versions:  3.0.0-r1^t(10:47:24 AM 10/05/2023)(-debug -doc -test PYTHON_TARGETS="python3_11 -pypy3 -python3_10 -python3_12")
     Homepage:            https://cython.org/ https://github.com/cython/cython/ https://pypi.org/project/Cython/
     Description:         A Python to C compiler
```
And then after `emerge -puDN world` I have
```
These are the packages that would be merged, in order:

[ebuild     UD ] dev-python/cython-0.29.36 [3.0.0-r1] USE="-emacs%" 
```
which appears to be due to `pandas`
```
# emerge -pv pandas

These are the packages that would be merged, in order:

[ebuild     UD ] dev-python/cython-0.29.36::gentoo [3.0.0-r1::gentoo] USE="-debug -doc -emacs% -test" PYTHON_TARGETS="python3_11 (-pypy3) -python3_10 (-python3_12)" 0 KiB
[ebuild   R    ] dev-python/pandas-1.5.2::gentoo  USE="X (-doc) -full-support -minimal -test" PYTHON_TARGETS="python3_11 -python3_10" 0 KiB
```
```
equery d cython
...
dev-python/pandas-1.5.2 (>=dev-python/cython-0.29.32[python_targets_python3_10(-)?,python_targets_python3_11(-)?])
                        (<dev-python/cython-3[python_targets_python3_10(-)?,python_targets_python3_11(-)?])
...
```

**Comment by kiwifb** [comment]
I was going to ask why you still are on pandas-1.5.2 instead of 2.0.3-r1, but it looks like 2.0.3-r1 is still cython<3 only. It is from 2.1.0 that it supports cython-3. I did not notice because my pandas is ~arch, since I needed fixes for sqlalchemy-2.0.0 early on.

Either, I can keyword pandas or it should be stabilised shortly. Still, what is holding pandas back for you?

**Comment by strogdon** [comment]
As far as I know I can use any pandas. But since I'm not ~arch maybe they should be keyworded.

**Comment by strogdon** [comment]
Or I can just keyword it locally. But others may have and issue.

**Comment by kiwifb** [comment]
The issue will hardy be unique to sage. I imagine some other people will get caught in that kind of stuff so long as there is not a cython 3 version of all the packages in the tree - or even at least an ~arch version. I can imagine some relatively dead package will never make the move without a distro patch. It will take time.

**Comment by kiwifb** [comment]
https://bugs.gentoo.org/915281

**Comment by strogdon** [comment]
It appears that https://bugs.gentoo.org/915281 has been fixed.

**Comment by kiwifb** [comment]
Indeed. I do hope sage 10.2 comes out very soon. It is currently impossible to emerge 10.1 because there is no cython<3 numpy left in the tree.
