### ISSUE TITLE
disorderly terminal output when building sage-doc (html docs)

### ISSUE THREAD

**Issue by strogdon** [cschwan/sage-on-gentoo#765]
I do not see the disorderly terminal output when building the html docs with `sphinx-6.2.1` and `furo-2013.9.10`. This version of `sphinx` uses `docutils-0.19`. However, using this version of `docutils` with `sphinx-7.1.2` did not remove the disorderly output. It is curious that the disorderly output was not observed when addressing https://github.com/sagemath/sage/pull/36296, https://github.com/sagemath/sage/issues/36295 and https://github.com/sagemath/sage/pull/36276.

**Comment by strogdon** [comment]
Vanilla sage now uses `sphinx-7.2.6` and I no longer see the `disorderly` terminal output when building html sage-docs on s-o-g. Vanilla must have made an internal change to  accommodate the new `sphinx`.

**Comment by kiwifb** [comment]
It was https://github.com/sagemath/sage/pull/37334

**Comment by strogdon** [comment]
closing
