### ISSUE TITLE
Missing package to emerge sage: dev-libs/ecls

### ISSUE THREAD

**Issue by mcizek-2** [cschwan/sage-on-gentoo#768]
When trying to emerge sci-mathematics/sage, I get the error:

```
emerge: there are no ebuilds to satisfy "~dev-lisp/ecls-21.2.1".
(dependency required by "sci-mathematics/sage-9.7-r3::sage-on-gentoo" [ebuild])
(dependency required by "sage" [argument])
```
When I search trough gentoo repos, it seems that the dev-lisp/ecls package no longer exists.

**Comment by kiwifb** [comment]
Hi,
That's right, `ecls` has been renamed `ecl`. But why are you on sage-9.7 when the available version in overlay is 10.1 and that version has the dependency fix to depend on `ecl`?

**Comment by mcizek-2** [comment]
Apologies: I just realised I added the overlay a while ago trough layman and so it hasn't been recieving any syncs. Thanks for the help.

**Comment by kiwifb** [comment]
It is all good. Was the documentation in the current README helpful or was there something missing or things that you think should be changed?

**Comment by mcizek-2** [comment]
@kiwifb No it was pretty clear to me. Thanks.
