### ISSUE TITLE
sage-doc-10.2 has references to 9999 ebuilds

### ISSUE THREAD

**Issue by CaptainBloodz** [cschwan/sage-on-gentoo#772]
`BDEPEND=

...
        ~sci-mathematics/sage-9999[${PYTHON_USEDEP},jmol]
        ~sci-mathematics/sage_docbuild-9999[${PYTHON_USEDEP}]
...

`

**Comment by kiwifb** [comment]
Thanks, I hate that section for which it is difficult to use `PV`,

**Comment by CaptainBloodz** [comment]
My 2 cents, can't it be splitted in 2 parts:
one for python
another for PV?
