### ISSUE TITLE
dev-python/pplpy versioning

### ISSUE THREAD

**Issue by strogdon** [cschwan/sage-on-gentoo#778]
I have `dev-python/pplpy-0.8.7-r1` installed which was removed from the overlay about 5 months ago. The current is `dev-python/pplpy-0.8.9`. `pplpy` is only required by s-o-g ebuilds
```
# equery d dev-python/pplpy
 * These packages depend on dev-python/pplpy:
sci-mathematics/sage-conf-9999 (dev-python/pplpy[doc,python_targets_python3_10(-)?,python_targets_python3_11(-)?,python_targets_python3_12(-)?])
sci-mathematics/sagemath-standard-9999 (dev-python/pplpy[doc,python_targets_python3_10(-)?,python_targets_python3_11(-)?,python_targets_python3_12(-)?])
```
I see no upgrade path except manually. Should there be version numbers in the above ebuilds?

**Comment by kiwifb** [comment]
I guess I could add some, but the reality is that there was no breaking changes. Not sure there was anything but cosmetic changes.

**Comment by strogdon** [comment]
That's what I suspected. Your call.

**Comment by kiwifb** [comment]
I could try to flush it by removing it from keywords or something. I will look into in a bit.

**Comment by kiwifb** [comment]
I had forgotten I had a concurrent version of pplpy in the overlay to support py3.12. The overlay version uses gmpy-2.2.0_alpha1 which supports py3.12 while everything in the main tree does not.
Still, I'll poke the keyword file so that the old version becomes unkeyworded.

**Comment by kiwifb** [comment]
Version poking done. The overlay mirror should update in the next 15mn or so.

**Comment by strogdon** [comment]
I still had to do this manually. Hopefully going forward it will update correctly.

**Comment by kiwifb** [comment]
Closing
