### ISSUE TITLE
Missing gap on fresh installation

### ISSUE THREAD

**Issue by ProgMiner** [cschwan/sage-on-gentoo#779]
Hello! I noticed that `sci-mathematics/sagemath-standard` depends on `~sci-mathematics/gap-4.12.2`, but unfortunately according version of gap was dropped from official repo: https://github.com/gentoo-mirror/gentoo/commit/7defea81a0e791ecb81999292862fb204f081b73

**Comment by kiwifb** [comment]
Thanks for letting me know. I am not sure we have gap-4.13 ready in sage upstream, the clean up is unfortunate. I will work on a solution ASAP.

**Comment by kiwifb** [comment]
Ok, there are doctests failures but no loss of functionality apart from one thing that will need migrating. So, I will enable gap 4.13 quickly.

**Comment by kiwifb** [comment]
For reference https://github.com/sagemath/sage/issues/37616

**Comment by kiwifb** [comment]
It will take about 15mn for the gentoo mirror of the overlay to sync, after that you should be able to sync locally and use gap-4.13.

**Comment by ProgMiner** [comment]
Wow, thank you, @kiwifb!
