### ISSUE TITLE
sci-mathematics/sage-doc-13 issue

### ISSUE THREAD

**Issue by CaptainBloodz** [cschwan/sage-on-gentoo#780]
All other sage related installed fine  against dev-lang/python:11.
Forces against dev-lang/python:12

**Comment by kiwifb** [comment]
Can you be more precise? Building against py3.12 requires the extra unmasking of gmpy from the sage-on-gentoo overlay.

**Comment by CaptainBloodz** [comment]
I've messed up with some unvalidated OP updates. Fixed.
Sorry.

**Comment by CaptainBloodz** [comment]
Here's an issue:

[sci-mathematics:sage-doc-10.3:20240323-225931.log.gz](https://github.com/cschwan/sage-on-gentoo/files/14733835/sci-mathematics.sage-doc-10.3.20240323-225931.log.gz)

A file present below seems misadressed:

equery f cysignals
 * Searching for cysignals ...
 * Contents of dev-python/cysignals-1.11.4:
/usr
/usr/bin
/usr/bin/cysignals-CSI -> ../lib/python-exec/python-exec2
/usr/lib
/usr/lib/python-exec
/usr/lib/python-exec/python3.11
/usr/lib/python-exec/python3.11/cysignals-CSI
/usr/lib/python3.11
/usr/lib/python3.11/site-packages
/usr/lib/python3.11/site-packages/cysignals
/usr/lib/python3.11/site-packages/cysignals-1.11.4.dist-info
/usr/lib/python3.11/site-packages/cysignals-1.11.4.dist-info/METADATA
/usr/lib/python3.11/site-packages/cysignals-1.11.4.dist-info/RECORD
/usr/lib/python3.11/site-packages/cysignals-1.11.4.dist-info/WHEEL
/usr/lib/python3.11/site-packages/cysignals-1.11.4.dist-info/top_level.txt
/usr/lib/python3.11/site-packages/cysignals/__init__.py
/usr/lib/python3.11/site-packages/cysignals/__pycache__
/usr/lib/python3.11/site-packages/cysignals/__pycache__/__init__.cpython-311.opt-1.pyc
/usr/lib/python3.11/site-packages/cysignals/__pycache__/__init__.cpython-311.opt-2.pyc
/usr/lib/python3.11/site-packages/cysignals/__pycache__/__init__.cpython-311.pyc
/usr/lib/python3.11/site-packages/cysignals/alarm.cpython-311-x86_64-linux-gnu.so
/usr/lib/python3.11/site-packages/cysignals/cysignals_config.h
/usr/lib/python3.11/site-packages/cysignals/macros.h
/usr/lib/python3.11/site-packages/cysignals/memory.pxd
/usr/lib/python3.11/site-packages/cysignals/pselect.cpython-311-x86_64-linux-gnu.so
/usr/lib/python3.11/site-packages/cysignals/pysignals.cpython-311-x86_64-linux-gnu.so
/usr/lib/python3.11/site-packages/cysignals/pysignals.pxd
/usr/lib/python3.11/site-packages/cysignals/signals.cpython-311-x86_64-linux-gnu.so
/usr/lib/python3.11/site-packages/cysignals/signals.pxd
/usr/lib/python3.11/site-packages/cysignals/struct_signals.h
/usr/lib/python3.11/site-packages/cysignals/tests.cpython-311-x86_64-linux-gnu.so
/usr/share
/usr/share/cysignals
/usr/share/cysignals/cysignals-CSI-helper.py
/usr/share/doc
/usr/share/doc/cysignals-1.11.4
/usr/share/doc/cysignals-1.11.4/README.rst.lzma

**Comment by kiwifb** [comment]
OK, that looks like two bugs rolled into one. First, the new in tree `cysignals` is not patched properly. Possibly, my patch was obsolete, if it has been imported - just checked, no patch for this behavior in the gentoo main tree. Second, there appear to be an issue with `libecl` from  `dev-lisp/ecl`. I would be tempted to rebuild `ecl` to see if it fixes thing.

Also, does sage starts?

**Comment by CaptainBloodz** [comment]
user@amd64 ~ $ sage
┌────────────────────────────────────────────────────────────────────┐
│ SageMath version 10.3, Release Date: 2024-03-19                    │
│ Using Python 3.11.8. Type "help()" for help.                       │
└────────────────────────────────────────────────────────────────────┘

eixi sci-mathematics/eclib
[I] sci-mathematics/eclib
     Available versions:  20231212(0/12)^t {boost flint minimal test}
     Installed versions:  20231212(0/12)^t(01:44:10 21/03/2024)(flint minimal -boost -test)
     Homepage:            https://github.com/JohnCremona/eclib
     Description:         Programs for elliptic curves defined over the rational numbers

Could USE=minimal causes failure?

**Comment by kiwifb** [comment]
OK, so sage starts, it is not that libecl or the binding to it is completely broken. But doing specific with it is.

**Comment by kiwifb** [comment]
I also may have incorrectly locked sage to ecl-21, when it should be able to use ecl-23. I'll look into that.

**Comment by kiwifb** [comment]
OK, you can upgrade ecl after synchronising the overlay with
```
emaint sync -r sage-on-gentoo
emerge -uv ecl --nodeps
emerge -1v maxima sagemath-standard
```

**Comment by CaptainBloodz** [comment]
new ecl maxima & sagemath-standard[-doc] went fine.

amd64 ~ # eix sage-doc
[I] sci-mathematics/sage-doc [1]
     Available versions:  (~)10.3^mt **9999*l^mt {doc-pdf L10N="ca de es fr hu it ja pt ru tr"}
     Installed versions:  10.3^mt(21:18:28 24/03/2024)(-doc-pdf L10N="fr -ca -de -es -hu -it -ja -pt -ru -tr")

went fine too.

However 
USE=doc-pdf emerge sci-mathematics/sage-doc
fails for some reason, possibly specific on my side:

Would you mind to have a look at:
[sci-mathematics:sage-doc-10.3:20240324-182724.log.gz](https://github.com/cschwan/sage-on-gentoo/files/14736745/sci-mathematics.sage-doc-10.3.20240324-182724.log.gz)

**Comment by kiwifb** [comment]
For doc-pdf, you may have missed the news https://github.com/cschwan/sage-on-gentoo/blob/master/metadata/news/2023-12-27-sage-doc-10.3.beta4-and-after/2023-12-27-sage-doc-10.3.beta4-and-after.en.txt
Some stuff changed since then, and maybe I should post an update. texlive-2023 has entered the main tree but is masked. If you want doc-pdf you need to link `tools/package.keywords/texlive-2023` in both `/etc/portage/package_acceptkeywords` and `/etc/portage/package.unmask` there is also the licenses and .use file.

**Comment by CaptainBloodz** [comment]
Clear enough +.

**Comment by CaptainBloodz** [comment]
Yes indeed, texlive-2023 version constraint could help others.
