### ISSUE TITLE
sagetex and python 3.12

### ISSUE THREAD

**Issue by Etn40ff** [cschwan/sage-on-gentoo#786]
Since June 1st `dev-tex/sagetex`  has unmet requirements on the default profile: the default profile switched to  `PYTHON_TARGETS="python3_12" which is not available for sagetex. As a result `sci-mathematics/sagemath-standard` does not emerge with the `USE` flag `latex`.

**Comment by kiwifb** [comment]
Thanks for pointing this out. It looks like something I overlooked because it change so infrequently.

**Comment by kiwifb** [comment]
Fixed by bbd3948f2c80f772b53dc09a223e31a701a0ceef

**Comment by Etn40ff** [comment]
Thanks!
It looks like `sci-mathematics/maxima` might have the same problem

**Comment by kiwifb** [comment]
Indeed, and in my opinion it should be a non issue. In the last version that was in the overlay, I had removed python support.
