### ISSUE TITLE
sci-mathematics/sagemath-tdlib not available

### ISSUE THREAD

**Issue by Etn40ff** [cschwan/sage-on-gentoo#787]
`@sagemath-optional` has unmet dependencies as `sci-mathematics/sagemath-tdlib` is only available as 9999.

**Comment by kiwifb** [comment]
Ooops, it should not have ended on the master branch. I probably should remove it until we have the 10.4 release.

**Comment by kiwifb** [comment]
Fixed by 18cd13f80e1bb6921b9e3f395b16ed140d8c4552

**Comment by Etn40ff** [comment]
thnks
