### ISSUE TITLE
sci-mathematics/sagemath-standard-10.4: build failure:

### ISSUE THREAD

**Issue by CaptainBloodz** [cschwan/sage-on-gentoo#789]
emerge -pv sci-mathematics/sagemath-standard
Dependency resolution took 167.61 s (backtrack: 0/20).

[ebuild  N    ~] sci-mathematics/sagemath-standard-10.4::sage-on-gentoo  USE="-X -debug -doc jmol -latex -test" PYTHON_TARGETS="-python3_10 python3_11 -python3_12" 0 KiB

[sci-mathematics:sagemath-standard-10.4:20240721-133007.log.gz](https://github.com/user-attachments/files/16324784/sci-mathematics.sagemath-standard-10.4.20240721-133007.log.gz)

egrf sci-mathematics/sagemath-standard
 * Searching for sagemath-standard in sci-mathematics ...

 * dependency graph for sci-mathematics/sagemath-standard-10.4
 `--  sci-mathematics/sagemath-standard-10.4  ~amd64 
   `--  dev-libs/gmp-6.3.0-r1  (dev-libs/gmp) amd64 
   `--  dev-libs/mpc-1.3.1  (>=dev-libs/mpc-1.1.0) amd64 
   `--  dev-libs/mpfr-4.2.1  (>=dev-libs/mpfr-4.0.0) amd64 
   `--  dev-libs/ntl-11.5.1-r4  (>=dev-libs/ntl-11.4.3) amd64 
   `--  dev-libs/ppl-1.2-r5  (>=dev-libs/ppl-1.1) amd64 
   `--  dev-lisp/ecl-23.9.9-r1  (>=dev-lisp/ecl-21.2.1) amd64 
   `--  dev-python/cypari2-2.1.4-r1  (>=dev-python/cypari2-2.1.4) amd64  [python_targets_python3_10(-)? python_targets_python3_11(-)? python_targets_python3_12(-)?]
   `--  dev-python/cysignals-1.11.4-r1  (>=dev-python/cysignals-1.11.2-r1) amd64  [python_targets_python3_10(-)? python_targets_python3_11(-)? python_targets_python3_12(-)?]
   `--  dev-python/docutils-0.21.2  (>=dev-python/docutils-0.12) amd64  [python_targets_python3_10(-)? python_targets_python3_11(-)? python_targets_python3_12(-)?]
   `--  dev-python/gmpy-2.2.0  (>=dev-python/gmpy-2.1.0_beta5) amd64  [python_targets_python3_10(-)? python_targets_python3_11(-)? python_targets_python3_12(-)?]
   `--  dev-python/ipykernel-6.29.4  (>=dev-python/ipykernel-4.6.0) amd64  [python_targets_python3_10(-)? python_targets_python3_11(-)? python_targets_python3_12(-)?]
   `--  dev-python/ipython-8.24.0  (>=dev-python/ipython-7.0.0) amd64  [notebook python_targets_python3_10(-)? python_targets_python3_11(-)? python_targets_python3_12(-)?]
   `--  dev-python/ipywidgets-8.1.3  (dev-python/ipywidgets) amd64  [python_targets_python3_10(-)? python_targets_python3_11(-)? python_targets_python3_12(-)?]
   `--  dev-python/jinja-3.1.4  (>=dev-python/jinja-2.8) amd64  [python_targets_python3_10(-)? python_targets_python3_11(-)? python_targets_python3_12(-)?]
   `--  dev-python/jupyter-core-5.7.2  (dev-python/jupyter-core) amd64  [python_targets_python3_10(-)? python_targets_python3_11(-)? python_targets_python3_12(-)?]
   `--  dev-python/jupyter-jsmol-2022.1.0  (~dev-python/jupyter-jsmol-2022.1.0) ~amd64  [python_targets_python3_10(-)? python_targets_python3_11(-)? python_targets_python3_12(-)?]
   `--  dev-python/lrcalc-2.1-r1  (dev-python/lrcalc) amd64  [python_targets_python3_10(-)? python_targets_python3_11(-)? python_targets_python3_12(-)?]
   `--  dev-python/matplotlib-3.9.1  (>=dev-python/matplotlib-3.5.0) amd64  [python_targets_python3_10(-)? python_targets_python3_11(-)? python_targets_python3_12(-)?]
   `--  dev-python/memory-allocator-0.1.4  (dev-python/memory-allocator) amd64  [python_targets_python3_10(-)? python_targets_python3_11(-)? python_targets_python3_12(-)?]
   `--  dev-python/numpy-2.0.0  (>=dev-python/numpy-1.16.1) amd64  [python_targets_python3_10(-)? python_targets_python3_11(-)? python_targets_python3_12(-)?]
   `--  dev-python/pkgconfig-1.5.5-r1  (>=dev-python/pkgconfig-1.2.2) amd64  [python_targets_python3_10(-)? python_targets_python3_11(-)? python_targets_python3_12(-)?]
   `--  dev-python/pplpy-0.8.10  (dev-python/pplpy) amd64  [doc python_targets_python3_10(-)? python_targets_python3_11(-)? python_targets_python3_12(-)?]
   `--  dev-python/primecountpy-0.1.0  (dev-python/primecountpy) amd64  [python_targets_python3_10(-)? python_targets_python3_11(-)? python_targets_python3_12(-)?]
   `--  dev-python/psutil-5.9.8  (>=dev-python/psutil-4.4.0) amd64  [python_targets_python3_10(-)? python_targets_python3_11(-)? python_targets_python3_12(-)?]
   `--  dev-python/six-1.16.0-r1  (>=dev-python/six-1.11.0) amd64  [python_targets_python3_10(-)? python_targets_python3_11(-)? python_targets_python3_12(-)?]
   `--  dev-python/sphinx-7.3.7-r2  (>=dev-python/sphinx-5.2.0) amd64  [python_targets_python3_10(-)? python_targets_python3_11(-)? python_targets_python3_12(-)?]
   `--  media-gfx/threejs-sage-extension-122-r2  (~media-gfx/threejs-sage-extension-122) ~amd64 
   `--  media-libs/gd-2.3.3-r4  (media-libs/gd) amd64  [jpeg png]
   `--  media-libs/libpng-1.6.43  (media-libs/libpng) amd64 
   `--  sci-mathematics/cliquer-1.22  (sci-mathematics/cliquer) amd64 
   `--  sci-mathematics/eclib-20231212  (sci-mathematics/eclib) amd64  [flint]
   `--  sci-mathematics/flint-3.1.0  (sci-mathematics/flint) amd64  [ntl]
   `--  sci-mathematics/gap-4.13.1  (>=sci-mathematics/gap-4.12.2) ~amd64 
   `--  sci-mathematics/giac-1.9.0.29-r1  (>=sci-mathematics/giac-1.9.0) amd64 
   `--  sci-mathematics/glpk-5.0-r1  (>=sci-mathematics/glpk-5.0) amd64  [gmp]
   `--  sci-mathematics/gmp-ecm-7.0.5-r1  (~sci-mathematics/gmp-ecm-7.0.5) amd64  [-openmp]
   `--  sci-mathematics/lcalc-2.0.5-r2  (=sci-mathematics/lcalc-2.0*) amd64 
   `--  sci-mathematics/pari-2.15.5  (>=sci-mathematics/pari-2.15.2) amd64 
   `--  sci-mathematics/planarity-3.0.2.0  (=sci-mathematics/planarity-3.0*) amd64 
   `--  sci-mathematics/rw-0.9  (>=sci-mathematics/rw-0.7) amd64 
   `--  sci-mathematics/sage_setup-10.4  (~sci-mathematics/sage_setup-10.4) ~amd64  [python_targets_python3_10(-)? python_targets_python3_11(-)? python_targets_python3_12(-)?]
   `--  sci-mathematics/sage-conf-10.4  (~sci-mathematics/sage-conf-10.4) ~amd64  [python_targets_python3_10(-)? python_targets_python3_11(-)? python_targets_python3_12(-)?]
   `--  sci-mathematics/singular-4.3.2_p16-r1  (>=sci-mathematics/singular-4.3.2_p15) amd64  [readline]
   `--  sci-libs/brial-1.2.12  (>=sci-libs/brial-1.2.10) amd64 
   `--  sci-libs/givaro-4.2.0  (>=sci-libs/givaro-4.1.1) amd64 
   `--  sci-libs/gsl-2.7.1-r2  (>=sci-libs/gsl-2.3) amd64 
   `--  sci-libs/iml-1.0.5  (>=sci-libs/iml-1.0.4) amd64 
   `--  sci-libs/libbraiding-1.2  (sci-libs/libbraiding) amd64 
   `--  sci-libs/libhomfly-1.02.6  (>=sci-libs/libhomfly-1.0.1) amd64 
   `--  sci-libs/linbox-1.7.0-r1  (>=sci-libs/linbox-1.6.3) amd64 
   `--  sci-libs/m4ri-20200125  (sci-libs/m4ri) amd64 
   `--  sci-libs/m4rie-20200115-r1  (sci-libs/m4rie) amd64 
   `--  sci-libs/mpfi-1.5.4  (>=sci-libs/mpfi-1.5.2) amd64 
   `--  sci-libs/symmetrica-3.0.1-r1  (>=sci-libs/symmetrica-2.0-r3) amd64 
   `--  sys-libs/readline-8.2_p10  (>=sys-libs/readline-6.2) amd64 
   `--  sys-libs/zlib-1.3.1-r1  (sys-libs/zlib) amd64 
   `--  virtual/cblas-3.8  (virtual/cblas) amd64 
   `--  sci-mathematics/sage_docbuild-10.4  (~sci-mathematics/sage_docbuild-10.4) ~amd64  [python_targets_python3_10(-)? python_targets_python3_11(-)? python_targets_python3_12(-)?]
   `--  dev-lang/python-3.10.14_p1-r1  (dev-lang/python) ~amd64  [readline sqlite]
   `--  dev-lang/python-3.11.9-r1  (dev-lang/python) ~amd64  [readline sqlite]
   `--  dev-lang/python-3.12.3-r1  (dev-lang/python) amd64  [readline sqlite]
   `--  sci-mathematics/sage-doc-10.4  (~sci-mathematics/sage-doc-10.4) ~amd64 
   `--  dev-tex/sagetex-3.6.1  (~dev-tex/sagetex-3.6.1) [~amd64 keyword] 
   `--  app-text/dvipng-1.17  (app-text/dvipng) amd64  [truetype]
   `--  media-gfx/imagemagick-7.1.1.25  (media-gfx/imagemagick) amd64  [png]
   `--  dev-lang/R-4.3.1-r1  (>=dev-lang/R-4.0.4) amd64 
   `--  dev-python/conway-polynomials-0.10  (dev-python/conway-polynomials) amd64  [python_targets_python3_10(-)? python_targets_python3_11(-)? python_targets_python3_12(-)?]
   `--  dev-python/cvxopt-1.3.2  (>=dev-python/cvxopt-1.2.6) ~amd64  [glpk python_targets_python3_10(-)? python_targets_python3_11(-)? python_targets_python3_12(-)?]
   `--  dev-python/fpylll-0.6.1  (>=dev-python/fpylll-0.6.0) amd64  [python_targets_python3_10(-)? python_targets_python3_11(-)? python_targets_python3_12(-)?]
   `--  dev-python/mpmath-1.3.0-r1  (>=dev-python/mpmath-1.2.1) amd64  [python_targets_python3_10(-)? python_targets_python3_11(-)? python_targets_python3_12(-)?]
   `--  dev-python/networkx-3.3  (>=dev-python/networkx-2.6) amd64  [python_targets_python3_10(-)? python_targets_python3_11(-)? python_targets_python3_12(-)?]
   `--  dev-python/pexpect-4.9.0  (>=dev-python/pexpect-4.2.1) amd64  [python_targets_python3_10(-)? python_targets_python3_11(-)? python_targets_python3_12(-)?]
   `--  dev-python/rpy-3.5.14  (>=dev-python/rpy-3.5.7) ~amd64  [python_targets_python3_10(-)? python_targets_python3_11(-)? python_targets_python3_12(-)?]
   `--  dev-python/scipy-1.14.0  (>=dev-python/scipy-1.1.0) amd64  [python_targets_python3_10(-)? python_targets_python3_11(-)? python_targets_python3_12(-)?]
   `--  dev-python/sympy-1.12.1  (dev-python/sympy) amd64  [python_targets_python3_10(-)? python_targets_python3_11(-)? python_targets_python3_12(-)?]
   `--  media-gfx/tachyon-0.99_beta6-r2  (media-gfx/tachyon) ~amd64  [png]
   `--  sci-libs/cddlib-094m-r1  (>=sci-libs/cddlib-094m) amd64  [tools]
   `--  sci-mathematics/cu2-20060223  (>=sci-mathematics/cu2-20060223) ~amd64 
   `--  sci-mathematics/cubex-20060128  (>=sci-mathematics/cubex-20060128) ~amd64 
   `--  sci-mathematics/dikcube-20070912-r1  (>=sci-mathematics/dikcube-20070912) ~amd64 
   `--  sci-mathematics/ExportSageNB-3.4  (>=sci-mathematics/ExportSageNB-3.3) ~amd64  [python_targets_python3_10(-)? python_targets_python3_11(-)? python_targets_python3_12(-)?]
   `--  sci-mathematics/gfan-0.6.2-r4  (~sci-mathematics/gfan-0.6.2) amd64 
   `--  sci-mathematics/maxima-5.47.0  (>=sci-mathematics/maxima-5.46.0) ~amd64  [ecl]
   `--  sci-mathematics/mcube-20051209  (>=sci-mathematics/mcube-20051209) ~amd64 
   `--  sci-mathematics/nauty-2.8.8-r1  (>=sci-mathematics/nauty-2.6.1) amd64 
   `--  sci-mathematics/optimal-20040603-r1  (>=sci-mathematics/optimal-20040603) ~amd64 
   `--  sci-mathematics/palp-2.21  (>=sci-mathematics/palp-2.1) ~amd64 
   `--  sci-mathematics/sage-data-combinatorial_designs-20140630  (~sci-mathematics/sage-data-combinatorial_designs-20140630) ~amd64 
   `--  sci-mathematics/sage-data-elliptic_curves-0.8  (~sci-mathematics/sage-data-elliptic_curves-0.8) ~amd64 
   `--  sci-mathematics/sage-data-graphs-20210214  (~sci-mathematics/sage-data-graphs-20210214) ~amd64 
   `--  sci-mathematics/sage-data-polytopes_db-20170220  (~sci-mathematics/sage-data-polytopes_db-20170220) ~amd64 
   `--  sci-mathematics/sympow-2.023.6  (>=sci-mathematics/sympow-1.018.1) amd64 
   `--  dev-python/tornado-6.4.1  (dev-python/tornado) amd64 
   `--  sci-chemistry/sage-jmol-bin-14.29.52  (sci-chemistry/sage-jmol-bin) ~amd64 
   `--  dev-python/cython-3.0.10  (>=dev-python/cython-3.0.0) amd64  [python_targets_python3_10(-)? python_targets_python3_11(-)? python_targets_python3_12(-)?]
   `--  dev-python/gpep517-16  (>=dev-python/gpep517-15) amd64  [python_targets_python3_10(-)? python_targets_python3_11(-)? python_targets_python3_12(-)?]
   `--  dev-python/setuptools-70.2.0-r1  (>=dev-python/setuptools-69.0.3) amd64  [python_targets_python3_10(-)? python_targets_python3_11(-)? python_targets_python3_12(-)?]
[ sci-mathematics/sagemath-standard-10.4 stats: packages (98), max depth (1) ]

**Comment by jiffygist** [comment]
Try updating sci-mathematics/flint to 3.1.3

**Comment by CaptainBloodz** [comment]
> I had to update sci-mathematics/flint to 3.1.3

Working here, indeed.

**Comment by kiwifb** [comment]
Indeed signature of an error with flint. But I cannot remember why it had to be updated or why I did not bump the dependency over 3.1.0. In any case I will have to raise it to force the update. And of course it does cause rebuilds, some of whom had to be forced on my machine.

**Comment by strogdon** [comment]
Could something other than flint be the issue? I built `sagemath-standard-9999` (which is sagemath-standard-10.4) yesterday without issue and I have `flint-3.1.0` installed.

**Comment by CaptainBloodz** [comment]
Did flint-3.1.0 first where sci-mathematics/sagemath-standard-10.4 failed
(+ a few depedencies update aka sci-libs/givaro, sci-libs/fflas-ffpack & sci-libs/linbox)
Then only flint-3.1.3_p1 to succeed.

**Comment by kiwifb** [comment]
OK technically, flint-3.0.x or flint-3.1.x should be usable. There was no change of sage's code related to updates to flint-3.1.0, 3.1.2 or 3.1.3. But flint may have needed a rebuild after gmp or another of its dependency was updated - but not picked up.
```
/usr/include/flint/mpoly.h:1366:43: error: expected ')' before '__extension__'
 1366 | void mpoly_gcd_info_init(mpoly_gcd_info_t I, slong nvars);
      |                                           ^
In file included from sage/libs/flint/flint_wrap.h:29,
                 from /var/no-tmpfs/portage/sci-mathematics/sagemath-standard-10.4/work/sagemath_standard-10.4-python3_11/build/cythonized/sage/matrix/change_ring.c:1274:
/usr/include/flint/mpoly.h:1366:46: error: expected ';', ',' or ')' before 'mp_limb_signed_t'
 1366 | void mpoly_gcd_info_init(mpoly_gcd_info_t I, slong nvars);
      |                                              ^~~~~
/usr/include/flint/mpoly.h:1368:44: error: expected ')' before '__extension__'
 1368 | void mpoly_gcd_info_clear(mpoly_gcd_info_t I);
      |                                            ^
/usr/include/flint/mpoly.h:1381:47: error: expected ')' before '__extension__'
 1381 | void mpoly_gcd_info_set_perm(mpoly_gcd_info_t I,
      |                                               ^
/usr/include/flint/mpoly.h:1382:26: error: expected ';', ',' or ')' before 'mp_limb_signed_t'
 1382 |                          slong Alength, slong Blength, const mpoly_ctx_t mctx);
      |                          ^~~~~
/usr/include/flint/mpoly.h:1384:67: error: expected ')' before '__extension__'
 1384 | slong mpoly_gcd_info_get_brown_upper_limit(const mpoly_gcd_info_t I,
      |                                                                   ^
/usr/include/flint/mpoly.h:1385:56: error: expected ';', ',' or ')' before 'mp_limb_signed_t'
 1385 |                                                        slong var, slong bound);
      |                                                        ^~~~~
/usr/include/flint/mpoly.h:1387:53: error: expected ')' before '__extension__'
 1387 | void mpoly_gcd_info_measure_hensel(mpoly_gcd_info_t I,
      |                                                     ^
/usr/include/flint/mpoly.h:1388:26: error: expected ';', ',' or ')' before 'mp_limb_signed_t'
 1388 |                          slong Alength, slong Blength, const mpoly_ctx_t mctx);
      |                          ^~~~~
/usr/include/flint/mpoly.h:1390:52: error: expected ')' before '__extension__'
 1390 | void mpoly_gcd_info_measure_brown(mpoly_gcd_info_t I,
      |                                                    ^
/usr/include/flint/mpoly.h:1391:26: error: expected ';', ',' or ')' before 'mp_limb_signed_t'
 1391 |                          slong Alength, slong Blength, const mpoly_ctx_t mctx);
      |                          ^~~~~
/usr/include/flint/mpoly.h:1393:50: error: expected ')' before '__extension__'
 1393 | void mpoly_gcd_info_measure_bma(mpoly_gcd_info_t I,
      |                                                  ^
/usr/include/flint/mpoly.h:1394:26: error: expected ';', ',' or ')' before 'mp_limb_signed_t'
 1394 |                          slong Alength, slong Blength, const mpoly_ctx_t mctx);
      |                          ^~~~~
/usr/include/flint/mpoly.h:1396:53: error: expected ')' before '__extension__'
 1396 | void mpoly_gcd_info_measure_zippel(mpoly_gcd_info_t I,
      |                                                     ^
/usr/include/flint/mpoly.h:1397:26: error: expected ';', ',' or ')' before 'mp_limb_signed_t'
 1397 |                          slong Alength, slong Blength, const mpoly_ctx_t mctx);
      |                          ^~~~~
/usr/include/flint/mpoly.h:1399:54: error: expected ')' before '__extension__'
 1399 | void mpoly_gcd_info_measure_zippel2(mpoly_gcd_info_t I,
      |                                                      ^
/usr/include/flint/mpoly.h:1400:26: error: expected ';', ',' or ')' before 'mp_limb_signed_t'
 1400 |                          slong Alength, slong Blength, const mpoly_ctx_t mctx);
      |                          ^~~~~
/usr/include/flint/fmpz_mpoly.h:1091:105: error: expected ')' before '__extension__'
 1091 | void fmpz_mpoly_reduction_primitive_part(fmpz_mpoly_t res, const fmpz_mpoly_t f, const fmpz_mpoly_vec_t I, const fmpz_mpoly_ctx_t ctx);
      |                                                                                                         ^
In file included from /usr/include/flint/fmpz_mpoly_q.h:26,
                 from /usr/include/flint/ca.h:22,
                 from sage/libs/flint/flint_wrap.h:61:
/usr/include/flint/fmpz_mpoly.h:1091:108: error: expected ';', ',' or ')' before 'const'
 1091 | void fmpz_mpoly_reduction_primitive_part(fmpz_mpoly_t res, const fmpz_mpoly_t f, const fmpz_mpoly_vec_t I, const fmpz_mpoly_ctx_t ctx);
      |                                                                                                            ^~~~~
/usr/include/flint/fmpz_mod_mpoly_factor.h:1206:54: error: expected ')' before '__extension__'
 1206 | int fmpz_mod_mpoly_pfrac_init(fmpz_mod_mpoly_pfrac_t I,
      |                                                      ^
/usr/include/flint/fmpz_mod_mpoly_factor.h:1207:5: error: expected ';', ',' or ')' before 'mp_limb_t'
 1207 |     flint_bitcnt_t bits, slong l, slong r, const fmpz_mod_mpoly_struct * betas,
      |     ^~~~~~~~~~~~~~
/usr/include/flint/fmpz_mod_mpoly_factor.h:1210:56: error: expected ')' before '__extension__'
 1210 | void fmpz_mod_mpoly_pfrac_clear(fmpz_mod_mpoly_pfrac_t I,
      |                                                        ^
In file included from sage/libs/flint/flint_wrap.h:92:
/usr/include/flint/fmpz_mod_mpoly_factor.h:1211:47: error: expected ';', ',' or ')' before 'const'
 1211 |                                               const fmpz_mod_mpoly_ctx_t ctx);
      |                                               ^~~~~
/usr/include/flint/fmpz_mod_mpoly_factor.h:1214:45: error: expected ')' before '__extension__'
 1214 |                      fmpz_mod_mpoly_pfrac_t I, const fmpz_mod_mpoly_ctx_t ctx);
      |                                             ^
/usr/include/flint/fmpz_mod_mpoly_factor.h:1214:48: error: expected ';', ',' or ')' before 'const'
 1214 |                      fmpz_mod_mpoly_pfrac_t I, const fmpz_mod_mpoly_ctx_t ctx);
      |                                                ^~~~~
/usr/include/flint/fmpz_mod_mpoly_factor.h:1293:28: error: expected ')' before '__extension__'
 1293 |     const mpoly_gcd_info_t I,
      |                            ^
/usr/include/flint/fmpz_mod_mpoly_factor.h:1294:5: error: expected ';', ',' or ')' before 'fmpz_mod_poly_polyun_mpolyn_stack_t'
 1294 |     fmpz_mod_poly_polyun_mpolyn_stack_t St);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/flint/nmod_mpoly.h:1624:77: error: expected ')' before '__extension__'
 1624 |                          const nmod_mpoly_ctx_t ctx, const mpoly_gcd_info_t I,
      |                                                                             ^
In file included from /usr/include/flint/fmpz_mpoly_factor.h:24,
                 from sage/libs/flint/flint_wrap.h:97:
/usr/include/flint/nmod_mpoly.h:1625:58: error: expected ';', ',' or ')' before 'nmod_poly_stack_t'
 1625 |                                                          nmod_poly_stack_t Sp);
      |                                                          ^~~~~~~~~~~~~~~~~
/usr/include/flint/nmod_mpoly.h:1630:77: error: expected ')' before '__extension__'
 1630 |                          const nmod_mpoly_ctx_t ctx, const mpoly_gcd_info_t I,
      |                                                                             ^
/usr/include/flint/nmod_mpoly.h:1631:25: error: expected ';', ',' or ')' before 'const'
 1631 |                         const thread_pool_handle * handles, slong num_workers);
      |                         ^~~~~
/usr/include/flint/fmpz_mpoly_factor.h:301:77: error: expected ')' before '__extension__'
  301 |                          const fmpz_mpoly_ctx_t ctx, const mpoly_gcd_info_t I);
      |                                                                             ^
/usr/include/flint/fmpz_mpoly_factor.h:305:77: error: expected ')' before '__extension__'
  305 |                          const fmpz_mpoly_ctx_t ctx, const mpoly_gcd_info_t I,
      |                                                                             ^
/usr/include/flint/fmpz_mpoly_factor.h:306:25: error: expected ';', ',' or ')' before 'const'
  306 |                         const thread_pool_handle * handles, slong num_handles);
      |                         ^~~~~
/usr/include/flint/fmpz_mpoly_factor.h:343:45: error: expected ')' before '__extension__'
  343 | void fmpz_poly_pfrac_init(fmpz_poly_pfrac_t I);
      |                                             ^
/usr/include/flint/fmpz_mpoly_factor.h:345:46: error: expected ')' before '__extension__'
  345 | void fmpz_poly_pfrac_clear(fmpz_poly_pfrac_t I);
      |                                              ^
/usr/include/flint/fmpz_mpoly_factor.h:347:50: error: expected ')' before '__extension__'
  347 | int fmpz_poly_pfrac_precompute(fmpz_poly_pfrac_t I,
      |                                                  ^
/usr/include/flint/fmpz_mpoly_factor.h:348:43: error: expected ';', ',' or ')' before 'const'
  348 |                                           const fmpz_poly_struct * b, slong r);
      |                                           ^~~~~
/usr/include/flint/fmpz_mpoly_factor.h:351:77: error: expected ')' before '__extension__'
  351 |                                      const fmpz_poly_t A, fmpz_poly_pfrac_t I);
      |                                                                             ^
/usr/include/flint/fmpz_mpoly_factor.h:375:46: error: expected ')' before '__extension__'
  375 | int fmpz_mpoly_pfrac_init(fmpz_mpoly_pfrac_t I, flint_bitcnt_t bits,
      |                                              ^
/usr/include/flint/fmpz_mpoly_factor.h:375:49: error: expected ';', ',' or ')' before 'mp_limb_t'
  375 | int fmpz_mpoly_pfrac_init(fmpz_mpoly_pfrac_t I, flint_bitcnt_t bits,
      |                                                 ^~~~~~~~~~~~~~
/usr/include/flint/fmpz_mpoly_factor.h:379:48: error: expected ')' before '__extension__'
  379 | void fmpz_mpoly_pfrac_clear(fmpz_mpoly_pfrac_t I,
      |                                                ^
/usr/include/flint/fmpz_mpoly_factor.h:380:52: error: expected ';', ',' or ')' before 'const'
  380 |                                                    const fmpz_mpoly_ctx_t ctx);
      |                                                    ^~~~~
/usr/include/flint/fmpz_mpoly_factor.h:383:49: error: expected ')' before '__extension__'
  383 |                              fmpz_mpoly_pfrac_t I, const fmpz_mpoly_ctx_t ctx);
      |                                                 ^
/usr/include/flint/fmpz_mpoly_factor.h:383:52: error: expected ';', ',' or ')' before 'const'
  383 |                              fmpz_mpoly_pfrac_t I, const fmpz_mpoly_ctx_t ctx);
      |                                                    ^~~~~
/usr/include/flint/fq_nmod_mpoly_factor.h:430:27: error: expected ')' before '__extension__'
  430 |     fq_nmod_mpoly_pfrac_t I,
      |                           ^
/usr/include/flint/fq_nmod_mpoly_factor.h:431:5: error: expected ';', ',' or ')' before 'mp_limb_t'
  431 |     flint_bitcnt_t bits,
      |     ^~~~~~~~~~~~~~
/usr/include/flint/fq_nmod_mpoly_factor.h:438:27: error: expected ')' before '__extension__'
  438 |     fq_nmod_mpoly_pfrac_t I,
      |                           ^
In file included from sage/libs/flint/flint_wrap.h:116:
/usr/include/flint/fq_nmod_mpoly_factor.h:439:5: error: expected ';', ',' or ')' before 'const'
  439 |     const fq_nmod_mpoly_ctx_t ctx);
      |     ^~~~~
/usr/include/flint/fq_nmod_mpoly_factor.h:445:27: error: expected ')' before '__extension__'
  445 |     fq_nmod_mpoly_pfrac_t I,
      |                           ^
/usr/include/flint/fq_nmod_mpoly_factor.h:446:5: error: expected ';', ',' or ')' before 'const'
  446 |     const fq_nmod_mpoly_ctx_t ctx);
      |     ^~~~~
/usr/include/flint/nmod_mpoly_factor.h:365:46: error: expected ')' before '__extension__'
  365 | int nmod_mpoly_pfrac_init(nmod_mpoly_pfrac_t I, flint_bitcnt_t bits,
      |                                              ^
/usr/include/flint/nmod_mpoly_factor.h:365:49: error: expected ';', ',' or ')' before 'mp_limb_t'
  365 | int nmod_mpoly_pfrac_init(nmod_mpoly_pfrac_t I, flint_bitcnt_t bits,
      |                                                 ^~~~~~~~~~~~~~
/usr/include/flint/nmod_mpoly_factor.h:369:48: error: expected ')' before '__extension__'
  369 | void nmod_mpoly_pfrac_clear(nmod_mpoly_pfrac_t I,
      |                                                ^
In file included from sage/libs/flint/flint_wrap.h:148:
/usr/include/flint/nmod_mpoly_factor.h:370:52: error: expected ';', ',' or ')' before 'const'
  370 |                                                    const nmod_mpoly_ctx_t ctx);
      |                                                    ^~~~~
/usr/include/flint/nmod_mpoly_factor.h:373:49: error: expected ')' before '__extension__'
  373 |                              nmod_mpoly_pfrac_t I, const nmod_mpoly_ctx_t ctx);
      |                                                 ^
/usr/include/flint/nmod_mpoly_factor.h:373:52: error: expected ';', ',' or ')' before 'const'
  373 |                              nmod_mpoly_pfrac_t I, const nmod_mpoly_ctx_t ctx);
      |                                                    ^~~~~
```
As you can it points to flint, but more interestingly that flint headers themselves are inconsistent.

**Comment by kiwifb** [comment]
> Did flint-3.1.0 first where sci-mathematics/sagemath-standard-10.4 failed (+ a few depedencies update aka sci-libs/givaro, sci-libs/fflas-ffpack & sci-libs/linbox) Then only flint-3.1.3_p1 to succeed.

I think a dependency of flint is the issue trigger, it may require a higher version of flint to be compatible.

**Comment by kiwifb** [comment]
Our guilty party may be a compiler update https://github.com/flintlib/flint/commit/1b93e73d00881be12e04b7f13e070214a3c9e1cc

**Comment by strogdon** [comment]
I'm using `gcc- 13.2.1_p20240210`.

**Comment by CaptainBloodz** [comment]
sys-devel/gcc-13.3.1_p20240614 here.

**Comment by kiwifb** [comment]
I think we have a culprit. Since gcc-13.3.1_px is stable, I think it is appropriate to do a dependency bump. I also have to include numpy-2.0 compat so there will be a revbump of sagemath-standard later today.

**Comment by kiwifb** [comment]
Just double checked and the flint-3.1.3_p1 ebuild does include a patch for the flint PR I quoted above but flint-3.1.0 does not. uSo, it probably is definitely that issue. It also matches the error messages that point to `I` in the first instance.

**Comment by kiwifb** [comment]
> sys-devel/gcc-13.3.1_p20240614 here.

Should actually work with gcc-13.3.1 (it does work here) are you sure you do not have gcc-14?

**Comment by kiwifb** [comment]
sagemath-standard-10.4-r1 pushed to the overlay with additional keywords for flint-3.1.3_p1.

**Comment by strogdon** [comment]
`sagemath-standard-9999` builds here with `gcc-13.3.1_p20240614` and `flint-3.1.3_p1` installed.

**Comment by kiwifb** [comment]
Should be done here, closing,

**Comment by CaptainBloodz** [comment]
Indeed

Thks
