### ISSUE TITLE
dev-python/gmpy is now called dev-python/gmpy2?

### ISSUE THREAD

**Issue by piotr5** [cschwan/sage-on-gentoo#800]
emerge @sagemath

gives me

```
emerge: there are no ebuilds to satisfy "dev-python/gmpy".
```

and there is no such package on this repository nor on gentoo, instead there is dev-python/gmpy2 likely with some api-break. or should we just change the sci-mathematics/sagemath-standard package to have that as a dependency?

**Comment by kiwifb** [comment]
Looks like some recent renaming to me. Let me check.

**Comment by kiwifb** [comment]
https://gitweb.gentoo.org/repo/gentoo.git/commit/dev-python/gmpy2?id=3a3b1a69be7106d0fd278c9b45f34f20e6cbf74c

It's been renamed. Updating ebuilds shortly.

**Comment by kiwifb** [comment]
Fixed by 202194ea11486e538219a1c3715f106fcfda938d wait about 15mn for the overlay to be synchronized.

**Comment by kiwifb** [comment]
And it looks like jinja has also been renamed jinja2 :(

**Comment by kiwifb** [comment]
https://gitweb.gentoo.org/repo/gentoo.git/diff/?id=832063fcffe02eb04f68486146ceb7b214197961

**Comment by kiwifb** [comment]
jinja2 migration done in 1d8180eab5d634dbd9b78f0feebf6359dc0b5e77 - again it may take 15mn for the gentoo mirror of the overlay to get updated.

**Comment by kiwifb** [comment]
rpy has just become rpy2

**Comment by kiwifb** [comment]
And fixed in overlay. I will keep the issue a opened a bit longer in case something else of that nature shows up.

**Comment by kiwifb** [comment]
No new move affecting the overlay, closing.
