### ISSUE TITLE
sci-mathematics/sagemath-standard-10.4-r3: build fails with sci-mathematics/eclib/eclib-20241112

### ISSUE THREAD

**Issue by kcning** [cschwan/sage-on-gentoo#801]
build fails with error message
```
/tmp/portage/sci-mathematics/sagemath-standard-10.4-r3/work/sagemath_standard-10.4-python3_12/build/cythonized/sage/libs/eclib/mat.cpp: In function 'PyObject* __pyx_pf_4sage_4libs_5eclib_3mat_6Matrix_16sage_matrix_over_ZZ(__pyx_obj_4sage_4libs_5eclib_3mat_Matrix*, PyObject*)':
/tmp/portage/sci-mathematics/sagemath-standard-10.4-r3/work/sagemath_standard-10.4-python3_12/build/cythonized/sage/libs/eclib/mat.cpp:6468:16: error: invalid cast from type 'const std::vector<int>' to type 'scalar*' {aka 'int*'}
 6468 |   __pyx_v_v = ((scalar *)__pyx_v_self->M->get_entries());
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

The attached patch fixes the issue. ([source](https://gitlab.archlinux.org/archlinux/packaging/packages/sagemath/-/blob/6daeafc767e275615cbb4edf9585067a5843f1b2/eclib-20241112.patch))
[sagemath-standard-10.4-eclib.patch.tar.gz](https://github.com/user-attachments/files/17775475/sagemath-standard-10.4-eclib.patch.tar.gz)

**Comment by kiwifb** [comment]
Sorry I have let that one slip. I am usually better at going after those.

**Comment by kiwifb** [comment]
This is upstream https://github.com/sagemath/sage/pull/38962 - my issue here is that those change are probably not backward compatible for people on stable. If I include this for 10.4, I will have to keyword that version of eclib as well.

**Comment by kiwifb** [comment]
OK. So, it not a backward compatible change. I will lock 10.4 to the current stable version but move the future 10.5 to the newest eclib. 10.5 has entered the release candidate stage, so we can expect a release in a couple of weeks at most.

**Comment by strogdon** [comment]
Data point:  Built `sagemath-9999 (10.5.rc0)` on top of `eclib-20241112` with the above patch w/o incident. The testsuite didn't exhibit any eclib-related failures.

**Comment by kiwifb** [comment]
Cool. I would not have expected any. Change will be incoming to include the patch in 9999 and version restriction in 10.4 in the next few hours.

**Comment by kiwifb** [comment]
Pushed to master.

**Comment by kcning** [comment]
Thank you!

**Comment by kiwifb** [comment]
sage 10.5 is out. Closing.
